### ISSUE TITLE
1.16.3 crashes with every version of Optifabrick

### ISSUE THREAD

**Issue by Glitchtrap4461** [Chocohead/OptiFabric#101]
I downloaded every version of Optifabrick 1.16.3 and it crashes every time

**Comment by Titaniumtown** [comment]
optifabric is for 1.16.4. Also can you please give more information? Like what mods you're using, etc. This bug report isn't anywhere close to descriptive.

**Comment by DeDogge** [comment]
same issue here, when i want to run minecraft it instantly crashes bcs of optifabric on 1.16.3 
posting a screenshot below what mods do i use 


![mods 1 16 3](https://user-images.githubusercontent.com/74607906/99402908-2994ad80-28ea-11eb-8e92-2c8bbef9580e.jpg)

**Comment by Chocohead** [comment]
> same issue here, when i want to run minecraft it instantly crashes bcs of optifabric on 1.16.3
> posting a screenshot below what mods do i use

Optifine doesn't work with Sodium so that'll be the issue you're having in particular. You'll have to pick which one you'd rather use and remove the other.

As Titaniumtown said for the issue in general we could do with the crash report from the `crash-reports` folder in order to be able to help you.

**Comment by Totemkopf** [comment]
So yea i have the same problem as above and heres the crashrapport

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 12/4/20 7:17 PM
Description: Unexpected error

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_918.method_23179(class_918.java:256)
	at net.minecraft.class_918.method_4021(class_918.java:428)
	at net.minecraft.class_918.method_4010(class_918.java:398)
	at mcp.mobius.waila.overlay.DisplayUtil.renderStack(DisplayUtil.java:34)
	at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:89)
	at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:57)
	at mcp.mobius.waila.overlay.WailaTickHandler.renderOverlay(WailaTickHandler.java:61)
	at net.minecraft.class_757.handler$bee000$renderOverlay(class_757.java:3437)
	at net.minecraft.class_757.method_3192(class_757.java:765)
	at net.minecraft.class_310.method_1523(class_310.java:1023)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method inject_render(Lnet/minecraft/class_1799;Lnet/minecraft/class_809$class_811;Lnet/minecraft/class_4587;Lnet/minecraft/class_4597;IILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in images.mixins.json:client.BuiltinModelItemRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap images-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 25 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_918.method_23179(class_918.java:256)
	at net.minecraft.class_918.method_4021(class_918.java:428)
	at net.minecraft.class_918.method_4010(class_918.java:398)
	at mcp.mobius.waila.overlay.DisplayUtil.renderStack(DisplayUtil.java:34)
	at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:89)
	at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:57)
	at mcp.mobius.waila.overlay.WailaTickHandler.renderOverlay(WailaTickHandler.java:61)
	at net.minecraft.class_757.handler$bee000$renderOverlay(class_757.java:3437)

-- Affected level --
Details:
	All players: 1 total; [class_746['Totemkopf18'/253180, l='ClientWorld minecraft:overworld', x=-261.46, y=77.00, z=-261.11]]
	Chunk stats: Client Chunks (ImmPtl) 504
	Level dimension: minecraft:overworld
	Level spawn location: World: (-230,69,-258), Chunk: (at 10,4,14 in -15,-17; contains blocks -240,0,-272 to -225,255,-257), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 33486201 game time, 37233629 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:617)
	at net.minecraft.class_310.method_1587(class_310.java:2183)
	at net.minecraft.class_310.method_1514(class_310.java:679)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3135227728 bytes (2989 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 1.12.1+1.16.4
		astromine: Astromine 1.11.4+fabric-1.16.3
		astromine-core: Astromine: Core 1.11.4+fabric-1.16.3
		astromine-discoveries: Astromine: Discoveries 1.11.4+fabric-1.16.3
		astromine-foundations: Astromine: Foundations 1.11.4+fabric-1.16.3
		astromine-technologies: Astromine: Technologies 1.11.4+fabric-1.16.3
		astromine-transportations: Astromine: Transportations 1.11.4+fabric-1.16.3
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bendy-lib: Bendy api 0.2.3
		betterend: Better End 0.6.2-beta
		betternether: Better Nether 4.1.8
		blade: Blade 2.0.0
		blue_endless_jankson: jankson +
		boot: BootZ 1.3.4
		bucket-hat: Bucket Hat 1.0.3
		campanion: Campanion 1.2.0+build.39
		cardinal-components-base: Cardinal Components API (base) 2.6.0
		cardinal-components-block: Cardinal Components API (blocks) 2.6.0
		cardinal-components-chunk: Cardinal Components API (chunks) 2.6.0
		cardinal-components-entity: Cardinal Components API (entities) 2.6.0
		cardinal-components-item: Cardinal Components API (items) 2.6.0
		cardinal-components-level: Cardinal Components API (world saves) 2.6.0
		cardinal-components-util: Cardinal Components API (utilities) 2.6.0
		cardinal-components-world: Cardinal Components API (worlds) 2.6.0
		carpet: Carpet Mod in Fabric 1.4.12
		chainmail: Chainmail 0.5.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.5
		cloth-config2: Cloth Config v4 4.8.3
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.8
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.8
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.8
		cloth-utils-v1: Cloth Utils v1 1.4.5
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.10.1
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.10.1
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.10.1
		com_github_shevek_parallelgzip: parallelgzip master-SNAPSHOT
		com_neovisionaries_nv-websocket-client: nv-websocket-client 2.10
		com_squareup_moshi_moshi: moshi 1.9.2
		com_squareup_okhttp3_okhttp: okhttp 3.13.0
		com_squareup_okio_okio: okio 1.17.2
		com_vdurmont_emoji-java: emoji-java 5.1.1
		computercraft: CC:T for Fabric 1.91.2
		continuebutton: Continue Button 1.0.2
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		couplings: Couplings 1.3.3
		croptopia: Croptopia 1.0.5-1.16.3-FABRIC
		custom-crosshair-mod: Custom Crosshair Mod 1.0.3-fabric
		customportals: Custom Portals 1.3.0
		dcch: DCCH 1.0
		disablecustomworldsadvice: Disable Custom Worlds Advice 1.1
		dontgrow: Dont Grow 1.0.2
		doorsofinfinity: Doors of Infinity 1.0.8-1.16.3
		easiercrafting: EasierCrafting 1.16.2-fabric0.17.2-1.6.5
		easiervillagertrading: EasierVillagerTrading 1.16.2-fabric0.17.2-1.5.3
		emotecraft: Emotecraft 1.2.3
		expandedstorage: ExpandedStorage 5.6.30
		extra-discs: Extra Disks 1.0.1
		fabric: Fabric API 0.25.0+build.415-1.16
		fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
		fabric-biome-api-v1: Fabric Biome API (v1) 3.0.0+8367596d95
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a95
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a95
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a95
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab95
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a95
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a95
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a95
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a95
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf3a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a95
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b46237995
		fabricloader: Fabric Loader 0.10.8
		fabrikommander: FabriKommander 1.0.0-MC1.16.3
		fastestf: Fastest F in the West 1.0.0
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
		fiber: fiber 0.23.0-1
		gbfabrictools: GBfabrictools 1.2.2+1.16.2
		golemsgalore: Golems Galore 0.2.0+mc.1.16.2
		goml: Get Off My Lawn 1.2.2-beta
		gravestones: Gravestones 1.5
		harvest: Harvest 1.2.12
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		images: Images 0.4.0+1.16.4
		imm_ptl_core: Immersive Portals Core 0.41
		immersive_portals: Immersive Portals 0.41
		impersonate: Impersonate 2.0.3
		inventorysorter: Inventory Sorter 1.7.4-1.16
		invview: InvView 1.2.0-1.16.2+
		itemflexer: ItemFlexer 1.0.1
		itemscroller: Item Scroller 0.15.0-dev.20201103.183933
		jankson: Jankson 3.0.1+j1.2.0
		javax_vecmath_vecmath: vecmath 1.5.2
		kyrptconfig: Kytpt Config 1.1.2-1.16
		launchersmod: Launchers 2.1.4
		libblockattributes: LibBlockAttributes 0.8.4
		libblockattributes_core: LibBlockAttributes (Core) 0.8.4
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.4
		libblockattributes_items: LibBlockAttributes (Items) 0.8.4
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.1.0+1.16.3
		libstructure: LibStructure 1.5
		lightoverlay: Light Overlay 5.5.4
		litematica: Litematica 0.0.0-dev.20201103.184101
		little_rocket_man: Little Rocket Man 1.0.1
		logical_zoom: Logical Zoom 0.0.7
		lvmnt: SuperAxes 2.0.5
		magna: Magna 1.4.3-1.16.2
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		maybe-data: Maybe data 1.0.0-1.16.2
		mess: MESS 1.16.4-1.0.0
		minecraft: Minecraft 1.16.3
		minihud: MiniHUD 0.19.0-dev.20201103.184029
		missingbits: Missing Bits v1.16.3 Fabric b1
		mm: Manningham Mills 2.1
		mobropes: Mob Ropes 1.16.4+1.0.2
		modmenu: Mod Menu 1.14.7+build.11
		modupdater: ModUpdater 1.1.11+1.16.3-rc2
		mostructures: Mo' Structures 1.0.0-pre3+mc.1.16.2
		net_dv8tion_jda: JDA 4.2.0_191
		net_sf_trove4j_trove4j: trove4j 3.0.3
		numericping: NumericPing 1.0.2-fabric1.16.3
		optifabric: OptiFabric 1.8.10
		org_apache_commons_commons-collections4: commons-collections4 4.1
		org_apache_commons_commons-compress: commons-compress 1.19
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		org_joml_joml: joml 1.9.25
		org_json_json: json 20170516
		org_slf4j_slf4j-api: slf4j-api 1.7.25
		org_slf4j_slf4j-nop: slf4j-nop 1.7.25
		org_tukaani_xz: xz 1.8
		patchouli: Patchouli 1.16.2-44-FABRIC
		phosphor: Phosphor 0.6.0+build.7
		piglib: Piglib 1.0.1
		pigpoop: Pig Poop 1.1.3
		plantinajar: Plant In A Jar 1.8.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		roughlyenoughitems: Roughly Enough Items 5.8.3
		roughlyenoughitems-api: REI (API) 5.8.3
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.3
		roughlyenoughitems-runtime: REI (Runtime) 5.8.3
		rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		screenshotclipboard: Screenshot to Clipboard 1.0.6
		shapes: Shapes 2.0.0+build.10
		simpleplanes: simpleplanes 3.2.1
		slotlink: slotlink 2.1.1+1.16.4
		structurized: Structurized 1.1.0
		team_reborn_energy: Energy 0.1.0
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
		terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.1
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.2
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
		terrestria: Terrestria 2.1.4+build.26
		textile_backup: Textile Backup 2.0.1-1.16.3
		traverse: Traverse 3.0.0+build.6
		trinkets: Trinkets 2.6.7
		tweakeroo: Tweakeroo 0.10.0-dev.20201110.132827
		villagernames: Villager Names 1.2.2
		waila: Hwyla 1.9.22
		whereisit: Where Is It 1.9.1
		wrenchable: Wrenchable 1.0.0+1.16.1
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.10.8-1.16.3
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
	OptiFine Version: OptiFine_1.16.3_HD_U_G5
	OptiFine Build: 20201106-202857
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.281 High.zip
	OpenGlVersion: 4.6.0 NVIDIA 456.71
	OpenGlRenderer: GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.3
	OptiFine jar version: OptiFine_1.16.3_HD_U_G5
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:\Users\Christian\AppData\Roaming\.minecraft\.optifine\OptiFine_1.16.3_HD_U_G5\Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by Titaniumtown** [comment]
Why are you using 1.16.3 though. Why not update to 1.16.4

**Comment by Totemkopf** [comment]
the server im playing on (with family) is running 1.16.3 soo...

**Comment by Titaniumtown** [comment]
Just use viaversion???

**Comment by IMS212** [comment]
> the server im playing on (with family) is running 1.16.3 soo...

use multiconnect @Totemkopf, can connect all the way to 1.9 without any server plugins

**Comment by Totemkopf** [comment]
both solid suggestions! do they work with mods?

**Comment by IMS212** [comment]
if they’re client side yes
