### ISSUE TITLE
Mod compatibility: owo-lib (dependency for DeathLog as of 1.19.3+) causes `ResourceManager` to either continuously reload or disable all resource packs due to shader initialisation failure with OptiFabric on 1.19.3 and 1.19.4.

### ISSUE THREAD

**Issue by akemin-dayo** [Chocohead/OptiFabric#1016]
**Mod compatibility:** [owo-lib](https://curseforge.com/minecraft/mc-mods/owo-lib/files/all) (dependency for [DeathLog](https://curseforge.com/minecraft/mc-mods/deathlog/files/all) as of 1.19.3+) causes `ResourceManager` to either continuously reload or disable all resource packs due to shader initialisation failure with OptiFabric on 1.19.3 and 1.19.4.

This occurs with a minimal mod set consisting of only:
* Fabric API
	* `0.76.0+1.19.4` (1.19.4)
	* `0.76.0+1.19.3` (1.19.3)
* owo-lib (※ DeathLog is not required to trigger this issue — simply having owo-lib be loaded is enough.)
	* `0.10.3+1.19.4` (1.19.4)
	* `0.10.3+1.19.3` (1.19.3)
* OptiFabric `1.13.24`
* OptiFine
	* 1.19.4 HD U I4 pre1
	* 1.19.4 HD U I3
	* 1.19.3 HD U I3

## Stack trace (1.19.4)
```
Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to initialized owo shader program
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:198) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:163) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1174) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[fabric-loader-0.14.18-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.18.jar:?]
Caused by: java.lang.RuntimeException: Failed to initialized owo shader program
	at io.wispforest.owo.shader.GlProgram.lambda$new$0(GlProgram.java:51) ~[owo-lib-0.10.3+1.19.4.jar:?]
	at net.minecraft.class_757.mdf76732$owo$lambda$loadAllTheShaders$0$1(class_757.java:2599) ~[client-intermediary.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at io.wispforest.owo.shader.GlProgram.forEachProgram(GlProgram.java:88) ~[owo-lib-0.10.3+1.19.4.jar:?]
	at net.minecraft.class_757.handler$zli000$owo$loadAllTheShaders(class_757.java:2599) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_34538(class_757.java:536) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:460) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:432) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 12 more
Caused by: net.minecraft.class_2973: Invalid shaders/core/spectrum.json: File not found
	at net.minecraft.class_2973.method_12856(class_2973.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:228) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:108) ~[client-intermediary.jar:?]
	at io.wispforest.owo.shader.GlProgram.lambda$new$0(GlProgram.java:49) ~[owo-lib-0.10.3+1.19.4.jar:?]
	at net.minecraft.class_757.mdf76732$owo$lambda$loadAllTheShaders$0$1(class_757.java:2599) ~[client-intermediary.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at io.wispforest.owo.shader.GlProgram.forEachProgram(GlProgram.java:88) ~[owo-lib-0.10.3+1.19.4.jar:?]
	at net.minecraft.class_757.handler$zli000$owo$loadAllTheShaders(class_757.java:2599) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_34538(class_757.java:536) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:460) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:432) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 12 more
Caused by: java.io.FileNotFoundException: owo:owo:shaders/core/spectrum.fsh
	at net.minecraft.class_5912.method_43043(class_5912.java:21) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.method_34579(class_5944.java:264) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:202) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:108) ~[client-intermediary.jar:?]
	at io.wispforest.owo.shader.GlProgram.lambda$new$0(GlProgram.java:49) ~[owo-lib-0.10.3+1.19.4.jar:?]
	at net.minecraft.class_757.mdf76732$owo$lambda$loadAllTheShaders$0$1(class_757.java:2599) ~[client-intermediary.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at io.wispforest.owo.shader.GlProgram.forEachProgram(GlProgram.java:88) ~[owo-lib-0.10.3+1.19.4.jar:?]
	at net.minecraft.class_757.handler$zli000$owo$loadAllTheShaders(class_757.java:2599) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_34538(class_757.java:536) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:460) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:432) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 12 more
```

## Stack trace (1.19.3)
```
Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to initialized owo shader program
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:198) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:163) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1144) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[fabric-loader-0.14.18-1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.18-1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.18.jar:?]
Caused by: java.lang.RuntimeException: Failed to initialized owo shader program
	at io.wispforest.owo.shader.GlProgram.lambda$new$0(GlProgram.java:51) ~[owo-lib-0.10.3+1.19.3.jar:?]
	at net.minecraft.class_757.md9f3c75$owo$lambda$loadAllTheShaders$0$1(class_757.java:2576) ~[client-intermediary.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at io.wispforest.owo.shader.GlProgram.forEachProgram(GlProgram.java:88) ~[owo-lib-0.10.3+1.19.3.jar:?]
	at net.minecraft.class_757.handler$zlj000$owo$loadAllTheShaders(class_757.java:2576) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_34538(class_757.java:531) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:455) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:427) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 13 more
Caused by: net.minecraft.class_2973: Invalid shaders/core/spectrum.json: File not found
	at net.minecraft.class_2973.method_12856(class_2973.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:226) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:106) ~[client-intermediary.jar:?]
	at io.wispforest.owo.shader.GlProgram.lambda$new$0(GlProgram.java:49) ~[owo-lib-0.10.3+1.19.3.jar:?]
	at net.minecraft.class_757.md9f3c75$owo$lambda$loadAllTheShaders$0$1(class_757.java:2576) ~[client-intermediary.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at io.wispforest.owo.shader.GlProgram.forEachProgram(GlProgram.java:88) ~[owo-lib-0.10.3+1.19.3.jar:?]
	at net.minecraft.class_757.handler$zlj000$owo$loadAllTheShaders(class_757.java:2576) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_34538(class_757.java:531) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:455) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:427) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 13 more
Caused by: java.io.FileNotFoundException: owo:owo:shaders/core/spectrum.fsh
	at net.minecraft.class_5912.method_43043(class_5912.java:21) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.method_34579(class_5944.java:261) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:200) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:106) ~[client-intermediary.jar:?]
	at io.wispforest.owo.shader.GlProgram.lambda$new$0(GlProgram.java:49) ~[owo-lib-0.10.3+1.19.3.jar:?]
	at net.minecraft.class_757.md9f3c75$owo$lambda$loadAllTheShaders$0$1(class_757.java:2576) ~[client-intermediary.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at io.wispforest.owo.shader.GlProgram.forEachProgram(GlProgram.java:88) ~[owo-lib-0.10.3+1.19.3.jar:?]
	at net.minecraft.class_757.handler$zlj000$owo$loadAllTheShaders(class_757.java:2576) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_34538(class_757.java:531) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:455) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:427) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 13 more
```

**Comment by bvhfve** [comment]
Same issue on 1.20/1.20.1
