### ISSUE TITLE
optifabric 1.19.4 crashing

### ISSUE THREAD

**Issue by Phossillikesfrog** [Chocohead/OptiFabric#1017]

**Comment by topia** [comment]
Please add additional information to clarify your problem; for example, the latest.log, using the optifine version, installed fabric mod/versions.

**Comment by rekryt** [comment]
fabric-api-0.76.0+1.19.4
optifabric-1.13.24
OptiFine_1.19.4_HD_U_I3_MOD
+
XaerosWorldMap_1.29.2_Fabric_1.19.4

XaerosWorldMap crashes client with optifabric, but without optifabric\optifine all works

**Comment by Phossillikesfrog** [comment]
i figured out the problem, replay mod kept crashing the game when optifabric was in my mods folder. can you guys try and fix that please.

**Comment by AugustusZebulon** [comment]
Here is my log from crashing with Replay Mod

[09:44:19] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.18
[09:44:19] [main/INFO]: Loading 67 mods:
	- appleskin 2.4.3+mc1.19.4
	- cloth-config 10.0.96
	   \-- cloth-basic-math 0.6.1
	- craftpresence 2.0.0-rc.1
	- eatinganimationid 1.9.3
	- entityculling 1.6.2-mc1.19.4
	- fabric-api 0.75.3+1.19.4
	   |-- fabric-api-base 0.4.23+9ff28bced8
	   |-- fabric-api-lookup-api-v1 1.6.24+49abcf7ed8
	   |-- fabric-biome-api-v1 13.0.5+fe9afa9dd8
	   |-- fabric-block-api-v1 1.0.5+e022e5d1d8
	   |-- fabric-blockrenderlayer-v1 1.1.33+c2e6f674d8
	   |-- fabric-client-tags-api-v1 1.0.14+1134c5b8d8
	   |-- fabric-command-api-v1 1.2.25+f71b366fd8
	   |-- fabric-command-api-v2 2.2.4+ae0966bad8
	   |-- fabric-commands-v0 0.2.42+df3654b3d8
	   |-- fabric-containers-v0 0.1.51+df3654b3d8
	   |-- fabric-content-registries-v0 3.5.6+ae0966bad8
	   |-- fabric-convention-tags-v1 1.3.0+6baaf971d8
	   |-- fabric-crash-report-info-v1 0.2.14+aeb40ebed8
	   |-- fabric-data-generation-api-v1 11.3.4+5da15ca1d8
	   |-- fabric-dimensions-v1 2.1.44+7f87f8fad8
	   |-- fabric-entity-events-v1 1.5.12+e45f7c65d8
	   |-- fabric-events-interaction-v0 0.4.42+a1ccd7bfd8
	   |-- fabric-events-lifecycle-v0 0.2.50+df3654b3d8
	   |-- fabric-game-rule-api-v1 1.0.32+a1ccd7bfd8
	   |-- fabric-item-api-v1 2.1.15+ae0966bad8
	   |-- fabric-item-group-api-v1 3.0.2+e45f7c65d8
	   |-- fabric-key-binding-api-v1 1.0.32+c477957ed8
	   |-- fabric-keybindings-v0 0.2.30+df3654b3d8
	   |-- fabric-lifecycle-events-v1 2.2.14+5da15ca1d8
	   |-- fabric-loot-api-v2 1.1.24+75e98211d8
	   |-- fabric-loot-tables-v1 1.1.28+9e7660c6d8
	   |-- fabric-message-api-v1 5.1.0+1ee8be40d8
	   |-- fabric-mining-level-api-v1 2.1.36+49abcf7ed8
	   |-- fabric-models-v0 0.3.29+11ba9c3bd8
	   |-- fabric-networking-v0 0.3.38+df3654b3d8
	   |-- fabric-object-builder-api-v1 7.0.0+63b515f4d8
	   |-- fabric-particles-v1 1.0.22+f1e4495bd8
	   |-- fabric-recipe-api-v1 1.0.5+a1ccd7bfd8
	   |-- fabric-registry-sync-v0 2.1.1+a383ab97d8
	   |-- fabric-renderer-api-v1 2.2.4+81e8c576d8
	   |-- fabric-renderer-indigo 1.1.0+81e8c576d8
	   |-- fabric-renderer-registries-v1 3.2.36+df3654b3d8
	   |-- fabric-rendering-data-attachment-v1 0.3.27+afca2f3ed8
	   |-- fabric-rendering-fluids-v1 3.0.20+f1e4495bd8
	   |-- fabric-rendering-v0 1.1.39+df3654b3d8
	   |-- fabric-rendering-v1 2.0.2+ae0966bad8
	   |-- fabric-resource-conditions-api-v1 2.3.0+e6c7d4eed8
	   |-- fabric-screen-api-v1 1.0.44+8c25edb4d8
	   |-- fabric-screen-handler-api-v1 1.3.17+5da15ca1d8
	   |-- fabric-sound-api-v1 1.0.8+75e98211d8
	   |-- fabric-transfer-api-v1 3.0.1+9003cbe9d8
	   \-- fabric-transitive-access-wideners-v1 3.0.2+63b515f4d8
	- fabricloader 0.14.18
	- ferritecore 5.2.0
	- gammautils 1.6.14
	- java 19
	- minecraft 1.19.4
	- modmenu 6.1.0-rc.4
	   \-- fabric-resource-loader-v0 0.11.0+938a1d56f4
	- optifabric 1.13.24
	   \-- mm 2.3
	- replaymod 1.19.4-2.6.11
	   |-- fabric-networking-api-v1 1.2.22+ca5f59aaf4
	   \-- fabric-resource-loader-v0 0.11.0+938a1d56f4
	- starlight 1.1.1+fabric.ae22326
	- visuality 0.7.0
[09:44:19] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/maksi/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[09:44:19] [main/INFO]: Compatibility level set to JAVA_17
[09:44:19] [main/WARN]: Reference map 'mixins.nonmmlauncher.replaymod.refmap.json' for mixins.nonmmlauncher.replaymod.json could not be read. If this is a development environment you can ignore this message
Found existing patched optifine jar, using that
Replay Mod is still using the traditional Early Riser initialisation
[09:44:20] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[09:44:20] [main/WARN]: Error loading class: net/coderbot/iris/uniforms/CommonUniforms (java.lang.ClassNotFoundException: net/coderbot/iris/uniforms/CommonUniforms)
[09:44:20] [main/WARN]: Error loading class: net/coderbot/iris/Iris (java.lang.ClassNotFoundException: net/coderbot/iris/Iris)
[09:44:20] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[09:44:20] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[09:44:21] [main/ERROR]: Mixin apply for mod replaymod failed mixins.jgui.json:MixinKeyboardListener from mod replaymod -> net.minecraft.class_309: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException 'static' modifier of handler method does not match target in net/minecraft/class_309::charTypedOptifine [PREINJECT Applicator Phase -> mixins.jgui.json:MixinKeyboardListener from mod replaymod -> Prepare Injections ->  -> handler$zma000$replaymod$charTypedOptifine(CILnet/minecraft/class_364;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: 'static' modifier of handler method does not match target in net/minecraft/class_309::charTypedOptifine [PREINJECT Applicator Phase -> mixins.jgui.json:MixinKeyboardListener from mod replaymod -> Prepare Injections ->  -> handler$zma000$replaymod$charTypedOptifine(CILnet/minecraft/class_364;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.checkTargetModifiers(Injector.java:347) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.sanityCheck(CallbackInjector.java:425) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:237) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.18.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Unknown Source) ~[?:?]
	at java.lang.Class.getDeclaredFields(Unknown Source) ~[?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) ~[Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:503) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:152) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.18.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[09:44:21] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:464) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.18.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_128.method_568(class_128.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:152) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
	... 5 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_309 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.18.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Unknown Source) ~[?:?]
	at java.lang.Class.getDeclaredFields(Unknown Source) ~[?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) ~[Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:503) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:152) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.18.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Unknown Source) ~[?:?]
	at java.lang.Class.getDeclaredFields(Unknown Source) ~[?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) ~[Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:503) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:152) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.jgui.json:MixinKeyboardListener from mod replaymod] from phase [DEFAULT] in config [mixins.jgui.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.18.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Unknown Source) ~[?:?]
	at java.lang.Class.getDeclaredFields(Unknown Source) ~[?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) ~[Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:503) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:152) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: 'static' modifier of handler method does not match target in net/minecraft/class_309::charTypedOptifine [PREINJECT Applicator Phase -> mixins.jgui.json:MixinKeyboardListener from mod replaymod -> Prepare Injections ->  -> handler$zma000$replaymod$charTypedOptifine(CILnet/minecraft/class_364;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.checkTargetModifiers(Injector.java:347) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.sanityCheck(CallbackInjector.java:425) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:237) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.18.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Unknown Source) ~[?:?]
	at java.lang.Class.getDeclaredFields(Unknown Source) ~[?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) ~[Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:503) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:152) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
	... 5 more
Process exited with code 1.

**Comment by kiwi-sheep** [comment]
The exact same issue has happened to me.

**Comment by Foxtrickx** [comment]
I am also having the same issue! Thank you for the issue report; otherwise, I may have gone crazy trying to figure this out!

**Comment by WinterGrave** [comment]
Having the same issue, need optifabric working with replay mod.

**Comment by Fasteroid** [comment]
Same issue here as well, but I only have nochatreports installed.

**Comment by Notplayingallday383** [comment]
Same issue here but somehow other people are getting onto 1.19.4 without issues. I've tried using Archives of Preview builds Optifine 1.19.4 (I3 Pre1) and it didn't work

**Comment by LightslicerGP** [comment]
I was going through every single mod and seeing which crashes my game, and to my surprise, out of all the mods it was replay mod

please fix this 😭

**Comment by Sparkening** [comment]
I have the same issue and I just prefer Optifine and cant really see myself switching to sodium. But unfortunately I really enjoy using Replaymod which sadly doesnt seem to be working anymore. I quote a admin from the replaymod discord "Optifine breaks Minecraft and other mods and we don't offer any support for it." which is a bummer since it's been working quite well for some time.

**Comment by Notplayingallday383** [comment]
I guess that explains it since I think were all using replaymod.

**Comment by SachinSAgrawal** [comment]
Hello! I am having a similar issue. I have OptiFabric and OptiFine installed, and when launching with the ReplayMod, my game crashes with error code 1. I talked to a dev from ReplayMod, and they said that OptiFine is too poorly written that it does not allow the mixin from ReplayMod to be applied. They said that it was also not worth their time or effort trying to fix it, but I hope that the devs of OptiFabric (or OptiFine) do something about it, but until then, the ReplayMod will be getting a bad rep from me.

**Comment by WinterGrave** [comment]
In my case I'm forced to use optifine since I heavily rely con custom entity models and do cinematics for youtube, no other mod offers reliable support for custom entity models as optifine does.

**Comment by ssyuk** [comment]
In my friend's case, there is only Optifabric without a replay mode, but an error occurs.

**Comment by PebbleCat-Studios** [comment]
Yah, I use OptiFabric with the Replay mod, and it crashes instantly, but without it, it boots up fine. I'm using 1.20.2.
