### ISSUE TITLE
Minecraft OptiFabric crash 

### ISSUE THREAD

**Issue by PatrickC1324** [Chocohead/OptiFabric#1022]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'OptiFabric' (optifabric) 1.13.16 with any version that is compatible with:
		 - minecraft 1.19.4
Unmet dependency listing:
	 - Mod 'OptiFabric' (optifabric) 1.13.16 requires version 1.16.1, version 1.16.2, version 1.16.3, version 1.16.4, version 1.16.5, version 1.17-alpha.21.8.b, version 1.17-beta.4, version 1.17, version 1.17.1, version 1.18-beta.1, version 1.18, version 1.18.1, version 1.18.2, version 1.19, version 1.19.1 or version 1.19.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by topia** [comment]
Please read the message again. your installed optifabric is not compatible with Minecraft 1.19.4. please download the "BETA" optifabric from curseforge.

**Comment by PatrickC1324** [comment]
that's the one I've been downloading.

**Comment by topia** [comment]
I can't replicate your problem.
![image](https://user-images.githubusercontent.com/13070/228922798-02178250-757c-418d-a3a4-71d7b5c5e0e4.png)
Could you try downloading "B" optifabric 1.13.24 again? your log mentioned optifabric 1.13.16, it should be the "R" version.

**Comment by PatrickC1324** [comment]
I figured out that it does not work with the journey map mod.

**Comment by PatrickC1324** [comment]
Or actually, I had an outdated version of the journey map, thank you for the help tho.
