### ISSUE TITLE
Mod Incompatibility Carpet Mod [1.19.4 - v230319.jar]

### ISSUE THREAD

**Issue by stuntguy3000** [Chocohead/OptiFabric#1029]
https://github.com/gnembon/fabric-carpet/releases/tag/1.4.101

Hi All,

Just reporting a game crash where OptiFabric is not working with CarpetMod.

```
[11:49:58] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.19
[11:49:58] [main/INFO]: Loading 56 mods:
	- carpet 1.4.101+v230319
	- fabric-api 0.77.0+1.19.4
	   |-- fabric-api-base 0.4.23+9ff28bcef4
	   |-- fabric-api-lookup-api-v1 1.6.24+49abcf7ef4
	   |-- fabric-biome-api-v1 13.0.6+348a9c64f4
	   |-- fabric-block-api-v1 1.0.5+e022e5d1f4
	   |-- fabric-blockrenderlayer-v1 1.1.33+c2e6f674f4
	   |-- fabric-client-tags-api-v1 1.0.14+1134c5b8f4
	   |-- fabric-command-api-v1 1.2.25+f71b366ff4
	   |-- fabric-command-api-v2 2.2.4+ae0966baf4
	   |-- fabric-commands-v0 0.2.42+df3654b3f4
	   |-- fabric-containers-v0 0.1.53+df3654b3f4
	   |-- fabric-content-registries-v0 3.5.7+ae0966baf4
	   |-- fabric-convention-tags-v1 1.4.0+9a7c5daaf4
	   |-- fabric-crash-report-info-v1 0.2.14+aeb40ebef4
	   |-- fabric-data-generation-api-v1 11.3.6+5da15ca1f4
	   |-- fabric-dimensions-v1 2.1.44+7f87f8faf4
	   |-- fabric-entity-events-v1 1.5.12+e45f7c65f4
	   |-- fabric-events-interaction-v0 0.4.42+a1ccd7bff4
	   |-- fabric-events-lifecycle-v0 0.2.51+df3654b3f4
	   |-- fabric-game-rule-api-v1 1.0.32+a1ccd7bff4
	   |-- fabric-item-api-v1 2.1.16+09a3510cf4
	   |-- fabric-item-group-api-v1 3.0.3+043f9acff4
	   |-- fabric-key-binding-api-v1 1.0.32+c477957ef4
	   |-- fabric-keybindings-v0 0.2.30+df3654b3f4
	   |-- fabric-lifecycle-events-v1 2.2.14+5da15ca1f4
	   |-- fabric-loot-api-v2 1.1.25+75e98211f4
	   |-- fabric-loot-tables-v1 1.1.29+9e7660c6f4
	   |-- fabric-message-api-v1 5.1.0+1ee8be40f4
	   |-- fabric-mining-level-api-v1 2.1.37+49abcf7ef4
	   |-- fabric-models-v0 0.3.29+11ba9c3bf4
	   |-- fabric-networking-api-v1 1.3.0+a6f3ccfaf4
	   |-- fabric-networking-v0 0.3.40+df3654b3f4
	   |-- fabric-object-builder-api-v1 7.0.1+63b515f4f4
	   |-- fabric-particles-v1 1.0.22+f1e4495bf4
	   |-- fabric-recipe-api-v1 1.0.7+a1ccd7bff4
	   |-- fabric-registry-sync-v0 2.1.3+a383ab97f4
	   |-- fabric-renderer-api-v1 2.2.4+81e8c576f4
	   |-- fabric-renderer-indigo 1.1.0+81e8c576f4
	   |-- fabric-renderer-registries-v1 3.2.37+df3654b3f4
	   |-- fabric-rendering-data-attachment-v1 0.3.27+afca2f3ef4
	   |-- fabric-rendering-fluids-v1 3.0.20+f1e4495bf4
	   |-- fabric-rendering-v0 1.1.40+df3654b3f4
	   |-- fabric-rendering-v1 2.1.0+8f878217f4
	   |-- fabric-resource-conditions-api-v1 2.3.0+e6c7d4eef4
	   |-- fabric-resource-loader-v0 0.11.0+938a1d56f4
	   |-- fabric-screen-api-v1 1.0.44+8c25edb4f4
	   |-- fabric-screen-handler-api-v1 1.3.19+5da15ca1f4
	   |-- fabric-sound-api-v1 1.0.8+75e98211f4
	   |-- fabric-transfer-api-v1 3.0.1+9003cbe9f4
	   \-- fabric-transitive-access-wideners-v1 3.0.2+63b515f4f4
	- fabricloader 0.14.19
	- java 17
	- minecraft 1.19.4
	- optifabric 1.13.24
	   \-- mm 2.3
[11:49:58] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/stunt/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[11:49:59] [main/INFO]: Compatibility level set to JAVA_17
[11:50:02] [main/ERROR]: Mixin apply for mod optifabric failed optifabric.compat.carpet.extra-new-mixins.json:LevelRendererExtraMixin from mod optifabric -> net.minecraft.class_761: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyVariable annotation on doNewChangeTickPhaseBack could not find any targets matching 'Lnet/minecraft/class_761;method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V' in net.minecraft.class_761. Using refmap optifabric-refmap.json [PREINJECT Applicator Phase -> optifabric.compat.carpet.extra-new-mixins.json:LevelRendererExtraMixin from mod optifabric -> Prepare Injections ->  -> localvar$bec000$optifabric$doNewChangeTickPhaseBack(F)F -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyVariable annotation on doNewChangeTickPhaseBack could not find any targets matching 'Lnet/minecraft/class_761;method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V' in net.minecraft.class_761. Using refmap optifabric-refmap.json [PREINJECT Applicator Phase -> optifabric.compat.carpet.extra-new-mixins.json:LevelRendererExtraMixin from mod optifabric -> Prepare Injections ->  -> localvar$bec000$optifabric$doNewChangeTickPhaseBack(F)F -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.ModifyVariableInjectionInfo.<init>(ModifyVariableInjectionInfo.java:45) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:277) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:152) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
[11:50:03] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:464) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_128.method_568(class_128.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:152) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_761 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:277) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:152) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:277) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:152) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [optifabric.compat.carpet.extra-new-mixins.json:LevelRendererExtraMixin from mod optifabric] from phase [DEFAULT] in config [optifabric.compat.carpet.extra-new-mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:277) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:152) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyVariable annotation on doNewChangeTickPhaseBack could not find any targets matching 'Lnet/minecraft/class_761;method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V' in net.minecraft.class_761. Using refmap optifabric-refmap.json [PREINJECT Applicator Phase -> optifabric.compat.carpet.extra-new-mixins.json:LevelRendererExtraMixin from mod optifabric -> Prepare Injections ->  -> localvar$bec000$optifabric$doNewChangeTickPhaseBack(F)F -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.ModifyVariableInjectionInfo.<init>(ModifyVariableInjectionInfo.java:45) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:277) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:152) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 2 more
```

Thanks

**Comment by theredfire99** [comment]
I have the same issue

**Comment by RosieTheGhostie** [comment]
I'm not a OptiFabric developer, but I was hoping to find a solution to this for my own purposes. Out of curiosity, I disabled OptiFine and kept OptiFabric installed, and the game managed to boot. It wouldn't go past a screen saying OptiFine wasn't found, but that was to be expected. Based on how the mod supposedly works (as per the README), I'm guessing OptiFabric is replacing one or more classes with their OptiFine counterparts while Carpet still looks for them by their original names. I may be incorrect, but that's just my guess. If I make any more developments, I'll update this comment.

**Comment by RefriZaddo** [comment]
im having the same problem
mods i use:

Carpet

Fabric API (duh)

FerriteCore

Gravity API

Immersive Portals

Indium

Iris

JEI

Mod Menu

Pehkui

Sodium
