### ISSUE TITLE
DarkKore-0.3.4-1.19.3 is incompatible with optifabric-1.13.24

### ISSUE THREAD

**Issue by GxEma17** [Chocohead/OptiFabric#1038]
hi when i try to open minecraft (fabric) with DarkKore-0.3.4-1.19.3 and optifabric-1.13.24 the game crash giving this error:
The game crashed whilst initialising game
Error: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921

Crash Reportt:
---- Minecraft Crash Report ----
// You're mean.

Time: 2023-04-19 16:49:36
Description: Initializing game

java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
	at net.minecraft.class_380.<init>(class_380.java:29)
	at net.minecraft.class_377.method_2012(class_377.java:163)
	at net.minecraft.class_7191.bake(class_7191.java:53)
	at net.minecraft.class_377.method_2004(class_377.java:53)
	at net.minecraft.class_378.method_27540(class_378.java:45)
	at net.minecraft.class_156.method_654(class_156.java:486)
	at net.minecraft.class_378.<init>(class_378.java:45)
	at net.minecraft.class_310.<init>(class_310.java:540)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_380.<init>(class_380.java:29)
	at net.minecraft.class_377.method_2012(class_377.java:163)
	at net.minecraft.class_7191.bake(class_7191.java:53)
	at net.minecraft.class_377.method_2004(class_377.java:53)
	at net.minecraft.class_378.method_27540(class_378.java:45)
	at net.minecraft.class_156.method_654(class_156.java:486)
	at net.minecraft.class_378.<init>(class_378.java:45)
	at net.minecraft.class_310.<init>(class_310.java:540)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:API Windows 32 Base avanzato:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:Libreria di controlli per le azioni dell'utente:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		ColorAdapterClient.dll:Microsoft Color Adapter Client:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.19041.2193:Microsoft Corporation
		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.19041.546:Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.19041.867 (WinBuild.160101.0800):Microsoft Corporation
		DEVOBJ.dll:Device Information Set DLL:10.0.19041.1620 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DLL API client DNS:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		GLU32.dll:OpenGL Utility Library DLL:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.2673 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:API helper IP:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:DLL client di Windows NT BASE API:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:DLL client di Windows NT BASE API:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		MMDevApi.dll:API MMDevice:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:MSCTF Server DLL:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.2303.8 (WinBuild.160101.0800):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.19041.2193 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.19041.610 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE per Windows:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.19041.985 (WinBuild.160101.0800):Microsoft Corporation
		OpenAL.dll:Main implementation library:1.21.1:
		PROPSYS.dll:Sistema di proprietà Microsoft:7.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:DLL helper Dati di prestazione di Windows:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Runtime RPC (Remote Procedure Call):10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:DLL comune della shell di Windows:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Servizi HTTP Windows:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:DLL API MCI:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:DLL a 32 bit di Windows Socket 2.0:10.0.19041.1081 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		Wldp.dll:Criterio di blocco di Windows:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.19041.2075 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Libreria primitive di crittografia di Windows:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.2486 (WinBuild.160101.0800):Microsoft Corporation
		cfgmgr32.dll:Configuration Manager DLL:10.0.19041.1620 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM per Windows:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.2311 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:Servizio Client DHCP:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:Client DHCPv6:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		dinput8.dll:Microsoft DirectInput:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		dwmapi.dll:API di Gestione finestre desktop Microsoft:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		dxgi.dll:DirectX Graphics Infrastructure:10.0.19041.2311 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:API modalità utente FWP/IPsec:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		icm32.dll:Microsoft Color Management Module (CMM):10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		ig9icd64.dll:OpenGL(R) Driver for Intel(R) Graphics Accelerator:27.20.100.8280:Intel Corporation
		igc64.dll:Intel Graphics Shader Compiler for Intel(R) Graphics Accelerator:27.20.100.8280:Intel Corporation
		igdgmm64.dll:User Mode Driver for Intel(R) Graphics Technology:27.20.100.8280:Intel Corporation
		igdml64.dll:Metrics Library for Intel(R) Graphics Technology:27.20.100.8280:Intel Corporation
		inputhost.dll:InputHost:10.0.19041.1741 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.3.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		jna15152362996691540949.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:17.0.3.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		lwjgl_opengl.dll
		lwjgl_stb.dll
		management.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		mscms.dll:DLL sistema di corrispondenza colori Microsoft:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Service Provider Microsoft Windows Sockets 2.0:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:Provider shim denominazione posta elettronica:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		ntdll.dll:DLL del livello NT:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		ntmarta.dll:Provider MARTA per Windows NT:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		opengl32.dll:OpenGL Client DLL:10.0.19041.2193 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:DLL oggetti delle prestazioni del sistema Windows:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		perfproc.dll:DLL oggetti delle prestazioni del processo di Windows:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:Provider spazio dei nomi PNRP:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		powrprof.dll:DLL helper del profilo di alimentazione:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.19041.844 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Libreria leggera di utilità per la shell:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		textinputframework.dll:"TextInputFramework.DYNLINK":10.0.19041.2546 (WinBuild.160101.0800):Microsoft Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		uxtheme.dll:Libreria UxTheme di Microsoft:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		win32u.dll:Win32u:10.0.19041.2728 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:API archiviazione Microsoft WinRT:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:DLL tipi di base Windows:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		xinput1_4.dll:API periferica comune Microsoft:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 255023272 bytes (243 MiB) / 536870912 bytes (512 MiB) up to 3221225472 bytes (3072 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 12
	Microarchitecture: Whiskey Lake
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9b41
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8280
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 17438.34
	Virtual memory used (MB): 7061.97
	Swap memory total (MB): 9415.29
	Swap memory used (MB): 1058.11
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.16
		advancedchatcore: AdvancedChatCore 1.19.3-1.5.9
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_github_darkkronicle_konstruct_addons: addons 2.0.3-build1
			com_github_darkkronicle_konstruct_core: core 2.0.3-build1
			io_github_maowimpl_owo: owo 2.0.0
			org_apache_commons_commons-csv: commons-csv 1.8
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 4.4.2
		advancedchathud: AdvancedChatHUD 1.19.3-1.3.7
		appleskin: AppleSkin 2.4.2+mc1.19.3
		architectury: Architectury 7.1.70
		armorchroma: Armor Chroma 1.2.4
		autoclicker-fabric: Auto Clicker 1.19.3-1.5.1-build.23
		autoswitch: AutoSwitch 6.0.2
			autoswitch-api: AutoSwitch API 3.0.0
		balm-fabric: Balm 5.0.4
		betterf3: BetterF3 5.1.0
		betterhurtcam: BetterHurtCam 1.5.2
			betterhurtcam-mc1193: BetterHurtCam+mc1.19.3 1.5.2
		boostedbrightness: Boosted Brightness 2.1.3
		brb: Better Recipe Book 1.7.0
		camerautils: Camera Utils 1.19.3-1.0.3
		cloth-config: Cloth Config v9 9.0.94
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+16
		cmdkeybind: Command Macros 1.6.0-1.19.3
			kyrptconfig: Kyrpt Config 1.5.1-1.19.3
		collective: Collective 6.53
		craftingtweaks: Crafting Tweaks 16.0.2
		darkkore: DarkKore 0.3.4-1.19.3
			com_electronwill_night-config_json: json 3.6.5
			satin: Satin 1.10.0
		dashloader: DashLoader 5.0.0-alpha.13+1.19.3
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.3
			dev_quantumfusion_taski: Taski 2.1.0
		dcch: DCCH 1.2
		eatinganimationid: Eating Animation 1.9.2
		ecs: Elytra/Chestplate Swapper 1.3.0-MC1.19
		fabric-api: Fabric API 0.76.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.21+70be179c85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.20+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.2+f1c68e5885
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d185
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.31+928d44d585
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.12+1134c5b885
			fabric-command-api-v1: Fabric Command API (v1) 1.2.22+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.39+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.47+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+521b5c5285
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.2+40dc7a9485
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.42+00a2eb1085
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.7+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.40+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.45+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.30+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.11+71b8257385
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.13+b5470ac785
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.31+bc01e09785
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.29+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.10+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.21+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.25+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+c85585f885
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.32+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.27+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.17+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.34+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.2+eb2a3ba985
			fabric-particles-v1: Fabric Particles (v1) 1.0.20+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.0+f7b4d36485
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.2+3a95925a85
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+3a95925a85
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.31+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.25+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.18+f1e4495b85
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.34+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.13.0+ad17775585
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e63306e085
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.0+68296ad585
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.41+f1e4495b85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.13+99f9db8085
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.15+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.1+40dc7a9485
		fabric-language-kotlin: Fabric Language Kotlin 1.9.2+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.18
		farsight: Farsight Mod 1.19-3.4
			com_github_jctools_jctools_jctools-core: jctools-core v4.0.1
		ferritecore: FerriteCore 5.1.0
		forgeconfigapiport: Forge Config API Port 5.0.11
		forgetmechunk: Forget Me Chunk 1.0.4-1.18.X-1.19.X
		fpsreducer: FPS Reducer 1.19.3-2.2
		freecam: Freecam 1.1.8+1.19
		freelook: freelook 1.1.2
		inventoryhud: Inventory HUD + 3.4.7
		inventoryprofilesnext: Inventory Profiles Next 1.9.4
		itemscroller: Item Scroller 0.18.0
		jamlib: JamLib 0.6.0+1.19.3
		java: OpenJDK 64-Bit Server VM 17
		kronhud: KronHUD 1.19.3-2.2.4
		lazydfu: LazyDFU 0.1.3
		libipn: libIPN 2.0.4
		litematica: Litematica 0.13.2
		lowfire: Low Fire 1.19.3-3.0.1
		malilib: MaLiLib 0.14.0
		minecraft: Minecraft 1.19.3
		minihud: MiniHUD 0.25.0
		mobplaques: Mob Plaques 5.0.0
		modmenu: Mod Menu 5.0.2
		notenoughanimations: NotEnoughAnimations 1.6.3
		notenoughcrashes: Not Enough Crashes 4.4.0+1.19.3
		optifabric: OptiFabric 1.13.24
			mm: Manningham Mills 2.3
		phosphor: Phosphor 0.8.1
		puzzleslib: Puzzles Lib 5.0.19
		rightclickharvest: Right Click Harvest 3.1.0+1.19.3
		roughlyenoughitems: Roughly Enough Items 10.0.596
			error_notifier: Error Notifier 1.0.9
		shulkerboxtooltip: Shulker Box Tooltip 3.2.4+1.19.3
		signtools: Sign Tools 1.0.3
		skinlayers: 3d Skin Layers 1.5.3-mc1.19.3
		spark: spark 1.10.29
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		titlefixer: Title Fixer 1.0+1.19.3
		tweakeroo: Tweakeroo 0.15.0
		ukulib: ukulib 0.6.1+1.19.3
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			gs_mclo_java_mclogs-java: mclogs-java 2.1.1
		worldedit: WorldEdit 7.2.13+46576cc
	Launched Version: fabric-loader-0.14.18-1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) UHD Graphics GL version 3.2.0 - Build 27.20.100.8280, Intel
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
	OptiFine Version: OptiFine_1.19.3_HD_U_I3
	OptiFine Build: 20230324-184409
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 - Build 27.20.100.8280
	OpenGlRenderer: Intel(R) UHD Graphics
	OpenGlVendor: Intel
	CpuCount: 4
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader)

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.19.3
	OptiFine jar version: OptiFine_1.19.3_HD_U_I3
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/clown/AppData/Roaming/.minecraft/.optifine/OptiFine_1.19.3_HD_U_I3/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by desplmfao** [comment]
just use sodium
