### ISSUE TITLE
Minecraft 1.16.5 - "Failed to load OptiFine, please report this!"

### ISSUE THREAD

**Issue by dndin10** [Chocohead/OptiFabric#1042]
When the mojang screen is done loading, shows this error instead of Title Screen. Im using minecraft version 1.16.5 and fabric 0.14.19

![image](https://user-images.githubusercontent.com/132314680/235555830-1a328cbf-fc2a-4a82-8771-f622886447d2.png)

Mods folder
![image](https://user-images.githubusercontent.com/132314680/235555954-ee979d55-140b-43f7-9dff-66be45f0c67c.png)

Stack trace
java.lang.NoSuchMethodError: net.fabricmc.loader.FabricLoader.getGameProvider()Lnet/fabricmc/loader/game/GameProvider;
	at me.modmuss50.optifabric.mod.OptifineSetup.getLaunchMinecraftJar(OptifineSetup.java:299)
	at me.modmuss50.optifabric.mod.OptifineSetup.getMinecraftJar(OptifineSetup.java:277)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:84)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by semka123321** [comment]
I have the same problem, I advise you to contact the neural network, for example, deepseek
