### ISSUE TITLE
Incompatability DarkKore / KronHud

### ISSUE THREAD

**Issue by MrKinau** [Chocohead/OptiFabric#1058]
Joining a server with a custom resource pack is almost impossible with DarkKore + Optifabric installed as the resources either constantly reloading, preventing you from joining the server or the loading screen is stuck at about 90%. In any case it'll print this error to the log:

```
[18:19:01] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "resourceName" is null
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:198) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:163) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1174) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "resourceName" is null
	at net.minecraft.class_2960.method_12830(class_2960.java:88) ~[client-intermediary.jar:?]
	at net.minecraft.class_2960.<init>(class_2960.java:51) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.impl.client.rendering.FabricShaderProgram.rewriteAsId(FabricShaderProgram.java:42) ~[fabric-rendering-v1-2.1.2+504944c8f4-d3f123cd32cf48f7.jar:?]
	at net.minecraft.class_5944.modify$zih000$fabric-rendering-v1$modifyProgramId(class_5944.java:654) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.localvar$zlg000$optifabric$modifyProgramID(class_5944.java:2134) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:108) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.impl.client.rendering.FabricShaderProgram.<init>(FabricShaderProgram.java:28) ~[fabric-rendering-v1-2.1.2+504944c8f4-d3f123cd32cf48f7.jar:?]
	at ladysnake.satin.impl.ResettableManagedCoreShader.parseShader(ResettableManagedCoreShader.java:59) ~[satin-1.11.0-f41dc2b8f92e7997.jar:?]
	at ladysnake.satin.impl.ResettableManagedCoreShader.parseShader(ResettableManagedCoreShader.java:37) ~[satin-1.11.0-f41dc2b8f92e7997.jar:?]
	at ladysnake.satin.impl.ResettableManagedShaderBase.initialize(ResettableManagedShaderBase.java:75) ~[satin-1.11.0-f41dc2b8f92e7997.jar:?]
	at ladysnake.satin.impl.ResettableManagedShaderBase.initializeOrLog(ResettableManagedShaderBase.java:63) ~[satin-1.11.0-f41dc2b8f92e7997.jar:?]
	at ladysnake.satin.impl.ReloadableShaderEffectManager.method_14491(ReloadableShaderEffectManager.java:118) ~[satin-1.11.0-f41dc2b8f92e7997.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
```

Using:
- OptiFine_1.19.4_HD_U_I4
- optifabric-1.13.24
- fabric-api-0.80.0+1.19.4
- DarkKore-0.3.5-1.19.4

**Comment by itsMarkiS** [comment]
this is cause of Satin API which is included in darkkore... i hate it so much
