### ISSUE TITLE
Incompatible with Sodium and Stack to Nearby Chests

### ISSUE THREAD

**Issue by ThunderStorm0203** [Chocohead/OptiFabric#1100]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Stack to Nearby Chests' (stack-to-nearby-chests) 0.3.1 with any version that is compatible with:
		 - optifabric 1.13.25
	 - Replace mod 'Sodium' (sodium) 0.4.10+build.27 with version 0.4.10 that is compatible with:
		 - optifabric 1.13.25
Unmet dependency listing:
	 - Mod 'Sodium' (sodium) 0.4.10+build.27 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.25!
	 - Mod 'Stack to Nearby Chests' (stack-to-nearby-chests) 0.3.1 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.25!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by AuroraDoesCode** [comment]
Sodium rewrites the rendering engine like Optifine so its never gonna be compatible. 

As for Stack to Nearby chests, the mod author has flagged that its Incompatible with Optifabric, so its not up to Chocohead, but the developer of Stack to Chests that needs to fix that. Its probably due to optifine changes.

**Comment by ThunderStorm0203** [comment]
Now I got the problem...
