### ISSUE TITLE
Game crashes upon loading world

### ISSUE THREAD

**Issue by MemeKueen2** [Chocohead/OptiFabric#1106]
After installing the latest Optifabric for 1.20.1 and attempting to load in a new world, after the the loading sequence with the square fully loading in to 100% but before I can actually see the world, the game crashes. This is the exit code I'm getting: 
![image](https://github.com/Chocohead/OptiFabric/assets/139596661/3cb09f1b-bbb7-4cb4-a98d-0c71d1a37991)
and this is the crash report:

---- Minecraft Crash Report ----
// Don't do that.

Time: 2023-07-14 19:11:53
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.setSampler(int, Object)" because "shaderinstance" is null
	at net.minecraft.class_761.method_3251(class_761.java:2365)
	at net.minecraft.class_761.method_22710(class_761.java:1716)
	at net.minecraft.class_757.method_3188(class_757.java:1651)
	at net.minecraft.class_757.method_3192(class_757.java:1279)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_761.method_3251(class_761.java:2365)
	at net.minecraft.class_761.method_22710(class_761.java:1716)
	at net.minecraft.class_757.method_3188(class_757.java:1651)

-- Affected level --
Details:
	All players: 1 total; [class_746['Meme_Kueen'/99, l='ClientLevel', x=-20.54, y=102.37, z=45.75]]
	Chunk stats: 1849, 850
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,112,0), Section: (at 0,0,0 in 0,7,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 870 game time, 870 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:590)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, file/pmc-mob-pack-wolf_tame_mutt-terrier-5884681.zip, fabric
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "resourceName" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.method_18859(class_1255.java:198)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:163)
	at net.minecraft.class_1255.method_5383(class_1255.java:140)
	at net.minecraft.class_310.method_1523(class_310.java:1175)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "resourceName" is null
	at net.minecraft.class_2960.method_12830(class_2960.java:95)
	at net.minecraft.class_2960.<init>(class_2960.java:58)
	at net.fabricmc.fabric.impl.client.rendering.FabricShaderProgram.rewriteAsId(FabricShaderProgram.java:42)
	at net.minecraft.class_5944.modify$bbo000$fabric-rendering-v1$modifyProgramId(class_5944.java:654)
	at net.minecraft.class_5944.localvar$bia000$optifabric$modifyProgramID(class_5944.java:1634)
	at net.minecraft.class_5944.<init>(class_5944.java:114)
	at net.minecraft.class_5944.<init>(class_5944.java:108)
	at net.fabricmc.fabric.impl.client.rendering.FabricShaderProgram.<init>(FabricShaderProgram.java:28)
	at net.minecraft.class_757.md6bba87$fabric-rendering-v1$lambda$registerShaders$0$0(class_757.java:1639)
	at io.github.cottonmc.cotton.gui.impl.client.LibGuiShaders.lambda$register$1(LibGuiShaders.java:18)
	at net.fabricmc.fabric.api.client.rendering.v1.CoreShaderRegistrationCallback.lambda$static$0(CoreShaderRegistrationCallback.java:44)
	at net.minecraft.class_757.handler$bbm000$fabric-rendering-v1$registerShaders(class_757.java:1642)
	at net.minecraft.class_757.method_34538(class_757.java:543)
	at net.minecraft.class_757$1.method_45777(class_757.java:465)
	at net.minecraft.class_757$1.method_18788(class_757.java:437)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	... 12 more
	
	

I can't make sense of this, can someone help?

**Comment by topia** [comment]
This should be a mod compatibility issue, but I only have an idea to try turning off the mod individually. I find "libgui" in your stack trace so that mod might cause it, but I don't have any confidence.

**Comment by MemeKueen2** [comment]
Nvm, i singled out the issue to another mod: horse stats vanilla

**Comment by Incompetenttwat** [comment]
I found a nother mod that does that "chestracker"
