### ISSUE TITLE
1.19.2 Crashing

### ISSUE THREAD

**Issue by meowisme** [Chocohead/OptiFabric#1119]
With how much I tend to play on 1.19.2, I'd like to have Optifine on it but I'm running into some trouble...
I've looked at other people reporting on the issue but none of it helped me.

It runs fine without the Fabric API (and the only mods being OptiFabric and OptiFine) but as soon as I add it, Minecraft just crashes.

I don't like Sodium and I can't use it anyways since it's prone to crashing my game at the littlest of things.

I'll manage without OptiFine but if anyone can help, it'd be lovely.
![image](https://github.com/Chocohead/OptiFabric/assets/127144330/9d3b98b8-25f6-4d72-91b1-e3181b655763)

**Comment by AuroraDoesCode** [comment]
Only thing I can think is the 0.76 fabric api fixes aren’t applied, which shouldn’t be happening. Can you post your log please?

you can also try using 0.75.1 instead, that’s known working for sure, I use it on a server that’s not updated since 1.19.2

**Comment by meowisme** [comment]
> Only thing I can think is the 0.76 fabric api fixes aren’t applied, which shouldn’t be happening. Can you post your log please?
> 
> you can also try using 0.75.1 instead, that’s known working for sure, I use it on a server that’s not updated since 1.19.2


0.75.1 didn't work either... I thought it was loading but then it still crashed.

Here's the log:
[18:51:40] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.19
[18:51:40] [main/INFO]: Loading 56 mods:
	- fabric-api 0.76.0+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.41+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.8+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.11+10eb22f490
	   |-- fabric-networking-v0 0.3.28+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.0.14+4d0d570390
	   |-- fabric-recipe-api-v1 1.0.1+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.32+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.24+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.27+df3654b390
	   |-- fabric-rendering-v1 1.12.1+d8ef690890
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabricloader 0.14.19
	- java 17
	- minecraft 1.19.2
	- optifabric 1.13.16
	   \-- mm 2.3
[18:51:41] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Rowen/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[18:51:41] [main/INFO]: Compatibility level set to JAVA_16
[18:51:41] [main/INFO]: Compatibility level set to JAVA_17
[18:51:47] [main/ERROR]: Mixin apply for mod optifabric failed optifabric.compat.fabric-renderer-api.new-mixins.json:BlockRenderManagerNewMixin from mod optifabric -> net.minecraft.class_776: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: Callback group @Group(name=default, min=1, max=1) in optifabric.compat.fabric-renderer-api.new-mixins.json:BlockRenderManagerNewMixin from mod optifabric failed injection check: expected 1 invocation(s) but 0 succeeded [ -> PostApply Phase -> optifabric.compat.fabric-renderer-api.new-mixins.json:BlockRenderManagerNewMixin from mod optifabric]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: Callback group @Group(name=default, min=1, max=1) in optifabric.compat.fabric-renderer-api.new-mixins.json:BlockRenderManagerNewMixin from mod optifabric failed injection check: expected 1 invocation(s) but 0 succeeded [ -> PostApply Phase -> optifabric.compat.fabric-renderer-api.new-mixins.json:BlockRenderManagerNewMixin from mod optifabric]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.postApply(MixinTargetContext.java:1281) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:346) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) [fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3297) [?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2371) [?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) [Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:503) [Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:175) [client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:159) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionValidationException: expected 1 invocation(s) but 0 succeeded
	at org.spongepowered.asm.mixin.injection.struct.InjectorGroupInfo.validate(InjectorGroupInfo.java:268) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectorGroupInfo$Map.validateAll(InjectorGroupInfo.java:126) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.postApply(MixinTargetContext.java:1274) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	... 23 more
[18:51:47] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:464) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_128.method_568(class_128.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:159) ~[fabric-loader-0.14.19-1.19.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.19-1.19.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_776 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3297) ~[?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2371) ~[?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) ~[Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:503) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:159) ~[fabric-loader-0.14.19-1.19.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.19-1.19.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3297) ~[?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2371) ~[?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) ~[Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:503) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:159) ~[fabric-loader-0.14.19-1.19.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.19-1.19.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [optifabric.compat.fabric-renderer-api.new-mixins.json:BlockRenderManagerNewMixin from mod optifabric] from phase [DEFAULT] in config [optifabric.compat.fabric-renderer-api.new-mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3297) ~[?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2371) ~[?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) ~[Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:503) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:159) ~[fabric-loader-0.14.19-1.19.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.19-1.19.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: Callback group @Group(name=default, min=1, max=1) in optifabric.compat.fabric-renderer-api.new-mixins.json:BlockRenderManagerNewMixin from mod optifabric failed injection check: expected 1 invocation(s) but 0 succeeded [ -> PostApply Phase -> optifabric.compat.fabric-renderer-api.new-mixins.json:BlockRenderManagerNewMixin from mod optifabric]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.postApply(MixinTargetContext.java:1281) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:346) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3297) ~[?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2371) ~[?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) ~[Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:503) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:159) ~[fabric-loader-0.14.19-1.19.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.19-1.19.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionValidationException: expected 1 invocation(s) but 0 succeeded
	at org.spongepowered.asm.mixin.injection.struct.InjectorGroupInfo.validate(InjectorGroupInfo.java:268) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectorGroupInfo$Map.validateAll(InjectorGroupInfo.java:126) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.postApply(MixinTargetContext.java:1274) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:346) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3297) ~[?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2371) ~[?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) ~[Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:503) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:159) ~[fabric-loader-0.14.19-1.19.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.19-1.19.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 2 more

**Comment by topia** [comment]
Do you have special motivation to use older optifabric over the latest? If not, please consider using 1.13.25; it should be compatible with 1.19.2 too.

**Comment by XXMA16** [comment]
Optifabric is outdated, use 1.13.25

**Comment by meowisme** [comment]
Ah, that works. ^^'' Thank you !
