### ISSUE TITLE
optifabric 1.16.5

### ISSUE THREAD

**Issue by pl3nk1** [Chocohead/OptiFabric#1130]
java.lang.RuntimeException: Failed to remap jar
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:226)
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:211)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:165)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:43)
	at com.chocohead.mm.Plugin$$Lambda$47/1862994526.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.nio.file.AccessDeniedException: C:\Windows\TEMP\optifabric3758860256724319276\Optifine-jarofthefree.jar
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:90)
	at sun.nio.fs.WindowsLinkSupport.getRealPath(WindowsLinkSupport.java:259)
	at sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:836)
	at sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:44)
	at com.sun.nio.zipfs.ZipFileSystemProvider.removeFileSystem(ZipFileSystemProvider.java:322)
	at com.sun.nio.zipfs.ZipFileSystem.close(ZipFileSystem.java:305)
	at net.fabricmc.tinyremapper.OutputConsumerPath.addNonClassFiles(OutputConsumerPath.java:187)
	at net.fabricmc.tinyremapper.OutputConsumerPath.addNonClassFiles(OutputConsumerPath.java:143)
	at net.fabricmc.tinyremapper.OutputConsumerPath.addNonClassFiles(OutputConsumerPath.java:135)
	at net.fabricmc.tinyremapper.OutputConsumerPath.addNonClassFiles(OutputConsumerPath.java:127)
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:220)
	... 29 more
	Suppressed: java.nio.file.AccessDeniedException: C:\Windows\TEMP\optifabric3758860256724319276\Optifine-remapped.jar
		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:90)
		at sun.nio.fs.WindowsLinkSupport.getRealPath(WindowsLinkSupport.java:259)
		at sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:836)
		at sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:44)
		at com.sun.nio.zipfs.ZipFileSystemProvider.removeFileSystem(ZipFileSystemProvider.java:322)
		at com.sun.nio.zipfs.ZipFileSystem.close(ZipFileSystem.java:305)
		at net.fabricmc.tinyremapper.OutputConsumerPath.close(OutputConsumerPath.java:226)
		at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:225)
		... 29 more

**Comment by AuroraDoesCode** [comment]
Caused by: java.nio.file.AccessDeniedException: C:\Windows\TEMP\optifabric3758860256724319276\Optifine-jarofthefree.jar
at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:90)
at sun.nio.fs.WindowsLinkSupport.getRealPath(WindowsLinkSupport.java:259)
at sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:836)
at sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:44)
at com.sun.nio.zipfs.ZipFileSystemProvider.removeFileSystem(ZipFileSystemProvider.java:322)
at com.sun.nio.zipfs.ZipFileSystem.close(ZipFileSystem.java:305)

Issue on your client, not Optifabric.

**Comment by pl3nk1** [comment]
thank you!

**Comment by pl3nk1** [comment]
I did everything but it didn't help                                                                    java.lang.RuntimeException: Failed to remap jar
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:234)
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:219)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:167)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at com.chocohead.mm.Plugin$$Lambda$51/203819996.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.nio.file.AccessDeniedException: C:\Windows\TEMP\optifabric640354350479580938\Optifine-jarofthefree.jar
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:90)
	at sun.nio.fs.WindowsLinkSupport.getRealPath(WindowsLinkSupport.java:259)
	at sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:836)
	at sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:44)
	at com.sun.nio.zipfs.ZipFileSystemProvider.removeFileSystem(ZipFileSystemProvider.java:322)
	at com.sun.nio.zipfs.ZipFileSystem.close(ZipFileSystem.java:305)
	at net.fabricmc.tinyremapper.OutputConsumerPath.addNonClassFiles(OutputConsumerPath.java:187)
	at net.fabricmc.tinyremapper.OutputConsumerPath.addNonClassFiles(OutputConsumerPath.java:143)
	at net.fabricmc.tinyremapper.OutputConsumerPath.addNonClassFiles(OutputConsumerPath.java:135)
	at net.fabricmc.tinyremapper.OutputConsumerPath.addNonClassFiles(OutputConsumerPath.java:127)
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:228)
	... 29 more
	Suppressed: java.nio.file.AccessDeniedException: C:\Windows\TEMP\optifabric640354350479580938\Optifine-remapped.jar
		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:90)
		at sun.nio.fs.WindowsLinkSupport.getRealPath(WindowsLinkSupport.java:259)
		at sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:836)
		at sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:44)
		at com.sun.nio.zipfs.ZipFileSystemProvider.removeFileSystem(ZipFileSystemProvider.java:322)
		at com.sun.nio.zipfs.ZipFileSystem.close(ZipFileSystem.java:305)
		at net.fabricmc.tinyremapper.OutputConsumerPath.close(OutputConsumerPath.java:226)
		at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:233)
		... 29 more

**Comment by AuroraDoesCode** [comment]
It’s still an issue your side, your MC install is failing to load the remapped jar from the folders, with a failed to access error. the only time I’ve seen this is when my instance was broken, and I had to start with a fresh install of just Optifabric, Optifine and Fabric API to start. It’s possible another mod of yours is interfering. Can’t really do anything more for you without a mod list, and a proper crash log

**Comment by pl3nk1** [comment]
НЕ ПОМОГЛО
