### ISSUE TITLE
Minecraft has crashed! Optifabric 1.20

### ISSUE THREAD

**Issue by Wendy4224** [Chocohead/OptiFabric#1135]
I decided to install the Optifine on Fabric for version 1.20, I downloaded the Optifine from the official website preview_OptiFine_1.20_HD_U_I5_pre5.jar . When I started Minecraft it crashed with the error window Fabric loader 0.14.21

java.lang.ExceptionInInitializerError
<html>at net.minecraft.class_128.method_568(class_128.java:175)<br>at net.minecraft.class_128.method_24305(class_128.java:345)<br>at net.minecraft.client.main.Main.main(Main.java:164)<br>at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)<br>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)<br>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)</html>
RuntimeException: Mixin transformation of net.minecraft.class_309 failed
<html>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)<br>at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)<br>at java.base/java.lang.Class.getDeclaredFields0(Native Method)<br>at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)<br>at java.base/java.lang.Class.getDeclaredFields(Class.java:2371)<br>at net.optifine.reflect.FieldLocatorTypes.&lt;init&gt;(FieldLocatorTypes.java:25)<br>at net.optifine.reflect.Reflector.&lt;clinit&gt;(Reflector.java:533)<br>... 6 more</html>
MixinTransformerError: An unexpected critical error was encountered
<html>at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)<br>at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)<br>at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)<br>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)<br>... 15 more</html>
<html>MixinApplyError: Mixin [mixins.jgui.json:MixinKeyboardListener from mod replaymod] from phase [DEFAULT] in config<br>[mixins.jgui.json] FAILED during APPLY</html>
<html>at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)<br>at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)<br>at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)<br>... 18 more</html>
<html>InvalidInjectionException: 'static' modifier of handler method does not match target in<br>net/minecraft/class_309::charTypedOptifine [PREINJECT Applicator Phase -&gt; mixins.jgui.json:MixinKeyboardListener from<br>mod replaymod -&gt; Prepare Injections -&gt;  -&gt;<br>handler$bmc000$replaymod$charTypedOptifine(CILnet/minecraft/class_364;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V<br>-&gt; Prepare]</html>
<html>at org.spongepowered.asm.mixin.injection.code.Injector.checkTargetModifiers(Injector.java:347)<br>at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.sanityCheck(CallbackInjector.java:425)<br>at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:237)<br>at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)<br>at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)<br>at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)<br>at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)<br>at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)<br>at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)<br>at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)<br>at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)<br>... 18 more</html>

**Comment by AuroraDoesCode** [comment]
Remove ReplayMod, its broken with Optifabric, and Choco or someone needs to supply the fixes.

**Comment by Wendy4224** [comment]
> Remove ReplayMod, its broken with Optifabric, and Choco or someone needs to supply the fixes.

That doesn`t help

**Comment by AuroraDoesCode** [comment]
Then you have more than one incompatibility. Post your mod list and the full log.
