### ISSUE TITLE
Can't load Minecraft 1.20.1 with Optifabric

### ISSUE THREAD

**Issue by GroteryW** [Chocohead/OptiFabric#1156]
I'm trying to launch Minecraft 1.20.1 with Optifabric but always having trouble with languages. I have only: "fabric-api", "optifabric 1.13.2", "preview_optifine pre6." Even when I'm trying to make the world, he's crashing the game with errors:

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, fabric
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: java.lang.AbstractMethodError: Receiver class net.minecraft.class_1088$class_7778 does not define or inherit an implementation of the resolved method 'abstract java.util.function.Function getModelTextureGetter()' of interface net.minecraftforge.client.extensions.IForgeModelBaker.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.AbstractMethodError: Receiver class net.minecraft.class_1088$class_7778 does not define or inherit an implementation of the resolved method 'abstract java.util.function.Function getModelTextureGetter()' of interface net.minecraftforge.client.extensions.IForgeModelBaker.
	at net.minecraft.class_806.<init>(class_806.java:49)
	at net.minecraft.class_793.method_3440(class_793.java:143)
	at net.minecraft.class_793.method_3446(class_793.java:213)
	at net.minecraft.class_1088$class_7778.redirect$zem000$fabric-model-loading-api-v1$invokeModifyAfterBake(class_1088.java:565)
	at net.minecraft.class_1088$class_7778.method_45873(class_1088.java:423)
	at net.minecraft.class_1088.method_45877(class_1088.java:211)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1008)
	at net.minecraft.class_1088.method_45876(class_1088.java:206)
	at net.minecraft.class_1092.method_45883(class_1092.java:145)
	at net.minecraft.class_1092.method_45885(class_1092.java:92)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 6 more

![photo_2023-07-30_19-22-25](https://github.com/Chocohead/OptiFabric/assets/140969590/598aaf77-8a62-43c5-913b-23129eb39e9e)

**Comment by AuroraDoesCode** [comment]
Downgrade fabric api to 0.85.0, and update Optifabric to 1.13.25. You're several versions behind, and im not sure how you loaded the game with 1.13.2. Issue for FAPI is #1123
