### ISSUE TITLE
Stuck while loading

### ISSUE THREAD

**Issue by Maddog63** [Chocohead/OptiFabric#1159]
When i try to start Minecraft it gets stuck while loading.
![Mods 1 20 1](https://github.com/Chocohead/OptiFabric/assets/141034895/755b55fc-1405-4f57-8b58-88ab5523a1e5)

This is my Mods List.
please point me to the one that's incompatible.

Thanks!

**Comment by AuroraDoesCode** [comment]
Is it crashing on the loading bar? If so, remove resource packs, load game, readd resource packs.

**Comment by Maddog63** [comment]
Not loading at all.
Mojang screen pops up and the bar goes circa 90%
and then stuck and won't go farther.
I waited 20 minutes and nothing.

Am 31. Juli 2023 14:52:59 schrieb Michael Fawkes ***@***.***>:

**Comment by AuroraDoesCode** [comment]
> Not loading at all. Mojang screen pops up and the bar goes circa 90% and then stuck and won't go farther. I waited 20 minutes and nothing. Am 31. Juli 2023 14:52:59 schrieb Michael Fawkes ***@***.***>:
> […](#)

Post your log.

**Comment by Maddog63** [comment]
Hope that helps.
It says resources load fail


Am 31. Juli 2023 16:14:34 schrieb Michael Fawkes ***@***.***>:
>
> Not loading at all. Mojang screen pops up and the bar goes circa 90% and
> then stuck and won't go farther. I waited 20 minutes and nothing. Am 31.
> Juli 2023 14:52:59 schrieb Michael Fawkes @.***>:
> …
> Post your log.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>


---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-07-31 17:07:17
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.setSampler(int, Object)" because "shaderinstance" is null
	at net.minecraft.class_761.method_3251(class_761.java:2365)
	at net.minecraft.class_761.method_22710(class_761.java:1716)
	at net.minecraft.class_757.method_3188(class_757.java:1651)
	at net.minecraft.class_757.method_3192(class_757.java:1279)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_761.method_3251(class_761.java:2365)
	at net.minecraft.class_761.method_22710(class_761.java:1716)
	at net.minecraft.class_757.method_3188(class_757.java:1651)

-- Affected level --
Details:
	All players: 1 total; [class_746['Minedog63'/296, l='ClientLevel', x=-26.91, y=-54.00, z=-65.88]]
	Chunk stats: 3025, 1088
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,72,-16), Section: (at 0,8,0 in 1,4,-1; chunk contains blocks 16,-64,-16 to 31,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 1534221 game time, 1946423 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:590)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, fabric, Supplementaries Generated Pack
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to initialized owo shader program
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.method_18859(class_1255.java:198)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:163)
	at net.minecraft.class_1255.method_5383(class_1255.java:140)
	at net.minecraft.class_310.method_1523(class_310.java:1175)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Failed to initialized owo shader program
	at io.wispforest.owo.shader.GlProgram.lambda$new$0(GlProgram.java:51)
	at net.minecraft.class_757.mdbe51bd$owo$lambda$loadAllTheShaders$0$1(class_757.java:2611)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.wispforest.owo.shader.GlProgram.forEachProgram(GlProgram.java:88)
	at net.minecraft.class_757.handler$bcp000$owo$loadAllTheShaders(class_757.java:2611)
	at net.minecraft.class_757.method_34538(class_757.java:543)
	at net.minecraft.class_757$1.method_45777(class_757.java:465)
	at net.minecraft.class_757$1.method_18788(class_757.java:437)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	... 12 more
Caused by: net.minecraft.class_2973: Invalid shaders/core/spectrum.json: File not found
	at net.minecraft.class_2973.method_12856(class_2973.java:48)
	at net.minecraft.class_5944.<init>(class_5944.java:228)
	at net.minecraft.class_5944.<init>(class_5944.java:108)
	at io.wispforest.owo.shader.GlProgram$OwoShaderProgram.<init>(GlProgram.java:93)
	at io.wispforest.owo.shader.GlProgram.lambda$new$0(GlProgram.java:49)
	... 21 more
Caused by: java.io.FileNotFoundException: owo:owo:shaders/core/spectrum.fsh
	at net.minecraft.class_5912.method_43043(class_5912.java:21)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:21)
	at net.minecraft.class_5944.method_34579(class_5944.java:264)
	at net.minecraft.class_5944.<init>(class_5944.java:202)
	... 24 more


-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1420525680 bytes (1354 MiB) / 3053453312 bytes (2912 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3598
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18658.34
	Virtual memory used (MB): 10727.24
	Swap memory total (MB): 2404.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ambientsounds: AmbientSounds 5.2.20
		cardinal-components: Cardinal Components API 5.2.1
			cardinal-components-block: Cardinal Components API (blocks) 5.2.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.1
			cardinal-components-item: Cardinal Components API (items) 5.2.1
			cardinal-components-level: Cardinal Components API (world saves) 5.2.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.1
			cardinal-components-world: Cardinal Components API (worlds) 5.2.1
		cardinal-components-base: Cardinal Components API (base) 5.2.1
		cardinal-components-entity: Cardinal Components API (entities) 5.2.1
		cloth-config: Cloth Config v11 11.0.99
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.62
		creativecore: CreativeCore (Fabric) 2.10.23
			net_minecraftforge_eventbus: eventbus 6.0.3
		elytraslot: Elytra Slot 6.3.0+1.20.1
		fabric-api: Fabric API 0.85.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a77
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.0+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.8+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.12+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.8+40e50c4677
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.38+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.42+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.48+b3afc78b77
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.0+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.0+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.0+c154966e77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.0+c154966e77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.8+e3d6ed2577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.3+43a3fedd77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabricloader: Fabric Loader 0.14.21
		fallingtree: FallingTree 4.1.0
		fwaystones: Fabric Waystones 3.1.2+mc1.20
		immersive_paintings: Immersive Paintings 0.6.1+1.20.1
		java: OpenJDK 64-Bit Server VM 17
		mcwlights: Macaw's Lights and Lamps 1.0.6
		mcwpaintings: Macaw's Paintings 1.0.0
		minecraft: Minecraft 1.20.1
		moonlight: Moonlight 1.20-2.6.1
		optifabric: OptiFabric 1.13.25
			mm: Manningham Mills 2.3
		owo: oωo 0.11.0+1.20
			blue_endless_jankson: jankson 1.2.2
		plushies: Plushie Mod 1.2.1
		supplementaries: Supplementaries 1.20-2.5.18
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.1
		trinkets: Trinkets 3.7.0
		villagernames: Villager Names 5.2
		xaerominimap: Xaero's Minimap 23.5.0
		xaeroworldmap: Xaero's World Map 1.30.6
	Launched Version: fabric-loader-0.14.21-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 535.98, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'optifine'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: en_us
	CPU: 12x Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Minedog63'/296, l='ServerLevel[Enceladus]', x=-26.91, y=-54.00, z=-65.88]]
	Data Packs: vanilla, fabric, Supplementaries Generated Pack
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	OptiFine Version: OptiFine_1.20.1_HD_U_I5
	OptiFine Build: 20230707-211226
	Render Distance Chunks: 24
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 535.98
	OpenGlRenderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.20.1
	OptiFine jar version: OptiFine_1.20.1_HD_U_I5
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/Michael/AppData/Roaming/.minecraft/.optifine/OptiFine_1.20.1_HD_U_I5/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by AuroraDoesCode** [comment]
Remove Owo and any mods that depend on it, I checked on my version of MC and Owo causes the issue you described.

**Comment by Maddog63** [comment]
Okay.  Thanks!

Am 31. Juli 2023 17:18:31 schrieb Michael Fawkes ***@***.***>:

**Comment by Maddog63** [comment]
It worked! Thank you! 👍
Waystones was the troublemaker..

Am 31. Juli 2023 17:18:31 schrieb Michael Fawkes ***@***.***>:

**Comment by AuroraDoesCode** [comment]
> It worked! Thank you! 👍 Waystones was the troublemaker.. Am 31. Juli 2023 17:18:31 schrieb Michael Fawkes ***@***.***>:
> […](#)
> Remove Owo and any mods that depend on it, I checked on my version of MC and Owo causes the issue you described. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Glad you figured it out.
