### ISSUE TITLE
OpenGL error when going through nether portal cause crash

### ISSUE THREAD

**Issue by Tasty213** [Chocohead/OptiFabric#116]
When you attempt to go through a nether portal with optifabric enabled the following crash occurs:
```
[17:15:35] [main/ERROR]: OpenGL API ERROR: 2 (GL_INVALID_VALUE in glCopyBufferSubData(readOffset 15264768 + size 98304 > src_buffer_size 0))
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL31C.glCopyBufferSubData(Native Method) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL31.glCopyBufferSubData(GL31.java:298) [lwjgl-opengl-3.2.2.jar:build 10]
	at net.minecraft.class_4493.copyBufferSubData(class_4493.java:2104) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.optifine.render.VboRegion.copyVboData(VboRegion.java:243) [Optifine-mapped.jar:?]
	at net.optifine.render.VboRegion.compactRanges(VboRegion.java:157) [Optifine-mapped.jar:?]
	at net.optifine.render.VboRegion.finishDraw(VboRegion.java:338) [Optifine-mapped.jar:?]
	at net.minecraft.class_761.drawRegion(class_761.java:2309) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_761.method_3251(class_761.java:2230) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1594) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1022) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:693) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1048) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.4-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[17:15:35] [main/ERROR]: [OptiFine] OpenGL error: 1281 (Invalid value), at: Copy VBO range
```

Optifabric version: 1.8.10
Optifine version: 1.16.4_HD_U_GS
Minecraft version: 1.16.4

**Comment by IMS212** [comment]
What mods do you have?

**Comment by Tasty213** [comment]
Mallib/litematica and mod loader  (the one tgat shows you what mods are installed) and carpet but i was playing online so don't know setver side

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by IMS212** [comment]
try removing all of them and see if the issue persists

**Comment by Chocohead** [comment]
ModMenu won't have been the cause, nor would any server side mods (as they'd not affect rendering). I'd be suspicious of Litematica, especially if it was rendering an outline, so it would be worth trying without that.
