### ISSUE TITLE
Crashes upon loading a world Exit Code: -1

### ISSUE THREAD

**Issue by Shakrazz** [Chocohead/OptiFabric#1160]
The game crashes only with optifabric installed. It launches to the main menu just fine but whenever I try to launch a world it crashes. I tried it with multiple different shaders and without any shaders enabled and it crashed the same regardless. it also gives me an error in the top right saying Resource reload failed. 

This is my mod list:

![image](https://github.com/Chocohead/OptiFabric/assets/141072147/157ac594-189c-4251-aee0-0e7cf3639b03)

Crash Message:

![image](https://github.com/Chocohead/OptiFabric/assets/141072147/0cb30869-da3a-4fe9-a262-89f00204ff57)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, fabric
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "resourceName" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.method_18859(class_1255.java:198)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:163)
	at net.minecraft.class_1255.method_5383(class_1255.java:140)
	at net.minecraft.class_310.method_1523(class_310.java:1175)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "resourceName" is null
	at net.minecraft.class_2960.method_12830(class_2960.java:95)
	at net.minecraft.class_2960.<init>(class_2960.java:58)
	at net.fabricmc.fabric.impl.client.rendering.FabricShaderProgram.rewriteAsId(FabricShaderProgram.java:42)
	at net.minecraft.class_5944.modify$zoe000$fabric-rendering-v1$modifyProgramId(class_5944.java:654)
	at net.minecraft.class_5944.localvar$bhe000$optifabric$modifyProgramID(class_5944.java:1634)
	at net.minecraft.class_5944.<init>(class_5944.java:114)
	at net.minecraft.class_5944.<init>(class_5944.java:108)
	at net.fabricmc.fabric.impl.client.rendering.FabricShaderProgram.<init>(FabricShaderProgram.java:28)
	at net.minecraft.class_757.md606134$fabric-rendering-v1$lambda$registerShaders$0$0(class_757.java:1639)
	at io.github.cottonmc.cotton.gui.impl.client.LibGuiShaders.lambda$register$1(LibGuiShaders.java:18)
	at net.fabricmc.fabric.api.client.rendering.v1.CoreShaderRegistrationCallback.lambda$static$0(CoreShaderRegistrationCallback.java:44)
	at net.minecraft.class_757.handler$zoc000$fabric-rendering-v1$registerShaders(class_757.java:1642)
	at net.minecraft.class_757.method_34538(class_757.java:543)
	at net.minecraft.class_757$1.method_45777(class_757.java:465)
	at net.minecraft.class_757$1.method_18788(class_757.java:437)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	... 12 more

**Comment by AuroraDoesCode** [comment]
Post your full log please, not enough info to diagnose in here.
