### ISSUE TITLE
OptiFabric crashes in Dev Environment 1.16.4

### ISSUE THREAD

**Issue by florianreuth** [Chocohead/OptiFabric#119]
Minecraft Version: 1.16.4
I built the latest OptiFabric Dev and FabricASM Dev jar and tried to use them in the development environment, when I start my game this error comes up (I tried to load OptifFabric via Gradle and the same error comes up):

`[15:41:41] [main/ERROR] (mixin) Error encountered during mixin config postInit step'mixins.mm.json': Failed to setup optifine
 java.lang.RuntimeException: Failed to setup optifine
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:49) ~[optifabric-1.8.13-dev.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_271]
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:339) ~[Manningham%20Mills-2.1-dev.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:667) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:542) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_271]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_271]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_271]
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:272) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.AssertionError: Unable to find Minecraft dev jar! Tried D:\Test\.gradle\loom-cache\1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.7-v2\minecraft-1.16.4-client.jar and D:\Test\.gradle\loom-cache\minecraft-1.16.4-client.jar
	at me.modmuss50.optifabric.mod.OptifineSetup.getMinecraftJar(OptifineSetup.java:208) ~[optifabric-1.8.13-dev.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:75) ~[optifabric-1.8.13-dev.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:36) ~[optifabric-1.8.13-dev.jar:?]
	... 26 more
Disconnected from the target VM, address: '127.0.0.1:52253', transport: 'socket'

Process finished with exit code 130
`

**Comment by Chocohead** [comment]
Are you using an access widener with your project? The logic for finding Loom's merged Minecraft isn't the best so might be tripping up from that.

**Comment by florianreuth** [comment]
Yes, I use an AccessWidener, but I can't just delete it, it's important and needed in the project, is there a solution?

**Comment by Chocohead** [comment]
That would certainly do it from Loom then using a project mapped jar rather than a globally cached one. I suppose I can add a system property to specify where the jar is when it can't be manually found to work around this situation.

**Comment by florianreuth** [comment]
Thank you

**Comment by Chocohead** [comment]
Thank you for your patience, the feature has been added 1.8.14. You'll want to run with something like `-Doptifabric.mc-jar=C:\Users\(your user)\.gradle\caches\fabric-loom\minecraft-1.16.4-client.jar` as a VM arg so OptiFabric can find the vanilla client jar to work from.

**Comment by florianreuth** [comment]
Can you add me on Discord? EnZaXD#7298 I like to Project and i want to help you
