### ISSUE TITLE
optifabric incompatibility  with Bewitchement mod

### ISSUE THREAD

**Issue by Bfungame** [Chocohead/OptiFabric#1200]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Bewitchment' (bewitchment) 1.19-7 with version 1.19-1 or later that is compatible with:
		 - optifabric 1.13.16
Unmet dependency listing:
	 - Mod 'Bewitchment' (bewitchment) 1.19-7 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.16!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by XXMA16** [comment]
> Mod 'Bewitchment' (bewitchment) 1.19-7 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.16!

Ask Bewitchment's dev to mark Optifabric as a `conflict` instead of a `break`, although it looks like making this mod compatible with Optifabric might take a while.

**Comment by sylv256** [comment]
https://lambdaurora.dev/optifine_alternatives/
