### ISSUE TITLE
Versions 1.13.25 and 1.13.24, Beta releases do not work on 1.19.4.

### ISSUE THREAD

**Issue by HollowPalea** [Chocohead/OptiFabric#1231]
Both crash upon trying to open. 1.13.25 makes it to opening Minecraft but hits an error anyway: 
java.lang.RuntimeException: GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
	at net.minecraft.class_276.method_1239(class_276.java:227)
	at net.minecraft.class_276.method_1231(class_276.java:194)
	at net.minecraft.class_276.method_22596(class_276.java:81)
	at net.minecraft.class_276.method_1234(class_276.java:59)
	at net.minecraft.class_310.method_15993(class_310.java:1352)
	at net.minecraft.class_310.<init>(class_310.java:638)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

while 1.13.24 doesn't even make it that far:
java.lang.ExceptionInInitializerError
RuntimeException: Mixin transformation of net.minecraft.class_757 failed
MixinTransformerError: An unexpected critical error was encountered
<html>MixinApplyError: Mixin [optifabric.compat.fabric-screen-api.newerer-mixins.json:GameRendererNewererMixin from mod<br>optifabric] from phase [DEFAULT] in config [optifabric.compat.fabric-screen-api.newerer-mixins.json] FAILED during APPLY</html>
<html>InvalidMixinException: Unexpecteded IllegalStateException whilst transforming the mixin class: [PostApply Phase -&gt;<br>optifabric.compat.fabric-screen-api.newerer-mixins.json:GameRendererNewererMixin from mod optifabric -&gt; Plugin<br>Post-Application]</html>
<html>IllegalStateException: Cannot find shim method<br>onBeforeRenderScreen(FJZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;IILnet/minecraft/class_4587;)V in<br>net/fabricmc/fabric/mixin/screen/GameRendererMixin</html>

Not sure if this mod is still being worked on since last update was 2 months ago, but I'll post this anyways in hopes of something happening. Also, don't exactly know what's happening, all I did was copy crash reports.

**Comment by Poopooracoocoo** [comment]
Duplicate of #1123. Use FAPI 0.85.0
