### ISSUE TITLE
Eror loading optifabric 1.18.2

### ISSUE THREAD

**Issue by Surrpojav** [Chocohead/OptiFabric#1289]
java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 25 more

**Comment by Poopooracoocoo** [comment]
Already reported. Use Fabric Loader 0.14.25

**Comment by Basanta777** [comment]
Hi

**Comment by Pritam456KUMAR** [comment]
> Already reported. Use Fabric Loader 0.14.25

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 12/19/23, 6:15 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'fabric-renderer-indigo'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5944 failed
	at net.minecraft.class_4668.<clinit>(class_4668.java:78)
	at net.fabricmc.fabric.api.renderer.v1.material.BlendMode.<clinit>(BlendMode.java:33)
	at net.fabricmc.fabric.impl.client.indigo.renderer.RenderMaterialImpl.<clinit>(RenderMaterialImpl.java:34)
	at net.fabricmc.fabric.impl.client.indigo.renderer.IndigoRenderer.materialFinder(IndigoRenderer.java:54)
	at net.fabricmc.fabric.impl.client.indigo.renderer.IndigoRenderer.<clinit>(IndigoRenderer.java:37)
	at net.fabricmc.fabric.impl.client.indigo.Indigo.onInitializeClient(Indigo.java:137)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	... 6 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5944 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 13 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 17 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fabric-rendering-v1.mixins.json:shader.ShaderMixin from mod fabric-rendering-v1] from phase [DEFAULT] in config [fabric-rendering-v1.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 20 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @ModifyArg handler before this() invocation must be static in injector net/minecraft/class_5944::modifyProgramId [INJECT Applicator Phase -> fabric-rendering-v1.mixins.json:shader.ShaderMixin from mod fabric-rendering-v1 -> Apply Injections ->  -> Inject -> fabric-rendering-v1.mixins.json:shader.ShaderMixin from mod fabric-rendering-v1->@ModifyArg::modifyProgramId(Ljava/lang/String;)Ljava/lang/String;]
	at org.spongepowered.asm.mixin.injection.code.Injector.checkTargetForNode(Injector.java:386)
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.inject(ModifyArgInjector.java:102)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 20 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:452)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (arm) version Android-10
	Java Version: 17.0.9-internal, N/A
	Java VM Version: OpenJDK Server VM (mixed mode), Oracle Corporation
	Memory: 158890320 bytes (151 MiB) / 786432000 bytes (750 MiB) up to 786432000 bytes (750 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: ARMv8 Processor rev 4 (v8l)
	Identifier: 0x41 Family 8 Model 0xd03 Stepping r0x0p4
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 3943.03
	Virtual memory used (MB): 3069.79
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 396.88
	JVM Flags: 3 total; -Xms750M -Xmx750M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Fabric Mods: 
		fabric-api: Fabric API 0.77.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.5+64b7c69360
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.3+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.7+e83becad60
			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+ee3621fc60
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.13+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.10+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.9+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.24+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.3+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.0+43ce63a460
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.1.0+6c70b68e60
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.21+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.9+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.20+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.22+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.6.2+8165403660
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.16+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.1+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.2+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.6+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.7+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.24+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.11+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.5+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.13+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.12+bb2e047760
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.5.0+bf48649860
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.1+03e2b68760
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.13+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.9+ee3621fc60
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.3+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.15+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+b7f3cf3460
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+047a5ecb60
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.11+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.3+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.13+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.4+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabricloader: Fabric Loader 0.14.25
		ias: In-Game Account Switcher 8.0.2
		java: OpenJDK Server VM 17
		minecraft: Minecraft 1.18.2
		modmenu: Mod Menu 3.2.5
		optifabric: OptiFabric 1.13.0
			mm: Manningham Mills 2.3
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.18.2_HD_U_H9
	OptiFine Build: 20230626-134040
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 0

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.18.2
	OptiFine jar version: OptiFine_1.18.2_HD_U_H9
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/.optifine/OptiFine_1.18.2_HD_U_H9/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by ToPlayer6478** [comment]
![изображение](https://github.com/Chocohead/OptiFabric/assets/135963040/99bde792-f3da-410a-a334-cc9eb823e62b)
Fabric loader didnt help. How can i fix it?

**Comment by Poopooracoocoo** [comment]
@ToPlayer6478 create a new issue with a log and crash report
