### ISSUE TITLE
Here I am!

### ISSUE THREAD

**Issue by Thienyeuvy** [Chocohead/OptiFabric#1294]
-tree\9.6\asm-tree-9.6.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-util\9.6\asm-util-9.6.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\net\fabricmc\intermediary\1.20.1\intermediary-1.20.1.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\net\fabricmc\fabric-loader\0.14.25\fabric-loader-0.14.25.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\com\github\oshi\oshi-core\6.2.2\oshi-core-6.2.2.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.10\gson-2.10.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\31.1-jre\guava-31.1-jre.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j\71.1\icu4j-71.1.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\tlauncher\authlib\4.0.43.1\authlib-4.0.43.1.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\com\mojang\blocklist\1.0.10\blocklist-1.0.10.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\com\mojang\brigadier\1.1.8\brigadier-1.1.8.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\com\mojang\datafixerupper\6.0.8\datafixerupper-6.0.8.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\com\mojang\logging\1.1.1\logging-1.1.1.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\tlauncher\patchy\2.2.10\patchy-2.2.10.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\com\mojang\text2speech\1.17.9\text2speech-1.17.9.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.15\commons-codec-1.15.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.11.0\commons-io-2.11.0.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\io\netty\netty-buffer\4.1.82.Final\netty-buffer-4.1.82.Final.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\io\netty\netty-codec\4.1.82.Final\netty-codec-4.1.82.Final.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\io\netty\netty-common\4.1.82.Final\netty-common-4.1.82.Final.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\io\netty\netty-handler\4.1.82.Final\netty-handler-4.1.82.Final.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\io\netty\netty-resolver\4.1.82.Final\netty-resolver-4.1.82.Final.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\io\netty\netty-transport-classes-epoll\4.1.82.Final\netty-transport-classes-epoll-4.1.82.Final.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\io\netty\netty-transport-native-unix-common\4.1.82.Final\netty-transport-native-unix-common-4.1.82.Final.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\io\netty\netty-transport\4.1.82.Final\netty-transport-4.1.82.Final.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\it\unimi\dsi\fastutil\8.5.9\fastutil-8.5.9.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna-platform\5.12.1\jna-platform-5.12.1.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\5.12.1\jna-5.12.1.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.4\jopt-simple-5.0.4.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.21\commons-compress-1.21.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.5.13\httpclient-4.5.13.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.4.15\httpcore-4.4.15.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.19.0\log4j-api-2.19.0.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.19.0\log4j-core-2.19.0.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-slf4j2-impl\2.19.0\log4j-slf4j2-impl-2.19.0.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\joml\joml\1.10.5\joml-1.10.5.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-glfw\3.3.1\lwjgl-glfw-3.3.1.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-glfw\3.3.1\lwjgl-glfw-3.3.1-natives-windows.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-glfw\3.3.1\lwjgl-glfw-3.3.1-natives-windows-arm64.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-glfw\3.3.1\lwjgl-glfw-3.3.1-natives-windows-x86.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.3.1\lwjgl-jemalloc-3.3.1.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.3.1\lwjgl-jemalloc-3.3.1-natives-windows.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.3.1\lwjgl-jemalloc-3.3.1-natives-windows-arm64.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.3.1\lwjgl-jemalloc-3.3.1-natives-windows-x86.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-openal\3.3.1\lwjgl-openal-3.3.1.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-openal\3.3.1\lwjgl-openal-3.3.1-natives-windows.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-openal\3.3.1\lwjgl-openal-3.3.1-natives-windows-arm64.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-openal\3.3.1\lwjgl-openal-3.3.1-natives-windows-x86.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-opengl\3.3.1\lwjgl-opengl-3.3.1.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-opengl\3.3.1\lwjgl-opengl-3.3.1-natives-windows.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-opengl\3.3.1\lwjgl-opengl-3.3.1-natives-windows-arm64.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-opengl\3.3.1\lwjgl-opengl-3.3.1-natives-windows-x86.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-stb\3.3.1\lwjgl-stb-3.3.1.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-stb\3.3.1\lwjgl-stb-3.3.1-natives-windows.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-stb\3.3.1\lwjgl-stb-3.3.1-natives-windows-arm64.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-stb\3.3.1\lwjgl-stb-3.3.1-natives-windows-x86.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-tinyfd\3.3.1\lwjgl-tinyfd-3.3.1.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-tinyfd\3.3.1\lwjgl-tinyfd-3.3.1-natives-windows.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-tinyfd\3.3.1\lwjgl-tinyfd-3.3.1-natives-windows-arm64.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-tinyfd\3.3.1\lwjgl-tinyfd-3.3.1-natives-windows-x86.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\3.3.1\lwjgl-3.3.1.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\3.3.1\lwjgl-3.3.1-natives-windows.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\3.3.1\lwjgl-3.3.1-natives-windows-arm64.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\3.3.1\lwjgl-3.3.1-natives-windows-x86.jar;C:\Users\socdi\AppData\Roaming\.minecraft\libraries\org\slf4j\slf4j-api\2.0.1\slf4j-api-2.0.1.jar;C:\Users\socdi\AppData\Roaming\.minecraft\versions\fabric-loader-0.14.25-1.20.1\fabric-loader-0.14.25-1.20.1.jar -DFabricMcEmu= net.minecraft.client.main.Main  -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true -Djava.net.preferIPv4Stack=true -Dminecraft.applet.TargetDirectory=C:\Users\socdi\AppData\Roaming\.minecraft -Dlog4j.configurationFile=C:\Users\socdi\AppData\Roaming\.minecraft\assets\log_configs\client-1.12.xml net.fabricmc.loader.impl.launch.knot.KnotClient --username vnxk_ --version fabric-loader-0.14.25-1.20.1 --gameDir C:\Users\socdi\AppData\Roaming\.minecraft --assetsDir C:\Users\socdi\AppData\Roaming\.minecraft\assets --assetIndex 5 --uuid e1bf0a9b17fd4d2e84565ea69f5d1e1e --accessToken null --clientId null --xuid null --userType mojang --versionType release --width 925 --height 530
[Launcher] Launching Minecraft...
I'm hiding!
[TLauncherManager] mods after C:\Users\socdi\AppData\Roaming\.minecraft\mods\fabric-api-0.85.0+1.20.1.jar C:\Users\socdi\AppData\Roaming\.minecraft\mods\optifabric-1.13.25.jar C:\Users\socdi\AppData\Roaming\.minecraft\mods\OptiFine_1.20.1_HD_U_I5_MOD.jar C:\Users\socdi\AppData\Roaming\.minecraft\mods\replaymod-1.20.1-2.6.14.jar
[InnerMinecraftServersImpl]  search changers of the servers
read servers from servers.dat [Server(name=HAi banh xeo , address=ww.hypixel.net, ip=ww.hypixel.net, port=null, hideAddress=false, acceptTextures=0), Server(name=LampSMP, address=MoonLightSMP33.aternos.me:43117, ip=MoonLightSMP33.aternos.me, port=43117, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=PLAY.JARTEXNETWORK.COM, ip=PLAY.JARTEXNETWORK.COM, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=luckyvn.com, ip=luckyvn.com, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=mineahihi.com, ip=mineahihi.com, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=play.pika-network.net, ip=play.pika-network.net, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=play.archevexmc.com, ip=play.archevexmc.com, port=null, hideAddress=false, acceptTextures=-1), Server(name=Minecraft Server, address=20.219.6.132, ip=20.219.6.132, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=newtownsmp.mcplay.eu, ip=newtownsmp.mcplay.eu, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=Erika091.aternos.me:23442, ip=Erika091.aternos.me, port=23442, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=127.0.0.1, ip=127.0.0.1, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=bwhub.net, ip=bwhub.net, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=bedwarspractice.club, ip=bedwarspractice.club, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=zenora.enia.net, ip=zenora.enia.net, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Se, address=mineocd.com, ip=mineocd.com, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=mc.deadpvp.eu, ip=mc.deadpvp.eu, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=3fmc.com, ip=3fmc.com, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=210.viemc.net, ip=210.viemc.net, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=heromc.net, ip=heromc.net, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=Erika091.aternos.me:23053, ip=Erika091.aternos.me, port=23053, hideAddress=false, acceptTextures=1), Server(name=Minecraft Server, address=bedwarspractice.club, ip=bedwarspractice.club, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=2b2t.org, ip=2b2t.org, port=null, hideAddress=false, acceptTextures=0), Server(name=anhemvn, address=anhemvn.aternos.me:63175, ip=anhemvn.aternos.me, port=63175, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=bridger.land, ip=bridger.land, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=minemen.club, ip=minemen.club, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=zakaz8026.aternos.me:22664, ip=zakaz8026.aternos.me, port=22664, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=mazer.club, ip=mazer.club, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=Newtown.mc-server.eu, ip=Newtown.mc-server.eu, port=null, hideAddress=false, acceptTextures=0), Server(name=Minecraft Server, address=jartexnetwork.com, ip=jartexnetwork.com, port=null, hideAddress=false, acceptTextures=0)]
[InnerMinecraftServersImpl]  prepare inner servers
save servers to servers.dat
[Launcher] Game skin type: TLAUNCHER
[Launcher] Starting Minecraft fabric-loader-0.14.25-1.20.1...
[Launcher] Launching in: C:\Users\socdi\AppData\Roaming\.minecraft
Starting garbage collector: 240 / 382 MB
Garbage collector completed: 56 / 448 MB
[Launcher] Processing post-launch actions. Assist launch: true
===============================================================================================
[21:23:56] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.25
[21:23:79] [main/INFO]: Loading 56 mods:
	- fabric-api 0.85.0+1.20.1
	   |-- fabric-api-base 0.4.29+b04edc7a77
	   |-- fabric-api-lookup-api-v1 1.6.34+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.9+e022e5d177
	   |-- fabric-blockrenderlayer-v1 1.1.39+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.0+97bb207577
	   |-- fabric-command-api-v1 1.2.32+f71b366f77
	   |-- fabric-command-api-v2 2.2.11+b3afc78b77
	   |-- fabric-commands-v0 0.2.49+df3654b377
	   |-- fabric-containers-v0 0.1.61+df3654b377
	   |-- fabric-content-registries-v0 4.0.8+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.3+b3afc78b77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.1.12+b3afc78b77
	   |-- fabric-dimensions-v1 2.1.51+b3afc78b77
	   |-- fabric-entity-events-v1 1.5.21+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.0+b3afc78b77
	   |-- fabric-events-lifecycle-v0 0.2.61+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.26+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.8+40e50c4677
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.38+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.42+9e7660c677
	   |-- fabric-message-api-v1 5.1.6+b3afc78b77
	   |-- fabric-mining-level-api-v1 2.1.48+b3afc78b77
	   |-- fabric-models-v0 0.3.35+b3afc78b77
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b77
	   |-- fabric-networking-v0 0.3.48+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.0+6beca84877
	   |-- fabric-particles-v1 1.1.0+201a23a077
	   |-- fabric-recipe-api-v1 1.0.18+b3afc78b77
	   |-- fabric-registry-sync-v0 2.2.6+b3afc78b77
	   |-- fabric-renderer-api-v1 3.1.0+c154966e77
	   |-- fabric-renderer-indigo 1.4.0+c154966e77
	   |-- fabric-renderer-registries-v1 3.2.44+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b77
	   |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b77
	   |-- fabric-rendering-v0 1.1.47+df3654b377
	   |-- fabric-rendering-v1 3.0.6+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-resource-loader-v0 0.11.8+e3d6ed2577
	   |-- fabric-screen-api-v1 2.0.6+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.27+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.2.3+43a3fedd77
	   \-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b77
	- fabricloader 0.14.25
	- java 17
	- minecraft 1.20.1
	- optifabric 1.13.25
	   \-- mm 2.3
	- replaymod 1.20.1-2.6.14
	   |-- fabric-api-base 0.4.29+b04edc7a77
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b77
	   \-- fabric-screen-api-v1 2.0.6+b3afc78b77
[21:23:96] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/socdi/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[21:23:17] [main/INFO]: Compatibility level set to JAVA_16
[21:23:18] [main/INFO]: Compatibility level set to JAVA_17
[21:23:49] [main/WARN]: Reference map 'mixins.nonmmlauncher.replaymod.refmap.json' for mixins.nonmmlauncher.replaymod.json could not be read. If this is a development environment you can ignore this message
Found existing patched optifine jar, using that
Replay Mod is still using the traditional Early Riser initialisation
[21:23:72] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[21:23:73] [main/WARN]: Error loading class: net/coderbot/iris/uniforms/CommonUniforms (java.lang.ClassNotFoundException: net/coderbot/iris/uniforms/CommonUniforms)
[21:23:74] [main/WARN]: Error loading class: net/coderbot/iris/Iris (java.lang.ClassNotFoundException: net/coderbot/iris/Iris)
[21:23:75] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[21:23:75] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[21:23:34] [main/ERROR]: Mixin apply for mod replaymod failed mixins.jgui.json:MixinKeyboardListener from mod replaymod -> net.minecraft.class_309: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException 'static' modifier of handler method does not match target in net/minecraft/class_309::charTypedOptifine [PREINJECT Applicator Phase -> mixins.jgui.json:MixinKeyboardListener from mod replaymod -> Prepare Injections ->  -> handler$zkh000$replaymod$charTypedOptifine(CILnet/minecraft/class_364;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: 'static' modifier of handler method does not match target in net/minecraft/class_309::charTypedOptifine [PREINJECT Applicator Phase -> mixins.jgui.json:MixinKeyboardListener from mod replaymod -> Prepare Injections ->  -> handler$zkh000$replaymod$charTypedOptifine(CILnet/minecraft/class_364;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.checkTargetModifiers(Injector.java:347)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.sanityCheck(CallbackInjector.java:425)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:237)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2371)
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:541)
	at net.minecraft.class_128.method_568(class_128.java:175)
	at net.minecraft.class_128.method_24305(class_128.java:345)
	at net.minecraft.client.main.Main.main(Main.java:164)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

[21:23:49] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_128.method_568(class_128.java:175)
	at net.minecraft.class_128.method_24305(class_128.java:345)
	at net.minecraft.client.main.Main.main(Main.java:164)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_309 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2371)
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:541)
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 15 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.jgui.json:MixinKeyboardListener from mod replaymod] from phase [DEFAULT] in config [mixins.jgui.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 18 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: 'static' modifier of handler method does not match target in net/minecraft/class_309::charTypedOptifine [PREINJECT Applicator Phase -> mixins.jgui.json:MixinKeyboardListener from mod replaymod -> Prepare Injections ->  -> handler$zkh000$replaymod$charTypedOptifine(CILnet/minecraft/class_364;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.checkTargetModifiers(Injector.java:347)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.sanityCheck(CallbackInjector.java:425)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:237)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 18 more

Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (87 ms)
[Launcher] Minecraft closed with exit code: 1
flush now
[Launcher] Launcher exited.
flush now
![Screenshot 2023-12-18 212523](https://github.com/Chocohead/OptiFabric/assets/95141156/8919366d-e4f9-451e-b197-f6261d6489b8)
![Screenshot 2023-12-18 212710](https://github.com/Chocohead/OptiFabric/assets/95141156/10d5daa0-33c8-4e28-8ae7-81799f757672)
![Screenshot 2023-12-18 212720](https://github.com/Chocohead/OptiFabric/assets/95141156/42463a2a-f275-4879-b37f-f5beaeeabd98)

**Comment by Thienyeuvy** [comment]
help me

**Comment by Unkrown6YT** [comment]
Did you download Java?

**Comment by Dracconis** [comment]
Well first off support isnt given to those who use a cracked launcher. So when you use an official MC Launcher and get an error then come back here and report the error. This ticket needs to be closed.
