### ISSUE TITLE
Optifabric for Minecraft 1.20

### ISSUE THREAD

**Issue by SkywardSylphina** [Chocohead/OptiFabric#1317]
I've been trying to get optifabric working over the past few days and keep running into the same error message.  Optifine and fabric are both working when they're separate but when I try and add optifine and optifabric into my fabric mods folder this is the message I'm getting.

<img width="410" alt="image" src="https://github.com/Chocohead/OptiFabric/assets/154928997/a28ed039-851f-48e8-97c8-f97295e66cb8">

Here's my mods folder
<img width="550" alt="image" src="https://github.com/Chocohead/OptiFabric/assets/154928997/029afe18-7ae9-4cdf-bae7-e17a2a046b15">

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-12-26 15:44:34
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of me.modmuss50.optifabric.mod.Text failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.class_442.handler$zkd003$optifabric$init(class_442.java:1089)
	at net.minecraft.class_442.method_25426(class_442.java:156)
	at net.minecraft.class_437.method_25423(class_437.java:297)
	at net.minecraft.class_310.method_1507(class_310.java:1080)
	at net.minecraft.class_310.method_51251(class_310.java:690)
	at net.minecraft.class_310.<init>(class_310.java:674)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 14 more
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider$Member
	at me.modmuss50.optifabric.util.RemappingUtils.mapMethod(RemappingUtils.java:35)
	at me.modmuss50.optifabric.mod.TextSetup.lambda$run$0(TextSetup.java:29)
	at com.chocohead.mm.Plugin.preApply(Plugin.java:378)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.preApply(PluginHandle.java:158)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.preApply(MixinInfo.java:1358)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.preApply(MixinTargetContext.java:1259)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:315)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 17 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider$Member
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 27 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.class_442.handler$zkd003$optifabric$init(class_442.java:1089)
	at net.minecraft.class_442.method_25426(class_442.java:156)
	at net.minecraft.class_437.method_25423(class_437.java:297)
	at net.minecraft.class_310.method_1507(class_310.java:1080)
	at net.minecraft.class_310.method_51251(class_310.java:690)
	at net.minecraft.class_310.<init>(class_310.java:674)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		AppXDeploymentClient.dll:AppX Deployment Client DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.22621.2506:Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		DEVOBJ.dll:Device Information Set DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		GLU32.dll:OpenGL Utility Library DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		MMDevApi.dll:MMDevice API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		MSASN1.dll:ASN.1 Runtime APIs:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:MSCTF Server DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.23110.3 (9ebb3643d539a6fc4659898b1df3124d5da4c0a9):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Oleacc.dll:Active Accessibility Core Component:7.2.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OpenAL.dll:Main implementation library:1.21.1:
		POWRPROF.dll:Power Profile Helper DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINTRUST.dll:Microsoft Trust Verification APIs:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Windows.ApplicationModel.dll:Windows ApplicationModel API Server:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Windows.FileExplorer.Common.dll:Windows.FileExplorer.Common:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		Windows.StateRepositoryPS.dll:Windows StateRepository Proxy/Stub Server:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		cfgmgr32.dll:Configuration Manager DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dinput8.dll:Microsoft DirectInput:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		directxdatabasehelper.dll:DirectXDatabaseHelper:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		dwmapi.dll:Microsoft Desktop Window Manager API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dxcore.dll:DXCore:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		dxgi.dll:DirectX Graphics Infrastructure:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		fastprox.dll:WMI Custom Marshaller:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22621.2861 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		icm32.dll:Microsoft Color Management Module (CMM):10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		igc64.dll:Intel Graphics Shader Compiler for Intel(R) Graphics Accelerator:31.0.101.4502:Intel Corporation
		igdgmm64.dll:User Mode Driver for Intel(R) Graphics Technology:31.0.101.4502:Intel Corporation
		igdml64.dll:Metrics Library for Intel(R) Graphics Technology:31.0.101.4502:Intel Corporation
		igxelpicd64.dll:OpenGL(R) Driver for Intel(R) Graphics Accelerator:31.0.101.4502:Intel Corporation
		inputhost.dll:InputHost:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.8.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jna10206011535457506916.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:17.0.8.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.22621.2715 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		lwjgl_opengl.dll
		lwjgl_stb.dll
		management.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		mscms.dll:Microsoft Color Matching System DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		mssprxy.dll:Microsoft Search Proxy:7.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		opengl32.dll:OpenGL Client DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		opus4j.dll
		perfos.dll:Windows System Performance Objects DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		propsys.dll:Microsoft Property System:7.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sapi.dll:Speech API:5.3.26906.00 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		textinputframework.dll:"TextInputFramework.DYNLINK":10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		uxtheme.dll:Microsoft UxTheme Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		wbemcomn.dll:WMI:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		wbemprox.dll:WMI:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		wbemsvc.dll:WMI:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		win32u.dll:Win32u:10.0.22621.2861 (WinBuild.160101.0800):Microsoft Corporation
		windows.staterepositoryclient.dll:Windows StateRepository Client API:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows Base Types DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		xinput1_4.dll:Microsoft Common Controller API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20
	Minecraft Version ID: 1.20
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 386959992 bytes (369 MiB) / 603979776 bytes (576 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i7-1255U
	Identifier: Intel64 Family 6 Model 154 Stepping 4
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.61
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x46a8
	Graphics card #0 versionInfo: DriverVersion=31.0.101.4502
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 6.40
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 6.40
	Memory slot #1 type: Unknown
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 6.40
	Memory slot #2 type: Unknown
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 6.40
	Memory slot #3 type: Unknown
	Memory slot #4 capacity (MB): 4096.00
	Memory slot #4 clockSpeed (GHz): 6.40
	Memory slot #4 type: Unknown
	Memory slot #5 capacity (MB): 4096.00
	Memory slot #5 clockSpeed (GHz): 6.40
	Memory slot #5 type: Unknown
	Memory slot #6 capacity (MB): 4096.00
	Memory slot #6 clockSpeed (GHz): 6.40
	Memory slot #6 type: Unknown
	Memory slot #7 capacity (MB): 4096.00
	Memory slot #7 clockSpeed (GHz): 6.40
	Memory slot #7 type: Unknown
	Virtual memory max (MB): 34640.39
	Virtual memory used (MB): 9129.28
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 0.05
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		audioplayer: AudioPlayer 1.20.1-1.7.1
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a82
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b82
		fabric-api: Fabric API 0.83.0+1.20
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c927
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b27
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d127
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b27
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.20+b3afc78b27
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f27
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b327
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b327
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b27
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b27
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe27
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.10+b3afc78b27
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b27
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b27
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b27
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b327
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a27
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b27
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b27
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da27
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b327
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b27
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b27
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c627
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b27
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b27
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b27
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b27
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b327
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b27
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b27
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b27
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b27
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.0.1+b3afc78b27
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.3.1+b3afc78b27
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b327
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b27
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b27
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b327
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b27
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.4+b3afc78b27
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+f7923f6d27
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b27
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b27
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b27
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b27
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b27
		fabricloader: Fabric Loader 0.15.3
			mixinextras: MixinExtras 0.3.2
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20
		modmenu: Mod Menu 7.0.1
		optifabric: OptiFabric 1.13.25
			mm: Manningham Mills 2.3
		voicechat: Simple Voice Chat 1.20.1-2.4.25
	Launched Version: fabric-loader-0.15.3-1.20
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) Iris(R) Xe Graphics GL version 3.2.0 - Build 31.0.101.4502, Intel
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 12x 12th Gen Intel(R) Core(TM) i7-1255U

-- OptiFabric --
Details:
	OptiFine jar designed for: ~~NULL~~
	OptiFine jar version: ~~NULL~~
	OptiFine jar status: Error whilst searching
	OptiFine remapped jar: ~~NULL~~
	OptiFabric error: Failed to load OptiFine, please report this!

net/fabricmc/tinyremapper/IMappingProvider

**Comment by Poopooracoocoo** [comment]
You'll need to use Fabric Loader 0.14.25
