### ISSUE TITLE
not compatible 

### ISSUE THREAD

**Issue by Combien** [Chocohead/OptiFabric#1359]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.4.10+build.24 with any version that is compatible with:
		 - optifabric 1.13.24
	 - Replace mod 'Iris' (iris) 1.6.11 with any version that is compatible with:
		 - optifabric 1.13.24
More details:
	 - Mod 'Iris' (iris) 1.6.11 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.24!
	 - Mod 'Sodium' (sodium) 0.4.10+build.24 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.24!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by xleb-normal** [comment]
Remove Sodium and Iris
