### ISSUE TITLE
Game crashes upon joining a server (1.20.4)

### ISSUE THREAD

**Issue by realrleReady2** [Chocohead/OptiFabric#1361]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-01-13 16:56:04
Description: Unexpected error

java.lang.NoSuchMethodError: 'void net.minecraft.class_702.renderParticles(net.minecraft.class_4587, net.minecraft.class_4597$class_4598, net.minecraft.class_765, net.minecraft.class_4184, float, net.minecraft.class_4604)'
	at net.minecraft.class_761.method_22710(class_761.java:1849)
	at net.minecraft.class_757.method_3188(class_757.java:1598)
	at net.minecraft.class_757.method_3192(class_757.java:1221)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_761.method_22710(class_761.java:1849)
	at net.minecraft.class_757.method_3188(class_757.java:1598)

-- Uptime --
Details:
	JVM uptime: 68.672s
	Wall uptime: 46.227s
	High-res time: 39.490s
	Client ticks: 617 ticks / 30.850s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:911)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['realrleReady2'/332710, l='ClientLevel', x=-772.50, y=67.23, z=-799.38]]
	Chunk stats: 729, 102
	Level dimension: minecraft:overworld
	Level spawn location: World: (-790,70,-611), Section: (at 10,6,13 in -50,4,-39; chunk contains blocks -800,-64,-624 to -785,319,-609), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,-64,-1024 to -513,319,-513)
	Level time: 20381327 game time, 120769 day time
	Server brand: Purpur
	Server type: Non-integrated multiplayer server
	Tracked entity count: 23

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, essential

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 529187448 bytes (504 MiB) / 1140850688 bytes (1088 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a60
	Graphics card #0 versionInfo: DriverVersion=31.0.101.4575
	Graphics card #1 name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x25a0
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3209
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 32221.57
	Virtual memory used (MB): 27448.75
	Swap memory total (MB): 16110.79
	Swap memory used (MB): 1687.66
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 2.5.1+mc1.20.3
			cloth-config: Cloth Config v13 13.0.114
				cloth-basic-math: cloth-basic-math 0.6.1
		badpackets: Bad Packets 0.5.4
		creativecore: CreativeCore 2.11.16
			net_neoforged_bus: bus 7.2.0
		effortless: Effortless Fabric 1.7.4dev0
		elementa: Elementa 619
		essential: Essential 1.3.0.2+ge922acc4a7
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.1
		fabric-api: Fabric API 0.92.0+1.20.4
			fabric-api-base: Fabric API Base 0.4.35+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.45+78d798af4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.15+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.14+78d798af4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.3+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.45+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.6+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.40+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.19+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.57+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.81+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.9+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.9+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.22+78d798af4f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.17+78d798af4f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.60+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.28+4ced05924f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.0+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.71+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.45+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.1.34+78d798af4f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.20+78d798af4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.40+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.38+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.29+78d798af4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.4+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.4+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.59+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.7+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.6+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.2+78d798af4f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.8+06274a474f
			fabric-particles-v1: Fabric Particles (v1) 1.1.6+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.15+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.13+78d798af4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.3+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.3+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.50+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.41+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.32+78d798af4f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.53+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.12+78d798af4f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.13+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.15+78d798af4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.16+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.50+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.16+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.6+78d798af4f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.13+78d798af4f
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
		fabricloader: Fabric Loader 0.15.3
			mixinextras: MixinExtras 0.3.2
		itemphysiclite: ItemPhysicLite 1.6.3
		java: OpenJDK 64-Bit Server VM 17
		litematica: Litematica 0.17.0
		malilib: MaLiLib 0.18.0
		minecraft: Minecraft 1.20.4
		modmenu: Mod Menu 9.0.0
		optifabric: OptiFabric 1.14.3
			mm: Manningham Mills 2.3
			optifabric-libs: OptiFabric Libraries 1.14.3
		org_jetbrains_annotations: annotations 13.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		tweakeroo: Tweakeroo 0.19.1
		universalcraft: UniversalCraft 323
		vigilance: Vigilance 295
		voicechat: Simple Voice Chat 1.20.4-2.4.32
		wthit: wthit 10.0.1
		xaerominimap: Xaero's Minimap 23.9.6
		xaeroworldmap: Xaero's World Map 1.37.6
	Launched Version: fabric-loader-0.15.3-1.20.4
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 532.09, NVIDIA Corporation
	Window size: 1920x991
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'optifine'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 10/15 chunks
	Resource Packs: vanilla, fabric
	Current Language: en_us
	Locale: en_IN
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	OptiFine Version: OptiFine_1.20.4_HD_U_I7_pre2
	OptiFine Build: 20231222-174400
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 532.09
	OpenGlRenderer: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.20.4
	OptiFine jar version: OptiFine_1.20.4_HD_U_I7_pre2
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/AppData/Roaming/.minecraft/essential_mod/fabric/1.20.4/1.20.4 Fabric Essential/.optifine/OptiFine_1.20.4_HD_U_I7_pre2/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by Chocohead** [comment]
Could you attach the full log file? This looks like something else has gone wrong joining the server, then the crash report is as a result rather than the root cause.

**Comment by realrleReady2** [comment]
Wdym by the full log file?

**Comment by Poopooracoocoo** [comment]
Reproduce this crash, then upload your latest.log from your logs folder.
