### ISSUE TITLE
WTF WITH MOD?!

### ISSUE THREAD

**Issue by AG4492** [Chocohead/OptiFabric#1367]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.5.5 with version 0.5.5 that is compatible with:
		 - optifabric 1.14.3
More details:
	 - Mod 'Sodium' (sodium) 0.5.5 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.14.3!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Poopooracoocoo** [comment]
It's not an actual crash. It's informing you that you must choose between Sodium and OptiFabric/OptiFine as they're not compatible with each other.
