### ISSUE TITLE
Minecraft 1.20.2 --- OptiFabric-v1.14.3 and 1.20.2 versions of Architectury

### ISSUE THREAD

**Issue by Dracconis** [Chocohead/OptiFabric#1381]
`06:47:15.038
FabricLoader/Mixin
main
Critical injection failure: LVT in net/minecraft/class_757::method_3192(FJZ)V has incompatible changes at opcode 672 in callback optifabric.compat.architectury-AB.new4er-mixins.json:GameRendererNew4erMixin from mod optifabric->@Inject::renderScreenPre(FJZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;IILnet/minecraft/class_1041;FLorg/joml/Matrix4f;Lnet/minecraft/class_4587;FLnet/minecraft/class_332;)V.
 Expected: [I, I, Lnet/minecraft/class_1041;, F, Lorg/joml/Matrix4f;, Lnet/minecraft/class_4587;, F, Lnet/minecraft/class_332;]
    Found: [Z, I, I, Lnet/minecraft/class_1041;, F, Lorg/joml/Matrix4f;, Lnet/minecraft/class_4587;, F]
Available: [Z, I, I, Lnet/minecraft/class_1041;, F, Lorg/joml/Matrix4f;, Lnet/minecraft/class_4587;, F, Lnet/minecraft/class_332;, Ljava/lang/Throwable;, Lnet/minecraft/class_128;, Lnet/minecraft/class_129;]
06:47:15.041
FabricLoader
main
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_128.method_568(class_128.java:176)
	at net.minecraft.class_128.method_24305(class_128.java:346)
	at net.minecraft.client.main.Main.main(Main.java:167)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2371)
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:550)
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_757::method_3192(FJZ)V has incompatible changes at opcode 672 in callback optifabric.compat.architectury-AB.new4er-mixins.json:GameRendererNew4erMixin from mod optifabric->@Inject::renderScreenPre(FJZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;IILnet/minecraft/class_1041;FLorg/joml/Matrix4f;Lnet/minecraft/class_4587;FLnet/minecraft/class_332;)V.
 Expected: [I, I, Lnet/minecraft/class_1041;, F, Lorg/joml/Matrix4f;, Lnet/minecraft/class_4587;, F, Lnet/minecraft/class_332;]
    Found: [Z, I, I, Lnet/minecraft/class_1041;, F, Lorg/joml/Matrix4f;, Lnet/minecraft/class_4587;, F]
Available: [Z, I, I, Lnet/minecraft/class_1041;, F, Lorg/joml/Matrix4f;, Lnet/minecraft/class_4587;, F, Lnet/minecraft/class_332;, Ljava/lang/Throwable;, Lnet/minecraft/class_128;, Lnet/minecraft/class_129;]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:547)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 18 more`

Although latest version of OF says it works (and it does WITHOUT architectury) it crashes when architectury is present as 1 of the mods.

**Comment by Dracconis** [comment]
Its been 3 weeks and still no answer?
