### ISSUE TITLE
It isnt opening with minecraft 1.20.4

### ISSUE THREAD

**Issue by LeagueYT** [Chocohead/OptiFabric#1383]
When i try to open the minecraft with optiFabric it gives me the error and this is the error:
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'ImmediatelyFast' (immediatelyfast) 1.2.8+1.20.4 with any version that is compatible with:
		 - optifabric 1.14.3
More details:
	 - Mod 'ImmediatelyFast' (immediatelyfast) 1.2.8+1.20.4 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.14.3!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
pls dude fix this.
And reply me the solution.

**Comment by Vaption** [comment]
As the log you provided says, the problem is with ImmediatelyFast. This is a known incompatibility, referring to the mod's page on Modrinth (as shown in the image attached):
![modrinth](https://github.com/Chocohead/OptiFabric/assets/153444810/832ad6d3-42c2-42db-9f03-f6b84c1ca145)
