### ISSUE TITLE
This crashes with my fabric mods

### ISSUE THREAD

**Issue by gedsweyerv** [Chocohead/OptiFabric#1415]
t]This is the crash report I keep getting. ---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 2/1/24, 10:41 PM
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_340 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.class_329.<init>(class_329.java:154)
	at net.minecraft.class_310.<init>(class_310.java:586)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 10 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [tweakermore.mixins.json:tweaks.mod_tweaks.ofUnlockF3FpsLimit.DebugHudMixin from mod tweakermore] from phase [DEFAULT] in config [tweakermore.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 13 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field updateInfoLeftTimeMs was not located in the target class net.minecraft.class_340. Using refmap tweakermore-mc1.19-refmap.json Field is @Dynamic(Added by optifine)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.class_329.<init>(class_329.java:154)
	at net.minecraft.class_310.<init>(class_310.java:586)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Mac OS X (aarch64) version 14.1.1
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 230813568 bytes (220 MiB) / 603979776 bytes (576 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: Apple Inc.
	Processor Name: Apple M2 Max
	Identifier: redacting
	Microarchitecture: unknown
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 12
	Graphics card #0 name: Apple M2 Max
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 66560.00
	Virtual memory used (MB): 25318.98
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 120.25
	JVM Flags: 7 total; -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		animatica: Animatica 0.5+1.19
		architectury: Architectury 5.14.84
		betterfpsdist: Better FPS distance Mod 1.19-1.9
		blanket-client-tweaks: Blanket Client-tweaks 1.1.2
		bobby: Bobby 4.0.0
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		borderlessmining: Borderless Mining 1.1.3+1.19
		capes: Capes 1.4.1+1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		citresewn: CIT Resewn 1.1.2+1.19.2
			citresewn-defaults: CIT Resewn: Defaults 1.1.2+1.19.2
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v8 8.0.75
		clumps: Clumps 9.0.0+7
		continuity: Continuity 2.0.0+1.19
		cull-less-leaves: Cull Less Leaves 1.0.3
		cullleaves: Cull Leaves 3.0.1
			midnightlib: MidnightLib 1.0.0
		dynview: Dynamic View Mod 1.19-2.2
		eatinganimationid: Eating Animation 1.9
		entitycollisionfpsfix: Entity Collision FPS Fix 2.0.0.0
		fabric: Fabric API 0.58.0+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.28+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.2+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c43a9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.1.0+442de8b8a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.15+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.18+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39fa9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e0a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.7+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.3
			mixinextras: MixinExtras 0.3.2
		fabricskyboxes: FabricSkyBoxes 0.7.2+mc1.19.2
		farsight: Farsight Mod 1.19-2.0
		faster_entity_animations: FastAnim 1.5.6
		ferritecore: FerriteCore 4.2.1
		freecam: Freecam 1.1.3
		infinitemusic: Infinite Music 1.6.2
		itemscroller: Item Scroller 0.17.0
		java: OpenJDK 64-Bit Server VM 17
		lazydfu: LazyDFU 0.1.3
		litematica: Litematica 0.12.1
		litematica_printer: Litematica Printer 3.2
		logical_zoom: Logical Zoom 0.0.15
		malilib: MaLiLib 0.13.0
		methane: Methane 1.7
		minecraft: Minecraft 1.19
		minihud: MiniHUD 0.23.0
		modmenu: Mod Menu 4.0.4
		moreculling: More Culling 1.19.1-0.10.1
		notenoughanimations: NotEnoughAnimations 1.6.4
		optifabric: OptiFabric 1.13.16
			mm: Manningham Mills 2.3
		player-animator: Player Animator 1.0.2
		presencefootsteps: Presence Footsteps 1.6.0
			kirin: Kirin UI 1.11.0
		rayon: Rayon 1.6.0
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.1
		sound_physics_remastered: Sound Physics Remastered 1.19-1.0.10
		sss: Super Secret Settings 1.1.0
		tweakermore: TweakerMore 3.6.1
			conditional-mixin: conditional mixin 0.3.1
		tweakeroo: Tweakeroo 0.14.0
		worldedit: WorldEdit 7.2.11-beta-02+315c5d0
		xaerominimap: Xaero's Minimap 22.12.0
		xaeroworldmap: Xaero's World Map 1.26.1
		yet-another-config-lib: YetAnotherConfigLib 1.7.1
	Launched Version: fabric-loader-0.15.3-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Apple M2 Max GL version 4.1 Metal - 88, Apple
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 12x Apple M2 Max

-- OptiFabric --
Details:
	OptiFine jar designed for: ~~NULL~~
	OptiFine jar version: ~~NULL~~
	OptiFine jar status: Error whilst searching
	OptiFine remapped jar: ~~NULL~~
	OptiFabric error: Failed to load OptiFine, please report this!

net/fabricmc/tinyremapper/IMappingProvider

**Comment by Dracconis** [comment]
Well from what I can see this mod isn't compatible with 1.19: omega-config: OmegaConfig 1.2.3-1.18.1. Also due to the vast number of mods you have installed I cant tell more than that. Try running MC with just Fabric loader, fabric api, optifabric, and optifine only to see if it will launch without crashing. Then IF it doesn't crash add only HALF of the mods in the list back in and try again (IF it does crash then the affecting mod is 1 of the 1s you added back in). Every time you try after adding back some of the mods, if it crashes then take out half of the mods you just added and keep trying until you find the mod that is causing the crash. Keep doing that until you get a crash. Once you get a crash you will know approximately which mod, if any, is causing the crash.
