### ISSUE TITLE
Loading OptiFabric Error

### ISSUE THREAD

**Issue by Ivan22090** [Chocohead/OptiFabric#1436]
Minecarft: 1.16.5 Fabric
Stack-trace:
java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 25 more
Help please

**Comment by Dracconis** [comment]
Try using Fabric Loader 0.14.25.

**Comment by Ivan22090** [comment]
> Try using Fabric Loader 0.14.25.
Tried it doesn't work
And should I uninstall the new version? If so, how?

**Comment by Dracconis** [comment]
Which mods are you using and what are their versions?

**Comment by Ivan22090** [comment]
> Which mods are you using and what are their versions?
i need to send All?

**Comment by Dracconis** [comment]
Ok fine. Fabric Loader version, Fabric API version, Optifabric version, Optifine version?

**Comment by Ivan22090** [comment]
> Ok fine. Fabric Loader version, Fabric API version, Optifabric version, Optifine version?

Fabric Loader version: 0.14.25
Fabric API version: fabric-api-0.42.0+1.16
Optifabric version: optifabric-1.13.16
Optifine version: OptiFine_1.16.5_HD_U_G8

**Comment by Ivan22090** [comment]
> Ok fine. Fabric Loader version, Fabric API version, Optifabric version, Optifine version?

Tried without mods nothing changed:
![Снимок экрана 2024-02-12 173023](https://github.com/Chocohead/OptiFabric/assets/159724728/e82c853d-409f-4a68-87e7-2596ba71922a)
Mods:
![Снимок экрана 2024-02-12 173142](https://github.com/Chocohead/OptiFabric/assets/159724728/410d2bee-8cc7-4093-89e6-9cb89550c094)
![Снимок экрана 2024-02-12 173151](https://github.com/Chocohead/OptiFabric/assets/159724728/831ddea1-fb54-4422-9b9c-fbbb42261425)

**Comment by Dracconis** [comment]
Did you try running it with only the 3 mods (Fabric API, Optifabric, Optifine) using the 14.25 Fabric Launcher profile?

**Comment by Ivan22090** [comment]
> Did you try running it with only the 3 mods (Fabric API, Optifabric, Optifine) using the 14.25 Fabric Launcher profile?

I already tried this in my comment

**Comment by Dracconis** [comment]
Just making sure we have all bases covered. Have you tried running the vanilla launcher for 1.16.5 once to ensure the version was downloaded by the launcher and the game started?

**Comment by Ivan22090** [comment]
> Just making sure we have all bases covered. Have you tried running the vanilla launcher for 1.16.5 once to ensure the version was downloaded by the launcher and the game started?

Yes its running perfectly

**Comment by Dracconis** [comment]
Is that the log file in the first post or is that just the stack trace of the error?

**Comment by Ivan22090** [comment]
> Is that the log file in the first post or is that just the stack trace of the error?

Stack trace

**Comment by Ivan22090** [comment]
> Is that the log file in the first post or is that just the stack trace of the error?

You want a log file?
Idk where it is :(

**Comment by Dracconis** [comment]
At this point it would be helpful to see what is going on when it is trying to launch MC.
%AppData%\Roaming\.minecraft\crash-reports (the 1 with the most recent date)
%AppData%\Roaming\.minecraft\logs (latest.log)

**Comment by Ivan22090** [comment]
> At this point it would be helpful to see what is going on when it is trying to launch MC. %AppData%\Roaming.minecraft\crash-reports (the 1 with the most recent date) %AppData%\Roaming.minecraft\logs (latest.log)

I didnt find it
I think its because i didnt use official launcher(i use Legacy Launcher)
But i find this
[launcher.log](https://github.com/Chocohead/OptiFabric/files/14253891/launcher.log)
[launcher.log.10.txt](https://github.com/Chocohead/OptiFabric/files/14253892/launcher.log.10.txt) < i think its the same file like upper

[latest.log](https://github.com/Chocohead/OptiFabric/files/14253898/latest.log) < Minecraft folder log

**Comment by Ivan22090** [comment]
i see in the latest.log he starting with Fabric Loader 0.15.6 but i didnt have it:
![Снимок экрана 2024-02-12 181604](https://github.com/Chocohead/OptiFabric/assets/159724728/8d8d8443-a7ec-4da1-9926-c85d311cd9fe)

**Comment by Ivan22090** [comment]
I think this is my mistake, sorry for wasting your time. 😔

**Comment by Ivan22090** [comment]
I think i cant use optifine on unofficial launcher

**Comment by Dracconis** [comment]
Its ok. That is one of the reasons we ask for logs. I hope you get it figured out and working.
