### ISSUE TITLE
There was an error loading OptiFbric!

### ISSUE THREAD

**Issue by GARRDAA** [Chocohead/OptiFabric#1480]
Failed to load OptiFine, please report this!

**Comment by danielxpc2010** [comment]
ami tampoco

**Comment by therange1** [comment]
java.lang.RuntimeException: Failed to remap jar
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:252)
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:236)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:184)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.nio.file.AccessDeniedException: C:\WINDOWS\TEMP\optifabric13676958153680136883\Optifine-remapped.jar
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:96)
	at java.base/sun.nio.fs.WindowsLinkSupport.getRealPath(WindowsLinkSupport.java:258)
	at java.base/sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:933)
	at java.base/sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:42)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:108)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
	at me.modmuss50.optifabric.shadow.tinyremapper.FileSystemReference.open(FileSystemReference.java:74)
	at me.modmuss50.optifabric.shadow.tinyremapper.FileSystemReference.openJar(FileSystemReference.java:48)
	at me.modmuss50.optifabric.shadow.tinyremapper.OutputConsumerPath.<init>(OutputConsumerPath.java:101)
	at me.modmuss50.optifabric.shadow.tinyremapper.OutputConsumerPath.<init>(OutputConsumerPath.java:42)
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:3074)
	... 27 more

**Comment by Dracconis** [comment]
> java.lang.RuntimeException: Failed to remap jar at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:252) at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:236) at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:184) at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46) at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) at com.chocohead.mm.Plugin.getMixins(Plugin.java:340) at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128) at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796) at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568) at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) at java.base/java.lang.Class.forName0(Native Method) at java.base/java.lang.Class.forName(Class.java:467) at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) Caused by: java.nio.file.AccessDeniedException: C:\WINDOWS\TEMP\optifabric13676958153680136883\Optifine-remapped.jar at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:96) at java.base/sun.nio.fs.WindowsLinkSupport.getRealPath(WindowsLinkSupport.java:258) at java.base/sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:933) at java.base/sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:42) at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:108) at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339) at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288) at me.modmuss50.optifabric.shadow.tinyremapper.FileSystemReference.open(FileSystemReference.java:74) at me.modmuss50.optifabric.shadow.tinyremapper.FileSystemReference.openJar(FileSystemReference.java:48) at me.modmuss50.optifabric.shadow.tinyremapper.OutputConsumerPath.(OutputConsumerPath.java:101) at me.modmuss50.optifabric.shadow.tinyremapper.OutputConsumerPath.(OutputConsumerPath.java:42) at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:3074) ... 27 more

You need to open your own ticket rather than hijacking someone else's ticket please.

**Comment by Dracconis** [comment]
> Failed to load OptiFine, please report this!

Please load your error log files
