### ISSUE TITLE
there was an error loading optifabric 1.16.5 solved

### ISSUE THREAD

**Issue by Quivesy** [Chocohead/OptiFabric#1487]
i tried the newest fabric loader and the 0.14.25 version

java.lang.NoSuchMethodError: net.fabricmc.loader.FabricLoader.getGameProvider()Lnet/fabricmc/loader/game/GameProvider;
	at me.modmuss50.optifabric.mod.OptifineSetup.getLaunchMinecraftJar(OptifineSetup.java:299)
	at me.modmuss50.optifabric.mod.OptifineSetup.getMinecraftJar(OptifineSetup.java:277)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:84)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at com.chocohead.mm.Plugin$$Lambda$60/1589707549.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
![screen](https://github.com/Chocohead/OptiFabric/assets/120107551/e821ffd1-ff08-44df-a82f-09e11e129572)

**Comment by Quivesy** [comment]
i fixed it by using fabric loader 0.10.8

**Comment by Poopooracoocoo** [comment]
You could alternatively have updated OptiFabric. Why would you use such an old version in the first place?

**Comment by Quivesy** [comment]
i need to stay with 1.16.5 for a server

**Comment by Poopooracoocoo** [comment]
I meant an old version of OptiFabric. The latest version of OptiFabric for Minecraft 1.16.5 is 1.13.16.

But now that you mention your Minecraft version, you could use the ViaFabricPlus mod on newer versions of Minecraft to play on that 1.16.5 server...
