### ISSUE TITLE
Help me optifabric is not working (1.20.1)

### ISSUE THREAD

**Issue by obligoblin** [Chocohead/OptiFabric#1493]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Specified index 2 for @ModifyArg is invalid for args (Lnet/minecraft/class_332;Lnet/minecraft/class_327;Lnet/minecraft/class_2561;III), expected I on net/minecraft/class_355::essential$shiftNameTextAndRenderIcon [INJECT Applicator Phase -> mixins.essential.json:client.gui.MixinGuiPlayerTabOverlay from mod (unknown) -> Apply Injections ->  -> Inject -> mixins.essential.json:client.gui.MixinGuiPlayerTabOverlay from mod (unknown)->@SugarWrapper::essential$shiftNameTextAndRenderIcon(Lnet/minecraft/class_327;Lnet/minecraft/class_2561;III)I]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.findArgIndex(ModifyArgInjector.java:158)
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.injectAtInvoke(ModifyArgInjector.java:113)
	at org.spongepowered.asm.mixin.injection.invoke.InvokeInjector.inject(InvokeInjector.java:82)
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.inject(ModifyArgInjector.java:103)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at gg.essential.lib.mixinextras.wrapper.InjectorWrapperImpl.inject(InjectorWrapperImpl.java:127)
	at gg.essential.lib.mixinextras.wrapper.InjectorWrapperImpl.doGranularInject(InjectorWrapperImpl.java:100)
	at gg.essential.lib.mixinextras.wrapper.InjectorWrapperImpl.granularInject(InjectorWrapperImpl.java:75)
	at gg.essential.lib.mixinextras.sugar.impl.SugarWrapperImpl.granularInject(SugarWrapperImpl.java:73)
	at gg.essential.lib.mixinextras.wrapper.InjectorWrapperImpl.inject(InjectorWrapperImpl.java:62)
	at gg.essential.lib.mixinextras.wrapper.WrapperInjectionInfo.inject(WrapperInjectionInfo.java:71)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1378)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_329.<init>(class_329.java:145)
	at net.minecraft.class_310.<init>(class_310.java:603)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)

       also im on feather so i dont know how im able to change the fabric loader version and all the text is just squares.

**Comment by oGless** [comment]
im on feather and all the text is just squares what do i do??????????????
PLEASE HELP

**Comment by Dracconis** [comment]
> im on feather and all the text is just squares what do i do?????????????? PLEASE HELP

Open your own ticket and not hijack someone else's instead.

**Comment by oGless** [comment]
how

**Comment by Dracconis** [comment]
> how

Upper right corner is a button that says "New Issue" either here in this ticket or on the main ticket listing
