### ISSUE TITLE
i wanna play with optiffine on multimc so i download optifabric as normal optifine wasntt working and it showed me error loading oftifabric

### ISSUE THREAD

**Issue by hardik210521** [Chocohead/OptiFabric#1497]
java.lang.RuntimeException: Error running OptiFine patcher at C:\Users\Admin\Downloads\mmc-develop-win32\MultiMC\instances\1.20.4\.minecraft\mods\preview_OptiFine_1.20.4_HD_U_I7_pre2.jar on C:\Users\Admin\Downloads\mmc-develop-win32\MultiMC\instances\1.20.4\.minecraft\bin\minecraft.jar
	at me.modmuss50.optifabric.mod.OptifineSetup.runInstaller(OptifineSetup.java:231)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:109)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at me.modmuss50.optifabric.mod.OptifineSetup.runInstaller(OptifineSetup.java:229)
	... 34 more
Caused by: java.lang.Exception: MD5 not matching, name: assets/minecraft/models/block/template_glass_pane_noside.json, saved: 3b95f19c72eec06718e565bfbf97ef8c, patched: 619016fe6f27aba1ea041a99c1ae8a38
	at optifine.Patcher.process(Patcher.java:101)
	... 39 more

**Comment by Vlader7** [comment]
i have the same problem

**Comment by hardik210521** [comment]
bruhhh
someone help pls

**Comment by hardik210521** [comment]
i have tried many methods 
nothing working

**Comment by Dracconis** [comment]
Which Fabric Loader, Fabric API, Optifabric are you using?

**Comment by koolkidjimmy** [comment]
Hey so I don't use the main installer for Optifine, I use the mod one when you extract it somewhere, I feel it is way more stable anyway.

**I don't use MultiMC so I can't provide any really helpful advice, but make sure you are using the most up to date Fabric-Loader for  your OptiFabric ( With 1.13.6?** [Is that the latest OptiFabric?] **0.14.25 is the most up to date Fabric-Loader).**
Aswell as use the most up to date OptiFabric version there is currently for your minecraft version.
