### ISSUE TITLE
optifabric issue in 1.16.5 using fabric loader 0.14.25

### ISSUE THREAD

**Issue by Aakish9638** [Chocohead/OptiFabric#1501]
java.lang.NoSuchMethodError: net.fabricmc.loader.FabricLoader.getGameProvider()Lnet/fabricmc/loader/game/GameProvider;
	at me.modmuss50.optifabric.mod.OptifineSetup.getLaunchMinecraftJar(OptifineSetup.java:299)
	at me.modmuss50.optifabric.mod.OptifineSetup.getMinecraftJar(OptifineSetup.java:277)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:84)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at com.chocohead.mm.Plugin$$Lambda$70/596779307.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Dracconis** [comment]
What version of Fabric API, Optifabric, and Optifine are you using?

**Comment by Poopooracoocoo** [comment]
The latest version of OptiFabric for 1.16.5 is 1.13.16. It supports Fabric Loader 0.14.25. You're likely using a much older version of OptiFabric. Keep in mind that CurseForge has a filter for Minecraft versions on the "files" page.

**Comment by Dracconis** [comment]
> The latest version of OptiFabric for 1.16.5 is 1.13.16. It supports Fabric Loader 0.14.25. You're likely using a much older version of OptiFabric. Keep in mind that CurseForge has a filter for Minecraft versions on the "files" page.

I hate doing this but when you have a chance could you look at my 3 open tickets sir?

**Comment by Poopooracoocoo** [comment]
@Dracconis My comments here have been more for the support requests to try to keep this as more of an issue tracker than a support forum. I don't have the knowledge to fix OptiFabric 0.14.3's incompatibility with Architectury, sorry.

**Comment by Dracconis** [comment]
> @Dracconis My comments here have been more for the support requests to try to keep this as more of an issue tracker than a support forum. I don't have the knowledge to fix OptiFabric 0.14.3's incompatibility with Architectury, sorry.

That is perfectly fine. I just see your help a lot and had no way of knowing your level of expertise, but having a different set of eyes may have shed some light on something I may have done wrong is all.
