### ISSUE TITLE
Optifabric bug with feather client

### ISSUE THREAD

**Issue by WolfysquadYT** [Chocohead/OptiFabric#1503]
all i see is [][][][][][][][][][][][][] but i remebered that i can copy it so i saw this when i copyed it:org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Specified index 2 for @ModifyArg is invalid for args (Lnet/minecraft/class_332;Lnet/minecraft/class_327;Lnet/minecraft/class_2561;III), expected I on net/minecraft/class_355::essential$shiftNameTextAndRenderIcon [INJECT Applicator Phase -> mixins.essential.json:client.gui.MixinGuiPlayerTabOverlay from mod (unknown) -> Apply Injections ->  -> Inject -> mixins.essential.json:client.gui.MixinGuiPlayerTabOverlay from mod (unknown)->@SugarWrapper::essential$shiftNameTextAndRenderIcon(Lnet/minecraft/class_327;Lnet/minecraft/class_2561;III)I]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.findArgIndex(ModifyArgInjector.java:158)
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.injectAtInvoke(ModifyArgInjector.java:113)
	at org.spongepowered.asm.mixin.injection.invoke.InvokeInjector.inject(InvokeInjector.java:82)
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.inject(ModifyArgInjector.java:103)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at gg.essential.lib.mixinextras.wrapper.InjectorWrapperImpl.inject(InjectorWrapperImpl.java:127)
	at gg.essential.lib.mixinextras.wrapper.InjectorWrapperImpl.doGranularInject(InjectorWrapperImpl.java:100)
	at gg.essential.lib.mixinextras.wrapper.InjectorWrapperImpl.granularInject(InjectorWrapperImpl.java:75)
	at gg.essential.lib.mixinextras.sugar.impl.SugarWrapperImpl.granularInject(SugarWrapperImpl.java:73)
	at gg.essential.lib.mixinextras.wrapper.InjectorWrapperImpl.inject(InjectorWrapperImpl.java:62)
	at gg.essential.lib.mixinextras.wrapper.WrapperInjectionInfo.inject(WrapperInjectionInfo.java:71)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1378)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_329.<init>(class_329.java:145)
	at net.minecraft.class_310.<init>(class_310.java:603)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)
![image_2024-03-04_162842026](https://github.com/Chocohead/OptiFabric/assets/102784095/f1f8b5bf-e5fa-4fe5-bdf7-84a1c6969709)

**Comment by Dracconis** [comment]
Which version of Fabric Launcher, Fabric API, Optifabric, and Optifine?

**Comment by StukleR** [comment]
> Which version of Fabric Launcher, Fabric API, Optifabric, and Optifine?

![image](https://github.com/Chocohead/OptiFabric/assets/162181749/c765135f-b613-4d3e-99e8-98d91a72b3fd)

**Comment by Dracconis** [comment]
> > Which version of Fabric Launcher, Fabric API, Optifabric, and Optifine?
> 
> ![image](https://private-user-images.githubusercontent.com/162181749/309855563-c765135f-b613-4d3e-99e8-98d91a72b3fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1ODEzOTgsIm5iZiI6MTcwOTU4MTA5OCwicGF0aCI6Ii8xNjIxODE3NDkvMzA5ODU1NTYzLWM3NjUxMzVmLWI2MTMtNGQzZS05OWU4LTk4ZDkxYTcyYjNmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQxOTM4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTMxZDk3MDdjNDgzZjNjY2VmNTU3MjQwNTBmMWFlMDEyOWJlNjg0MGZiZGJlYTQwYjY4ZmZkMjY3ZjYwNjkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Zi9rOmLtTckswrhZpzUZvwIluo2CZ2U9sAEaO9mtaTo)

Please dont hijack someone else ticket to get help. Even if you are having the same issue please open your own ticket and provide the needed information to get help.
