### ISSUE TITLE
cant load fabric 1 16 5

### ISSUE THREAD

**Issue by vecrychristmas** [Chocohead/OptiFabric#1508]
java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:43)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
![image](https://github.com/Chocohead/OptiFabric/assets/162622172/cc736f49-32d5-47b2-8c82-343d69c8c8da)
![image](https://github.com/Chocohead/OptiFabric/assets/162622172/6fdc3413-0b0f-4928-b4f5-67c875a3322e)

**Comment by vecrychristmas** [comment]
pls help i start maincraft in version fabric 1.16.5

**Comment by Dracconis** [comment]
Use optifabric 1.13.6 and Fabric Loader 0.14.25.

**Comment by vecrychristmas** [comment]
> Use optifabric 1.13.6 and Fabric Loader 0.14.25.

![image](https://github.com/Chocohead/OptiFabric/assets/162622172/a0ac123d-39d7-463d-a5f8-2e9d7f2726fc)

pls give me link to download this

**Comment by Dracconis** [comment]
> > Use optifabric 1.13.6 and Fabric Loader 0.14.25.
> 
> ![image](https://private-user-images.githubusercontent.com/162622172/311419956-a0ac123d-39d7-463d-a5f8-2e9d7f2726fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5Nzg3MTMsIm5iZiI6MTcwOTk3ODQxMywicGF0aCI6Ii8xNjI2MjIxNzIvMzExNDE5OTU2LWEwYWMxMjNkLTM5ZDctNDYzZC1hNWY4LTJlOWQ3ZjI3MjZmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOVQxMDAwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjg1ZDc2ZDU0NGIyYTQ1M2ZlODMyZmFkZDE3ZjhjYWFiMDdkMWNlZjg1NTMyZDAzZDdiMWZkYjI4MDE3NjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DsrbXuUl8Aqb5dZ19FHmdGUWBjMfA2w6YHBdLPPHbBs)
> 
> pls give me link to download this

You are on the page, you just click on the version and then download. 1.13.6 is used for several versions of MC.

**Comment by vecrychristmas** [comment]
bro could you contact me, I beg you for further help, I don’t understand, I’m just Ukrainian, I really need help, I beg you, write to me on Discord, my discord ID is verychristmas

**Comment by Poopooracoocoo** [comment]
Dracconis meant 1.13.16

https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3961344
