### ISSUE TITLE
Error loading OptiFabric 1.17.1. Failed to load OptiFine

### ISSUE THREAD

**Issue by Vlader7** [Chocohead/OptiFabric#1513]
java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:43)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 25 more

![Screenshot (1829)](https://github.com/Chocohead/OptiFabric/assets/161700893/8671f5c1-408a-4421-afb1-8ed6cd4c5da0)
![Screenshot (1828)](https://github.com/Chocohead/OptiFabric/assets/161700893/dfab39d3-1990-4404-acff-f50ef2c784e1)
![Screenshot (1840)](https://github.com/Chocohead/OptiFabric/assets/161700893/1ddf7ca8-2be7-4aee-a49f-51d3aa575aa5)

#Optifabric error

**Comment by Vlader7** [comment]
But when I put the loader version from the FABRIC installer it works (the error no longer appears), but a new problem appears. I have a server on aternos and as an example I use 0.14.25 as FABRIC loader and the server on aternos is also FABRIC which has FABRIC loader 0.15 .7 gives me an incompatible version.

**Comment by Dracconis** [comment]
> But when I put the loader version from the FABRIC installer it works (the error no longer appears), but a new problem appears. I have a server on aternos and as an example I use 0.14.25 as FABRIC loader and the server on aternos is also FABRIC which has FABRIC loader 0.15 .7 gives me an incompatible version.

Does the server have an option to change the fabric loader version?

**Comment by Vlader7** [comment]
no

**Comment by Dracconis** [comment]
> no

Then you will definitely have to wait for someone more knowledgeable than I to assist you with this 1
