### ISSUE TITLE
Failed to Load OptiFine

### ISSUE THREAD

**Issue by EerieDeceit** [Chocohead/OptiFabric#1515]
Said to report this so here I am.

java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:43)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 25 more

**Comment by Dracconis** [comment]
Try using Fabric Loader 0.14.25.

**Comment by koolkidjimmy** [comment]
Hey! I'm gonna need a little more info to help you out, are using Forge or Fabric? Or are you just using the default Optifine version?

If you're using Fabric, make sure you have the most up to date OptiFabric file for your Minecraft version (What is your Minecraft version btw?)
You can see the most up to date OptiFabric versions here: https://www.curseforge.com/minecraft/mc-mods/optifabric

If you're using Forge, make sure you have the most up to date OptiForge file for your Minecraft version.
You can see the most up to date OptiForge versions here: https://www.curseforge.com/minecraft/mc-mods/optiforge

OptiFabric supports Fabric-Loaders up to 0.14.25, if you are using 0.15.7 then it won't work.
Not sure about OptiForge as I don't use it for Optifine, though I would presume checking other tickets to see.

If you're using the default Optifine version of Minecraft and it's not working, Try seeing if their is a updated version of Optifine for that Minecraft versions, if there's none, then I'm not sure what could be wrong. Try reinstalling your Minecraft version and seeing if that fixes it. (If you had deleted the profile of the non-modded Minecraft version, then it won't work, you must keep it.)

Hope this helped!

**Comment by Dracconis** [comment]
> Hey! I'm gonna need a little more info to help you out, are using Forge or Fabric? Or are you just using the default Optifine version?
> 
> **I'll assume you're using Fabric based on the details in the error, make sure you have the most up to date OptiFabric file for your Minecraft version (What is your Minecraft version btw?) You can see the most up to date OptiFabric versions here: https://www.curseforge.com/minecraft/mc-mods/optifabric**
> 
> > If you're using Forge though, make sure you have the most up to date OptiForge file for your Minecraft version.
> > You can see the most up to date OptiForge versions here: https://www.curseforge.com/minecraft/mc-mods/optiforge
> 
> **OptiFabric supports Fabric-Loaders up to 0.14.25, if you are using 0.15.7 then it won't work. Not sure about OptiForge as I don't use it for Optifine, though I would presume checking other tickets to see.**
> 
> > Also, if you're using the default Optifine version of Minecraft and it's not working, Try seeing if their is a updated version of Optifine for that Minecraft's version, if there's none, then I'm not sure what could be wrong. Try reinstalling your Minecraft version and seeing if that fixes it. (If you had deleted the profile of the non-modded Minecraft version, then it won't work, you must keep it.)
> 
> **Hope this helped!**
Help was already provided that would assist and fix their issue.

**Comment by koolkidjimmy** [comment]
> > Hey! I'm gonna need a little more info to help you out, are using Forge or Fabric? Or are you just using the default Optifine version?
> > **I'll assume you're using Fabric based on the details in the error, make sure you have the most up to date OptiFabric file for your Minecraft version (What is your Minecraft version btw?) You can see the most up to date OptiFabric versions here: https://www.curseforge.com/minecraft/mc-mods/optifabric**
> > > If you're using Forge though, make sure you have the most up to date OptiForge file for your Minecraft version.
> > > You can see the most up to date OptiForge versions here: https://www.curseforge.com/minecraft/mc-mods/optiforge
> > 
> > 
> > **OptiFabric supports Fabric-Loaders up to 0.14.25, if you are using 0.15.7 then it won't work. Not sure about OptiForge as I don't use it for Optifine, though I would presume checking other tickets to see.**
> > > Also, if you're using the default Optifine version of Minecraft and it's not working, Try seeing if their is a updated version of Optifine for that Minecraft's version, if there's none, then I'm not sure what could be wrong. Try reinstalling your Minecraft version and seeing if that fixes it. (If you had deleted the profile of the non-modded Minecraft version, then it won't work, you must keep it.)
> > 
> > 
> > **Hope this helped!**
> > Help was already provided that would assist and fix their issue.

Yup don't know why I commented on it, that's my bad.
