### ISSUE TITLE
Optifabric 1.18 issue

### ISSUE THREAD

**Issue by ahelms05** [Chocohead/OptiFabric#1533]
java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:43)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 25 more

**Comment by Dracconis** [comment]
Try using Fabric Loader 0.14.25

**Comment by ahelms05** [comment]
Sorry, my knowledge is limited, I'm not sure where to get that. Where I downloaded Fabric did not give me options for different versionsSent via the Samsung Galaxy S23 Ultra 5G, an AT&T 5G smartphone
-------- Original message --------From: Dracconis ***@***.***> Date: 3/24/24  4:29 AM  (GMT-05:00) To: Chocohead/OptiFabric ***@***.***> Cc: ahelms05 ***@***.***>, Author ***@***.***> Subject: Re: [Chocohead/OptiFabric] Optifabric 1.18 issue (Issue #1533) 
Try using Fabric Loader 0.14.25

**Comment by Dracconis** [comment]
Go to this link: https://fabricmc.net/use/installer/
And download the installer for your Operating System type.
Make sure MC is closed including the launcher.
Then run the installer, click the first dropdown and choose the 1.18 version of MC, then click the 2nd dropdown (Loader Version) and choose 0.14.25.

**Comment by ahelms05** [comment]
Thank you! That helped. Also I had to remove all other versions of optifine from the folderSent via the Samsung Galaxy S23 Ultra 5G, an AT&T 5G smartphone
-------- Original message --------From: Dracconis ***@***.***> Date: 3/24/24  1:14 PM  (GMT-05:00) To: Chocohead/OptiFabric ***@***.***> Cc: ahelms05 ***@***.***>, Author ***@***.***> Subject: Re: [Chocohead/OptiFabric] Optifabric 1.18 issue (Issue #1533) 
Go to this link: https://fabricmc.net/use/installer/
And download the installer for your Operating System type.
Make sure MC is closed including the launcher.
Then run the installer, click the first dropdown and choose the 1.18 version of MC, then click the 2nd dropdown (Loader Version) and choose 0.14.25.

**Comment by Dracconis** [comment]
You're welcome. If it works and you no longer get any errors, please close this ticket.
