### ISSUE TITLE
optifabric not working 1.18.2

### ISSUE THREAD

**Issue by welshman97** [Chocohead/OptiFabric#1548]
java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 25 more

optifine version OptiFine HD U H9 1.18.2

**Comment by welshman97** [comment]
Tried using Fabric Loader 0.14.25, not working

**Comment by Dracconis** [comment]
If you downloaded and installed Fabric Loader 0.14.25 AND changed the play profile to THAT version then it does work. So double check that the correct version was installed and that your play profile is set to that version of the loader.

**Comment by welshman97** [comment]
fresh install of 0.14.25 fabric worked

**Comment by welshman97** [comment]
[03/04/2024 16:36:39 PM] [Render thread/ERROR] Mixin apply for mod fabric-rendering-v1 failed fabric-rendering-v1.mixins.json:shader.ShaderMixin from mod fabric-rendering-v1 -> net.minecraft.class_5944: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @ModifyArg handler before this() invocation must be static in injector net/minecraft/class_5944::modifyProgramId [INJECT Applicator Phase -> fabric-rendering-v1.mixins.json:shader.ShaderMixin from mod fabric-rendering-v1 -> Apply Injections ->  -> Inject -> fabric-rendering-v1.mixins.json:shader.ShaderMixin from mod fabric-rendering-v1->@ModifyArg:

[03/04/2024 16:36:40 PM] java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'fabric-renderer-indigo'!
[03/04/2024 16:36:40 PM] 	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
[03/04/2024 16:36:40 PM] 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)

[03/04/2024 16:36:40 PM] Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5944 failed

[03/04/2024 16:36:40 PM] Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @ModifyArg handler before this() invocation must be static in injector net/minecraft/class_5944::modifyProgramId [INJECT Applicator Phase -> fabric-rendering-v1.mixins.json:shader.ShaderMixin from mod fabric-rendering-v1 -> Apply Injections ->  -> Inject -> fabric-rendering-v1.mixins.json:shader.ShaderMixin from


minecraft no longer opening when Fabric API is installed

**Comment by Dracconis** [comment]
Fabric loader 0.14.25, so what are the other mods you are using and their respective versions?

**Comment by welshman97** [comment]
Just optifine, optifabric and the version of fabric API it downloads when I clicked the button saying "you need to install the fabric API to use mods"

**Comment by Dracconis** [comment]
For 1.18.2 try using Fabric Loader 0.14.25, Fabric API 0.51.1, Optifabric 1.14.3, and Optifine 1.18.2 H7 and see if it loads. If it does load at that point then try it with Optifine H9.

**Comment by Poopooracoocoo** [comment]
Just FAPI 0.76.0 is enough. 

FAPI 0.77.0 made changes to core shader support in the FRAPI which OptiFabric does not yet support.

**Comment by welshman97** [comment]
used FAPI 0.76.0, now is working
