### ISSUE TITLE
There was an error loading optifabric

### ISSUE THREAD

**Issue by Abdullah7922** [Chocohead/OptiFabric#1556]
![image](https://github.com/Chocohead/OptiFabric/assets/150436446/a7ab9935-3040-4d11-87ec-31394f29ffb5)
![image](https://github.com/Chocohead/OptiFabric/assets/150436446/163a4f8a-94b0-4bb1-8f72-816d151ba80d)
java.lang.NoSuchMethodError: net.fabricmc.loader.FabricLoader.getGameProvider()Lnet/fabricmc/loader/game/GameProvider;
	at me.modmuss50.optifabric.mod.OptifineSetup.getLaunchMinecraftJar(OptifineSetup.java:299)
	at me.modmuss50.optifabric.mod.OptifineSetup.getMinecraftJar(OptifineSetup.java:277)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:84)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at com.chocohead.mm.Plugin$$Lambda$46/1947941827.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Dracconis** [comment]
Tried using Fabric Loader 0.14.25, Optifabric 1.13.6, and Fabric API 0.42.0 with your current mod set and try again.

**Comment by Abdullah7922** [comment]
> Tried using Fabric Loader 0.14.25, Optifabric 1.13.6, and Fabric API 0.42.0 with your current mod set and try again.

I cant find Optifabric 1.13.6 can u drop me a link pls

**Comment by Dracconis** [comment]
Should be the same place you got it before, but here you go: https://www.curseforge.com/minecraft/mc-mods/optifabric/files

Edit: That is my bad I just looked it up and it should have been 1.13.16

**Comment by Abdullah7922** [comment]
> Should be the same place you got it before, but here you go: https://www.curseforge.com/minecraft/mc-mods/optifabric/files
> 
> Edit: That is my bad I just looked it up and it should have been 1.13.16
ty

**Comment by Abdullah7922** [comment]
> Should be the same place you got it before, but here you go: https://www.curseforge.com/minecraft/mc-mods/optifabric/files
> 
> Edit: That is my bad I just looked it up and it should have been 1.13.16

ty

**Comment by Dracconis** [comment]
> > Should be the same place you got it before, but here you go: https://www.curseforge.com/minecraft/mc-mods/optifabric/files
> > Edit: That is my bad I just looked it up and it should have been 1.13.16
> 
> ty

Yw and good luck.
