### ISSUE TITLE
Optifabric loads, but not Optifine

### ISSUE THREAD

**Issue by melesiv** [Chocohead/OptiFabric#156]
I turned off my shaders to use a mod that conflicts with Optifine, but I couldn't find the shaders menu anymore. I uninstalled and reinstalled both Optifine and Optifabric multiple times and uninstalled the conflicting mod but Optifine never loads. 

Optifabric loads, but just not Optifine... It worked before, why not now??
![image](https://user-images.githubusercontent.com/77087552/105249869-68d7b880-5b3e-11eb-9e06-25fec5553c82.png)

log:
[log optifabric.txt](https://github.com/Chocohead/OptiFabric/files/5845712/log.optifabric.txt)

**Comment by Chocohead** [comment]
Taking a look at the attached log file (thank you for that by the way)...
```
[16:34:53] [main/ERROR]: Error loading companion plugin class [com.chocohead.mm.Plugin] for mixin config [mixins.mm.json]. The plugin may be out of date: LinkageError:loader constraint violation: loader (instance of net/fabricmc/loader/launch/knot/KnotClassLoader) previously initiated loading for a different type with name "org/objectweb/asm/tree/ClassNode"
java.lang.LinkageError: loader constraint violation: loader (instance of net/fabricmc/loader/launch/knot/KnotClassLoader) previously initiated loading for a different type with name "org/objectweb/asm/tree/ClassNode"
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_51]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_51]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163) ~[fabric-loader-0.10.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at net.fabricmc.loader.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:83) ~[fabric-loader-0.10.8.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.<init>(PluginHandle.java:96) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:598) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:475) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:437) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.10.8.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.10.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_51]
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:272) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]
```
Which would suggest something has gone catastrophically wrong classloading that is preventing OptiFine from being applied. I'd suggest try removing the other mods one at a time (probably leaving Fabric API until last given at least one of the others will depend on it) and seeing if that stops the error being produced. Hopefully it will be as simple as that so a fix for which ever mod is unhappy can be made.

**Comment by melesiv** [comment]
Well, I only just saw this, actually! (Thank you)

I did as said and removed mods one by one and it eventually worked after getting rid of 'Dynamic Music Discs'. Weird.
