### ISSUE TITLE
Optifabric is crashing my game on load.

### ISSUE THREAD

**Issue by snakedeshazer** [Chocohead/OptiFabric#1569]
[22:12:17] [main/ERROR]: Critical injection failure: LVT in net/minecraft/class_757::method_3192(FJZ)V has incompatible changes at opcode 653 in callback optifabric.compat.architectury-AB.new4er-mixins.json:GameRendererNew4erMixin from mod optifabric->@Inject::renderScreenPre(FJZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;IILnet/minecraft/class_1041;FLorg/joml/Matrix4f;Lnet/minecraft/class_4587;FLnet/minecraft/class_332;)V.
 Expected: [I, I, Lnet/minecraft/class_1041;, F, Lorg/joml/Matrix4f;, Lnet/minecraft/class_4587;, F, Lnet/minecraft/class_332;]
    Found: [F, Z, I, I, Lnet/minecraft/class_1041;, F, Lorg/joml/Matrix4f;, Lnet/minecraft/class_4587;]
Available: [F, Z, I, I, Lnet/minecraft/class_1041;, F, Lorg/joml/Matrix4f;, Lnet/minecraft/class_4587;, F, Lnet/minecraft/class_332;, Ljava/lang/Throwable;, Lnet/minecraft/class_128;, Lnet/minecraft/class_129;]
java.lang.ExceptionInInitializerError
	at net.minecraft.class_128.method_557(class_128.java:139)
	at net.minecraft.class_128.method_568(class_128.java:186)
	at net.minecraft.class_128.method_24305(class_128.java:345)
	at net.minecraft.client.main.Main.main(Main.java:167)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2371)
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:559)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 19 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_757::method_3192(FJZ)V has incompatible changes at opcode 653 in callback optifabric.compat.architectury-AB.new4er-mixins.json:GameRendererNew4erMixin from mod optifabric->@Inject::renderScreenPre(FJZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;IILnet/minecraft/class_1041;FLorg/joml/Matrix4f;Lnet/minecraft/class_4587;FLnet/minecraft/class_332;)V.
 Expected: [I, I, Lnet/minecraft/class_1041;, F, Lorg/joml/Matrix4f;, Lnet/minecraft/class_4587;, F, Lnet/minecraft/class_332;]
    Found: [F, Z, I, I, Lnet/minecraft/class_1041;, F, Lorg/joml/Matrix4f;, Lnet/minecraft/class_4587;]
Available: [F, Z, I, I, Lnet/minecraft/class_1041;, F, Lorg/joml/Matrix4f;, Lnet/minecraft/class_4587;, F, Lnet/minecraft/class_332;, Ljava/lang/Throwable;, Lnet/minecraft/class_128;, Lnet/minecraft/class_129;]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:544)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:494)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:277)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 22 more
[22:12:17] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: Could not initialize class net.optifine.reflect.Reflector
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.10.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.optifine.reflect.Reflector
	at net.minecraft.class_128.method_555(class_128.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:195) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	... 5 more

**Comment by snakedeshazer** [comment]
I have read through the other similar issues, I have tried older loads for fabric, etc. but my mods require the most recent version.

**Comment by Dracconis** [comment]
Fabric Loader 0.15.6, API 0.95.4, Optifabric 1.14.3, preview_OptiFine_1.20.4_HD_U_I7_pre2 work just fine without crashing.

**Comment by Poopooracoocoo** [comment]
the architectury incompatibility was also reported in #1374

also for future reference, it's a good idea to share log and crash report. See [this](https://docs.fabricmc.net/players/troubleshooting/uploading-logs) to learn where to find them.

**Comment by snakedeshazer** [comment]
Thanks I appreciate it!
