### ISSUE TITLE
Optifabric does not see OptiFine fabric 1.16.5

### ISSUE THREAD

**Issue by PAPAKarloo** [Chocohead/OptiFabric#1575]
![папа карло](https://github.com/Chocohead/OptiFabric/assets/167679553/b11d5f75-1a82-42af-9e15-c3471cc8bdb2)
java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at com.chocohead.mm.Plugin$$Lambda$63/1401295795.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more

**Comment by PAPAKarloo** [comment]
Pls help me

**Comment by Dracconis** [comment]
Use Fabric Loader 0.14.25.

**Comment by PAPAKarloo** [comment]
How? Dracconis

**Comment by PAPAKarloo** [comment]
> Use Fabric Loader 0.14.25.

how?

**Comment by PAPAKarloo** [comment]
> Use Fabric Loader 0.14.25.

what is it

**Comment by Dracconis** [comment]
Go here: https://fabricmc.net/use/installer/ Download the installer for you computer OS type. Then run the installer and choose the Fabric Loader version 0.14.25 and in the MC Version choose 1.16.5. Once it is complete open MC and choose the profile for Fabric Loader 0.14.25- 1.16.5 and click Play. You should then be able to Play MC without that error.

**Comment by PAPAKarloo** [comment]
> Перейдите сюда: https://fabricmc.net/use/installer/ Скачайте установщик для вашего типа ОС компьютера. Затем запустите установщик и выберите Fabric Loader версии 0.14.25 и в MC Version выберите 1.16.5. После завершения откройте MC и выберите профиль для Fabric Loader 0.14.25- 1.16.5 и нажмите Play. После этого вы сможете играть в MC без этой ошибки.

I can use it if I don't have official launcher

**Comment by PAPAKarloo** [comment]
> Go here: https://fabricmc.net/use/installer/ Download the installer for you computer OS type. Then run the installer and choose the Fabric Loader version 0.14.25 and in the MC Version choose 1.16.5. Once it is complete open MC and choose the profile for Fabric Loader 0.14.25- 1.16.5 and click Play. You should then be able to Play MC without that error.

![image](https://github.com/Chocohead/OptiFabric/assets/167679553/0c88ee69-2428-40d1-b9c8-a9e627993b21)
my mods

**Comment by PAPAKarloo** [comment]
> Перейдите сюда: https://fabricmc.net/use/installer/ Скачайте установщик для вашего типа ОС компьютера. Затем запустите установщик и выберите Fabric Loader версии 0.14.25 и в MC Version выберите 1.16.5. После завершения откройте MC и выберите профиль для Fabric Loader 0.14.25- 1.16.5 и нажмите Play. После этого вы сможете играть в MC без этой ошибки.

I use TLauncher

**Comment by PAPAKarloo** [comment]
> Go here: https://fabricmc.net/use/installer/ Download the installer for you computer OS type. Then run the installer and choose the Fabric Loader version 0.14.25 and in the MC Version choose 1.16.5. Once it is complete open MC and choose the profile for Fabric Loader 0.14.25- 1.16.5 and click Play. You should then be able to Play MC without that error.

PLS HELP

**Comment by PAPAKarloo** [comment]
> Go here: https://fabricmc.net/use/installer/ Download the installer for you computer OS type. Then run the installer and choose the Fabric Loader version 0.14.25 and in the MC Version choose 1.16.5. Once it is complete open MC and choose the profile for Fabric Loader 0.14.25- 1.16.5 and click Play. You should then be able to Play MC without that error.


Please me

**Comment by Dracconis** [comment]
Wyszukiwarka Google jest Twoim przyjacielem. Przeczytaj to: https://tlauncher.org/en/how-install-fabric.html
