### ISSUE TITLE
There was an error loading OrtiF abrie! 

### ISSUE THREAD

**Issue by Yumekiosa** [Chocohead/OptiFabric#1580]
![PYQQBKU$LD@GSFT3 5CUGLK](https://github.com/Chocohead/OptiFabric/assets/168281596/847d808e-4921-4ced-965b-0337bf48c79b)
![PYQQBKU$LD@GSFT3 5CUGLK](https://github.com/Chocohead/OptiFabric/assets/168281596/871322d3-2b64-4f85-90ec-02779b937606)
![R}}GL~HFE8WD}TJOMO02@)Y](https://github.com/Chocohead/OptiFabric/assets/168281596/97c99716-dd4d-4bd2-950f-cbeece654978)

java.lang.RuntimeException: Error running OptiFine patcher at D:\WDSJ\.minecraft\versions\1.19.2-Fabric 0.15.10-OptiFine_I2\mods\OptiFine_1.19.2_HD_U_I2.jar on D:\WDSJ\.minecraft\versions\1.19.2-Fabric 0.15.10-OptiFine_I2\1.19.2-Fabric 0.15.10-OptiFine_I2.jar
	at me.modmuss50.optifabric.mod.OptifineSetup.runInstaller(OptifineSetup.java:231)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:109)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:529)
	at java.base/java.lang.Class.forName(Class.java:508)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at me.modmuss50.optifabric.mod.OptifineSetup.runInstaller(OptifineSetup.java:229)
	... 31 more
Caused by: java.util.zip.ZipException: invalid block type
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:181)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:95)
	at optifine.Utils.readAll(Utils.java:147)
	at optifine.Patcher.process(Patcher.java:96)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 33 more

**Comment by Dracconis** [comment]
What launcher are you using? Use Fabric Loader 0.14.9 instead of 0.15.10 and Fabric API 0.76.1 instead of 0.77.0.

**Comment by Yumekiosa** [comment]
> 你用的是什么启动器？使用 Fabric Loader 0.14.9 而不是 0.15.10，使用 Fabric API 0.76.1 而不是 0.77.0。

The launcher I use is Plain Craft Launcher 2
