### ISSUE TITLE
can't start minecraft

### ISSUE THREAD

**Issue by maximtsepaev** [Chocohead/OptiFabric#1582]
Minecraft crashes without starting, I tried different versions (fabric, api, optifabric and optifine), but it crashes anyway.
Fabric 0.15.6, API 0.95.4, OptiFabric 1.14.4, Optifine I7

Logs:

> [01:09:14] [main/ERROR]: Minecraft has crashed!
> net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: Could not initialize class net.optifine.reflect.Reflector
> 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.7.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.7.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
> Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.optifine.reflect.Reflector
> 	at net.minecraft.class_128.method_555(class_128.java:107) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_128.method_568(class_128.java:195) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:167) ~[fabric-loader-0.15.7-1.20.4.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
> 	... 2 more
how I can fix it?

**Comment by Dracconis** [comment]
Minimum Fabric Loader 0.15.6, Minimum Fabric API 0.95.4, Minimum Optifabric 1.14.3, Optifine Hosted here: https://www.mediafire.com/file/tyk30u6yxele2z1/preview_OptiFine_1.20.4_HD_U_I7_pre2.jar

**Comment by maximtsepaev** [comment]
> Minimum Fabric Loader 0.15.6, Minimum Fabric API 0.95.4, Minimum Optifabric 1.14.3, Optifine Hosted here: https://www.mediafire.com/file/tyk30u6yxele2z1/preview_OptiFine_1.20.4_HD_U_I7_pre2.jar

minecraft has loaded, but the optifine is still not working

**Comment by Dracconis** [comment]
That combination works just fine as that is my current setup. New error log?
