### ISSUE TITLE
error 1.20.4

### ISSUE THREAD

**Issue by ZatoUyutnOUmirat** [Chocohead/OptiFabric#1587]
minecraft just crashed , my code of error - 1                
Error
The game crashes
The game crashed due to an unexpected error.
We apologize for the inconvenience.
Completion code: 1

**Comment by Dracconis** [comment]
We will need more than that error in order to determine how to help. Please provide the error log.

**Comment by 12411234** [comment]
java.lang.RuntimeException: Error running OptiFine patcher at E:\.minecraft\versions\1.20.4-Fabric 0.15.11-OptiFine_I7\mods\OptiFine_1.20.4_HD_U_I7.jar on E:\.minecraft\versions\1.20.4-Fabric 0.15.11-OptiFine_I7\1.20.4-Fabric 0.15.11-OptiFine_I7.jar
	at me.modmuss50.optifabric.mod.OptifineSetup.runInstaller(OptifineSetup.java:231)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:109)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at me.modmuss50.optifabric.mod.OptifineSetup.runInstaller(OptifineSetup.java:229)
	... 32 more
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:453)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:106)
	at optifine.Utils.readAll(Utils.java:147)
	at optifine.Patcher.process(Patcher.java:81)
	... 37 more

**Comment by Dracconis** [comment]
> java.lang.RuntimeException: Error running OptiFine patcher at E:.minecraft\versions\1.20.4-Fabric 0.15.11-OptiFine_I7\mods\OptiFine_1.20.4_HD_U_I7.jar on E:.minecraft\versions\1.20.4-Fabric 0.15.11-OptiFine_I7\1.20.4-Fabric 0.15.11-OptiFine_I7.jar at me.modmuss50.optifabric.mod.OptifineSetup.runInstaller(OptifineSetup.java:231) at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:109) at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46) at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) at com.chocohead.mm.Plugin.getMixins(Plugin.java:340) at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128) at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796) at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568) at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) at java.base/java.lang.Class.forName0(Native Method) at java.base/java.lang.Class.forName(Class.java:467) at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) at oolloo.jlw.Wrapper.main(Wrapper.java:51) Caused by: java.lang.reflect.InvocationTargetException at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at me.modmuss50.optifabric.mod.OptifineSetup.runInstaller(OptifineSetup.java:229) ... 32 more Caused by: java.io.EOFException: Unexpected end of ZLIB input stream at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:453) at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) at java.base/java.io.FilterInputStream.read(FilterInputStream.java:106) at optifine.Utils.readAll(Utils.java:147) at optifine.Patcher.process(Patcher.java:81) ... 37 more

Stop hijacking other people's ticket and open your own ticket so that you can get help.
