### ISSUE TITLE
C R A S H E S

### ISSUE THREAD

**Issue by huang390** [Chocohead/OptiFabric#159]
[16:55:40] [main/INFO]: Loading for game Minecraft 1.16.5
[16:55:42] [ForkJoinPool-1-worker-1/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[16:55:42] [ForkJoinPool-1-worker-1/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[16:55:42] [ForkJoinPool-1-worker-1/WARN]: Non-Fabric mod JAR at "E:\Minecraft Launcher\.minecraft\mods\OptiFine_1.16.5_HD_U_G6.jar", ignoring
[16:55:43] [main/WARN]: Warnings were found! 
 - Mod 'Cardinal Components API (items)' (cardinal-components-item) conflicts with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.9.2!
	 - While this won't prevent you from starting the game, the developer(s) of 'Cardinal Components API (items)' (cardinal-components-item) have found that version 1.9.2 of 'OptiFabric' (optifabric) conflicts with their mod.
	 - It is heavily recommended to remove one of the mods.
	 - Mod 'OptiFabric' (optifabric) v1.9.2 is being loaded from the user's mod directory.
[16:55:43] [main/INFO]: [FabricLoader] Loading 105 mods: fabric-keybindings-v0@0.2.1+ca58154a7d, roughlyenoughitems-api@5.8.7, notenoughcrashes@3.1.5, trinkets@2.6.4, inventoryprofiles@0.4.2, fabricloader@0.11.1, bbor@2.4-1.16.3, fabriczero@0.2.1, fabric-dimensions-v1@2.0.2+ca58154a7d, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.0+daa38b3d7d, diggusmaximus@1.4.2-1.16.3, tweakeroo@0.10.0-dev.20201213.222846, roughlyenoughresources@2.1.3, litematica@0.0.0-dev.20210112.155314, org_jetbrains_kotlin_kotlin-stdlib@1.4.21, playerabilitylib@1.2.1, waila@1.9.22, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, simple_backpack@1.0.38, minihud@0.19.0-dev.20201103.184029, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.21, fabric@0.30.0+1.16, i18nreborn@fabric-1.15, fabric-networking-v0@0.3.2+ca58154a7d, fabric-screen-handler-api-v1@1.1.1+ca58154a7d, com_github_therandomlabs_trlutils-config@master-SNAPSHOT, modmenu@1.14.13+build.19, fabricforfabric@1.4.1, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.21, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, roughlyenoughitems-runtime@5.8.7, cloth-client-events-v0@1.4.5, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-language-kotlin@1.4.21+build.1, curios@0.0.10-1.16.3, nbtcrafting@2.0.0-rc.7+mc1.16.2-pre1, fabric-key-binding-api-v1@1.0.2+ca58154a7d, cloth-config2@4.8.3, ring_of_miner@1.0.21, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.4.2, fabric-resource-loader-v0@0.4.2+ca58154a7d, chainmail@0.5.0, malilib@0.10.0-dev.21+arne.2, org_jetbrains_kotlin_kotlin-reflect@1.4.21, cardinal-components-entity@2.7.5, colormatic@2.2.8+mc.1.16.3, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, lanserverproperties@${version}, cardinal-components-base@2.7.5, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-models-v0@0.2.1+ca58154a7d, org_jetbrains_annotations@20.0.0, fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.10+ca58154a7d, fabric-object-builder-api-v1@1.9.3+ca58154a7d, mm@2.0, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, cardinal-components-item@2.7.2, com_electronwill_night-config_core@3.6.0, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, starlight@0.0.3, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, com_github_therandomlabs_trlutils-fabric@1.16-SNAPSHOT, fabric-renderer-registries-v1@2.2.1+ca58154a7d, fabric-loot-tables-v1@1.0.2+ca58154a7d, carpet@1.4.23, fabric-particles-v1@0.2.4+ca58154a7d, tellme@0.9.1-beta.1, roughlyenoughitems-default-plugin@5.8.7, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, minecraft@1.16.5, jankson@3.0.0+j1.2.0, fabric-command-api-v1@1.0.10+ca58154a7d, cloth-basic-math@0.5.1, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-renderer-indigo@0.4.4+ca58154a7d, org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.4.2, com_electronwill_night-config_toml@3.6.0, roughlyenoughitems@5.8.7, fabric-item-api-v1@1.2.1+ca58154a7d, kyrptconfig@1.1.4-1.16, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, torcherino@2.12.69, autoconfig1u@3.3.1, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, blue_endless_jankson@1.2.0, vanilladeathchest@1.16.3-1.11.0.7-fabric, optifabric@1.9.2, fabric-biome-api-v1@3.1.1+ca58154a7d, itemscroller@0.15.0-dev.20210111.205029, carrier@1.6.1, voxelmap@1.10.14, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d
[16:55:43] [main/WARN]: Mod `i18nreborn` (fabric-1.15) does not respect SemVer - comparison support is limited.
[16:55:43] [main/WARN]: Mod `com_github_therandomlabs_trlutils-config` (master-SNAPSHOT) does not respect SemVer - comparison support is limited.
[16:55:43] [main/WARN]: Mod `lanserverproperties` (${version}) does not respect SemVer - comparison support is limited.
[16:55:44] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/E:/Minecraft%20Launcher/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[16:55:46] [main/WARN]: FabricZero is in it's end of life, please consider stopping using it!
[16:55:47] [main/INFO]: FabricZero: Loaded!
[16:55:49] [main/WARN]: @Mixin target me/shedaniel/rei/server/RecipeFinder is public in nbtcrafting.compat.mixins.json:MixinREIRecipeFinder and should be specified in value
[16:55:49] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/world/WorldSlice (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/world/WorldSlice)
[16:55:56] [main/INFO]: [OptiFine] (Reflector) Field not found: World.tileEntitiesToBeRemoved
[16:55:57] [main/FATAL]: Mixin apply failed colormatic.mixins.json:dye.TextureManagerMixin -> net.minecraft.class_1060: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on onReload could not find any targets matching 'method_18167' in net.minecraft.class_1060. Using refmap colormatic-refmap.json Method is @Dynamic(Post reload lambda method). [PREINJECT Applicator Phase -> colormatic.mixins.json:dye.TextureManagerMixin -> Prepare Injections ->  -> handler$zib000$onReload(Lnet/minecraft/class_3300;Ljava/util/concurrent/Executor;Ljava/lang/Void;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onReload could not find any targets matching 'method_18167' in net.minecraft.class_1060. Using refmap colormatic-refmap.json Method is @Dynamic(Post reload lambda method). [PREINJECT Applicator Phase -> colormatic.mixins.json:dye.TextureManagerMixin -> Prepare Injections ->  -> handler$zib000$onReload(Lnet/minecraft/class_3300;Ljava/util/concurrent/Executor;Ljava/lang/Void;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_282]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_282]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.1.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at com.fox2code.fabriczero.FabricZeroTransformerHook.transformClassBytes(FabricZeroTransformerHook.java:41) [fabriczero-0.2.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.11.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_282]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_282]
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583) [?:1.8.0_282]
	at java.lang.Class.getDeclaredFields(Class.java:1916) [?:1.8.0_282]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) [Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:495) [Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_559(class_128.java:101) [intermediary-1.16.5-Fabric%200.11.1.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:54) [intermediary-1.16.5-Fabric%200.11.1.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:425) [intermediary-1.16.5-Fabric%200.11.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:135) [intermediary-1.16.5-Fabric%200.11.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
  

[错误报告 - 1.16.5-Fabric 0.11.1.zip](https://github.com/Chocohead/OptiFabric/files/5909870/-.1.16.5-Fabric.0.11.1.zip)

**Comment by Titaniumtown** [comment]
> Mod 'Cardinal Components API (items)' (cardinal-components-item) conflicts with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.9.2!

lol

**Comment by Chocohead** [comment]
This is a conflict with Colormatic which can be fixed easily enough, but the bigger question is why you'd need that when it's adding the same feature OptiFine itself has?
