### ISSUE TITLE
Help pls Optifabric does not work

### ISSUE THREAD

**Issue by remover223** [Chocohead/OptiFabric#1597]
![2024-05-03](https://github.com/Chocohead/OptiFabric/assets/168759281/ae61906e-9b49-444a-9960-ad42d25d88ee)
java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at com.chocohead.mm.Plugin$$Lambda$57/2075372030.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more

**Comment by remover223** [comment]
downloaded it Fabric Loader 0.14.25 Everything is exactly not working

**Comment by Poopooracoocoo** [comment]
Mind sharing the latest.log file from your logs folder? Share the file, not the contents. It may be called "latest" if you have file extensions turned off.

**Comment by remover223** [comment]
> Не возражаете против того, чтобы поделиться latest.log файлом из папки журналов? Делитесь файлом, а не содержимым. Он может называться «последним», если у вас отключены расширения файлов.

[15:52:31] [main/INFO]: Setting user: remover223
[15:52:31] [main/INFO]: [STDOUT]: Loading Collective (Fabric) version 5.50.
[15:52:31] [main/INFO]: [Config Manager (Read)] Started reading file 'crosshair_config.ccmcfg'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'dot_enabled' to 'false'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'highlight_passive_enabled' to 'true'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'visible_default' to 'true'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'crosshair_height' to '0'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'outline_enabled' to 'true'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'crosshair_style' to 'CROSS'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'dot_colour' to '255/255/255/255'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'crosshair_scale' to '124'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'mod_enabled' to 'true'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'rainbow_enabled' to 'false'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'highlight_hostile_enabled' to 'true'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'crosshair_width' to '0'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'dynamic_bow_enabled' to 'true'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'crosshair_thickness' to '1'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'highlight_players_colour' to '60/60/240/255'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'itemcooldown_enabled' to 'false'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'crosshair_rotation' to '48'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'highlight_hostile_colour' to '220/40/40/255'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'visible_holding_throwable_item' to 'true'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'visible_holding_ranged_weapon' to 'true'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'visible_spectator' to 'true'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'visible_debug' to 'true'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'visible_hiddengui' to 'true'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'rainbow_speed' to '500'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'outline_colour' to '32/32/32/255'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'crosshair_gap' to '0'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'highlight_passive_colour' to '40/230/40/255'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'dynamic_attackindicator_enabled' to 'false'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'itemcooldown_colour' to '255/255/255/80'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'crosshair_colour' to '255/0/238/121'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'highlight_players_enabled' to 'true'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Set property 'visible_thirdperson' to 'false'.
[15:52:31] [main/INFO]: [Config Manager (Read)] Finished reading file 'crosshair_config.ccmcfg'.
[15:52:32] [main/INFO]: Definitely not up to no good
[15:52:33] [main/INFO]: WorldEdit for Fabric (version 7.2.5+57d5ac9) is loaded
[15:52:34] [main/INFO]: [Indigo] Registering Indigo renderer!
[15:52:34] [main/INFO]: [Indigo] Compatibility mode enabled.
[15:52:35] [main/INFO]: [STDOUT]: Inventory HUD + has been initialized!
[15:52:35] [main/WARN]: WARNING! Mod fiber is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[15:52:35] [main/WARN]: WARNING! Mod kyrptconfig is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[15:52:35] [main/WARN]: WARNING! Mod malilib is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[15:52:35] [main/WARN]: WARNING! Mod mm is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[15:52:35] [main/WARN]: WARNING! Mod replaymod is only using deprecated 'modmenu:clientsideOnly' custom value! This is no longer needed and will be removed in 1.18 snapshots.
[15:52:35] [main/INFO]: Loading Xaero's Minimap - Stage 1/2
[15:52:36] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[15:52:41] [main/INFO]: [STDOUT]: InvGUI Initialized
[15:52:41] [main/INFO]: Narrator library for x64 successfully loaded
[15:52:41] [main/INFO]: Reloading ResourceManager: Default, miniitems1165.zip, Рп СкайПлайна.zip, Fabric Mods (Cloth Config v4, Command Macros, Collective (Fabric), Custom Crosshair Mod, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking Block Entity (v0), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Structure API (v1), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric Transfer API (v1), Fabric Loader, Gamma Utils, In-Game Account Switcher, Inventory HUD +, Item Scroller, MaLiLib, Manningham Mills, Mod Menu, OptiFabric, Replay Mod, §a§lTopkaHealth§f, WorldEdit, Xaero's Minimap), replaymod_lang
[15:52:43] [Worker-Main-6/WARN]: Unable to resolve texture reference: missingtexture in minecraft:block/rail_corner
[15:53:06] [main/INFO]: Loading Xaero's Minimap - Stage 2/2
[15:53:06] [main/INFO]: [STDOUT]: No Optifine!
[15:53:07] [main/INFO]: OpenAL initialized.
[15:53:07] [main/INFO]: Sound engine started
[15:53:07] [main/INFO]: Created: 4096x4096x4 minecraft:textures/atlas/blocks.png-atlas
[15:53:07] [main/INFO]: Created: 512x512x4 minecraft:textures/atlas/signs.png-atlas
[15:53:07] [main/INFO]: Created: 4096x2048x4 minecraft:textures/atlas/banner_patterns.png-atlas
[15:53:07] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/shield_patterns.png-atlas
[15:53:07] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/chest.png-atlas
[15:53:07] [main/INFO]: Created: 2048x1024x4 minecraft:textures/atlas/beds.png-atlas
[15:53:07] [main/INFO]: Created: 2048x1024x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[15:53:07] [main/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/particles.png-atlas
[15:53:07] [main/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/paintings.png-atlas
[15:53:07] [main/INFO]: Created: 1024x512x0 minecraft:textures/atlas/mob_effects.png-atlas
[18:09:02] [main/INFO]: Stopping!

**Comment by remover223** [comment]
[latest.log](https://github.com/Chocohead/OptiFabric/files/15199131/latest.log)

**Comment by Poopooracoocoo** [comment]
You're using Fabric Loader 0.15.7. You're not using Fabric Loader 0.14.25.

What launcher are you using? If you're using Minecraft Launcher, you can change your Fabric Loader by re-running the [Fabric Installer](https://fabricmc.net/use/installer/).

**Comment by remover223** [comment]
> Вы используете Fabric Loader 0.15.7. Вы не используете Fabric Loader 0.14.25.
> 
> Какой лаунчер вы используете? Если вы используете Minecraft Launcher, вы можете изменить загрузчик Fabric, повторно запустив [Fabric Installer](https://fabricmc.net/use/installer/).

TLauncher 2.923

**Comment by Dracconis** [comment]
> > Вы используете Fabric Loader 0.15.7. Вы не используете Fabric Loader 0.14.25.
> > Какой лаунчер вы используете? Если вы используете Minecraft Launcher, вы можете изменить загрузчик Fabric, повторно запустив [Fabric Installer](https://fabricmc.net/use/installer/).
> 
> TLauncher 2.923

Follow the instructions for Manual installation: https://tlauncher.org/en/how-install-fabric.html
