### ISSUE TITLE
Crashes with newer versions of optifine

### ISSUE THREAD

**Issue by SunnySlopes** [Chocohead/OptiFabric#160]
When I tried to load the newest optifabric(v 1.0.1) on 1.15.2 optifine G6, and v 0.7.1 on 1.14.4 optifine G6, the game always crash when I tried to launch them.

**Comment by Chocohead** [comment]
Could do with a crash report from this ideally, I know 1.14.4 already has issues with newer Fabric API versions (#98) and I suspect they'll both have problems with version 0.30+ as well.

**Comment by SunnySlopes** [comment]
Hello! ChocoHead, this is my newest crash report which I've run just now while my game failed to launch and couldn't figure out the ploblem on the GUI.
Game version: 1.15.2
Fabric version: 0.11.1
API version: 0.28.5

Optifabric version: 1.0.1

Optifine version: 1.15.2_HD_U_G6

Thanks a lot!







At 2021-02-12 10:29:43, "Chocohead" <notifications@github.com> wrote:

Could do with a crash report from this ideally, I know 1.14.4 already has issues with newer Fabric API versions (#98) and I suspect they'll both have problems with version 0.30+ as well.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
[11:25:55] [ForkJoinPool-1-worker-1/WARN]: Non-Fabric mod JAR at "H:\Minecraft\mods\OptiFine_1.15.2_HD_U_G6.jar", ignoring
[11:25:55] [ForkJoinPool-1-worker-2/WARN]: The mod "shulkerboxtooltip" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 8 column 12
[11:25:55] [ForkJoinPool-1-worker-1/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[11:25:55] [ForkJoinPool-1-worker-2/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[11:25:55] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.1.2+28f8190f42, also found 0.1.2+9826cad80c, 0.1.2+b7f9825d0c
[11:25:55] [main/INFO]: [FabricLoader] Loading 82 mods: fabric-renderer-api-v1@0.2.11+c1455e800c, fabric-keybindings-v0@0.2.1+c1455e800c, gbfabrictools@1.1.0, notenoughcrashes@1.2.4+1.15.1, inventoryprofiles@0.4.2, fabricloader@0.11.1, explayerenderer@1.2, org_zeroturnaround_zt-zip@1.14, customskinloader@14.12-SNAPSHOT-109, bbor@2.4-1.15.2, fabric-containers-v0@0.1.4+c1455e800c, fabric-object-builder-api-v1@1.3.2+c1455e800c, fabric-dimensions-v1@0.3.1+c1455e800c, java@8, fabric-api-base@0.1.2+28f8190f42, fabric-rendering-data-attachment-v1@0.1.4+c1455e800c, mm@2.0, tweakeroo@0.10.0-dev.20200424.222527, fabric-textures-v0@1.0.5+c1455e800c, fabric-rendering-fluids-v1@0.1.7+c1455e800c, litematica@0.0.0-dev.20200515.184506, waila@1.9.22, easiervillagertrading@1.14.4-fabric0.4.1-1.4, me_shedaniel_cloth_basic-math@0.3.0, fabric-blockrenderlayer-v1@1.1.5+c1455e800c, fabric-lifecycle-events-v1@1.2.1+c1455e800c, fabric-renderer-registries-v1@2.1.1+c1455e800c, minihud@0.19.0-dev.20200427.222110, fabric-loot-tables-v1@0.1.6+c1455e800c, carpet-extra@1.4.0, org_slf4j_slf4j-api@1.7.30, fabric@0.28.5+1.15, carpet@1.4.8, fabric-particles-v1@0.2.2+c1455e800c, fabric-networking-v0@0.2.1+c1455e800c, cloth@1.2.0, fabric-networking-blockentity-v0@0.2.4+c1455e800c, minecraft@1.15.2, modmenu@1.10.5, cloth-basic-math@0.5.0, fabric-command-api-v1@1.0.3+c1455e800c, phosphor@0.5.2+build.6, easiercrafting@1.15-fabric0.4.23-1.5.0, fabric-tool-attribute-api-v1@1.2.4+c1455e800c, fabric-renderer-indigo@0.3.5+c1455e800c, autofish@0.8.5, fabric-biomes-v1@0.1.6+c1455e800c, roughlyenoughitems@3.6.21, fabric-item-api-v1@1.1.1+c1455e800c, fabric-events-interaction-v0@0.4.1+c1455e800c, fabric-crash-report-info-v1@0.1.3+c1455e800c, org_slf4j_slf4j-simple@1.7.30, loadcatcher@2.0.0, orderly@1.2.1+build.4-1.15, fabric-rendering-v0@1.1.1+c1455e800c, fabric-rendering-v1@1.2.1+c1455e800c, fabric-key-binding-api-v1@1.0.2+c1455e800c, cloth-config2@2.13.4, replaymod@1.15.2-2.5.1, autoconfig1u@2.0.1, fabric-resource-loader-v0@0.1.11+c1455e800c, inventoryhud@3.2.2, carpet-tis-addition@1.12.1, malilib@0.10.0-dev.21+arne.2, fabric-content-registries-v0@0.1.4+c1455e800c, fabric-tag-extensions-v0@0.1.4+c1455e800c, worldedit@7.1.0;8e55131, optifabric@1.0.1, appleskin@1.0.11, fabric-registry-sync-v0@0.7.2+c1455e800c, fabric-commands-v0@0.2.1+c1455e800c, fabric-mining-levels-v0@0.1.3+c1455e800c, fabric-climbable-api-v1@1.0.1+c1455e800c, fabric-networking-api-v1@1.0.1+c1455e800c, voxelmap@1.9.28, fabric-events-lifecycle-v0@0.2.1+c1455e800c, fabric-models-v0@0.1.1+c1455e800c, fabric-item-groups-v0@0.2.1+c1455e800c, horseinfo@0.1.2-1.15.2, shulkerboxtooltip@2.0.3+1.15.2, fabric-object-builders-v0@0.6.1+c1455e800c, org_jetbrains_annotations@18.0.0
[11:25:55] [main/WARN]: Mod `worldedit` (7.1.0;8e55131) does not respect SemVer - comparison support is limited.
[11:25:55] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Lenovo/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[11:25:55] [main/WARN]: Reference map 'mixins.nonmmlauncher.replaymod.refmap.json' for mixins.nonmmlauncher.replaymod.json could not be read. If this is a development environment you can ignore this message
[11:25:58] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)

**Comment by Titaniumtown** [comment]
You should probably update.

**Comment by SunnySlopes** [comment]
> You should probably update.

However i'm now using the newest ver of optifabric? what do you mean by update?

**Comment by Chocohead** [comment]
There's no actual crash in that log, just the game starting up. Is there any report in the `crash-reports` folder from it? I suppose it's relevant how you know it's crashing at all.



> 
> 
> > You should probably update.
> 
> However i'm now using the newest ver of optifabric? what do you mean by update?

They mean update to 1.16, 1.14 and 1.15 have been ad hoc support for a long time.

**Comment by SunnySlopes** [comment]
sorry, i've tried to rerun the game, but there're no crash report created because of the crash, the game just quit with exit code 0.
















At 2021-02-17 11:09:32, "Chocohead" <notifications@github.com> wrote:

There's no actual crash in that log, just the game starting up. Is there any report in the crash-reports folder from it? I suppose it's relevant how you know it's crashing at all.

You should probably update.

However i'm now using the newest ver of optifabric? what do you mean by update?

They mean update to 1.16, 1.14 and 1.15 have been ad hoc support for a long time.

**Comment by SunnySlopes** [comment]
here's the crash report.













At 2021-02-17 11:09:32, "Chocohead" <notifications@github.com> wrote:

There's no actual crash in that log, just the game starting up. Is there any report in the crash-reports folder from it? I suppose it's relevant how you know it's crashing at all.

You should probably update.

However i'm now using the newest ver of optifabric? what do you mean by update?

They mean update to 1.16, 1.14 and 1.15 have been ad hoc support for a long time.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Command: "C:\\Program Files\\Java\\jre1.8.0_281\\bin\\java.exe" -Dminecraft.client.jar=.minecraft\versions\1.15.2\1.15.2.jar -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx8096m -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Djava.library.path=H:\HMCL\.minecraft\versions\1.15.2\natives -Dminecraft.launcher.brand=HMCL -Dminecraft.launcher.version=3.3.172 -cp H:\HMCL\.minecraft\libraries\net\fabricmc\tiny-mappings-parser\0.2.2.14\tiny-mappings-parser-0.2.2.14.jar;H:\HMCL\.minecraft\libraries\net\fabricmc\sponge-mixin\0.8.2+build.24\sponge-mixin-0.8.2+build.24.jar;H:\HMCL\.minecraft\libraries\net\fabricmc\tiny-remapper\0.3.0.70\tiny-remapper-0.3.0.70.jar;H:\HMCL\.minecraft\libraries\net\fabricmc\access-widener\1.0.0\access-widener-1.0.0.jar;H:\HMCL\.minecraft\libraries\net\fabricmc\fabric-loader-sat4j\2.3.5.4\fabric-loader-sat4j-2.3.5.4.jar;H:\HMCL\.minecraft\libraries\com\google\jimfs\jimfs\1.2-fabric\jimfs-1.2-fabric.jar;H:\HMCL\.minecraft\libraries\org\ow2\asm\asm\9.0\asm-9.0.jar;H:\HMCL\.minecraft\libraries\org\ow2\asm\asm-analysis\9.0\asm-analysis-9.0.jar;H:\HMCL\.minecraft\libraries\org\ow2\asm\asm-commons\9.0\asm-commons-9.0.jar;H:\HMCL\.minecraft\libraries\org\ow2\asm\asm-tree\9.0\asm-tree-9.0.jar;H:\HMCL\.minecraft\libraries\org\ow2\asm\asm-util\9.0\asm-util-9.0.jar;H:\HMCL\.minecraft\libraries\com\google\guava\guava\21.0\guava-21.0.jar;H:\HMCL\.minecraft\libraries\net\fabricmc\intermediary\1.15.2\intermediary-1.15.2.jar;H:\HMCL\.minecraft\libraries\net\fabricmc\fabric-loader\0.11.1\fabric-loader-0.11.1.jar;H:\HMCL\.minecraft\libraries\com\mojang\patchy\1.1\patchy-1.1.jar;H:\HMCL\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;H:\HMCL\.minecraft\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar;H:\HMCL\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;H:\HMCL\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;H:\HMCL\.minecraft\libraries\com\mojang\javabridge\1.0.22\javabridge-1.0.22.jar;H:\HMCL\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar;H:\HMCL\.minecraft\libraries\io\netty\netty-all\4.1.25.Final\netty-all-4.1.25.Final.jar;H:\HMCL\.minecraft\libraries\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar;H:\HMCL\.minecraft\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar;H:\HMCL\.minecraft\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;H:\HMCL\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;H:\HMCL\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;H:\HMCL\.minecraft\libraries\com\mojang\brigadier\1.0.17\brigadier-1.0.17.jar;H:\HMCL\.minecraft\libraries\com\mojang\datafixerupper\2.0.24\datafixerupper-2.0.24.jar;H:\HMCL\.minecraft\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar;H:\HMCL\.minecraft\libraries\com\mojang\authlib\1.5.25\authlib-1.5.25.jar;H:\HMCL\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;H:\HMCL\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;H:\HMCL\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;H:\HMCL\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;H:\HMCL\.minecraft\libraries\it\unimi\dsi\fastutil\8.2.1\fastutil-8.2.1.jar;H:\HMCL\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.8.1\log4j-api-2.8.1.jar;H:\HMCL\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.8.1\log4j-core-2.8.1.jar;H:\HMCL\.minecraft\libraries\org\lwjgl\lwjgl\3.2.2\lwjgl-3.2.2.jar;H:\HMCL\.minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.2.2\lwjgl-jemalloc-3.2.2.jar;H:\HMCL\.minecraft\libraries\org\lwjgl\lwjgl-openal\3.2.2\lwjgl-openal-3.2.2.jar;H:\HMCL\.minecraft\libraries\org\lwjgl\lwjgl-opengl\3.2.2\lwjgl-opengl-3.2.2.jar;H:\HMCL\.minecraft\libraries\org\lwjgl\lwjgl-glfw\3.2.2\lwjgl-glfw-3.2.2.jar;H:\HMCL\.minecraft\libraries\org\lwjgl\lwjgl-stb\3.2.2\lwjgl-stb-3.2.2.jar;H:\HMCL\.minecraft\libraries\org\lwjgl\lwjgl-tinyfd\3.2.2\lwjgl-tinyfd-3.2.2.jar;H:\HMCL\.minecraft\libraries\com\mojang\text2speech\1.11.3\text2speech-1.11.3.jar;H:\HMCL\.minecraft\versions\1.15.2\1.15.2.jar net.fabricmc.loader.launch.knot.KnotClient --username SunnySlopes --version "HMCL 3.3.172" --gameDir H:\HMCL\.minecraft --assetsDir H:\HMCL\.minecraft\assets --assetIndex 1.15 --uuid ce7f10e9d25744628c63602fe7afaaf1 --accessToken eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5NmM0M2QzMTE4YWMyN2M3ZjY5ODAxN2NlYmQzYTYzZCIsInlnZ3QiOiI4NzBjNWEwZWYyNzQ0ZDEwOThlY2VmMTVkMTIyMGU2MCIsInNwciI6ImNlN2YxMGU5ZDI1NzQ0NjI4YzYzNjAyZmU3YWZhYWYxIiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE2MTQwNzQ2NDYsImlhdCI6MTYxMzkwMTg0Nn0.F9YDu7XBpNdfC1P9C_t83QHDSfHAfZnEdXdno56OGiw --userType mojang --versionType "HMCL 3.3.172" --width 1600 --height 900
[18:04:12] [main/INFO]: Loading for game Minecraft 1.15.2
[18:04:13] [ForkJoinPool-1-worker-1/WARN]: Non-Fabric mod JAR at "H:\HMCL\.minecraft\mods\OptiFine_1.15.2_HD_U_G6.jar", ignoring
[18:04:13] [ForkJoinPool-1-worker-1/WARN]: Non-Fabric mod JAR at "H:\HMCL\.minecraft\mods\randomblockplacement-1.15.2-forge31.1.0-1.0.jar", ignoring
[18:04:13] [ForkJoinPool-1-worker-1/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[18:04:13] [ForkJoinPool-1-worker-3/WARN]: The mod "shulkerboxtooltip" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 8 column 12
[18:04:13] [ForkJoinPool-1-worker-1/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[18:04:13] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.1.2+28f8190f42, also found 0.1.2+9826cad80c, 0.1.2+b7f9825d0c
[18:04:13] [main/WARN]: Mod `{}` ({}) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[18:04:13] [main/INFO]: [FabricLoader] Loading 90 mods: fabric-renderer-api-v1@0.2.11+c1455e800c, fabric-keybindings-v0@0.2.1+c1455e800c, gbfabrictools@1.2.0, notenoughcrashes@1.2.4+1.15.1, inventoryprofiles@0.4.2, fabricloader@0.11.1, explayerenderer@1.2, org_zeroturnaround_zt-zip@1.14, customskinloader@14.12-SNAPSHOT-109, beenfo@1.15-fabric0.4.23-1.0.3, bbor@2.4-1.15.2, fabric-containers-v0@0.1.4+c1455e800c, fabric-object-builder-api-v1@1.3.2+c1455e800c, fabric-dimensions-v1@0.3.1+c1455e800c, java@8, cotton-client-commands@0.4.2+1.14.3-SNAPSHOT, fabric-api-base@0.1.2+28f8190f42, fabric-rendering-data-attachment-v1@0.1.4+c1455e800c, mm@2.0, tweakeroo@0.10.0-dev.20200424.222527, fabric-textures-v0@1.0.5+c1455e800c, fabric-rendering-fluids-v1@0.1.7+c1455e800c, litematica@0.0.0-dev.20200515.184506, waila@1.9.22, easiervillagertrading@1.14.4-fabric0.4.1-1.4, me_shedaniel_cloth_basic-math@0.3.0, fabric-blockrenderlayer-v1@1.1.5+c1455e800c, fabric-lifecycle-events-v1@1.2.1+c1455e800c, fabric-renderer-registries-v1@2.1.1+c1455e800c, minihud@0.19.0-dev.20200427.222110, fabric-loot-tables-v1@0.1.6+c1455e800c, carpet-extra@1.4.0, fast_chest@1.1-1.15,1.16, org_slf4j_slf4j-api@1.7.30, fabric@0.28.5+1.15, carpet@1.4.8, fabric-particles-v1@0.2.2+c1455e800c, fabric-networking-v0@0.2.1+c1455e800c, cloth@1.2.0, fabric-networking-blockentity-v0@0.2.4+c1455e800c, minecraft@1.15.2, modmenu@1.10.5, fabric-command-api-v1@1.0.3+c1455e800c, cloth-basic-math@0.5.0, phosphor@0.5.2+build.6, easiercrafting@1.15-fabric0.4.23-1.5.0, fabric-tool-attribute-api-v1@1.2.4+c1455e800c, fabric-renderer-indigo@0.3.5+c1455e800c, autofish@0.8.5, bebooks@1.0.2, fabric-biomes-v1@0.1.6+c1455e800c, roughlyenoughitems@3.6.21, fabric-item-api-v1@1.1.1+c1455e800c, fabric-events-interaction-v0@0.4.1+c1455e800c, org_slf4j_slf4j-simple@1.7.30, fabric-crash-report-info-v1@0.1.3+c1455e800c, loadcatcher@2.0.0, orderly@1.2.1+build.4-1.15, fabric-rendering-v0@1.1.1+c1455e800c, fabric-rendering-v1@1.2.1+c1455e800c, fabric-key-binding-api-v1@1.0.2+c1455e800c, cloth-config2@2.14.2, replaymod@1.15.2-2.5.1, autoconfig1u@2.0.1, fabric-resource-loader-v0@0.1.11+c1455e800c, inventoryhud@3.2.2, carpet-tis-addition@1.12.1, malilib@0.10.0-dev.21+arne.2, audiooutput@0.0.1, fabric-content-registries-v0@0.1.4+c1455e800c, antighost@1.15-fabric0.4.23-1.1.1, fabric-tag-extensions-v0@0.1.4+c1455e800c, worldedit@7.1.0;8e55131, optifabric@1.0.1, appleskin@1.0.11, fabric-registry-sync-v0@0.7.2+c1455e800c, fabric-commands-v0@0.2.1+c1455e800c, fabric-mining-levels-v0@0.1.3+c1455e800c, blockmeter@1.15-fabric0.4.23-1.4.2, fabric-climbable-api-v1@1.0.1+c1455e800c, fabric-networking-api-v1@1.0.1+c1455e800c, voxelmap@1.9.28, fabric-events-lifecycle-v0@0.2.1+c1455e800c, fabric-models-v0@0.1.1+c1455e800c, fabric-item-groups-v0@0.2.1+c1455e800c, horseinfo@0.1.2-1.15.2, shulkerboxtooltip@2.0.3+1.15.2, entityoutliner@1.0.0, fabric-object-builders-v0@0.6.1+c1455e800c, org_jetbrains_annotations@18.0.0
[18:04:13] [main/WARN]: Mod `fast_chest` (1.1-1.15,1.16) does not respect SemVer - comparison support is limited.
[18:04:13] [main/WARN]: Mod `worldedit` (7.1.0;8e55131) does not respect SemVer - comparison support is limited.
[18:04:13] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/H:/HMCL/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[18:04:13] [main/WARN]: Reference map 'mixins.nonmmlauncher.replaymod.refmap.json' for mixins.nonmmlauncher.replaymod.json could not be read. If this is a development environment you can ignore this message
[18:04:13] [main/WARN]: Reference map 'AntiGhost-refmap.json' for mixins.antighost.json could not be read. If this is a development environment you can ignore this message
Fetching https://api.sk1er.club/modcore_versions
No ModCore target for 1.15.2_fabric. This in fine, unless you're specifically looking for ModCore.
Replay Mod is still using the traditional Early Riser initialisation
Optifabric is still using the traditional Early Riser initialisation
Found existing patched optifine jar, using that
[18:04:16] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:302)
	at net.minecraft.class_128.method_559(class_128.java:101)
	at net.minecraft.class_128.<init>(class_128.java:54)
	at net.minecraft.class_128.method_24305(class_128.java:414)
	at net.minecraft.client.main.Main.main(Main.java:129)
	... 7 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method changeTickPhase(F)F in carpet.mixins.json:WorldRenderer_pausedShakeMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-carpet-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 18 more

**Comment by SunnySlopes** [comment]
Optifabric is still using the traditional Early Riser initialisation

at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)

at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)

at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)

at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:137)

at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 9 path $

at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)

at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401)

at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)

at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)

at com.google.gson.JsonParser.parse(JsonParser.java:60)

... 31 more

Found existing patched optifine jar, using that

[18:20:25] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)

Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)

at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)

at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

Caused by: java.lang.reflect.InvocationTargetException

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

at java.lang.reflect.Method.invoke(Unknown Source)

at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)

... 2 more

Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)

at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)

at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)

at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)

at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)

at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)

at java.lang.ClassLoader.loadClass(Unknown Source)

at net.optifine.reflect.Reflector.<clinit>(Reflector.java:302)

at net.minecraft.class_128.method_559(class_128.java:101)

at net.minecraft.class_128.<init>(class_128.java:54)

at net.minecraft.class_128.method_24305(class_128.java:414)

at net.minecraft.client.main.Main.main(Main.java:129)

... 7 more

Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method changeTickPhase(F)F in carpet.mixins.json:WorldRenderer_pausedShakeMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-carpet-refmap.json

at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)

at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)

at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)

at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)

at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)

at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)

at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)

at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)

... 18 more

this is the error related to optifabric and optifine when i tried to launch the game.
















At 2021-02-17 11:09:32, "Chocohead" <notifications@github.com> wrote:

There's no actual crash in that log, just the game starting up. Is there any report in the crash-reports folder from it? I suppose it's relevant how you know it's crashing at all.

You should probably update.

However i'm now using the newest ver of optifabric? what do you mean by update?

They mean update to 1.16, 1.14 and 1.15 have been ad hoc support for a long time.

**Comment by SunnySlopes** [comment]
the problem is probably related to the compatibility with carpet mod, which i discovered yesterday. i'll open a new issue then.
