### ISSUE TITLE
The compatibility issue between Fabric API and OptiFabric.

### ISSUE THREAD

**Issue by wenwentw** [Chocohead/OptiFabric#1601]
If I download Fabric API and OptiFabric at the same time while on game version 1.20.4, I get stuck on the Mojang loading screen. Could you please advise on how to resolve this?

**Comment by Dracconis** [comment]
Depends on the version of Fabric Loader, Fabric API, Optifabric, and Optifine versions you are using.

**Comment by Poopooracoocoo** [comment]
Could you share the latest.log file from your logs folder?
I was able to get to the main menu of Minecraft using Minecraft 1.20.4, Fabric Loader 0.15.11, Fabric API 0.97.0, OptiFabric 1.14.3, and OptiFine HD U I7.

**Comment by Heyh520** [comment]
[10:13:46] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.11
[10:13:46] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[10:13:46] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:197) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?]
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:159) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:159) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:215) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.15.11.jar:?]
	... 9 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [D:\mc    \.minecraft\versions\1.20.4-Fabric 0.15.11-OptiFine_I7\mods\OptiFine_1.20.4_HD_U_I7.jar]: java.util.zip.ZipException: invalid CEN header (bad signature)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562) ~[?:?]
	at java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604) ~[?:?]
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981) ~[?:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:156) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:215) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.15.11.jar:?]
	... 9 more
Caused by: java.lang.RuntimeException: Error analyzing [D:\mc    \.minecraft\versions\1.20.4-Fabric 0.15.11-OptiFine_I7\mods\OptiFine_1.20.4_HD_U_I7.jar]: java.util.zip.ZipException: invalid CEN header (bad signature)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:300) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:249) ~[fabric-loader-0.15.11.jar:?]
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.util.zip.ZipException: invalid CEN header (bad signature)
	at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1730) ~[?:?]
	at java.util.zip.ZipFile$Source.checkAndAddEntry(ZipFile.java:1191) ~[?:?]
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1669) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1447) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1409) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:717) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:251) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:180) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:194) ~[?:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:321) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:290) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:249) ~[fabric-loader-0.15.11.jar:?]
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

**Comment by Heyh520** [comment]
Mine is the same as the mods version you mentioned, and I can't get in either.

**Comment by Heyh520** [comment]
java.lang.RuntimeException: Error running OptiFine patcher at D:\mc整合\.minecraft\versions\1.20.4-Fabric 0.15.11-OptiFine_I7\mods\OptiFine_1.20.4_HD_U_I7.jar on D:\mc整合\.minecraft\versions\1.20.4-Fabric 0.15.11-OptiFine_I7\1.20.4-Fabric 0.15.11-OptiFine_I7.jar
	at me.modmuss50.optifabric.mod.OptifineSetup.runInstaller(OptifineSetup.java:231)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:109)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at me.modmuss50.optifabric.mod.OptifineSetup.runInstaller(OptifineSetup.java:229)
	... 32 more
Caused by: java.util.zip.ZipException: invalid distance too far back
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:106)
	at optifine.Utils.readAll(Utils.java:147)
	at optifine.Patcher.process(Patcher.java:81)
	... 37 more

**Comment by Dracconis** [comment]
> java.lang.RuntimeException: Error running OptiFine patcher at D:\mc整合.minecraft\versions\1.20.4-Fabric 0.15.11-OptiFine_I7\mods\OptiFine_1.20.4_HD_U_I7.jar on D:\mc整合.minecraft\versions\1.20.4-Fabric 0.15.11-OptiFine_I7\1.20.4-Fabric 0.15.11-OptiFine_I7.jar at me.modmuss50.optifabric.mod.OptifineSetup.runInstaller(OptifineSetup.java:231) at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:109) at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46) at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) at com.chocohead.mm.Plugin.getMixins(Plugin.java:340) at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128) at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796) at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568) at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) at java.base/java.lang.Class.forName0(Native Method) at java.base/java.lang.Class.forName(Class.java:467) at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) at oolloo.jlw.Wrapper.main(Wrapper.java:51) Caused by: java.lang.reflect.InvocationTargetException at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at me.modmuss50.optifabric.mod.OptifineSetup.runInstaller(OptifineSetup.java:229) ... 32 more Caused by: java.util.zip.ZipException: invalid distance too far back at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164) at java.base/java.io.FilterInputStream.read(FilterInputStream.java:106) at optifine.Utils.readAll(Utils.java:147) at optifine.Patcher.process(Patcher.java:81) ... 37 more

STOP HIJACKING OTHER'S TICKETS! Create your own ticket so that you can get help for your issue.

**Comment by Poopooracoocoo** [comment]
@pipixixi233 looks like your OptiFine jar file is corrupt. Download it again.

**Comment by Heyh520** [comment]
Is that right? It's just as weird that I tried to redownload it several times.

**Comment by Heyh520** [comment]
I went to the official website to download OptiFine again. How can you tell? I am also a java developer o. O, but thank you very much.

**Comment by Poopooracoocoo** [comment]
You didn't state whether downloading it again actually worked or not. 

I said that because I read this line:
> Caused by: java.lang.RuntimeException: Error analyzing [D:\mc .minecraft\versions\1.20.4-Fabric 0.15.11-OptiFine_I7\mods\OptiFine_1.20.4_HD_U_I7.jar]: java.util.zip.ZipException: invalid CEN header (bad signature)

> java.util.zip.ZipException: invalid CEN header (bad signature)

usually means that its corrupt
