### ISSUE TITLE
Help Uncaught exception in thread  "main"

### ISSUE THREAD

**Issue by Trieestk6** [Chocohead/OptiFabric#1621]
IllegalArgumentException: can't parse argument number: 4 
<html>at java.base/java.text.MessageFormat.makeFormat(MessageFormat.java:1454)<br>at java.base/java.text.MessageFormat.applyPattern(MessageFormat.java:492)<br>at java.base/java.text.MessageFormat.&lt;init&gt;(MessageFormat.java:371)<br>at java.base/java.text.MessageFormat.format(MessageFormat.java:860)<br>at net.fabricmc.loader.impl.util.Localization.format(Localization.java:38)<br>at net.fabricmc.loader.impl.discovery.ResultAnalyzer.addErrorToList(ResultAnalyzer.java:302)<br>at net.fabricmc.loader.impl.discovery.ResultAnalyzer.gatherErrors(ResultAnalyzer.java:83)<br>at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:148)<br>at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)<br>at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:229)<br>at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)<br>at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)<br>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)<br>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)</html>
NumberFormatException: For input string: "4 "
<html>at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)<br>at java.base/java.lang.Integer.parseInt(Integer.java:668)<br>at java.base/java.lang.Integer.parseInt(Integer.java:786)<br>at java.base/java.text.MessageFormat.makeFormat(MessageFormat.java:1452)<br>... 13 more</html>
![Ảnh chụp màn hình 2024-05-14 205722](https://github.com/Chocohead/OptiFabric/assets/169816290/1310139c-f5f7-4ef1-9db4-00ca3c3a55d9)

**Comment by Dracconis** [comment]
Error log please

**Comment by Trieestk6** [comment]
> Vui lòng ghi nhật ký lỗi

[20:55:40] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.11
[20:55:40] [main/WARN]: Mod resolution failed
[20:55:40] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED optifabric 1.13.25 {depends minecraft @ [1.16.1 || 1.16.2 || 1.16.3 || 1.16.4 || 1.16.5 || 1.17-alpha.21.8.b || 1.17-beta.4 || 1.17 || 1.17.1 || 1.18-beta.1 || 1.18 || 1.18.1 || 1.18.2 || 1.19 || 1.19.1 || 1.19.2 || 1.19.3 || 1.19.4 || 1.20 || 1.20.1]}, ROOT_FORCELOAD_SINGLE optifabric 1.13.25]
[20:55:40] [main/INFO]: Reason: [NEG_HARD_DEP sodium 0.5.8+mc1.20.4 {breaks optifabric @ [*]}, NEG_HARD_DEP iris 1.6.17 {breaks optifabric @ [*]}, HARD_DEP optifabric 1.13.25 {depends minecraft @ [1.16.1 || 1.16.2 || 1.16.3 || 1.16.4 || 1.16.5 || 1.17-alpha.21.8.b || 1.17-beta.4 || 1.17 || 1.17.1 || 1.18-beta.1 || 1.18 || 1.18.1 || 1.18.2 || 1.19 || 1.19.1 || 1.19.2 || 1.19.3 || 1.19.4 || 1.20 || 1.20.1]}]
[20:55:40] [main/INFO]: Fix: add [], remove [], replace [[optifabric 1.13.25] -> add:optifabric 1 ([(-?,?)]), [iris 1.6.17] -> add:iris 1 ([(-?,?)]), [sodium 0.5.8+mc1.20.4] -> add:sodium 0.5.8 ([[0.5.8,0.5.8]])]
[20:55:40] [main/ERROR]: Uncaught exception in thread "main"
java.lang.IllegalArgumentException: can't parse argument number: 4 
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1454) ~[?:?]
	at java.text.MessageFormat.applyPattern(MessageFormat.java:492) ~[?:?]
	at java.text.MessageFormat.<init>(MessageFormat.java:371) ~[?:?]
	at java.text.MessageFormat.format(MessageFormat.java:860) ~[?:?]
	at net.fabricmc.loader.impl.util.Localization.format(Localization.java:38) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.discovery.ResultAnalyzer.addErrorToList(ResultAnalyzer.java:302) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.discovery.ResultAnalyzer.gatherErrors(ResultAnalyzer.java:83) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:148) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:229) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
Caused by: java.lang.NumberFormatException: For input string: "4 "
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1452) ~[?:?]
	... 13 more

**Comment by Dracconis** [comment]
You need to choose to use either Sodium/Iris OR Optifabric/Optifine, but not both.

**Comment by Trieestk6** [comment]
> You need to choose to use either Sodium/Iris OR Optifabric/Optifine, but not both.

thank bro

**Comment by Dracconis** [comment]
You're welcome. If this resolves your issue please close this ticket.
