### ISSUE TITLE
Minecraft 1.16.5 cant load this mod

### ISSUE THREAD

**Issue by Safir-Lemmings** [Chocohead/OptiFabric#1625]
---- Minecraft Crash Report ----
// There are four lights!

Time: 5/17/24 7:12 PM
Description: Ticking screen

java.lang.IllegalStateException: [fabric-screen-api-v1] The current screen (net.minecraft.class_437) has not been correctly initialised, please send this crash log to the mod author. This is usually caused by the screen not calling super.init(Lnet/minecraft/client/MinecraftClient;II)V
	at net.minecraft.class_437.ensureEventsAreInitialised(class_437.java:1663)
	at net.minecraft.class_437.fabric_getBeforeTickEvent(class_437.java:1676)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.beforeTick(ScreenEvents.java:151)
	at net.minecraft.class_310.handler$zid000$fabric-screen-api-v1$beforeScreenTick(class_310.java:5902)
	at net.minecraft.class_310.method_1572(class_310.java:1526)
	at net.minecraft.class_310$$Lambda$3775/200873209.run(Unknown Source)
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_310.method_1574(class_310.java:1526)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_437.ensureEventsAreInitialised(class_437.java:1663)
	at net.minecraft.class_437.fabric_getBeforeTickEvent(class_437.java:1676)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.beforeTick(ScreenEvents.java:151)
	at net.minecraft.class_310.handler$zid000$fabric-screen-api-v1$beforeScreenTick(class_310.java:5902)
	at net.minecraft.class_310.method_1572(class_310.java:1526)
	at net.minecraft.class_310$$Lambda$3775/200873209.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_410
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_310.method_1574(class_310.java:1526)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1805384584 bytes (1721 MB) / 3154116608 bytes (3008 MB) up to 3154116608 bytes (3008 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 1.14.2+1.16.5
		advancementbook: Advancement Book 1.0.4
		annotateddi: Annotated DI 4.0.1+1.16.5
		aopalliance_aopalliance: aopalliance 1.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		biome_locator: Biome Locator 1.1.2
		chas: Craftable Horse Armour & Saddle 1.16-1.7-Fabric
		chatplus: chatplus 1.0.1
		chromaconcrete: Chroma Concrete 1.1.1
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 1.6.59
		cloth-config2: Cloth Config v4 4.14.54
		colorfulmasonry: Colorful Masonry 1.0.0
		com_google_inject_guice: guice 5.1.0
		complete_bone_meal: Complete Bone Meal 1.1.0
		compressedblocks: Compressed Blocks 1.3.5
		customportalapi: Custom Portals 0.0.1-beta32-1.16
		fabric: Fabric API 0.42.0+1.16
		fabric-api-base: Fabric API Base 0.4.0+3cc0f0907d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+3cc0f0907d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.13+3cc0f0907d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+3cc0f0907d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+3cc0f0907d
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+3cc0f0907d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+3cc0f0907d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.5+3cc0f0907d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+3cc0f0907d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.8+3cc0f0907d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+3cc0f0907d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.5+3cc0f0907d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+3cc0f0907d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+3cc0f0907d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.2+3cc0f0907d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+3cc0f0907d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+3cc0f0907d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+3cc0f0907d
		fabric-language-kotlin: Fabric Language Kotlin 1.8.7+kotlin.1.7.22
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.2+3cc0f0907d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+3cc0f0907d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+3cc0f0907d
		fabric-models-v0: Fabric Models (v0) 0.3.1+3cc0f0907d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+3cc0f0907d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+3cc0f0907d
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+3cc0f0907d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.6+3cc0f0907d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+3cc0f0907d
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+3cc0f0907d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+3cc0f0907d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+3cc0f0907d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.5+3cc0f0907d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.1+3cc0f0907d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+3cc0f0907d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.15+3cc0f0907d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+3cc0f0907d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.1+3cc0f0907d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+3cc0f0907d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+3cc0f0907d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+3cc0f0907d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+3cc0f0907d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+3cc0f0907d
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+3cc0f0907d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.8+3cc0f0907d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+3cc0f0907d
		fabricloader: Fabric Loader 0.15.11
		fallingtree: FallingTree 2.11.0
		fireplacelib: Fireplace Lib 7.0.2+1.16.5
		flytre_lib: FlytreLib 0.2.11
		fpsdisplay: FPS-Display 3.1.0+1.16.x
		here-be-no-dragons: Here be no Dragons! 1.0.0
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		javax_inject_javax_inject: javax.inject 1
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.3+1.16.5
		lucky: Lucky Block 1.16.5-5
		mcsa: MC Story Mode Armor 2.3.2
		mcvmcomputers: VM Computers 1.4.15
		microconfig: Microconfig 1.0.5
		minecraft: Minecraft 1.16.5
		mining_dims: Mining Dimensions 1.0.5
		mixinextras: MixinExtras 0.3.5
		mm: Manningham Mills 2.2
		modid: Portable Jukebox 1.1.0
		modmenu: Mod Menu 1.16.23
		opitems: Op Items 1.1.0
		optifabric: OptiFabric 1.10.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.22
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.22
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.22
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.22
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		pandamc_concreteplus: Concrete plus 1.5.4
		pipe: Pipe 1.3.1
		roughlyenoughitems: Roughly Enough Items 5.12.385
		roughlyenoughitems-api: REI (API) 5.12.385
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.385
		roughlyenoughitems-runtime: REI (Runtime) 5.12.385
		slime_sling: SlimeSling 1.0.0
		tardim: TARDIM 1.1.3
		textbook: Textbook 2.2.1+1.16.5
		timeinabottle: Time in a Bottle 1.3-mc1.16.4-fabric
		tlskincape: TLSkinCape 1.19
		torohealth: ToroHealth Damage Indicators 1.16.5-fabric-6
	Launched Version: Computer
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 5500 GL version 4.4.0 - Build 20.19.15.4835, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, programer_art, file/Creative+Computers.zip, file/Better+leaves+bush+1.16.2+.zip, file/Better-Leaves-7.0-1.13+.zip (incompatible), file/Round-Trees-6.0-1.13+.zip (incompatible), file/round-moonv6.zip, file/round-sun-v6.zip, file/FreshAnimations_v1.6.zip (incompatible)
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz

-- OptiFabric --
Details:
	OptiFine jar designed for: ~~NULL~~
	OptiFine jar version: ~~NULL~~
	OptiFine jar status: Error whilst searching
	OptiFine remapped jar: ~~NULL~~
	OptiFabric error: Failed to load OptiFine, please report this!

net/fabricmc/tinyremapper/IMappingProvider

**Comment by Dracconis** [comment]
You need to be using Fabric Loader 0.14.25 (NOT 0.15.11), Optifabric 1.13.16 (NOT 1.10.1), and since I don't see what version of Optifine that you are using it should version Optifine HD U G8.
