### ISSUE TITLE
Mod Lithium doesn't work on Pojavlauncher 1.18.2.

### ISSUE THREAD

**Issue by ArmaN11123885** [Chocohead/OptiFabric#1628]
This mod doesn't work for me. Please advise which version of this mod to download for fabric 
Optifabric version 0.13.16
Fabric 0.14.25
![Screenshot_20240520_190543](https://github.com/Chocohead/OptiFabric/assets/169547149/79a5d431-44c9-4f85-8080-c6b95451dd5b)
![Screenshot_20240520_190524](https://github.com/Chocohead/OptiFabric/assets/169547149/9eab896b-40a2-40fd-a02c-16adf3a580ff)

**Comment by Dracconis** [comment]
Need to use the Fabric Loader 0.14.25

**Comment by ArmaN11123885** [comment]
This is the version I use, but the Lithium mod does not work. Optifabric version 0.13.16. Recommend some version to work on it. When I look there at log output  it says that it does not fit the OptiFabric version.



2024-05-20 21:18:06,612 main ERROR appender Console has no parameter that matches element Policies
[21:18:06] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.25
[21:18:07] [main/WARN]: Mod resolution failed
[21:18:07] [main/INFO]: Immediate reason: [NEG_HARD_DEP lithium 0.7.9 {breaks optifabric @ [*]}, ROOT_FORCELOAD_SINGLE lithium 0.7.9, ROOT_FORCELOAD_SINGLE optifabric 1.13.16]
[21:18:07] [main/INFO]: Reason: [NEG_HARD_DEP lithium 0.7.9 {breaks optifabric @ [*]}]
[21:18:07] [main/INFO]: Fix: add [], remove [], replace [[lithium 0.7.9] -> add:lithium 1 ([(-∞,∞)])]
[21:18:07] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Lithium' (lithium) 0.7.9 with any version that is compatible with:
		 - optifabric 1.13.16
More details:
	 - Mod 'Lithium' (lithium) 0.7.9 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.16!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.25.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:194) ~[fabric-loader-0.14.25.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.14.25.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.25.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Dracconis** [comment]
Cannot use Lithium AND Optifabric. You must use 1 or the other but not both.

**Comment by ArmaN11123885** [comment]
Okay, is there any replacement for Lithium to work on OptiFabric?

**Comment by Dracconis** [comment]
No not that I am aware of

**Comment by ArmaN11123885** [comment]
OK, thank you.
