### ISSUE TITLE
I'm running minecraft 1.16.5 fabric 1.14.25

### ISSUE THREAD

**Issue by AgentN1kto** [Chocohead/OptiFabric#1642]
java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 25 more

**Comment by Dracconis** [comment]
Then you can't be running Fabric Loader 0.14.25 or you wouldn't be getting that error message. Check to make sure you are using Fabric API 0.42.0, Optifabric 1.13.16, Optifine G8, and lastly look at the Profile set in the Launcher to make sure it reads: release fabric-loader-0.14.25-1.16.5

**Comment by AgentN1kto** [comment]
> Тогда вы не сможете использовать Fabric Loader 0.14.25, иначе вы не получите это сообщение об ошибке. Убедитесь, что вы используете Fabric API 0.42.0, Optifabric 1.13.16, Optifine G8, и, наконец, посмотрите на профиль, установленный в панели запуска, чтобы убедиться, что он гласит: Release Fabric-Loader-0.14.25-1.16.5

I checked everything according to your comment, but maybe it’s because I’m using Legacy Launcher?

**Comment by AgentN1kto** [comment]
> Then you can't be running Fabric Loader 0.14.25 or you wouldn't be getting that error message. Check to make sure you are using Fabric API 0.42.0, Optifabric 1.13.16, Optifine G8, and lastly look at the Profile set in the Launcher to make sure it reads: release fabric-loader-0.14.25-1.16.5


Is the Optifine HD U 8 version suitable?

**Comment by Dracconis** [comment]
If you mean the G8 version as there is no U 8 version, they yes otherwise I wouldn't use whatever version that is.

**Comment by AgentN1kto** [comment]
> If you mean the G8 version as there is no U 8 version, they yes otherwise I wouldn't use whatever version that is.


thank you, yes, I meant HD U G8, but your help did not help me

**Comment by Dracconis** [comment]
What do you mean by legacy launcher? If you can provide a screenshot of the launcher I might be able to help get you sorted out.

**Comment by Poopooracoocoo** [comment]
Legacy Launcher is a pirated/illegal Minecraft launcher.
