### ISSUE TITLE
OptiFabric loading error. | 1.16.5 version

### ISSUE THREAD

**Issue by TheKsenon** [Chocohead/OptiFabric#1660]
Log:

--------- beginning with launcher debug
Info: Launcher version: edelweiss-20230928-9484d0c-v3_openjdk
Info: Architecture: arm64
Info: Device model: Xiaomi M2103K19C
Info: API version: 33
Info: Selected Minecraft version: fabric-loader-0.15.11-1.16.5
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2400
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~qCU9KXxqa3r0oOAnfFojgw==/net.kdt.pojavlaunch-xFqSalmwzTMeRFB0wxeoGA==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~qCU9KXxqa3r0oOAnfFojgw==/net.kdt.pojavlaunch-xFqSalmwzTMeRFB0wxeoGA==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
Initialising gl4es
v1.1.5 built on Sep 27 2023 17:42:09
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16383
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 64), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is ARM
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
glXMakeCurrent FBO workaround enabled
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
--------- beginning of main
I/jrelog  (13813): dlopen libgl4es_114.so success
I/jrelog  (13813): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (13813): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (13813): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libdt_socket.so success
I/jrelog  (13813): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjawt.so success
I/jrelog  (13813): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmanagement.so success

I/jrelog  (13813): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjdwp.so success
I/jrelog  (13813): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (13813): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  (13813): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pkcs11.so success

I/jrelog  (13813): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsunec.so success

I/jrelog  (13813): dlopen /data/app/~~qCU9KXxqa3r0oOAnfFojgw==/net.kdt.pojavlaunch-xFqSalmwzTMeRFB0wxeoGA==/lib/arm64/libopenal.so success

I/jrelog  (13813): Done processing args

I/jrelog  (13813): Found JLI lib
I/jrelog  (13813): Calling JLI_Launch

OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider jdk.nashorn.api.scripting.NashornScriptEngineFactory not found
2024-06-08 20:35:22,091 main ERROR appender Console has no parameter that matches element Policies
[20:35:22] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.15.11
[20:35:22] [main/INFO]: Loading 52 mods:
	- fabric 0.42.0+1.16
	   |-- fabric-api-base 0.4.0+3cc0f0907d
	   |-- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d
	   |-- fabric-biome-api-v1 3.1.13+3cc0f0907d
	   |-- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d
	   |-- fabric-command-api-v1 1.1.3+3cc0f0907d
	   |-- fabric-commands-v0 0.2.3+3cc0f0907d
	   |-- fabric-containers-v0 0.1.12+3cc0f0907d
	   |-- fabric-content-registries-v0 0.2.5+3cc0f0907d
	   |-- fabric-crash-report-info-v1 0.1.4+3cc0f0907d
	   |-- fabric-dimensions-v1 2.0.8+3cc0f0907d
	   |-- fabric-entity-events-v1 1.2.4+3cc0f0907d
	   |-- fabric-events-interaction-v0 0.4.5+3cc0f0907d
	   |-- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d
	   |-- fabric-game-rule-api-v1 1.0.7+3cc0f0907d
	   |-- fabric-item-api-v1 1.2.2+3cc0f0907d
	   |-- fabric-item-groups-v0 0.3.1+3cc0f0907d
	   |-- fabric-key-binding-api-v1 1.0.5+3cc0f0907d
	   |-- fabric-keybindings-v0 0.2.2+3cc0f0907d
	   |-- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d
	   |-- fabric-loot-tables-v1 1.0.3+3cc0f0907d
	   |-- fabric-mining-levels-v0 0.1.4+3cc0f0907d
	   |-- fabric-models-v0 0.3.1+3cc0f0907d
	   |-- fabric-networking-api-v1 1.0.5+3cc0f0907d
	   |-- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d
	   |-- fabric-networking-v0 0.3.3+3cc0f0907d
	   |-- fabric-object-builder-api-v1 1.9.6+3cc0f0907d
	   |-- fabric-object-builders-v0 0.7.3+3cc0f0907d
	   |-- fabric-particles-v1 0.2.5+3cc0f0907d
	   |-- fabric-registry-sync-v0 0.7.6+3cc0f0907d
	   |-- fabric-renderer-api-v1 0.4.5+3cc0f0907d
	   |-- fabric-renderer-indigo 0.4.5+3cc0f0907d
	   |-- fabric-renderer-registries-v1 2.3.1+3cc0f0907d
	   |-- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d
	   |-- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d
	   |-- fabric-rendering-v0 1.1.3+3cc0f0907d
	   |-- fabric-rendering-v1 1.6.1+3cc0f0907d
	   |-- fabric-resource-loader-v0 0.4.8+3cc0f0907d
	   |-- fabric-screen-api-v1 1.0.1+3cc0f0907d
	   |-- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d
	   |-- fabric-structure-api-v1 1.1.12+3cc0f0907d
	   |-- fabric-tag-extensions-v0 1.1.2+3cc0f0907d
	   |-- fabric-textures-v0 1.0.7+3cc0f0907d
	   |-- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d
	   \-- fabric-transfer-api-v1 1.5.0+3cc0f0907d
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- java 8
	- minecraft 1.16.5
	- optifabric 1.13.16
	   \-- mm 2.3
	- voxelmap 1.10.15
[20:35:22] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
Failed to setup optifine:
java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.lang.ClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 25 more

![error.png](https://disk.gozle.org/api/v1/file-entries/download/MjMzNjUyfHBhZA?shareable_link=13277&password=null)

There is a error in Pojavlauncher. 
But, I have: optifabric-1.13.16, fabric-api-0.42.0+1.16

**Comment by Dracconis** [comment]
Use Fabric Loader 0.14.25. also next time please do a search to see if your issue has already been solved.
