### ISSUE TITLE
Error loading OptiFabric/Failed to remap jar 1.20.1

### ISSUE THREAD

**Issue by A35K-K** [Chocohead/OptiFabric#1668]
java.lang.RuntimeException: Failed to remap jar
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:252)
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:236)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:184)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Unfixable conflicts
	at me.modmuss50.optifabric.shadow.tinyremapper.TinyRemapper.handleConflicts(TinyRemapper.java:885)
	at me.modmuss50.optifabric.shadow.tinyremapper.TinyRemapper.propagate(TinyRemapper.java:785)
	at me.modmuss50.optifabric.shadow.tinyremapper.TinyRemapper.mrjRefresh(TinyRemapper.java:1064)
	at me.modmuss50.optifabric.shadow.tinyremapper.TinyRemapper.apply(TinyRemapper.java:916)
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:3890)
	... 27 more

![image](https://github.com/Chocohead/OptiFabric/assets/172265549/33055041-aedc-4b7b-8c63-07a987cd418d)
Mod list ^

**Comment by Dracconis** [comment]
Please remove Bobby mod from your mods and try again. It has been reported the it does NOT work with optifabric/fine.

**Comment by A35K-K** [comment]
> Please remove Bobby mod from your mods and try again. It has been reported the it does NOT work with optifabric/fine.

The issue persits even when removing Bobby from the mods folder

**Comment by Dracconis** [comment]
What version of the Fabric Loader are you using?

**Comment by A35K-K** [comment]
> What version of the Fabric Loader are you using?
I have tried with Versions 0.14.21 and 0.15.11

**Comment by Dracconis** [comment]
Try just using:
Fabric Loader 0.14.25
Fabric API 0.85.0
Optifabric 1.14.3
Optifine HD U I6
IF using only those mods and loader and you still get an error then please give us the new error. IF it works just fine then add 1 mod in at a time until you get an error.

**Comment by A35K-K** [comment]
Hello, with that setup the game doesn´t launch at all and just gets stuck at the loading screen for the past 10 minutes.
![image](https://github.com/Chocohead/OptiFabric/assets/172265549/447336f3-0cee-4224-a1bd-c19ab232f111)

**Comment by Dracconis** [comment]
Which MC Launcher are you using?

**Comment by A35K-K** [comment]
I am using the (I believe) normal launcher
![image](https://github.com/Chocohead/OptiFabric/assets/172265549/68f1ddfc-68f8-4aa1-8505-00675b66c6a9)
![image](https://github.com/Chocohead/OptiFabric/assets/172265549/41d53806-1ed1-412f-a950-1a12040ff7ac)

**Comment by Dracconis** [comment]
Ok then if only using the mods I listed before and you are getting just the loading screen, then please provide the error log so that we can see what else is going on.
