### ISSUE TITLE
Optifabric 1.16.5 Error

### ISSUE THREAD

**Issue by Nikita459843** [Chocohead/OptiFabric#1673]
Optifabric 1.16.5
![image](https://github.com/Chocohead/OptiFabric/assets/172440153/738393f4-9162-4afd-b3cb-f69158ef97c7)
Optifabric 1.13.16
Fabric 0.42.0
Optifine HD U G8
java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at com.chocohead.mm.Plugin$$Lambda$54/1170788511.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more

**Comment by Dracconis** [comment]
Use Fabric Loader 0.14.25. also next time please do a search to see if your issue has already been solved.

**Comment by Nikita459843** [comment]
And how to install it? Is it a mod or something else?

**Comment by Dracconis** [comment]
> And how to install it? Is it a mod or something else?

How are you using Fabric Loader in the first place? Without it you wouldnt be getting that error at all as it wouldnt load any mods.

**Comment by Nikita459843** [comment]
> > And how to install it? Is it a mod or something else?
> 
> How are you using Fabric Loader in the first place? Without it you wouldnt be getting that error at all as it wouldnt load any mods.

I did the build in curseforge

**Comment by Dracconis** [comment]
Then you need to be following the installation instructions in Curseforge for how to install and use the Fabric Loader version I mentioned. Google is your friend. Instructions here and took me 5 seconds to find it. https://shockbyte.com/billing/knowledgebase/658/How-To-Install-Fabric-On-Your-PC-Using-CurseForge-or-MultiMC.html

**Comment by Nikita459843** [comment]
> Then you need to be following the installation instructions in Curseforge for how to install and use the Fabric Loader version I mentioned. Google is your friend. Instructions here and took me 5 seconds to find it. https://shockbyte.com/billing/knowledgebase/658/How-To-Install-Fabric-On-Your-PC-Using-CurseForge-or-MultiMC.html

I downloaded Fabric Loader 0.14.25, but another error comes out. Should I take off the error screen?

**Comment by Dracconis** [comment]
What error are you getting now?

**Comment by Nikita459843** [comment]
![image](https://github.com/Chocohead/OptiFabric/assets/172440153/73d2d98a-4a7c-4d46-a9f6-0f8766aa1cc8)

**Comment by Nikita459843** [comment]
> What error are you getting now?

![image](https://github.com/Chocohead/OptiFabric/assets/172440153/48437b2b-6624-49a4-913e-b9a1506c5f35)

**Comment by Dracconis** [comment]
Well that is why you have anew error as you are using the wrong version of Optifabric. The error states you are using 1.11.20 and not the 1.13.16 that you said you were using in the first post.

**Comment by Nikita459843** [comment]
Oh, I'm sorry, I'll change it now

**Comment by Nikita459843** [comment]
There are no problems at all

**Comment by Nikita459843** [comment]
Sorry, I used OptiFabric from the YouTuber build and the video was old.

**Comment by Dracconis** [comment]
Ok well if this solves this issue please close the ticket

**Comment by Nikita459843** [comment]
And how do I close the ticket?

**Comment by Dracconis** [comment]
> And how do I close the ticket?

At the bottom of the text box you type in, right next to the comment button is a close issue button.
