### ISSUE TITLE
1.16.5 not working

### ISSUE THREAD

**Issue by ApsonCanPvP** [Chocohead/OptiFabric#1689]
Basically I cant play tlaucher because in my laptop optifabric and optifine is not working so can anyone help me?

**Comment by Dracconis** [comment]
Need an error or error log to know what is happening to be able to provide help.

**Comment by oxbq** [comment]
> Need an error or error log to know what is happening to be able to provide help.

bro, pls, I have already tried many versions of fabric loader and the 3 optifine 1.16 and that error keeps appearing
![image](https://github.com/Chocohead/OptiFabric/assets/173572051/eac512b5-2353-4b54-b8e4-1f220441f69e)

**Comment by Dracconis** [comment]
> > Need an error or error log to know what is happening to be able to provide help.
> 
> bro, pls, I have already tried many versions of fabric loader and the 3 optifine 1.16 and that error keeps appearing ![image](https://private-user-images.githubusercontent.com/173572051/341994212-eac512b5-2353-4b54-b8e4-1f220441f69e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwODU5OTAsIm5iZiI6MTcxOTA4NTY5MCwicGF0aCI6Ii8xNzM1NzIwNTEvMzQxOTk0MjEyLWVhYzUxMmI1LTIzNTMtNGI1NC1iOGU0LTFmMjIwNDQxZjY5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQxOTQ4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWYxYzZiODUzNmNiOWQxMzJmNDlhY2JlYWI4ZmU0ZGYxN2I2YWIwMjcxMjc4M2JmMTBlN2ZhMGM3ZmQzNjg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hAR6-NKYD8WD61_hUGZjtQ6gmkKDm3TM_nS0ZfFoThE)

1.16 or 1.16+ version?

**Comment by oxbq** [comment]
> > > Need an error or error log to know what is happening to be able to provide help.
> > 
> > 
> > bro, pls, I have already tried many versions of fabric loader and the 3 optifine 1.16 and that error keeps appearing ![image](https://private-user-images.githubusercontent.com/173572051/341994212-eac512b5-2353-4b54-b8e4-1f220441f69e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwODU5OTAsIm5iZiI6MTcxOTA4NTY5MCwicGF0aCI6Ii8xNzM1NzIwNTEvMzQxOTk0MjEyLWVhYzUxMmI1LTIzNTMtNGI1NC1iOGU0LTFmMjIwNDQxZjY5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQxOTQ4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWYxYzZiODUzNmNiOWQxMzJmNDlhY2JlYWI4ZmU0ZGYxN2I2YWIwMjcxMjc4M2JmMTBlN2ZhMGM3ZmQzNjg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hAR6-NKYD8WD61_hUGZjtQ6gmkKDm3TM_nS0ZfFoThE)
> 
> 1.16 or 1.16+ version?

1.16.5

**Comment by Dracconis** [comment]
Make sure you follow these instructions if you havent already to install fabric loader and use FL version 0.14.25
https://tlauncher.org/en/how-install-fabric.html
BTW google is your friend and so is the search feature here in github

**Comment by oxbq** [comment]
> Make sure you follow these instructions if you havent already to install fabric loader and use FL version 0.14.25 https://tlauncher.org/en/how-install-fabric.html BTW google is your friend and so is the search feature here in github

I already tried FL 0.14.25, and I was searching but I can't find the solution

**Comment by oxbq** [comment]
> Make sure you follow these instructions if you havent already to install fabric loader and use FL version 0.14.25 https://tlauncher.org/en/how-install-fabric.html BTW google is your friend and so is the search feature here in github

this is the stack-trace

java.lang.NoSuchMethodError: net.fabricmc.loader.FabricLoader.getGameProvider()Lnet/fabricmc/loader/game/GameProvider;
	at me.modmuss50.optifabric.mod.OptifineSetup.getLaunchMinecraftJar(OptifineSetup.java:299)
	at me.modmuss50.optifabric.mod.OptifineSetup.getMinecraftJar(OptifineSetup.java:277)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:84)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at com.chocohead.mm.Plugin$$Lambda$47/180316302.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by oxbq** [comment]
[latest.log](https://github.com/user-attachments/files/15938165/latest.log)
the lastest log

**Comment by Dracconis** [comment]
Wrong optifabric. You need to be using OF 1.13.16 and your error log doesnt show what version of Optifine that you are using which btw should be Optifine HD U G8 for 1.16.5 So change optifabric versions and make sure you are using the optifine version and IF you get any new errors let us know. IF this solves your issue please close the ticket.

**Comment by oxbq** [comment]
> Wrong optifabric. You need to be using OF 1.13.16 and your error log doesnt show what version of Optifine that you are using which btw should be Optifine HD U G8 for 1.16.5 So change optifabric versions and make sure you are using the optifine version and IF you get any new errors let us know. IF this solves your issue please close the ticket.

lol, It was solved, thank you very much

**Comment by Dracconis** [comment]
> > Wrong optifabric. You need to be using OF 1.13.16 and your error log doesnt show what version of Optifine that you are using which btw should be Optifine HD U G8 for 1.16.5 So change optifabric versions and make sure you are using the optifine version and IF you get any new errors let us know. IF this solves your issue please close the ticket.
> 
> lol, It was solved, thank you very much

You're welcome. Please close the ticket.

**Comment by Dracconis** [comment]
> > Wrong optifabric. You need to be using OF 1.13.16 and your error log doesnt show what version of Optifine that you are using which btw should be Optifine HD U G8 for 1.16.5 So change optifabric versions and make sure you are using the optifine version and IF you get any new errors let us know. IF this solves your issue please close the ticket.
> 
> lol, It was solved, thank you very much

Next time you have an issue with a mod and you need to get support here on Github please open a separate ticket instead of hijacking someone else's ticket.
