### ISSUE TITLE
Optifabric 1.16.5 error

### ISSUE THREAD

**Issue by hadimalware** [Chocohead/OptiFabric#1723]
java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.lang.ClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 25 more
![Screenshot_2024-07-04-19-16-07-088_net kdt pojavlaunch firefly debug](https://github.com/Chocohead/OptiFabric/assets/174709529/a89ef494-ee43-497e-9a89-ea2873a9bcb1)

**Comment by Dracconis** [comment]
Use Fabric Loader 0.14.25, also next time please do a search to see if your issue has already been solved. If this solves your issue please close the ticket.

**Comment by hadimalware** [comment]
when I use fabric loader 0.14.25 I experience a black screen

**Comment by Dracconis** [comment]
> when I use fabric loader 0.14.25 I experience a black screen

What launcher are you using?

**Comment by hadimalware** [comment]
when I'm using fabric 0.14.25 I'm get blackscreen

**Comment by hadimalware** [comment]
pojav glow worm

**Comment by Dracconis** [comment]
> pojav glow worm

Ok what mods are you using and their versions?

**Comment by hadimalware** [comment]
optifabric, optifine, mod menu, fabric api,

**Comment by Dracconis** [comment]
> optifabric, optifine, mod menu, fabric api,

Need their versions too not just the name of the mods

**Comment by hadimalware** [comment]
fabric api 0.42.0+1.16
modmenu 1.16.23
optifabric 1.13.16
optifine 1.16.5 hd u g8

**Comment by Dracconis** [comment]
> fabric api 0.42.0+1.16 modmenu 1.16.23 optifabric 1.13.16 optifine 1.16.5 hd u g8

Then you either need to use a different launcher or you need to issue a ticket to the Launcher Dev, because the mods and versions using fabric launcher 0.14.25 is correct and you should have no errors or black screens.

**Comment by hadimalware** [comment]
I feel like the problem is with optifine, but when I try all versions of optifine it doesn't work

**Comment by Dracconis** [comment]
It is an issue with the launcher not supporting optifabric

**Comment by hadimalware** [comment]
but I'm using version 1.20.1 working

**Comment by Dracconis** [comment]
> but I'm using version 1.20.1 working

That maybe true but it isnt for prior versions.
