### ISSUE TITLE
Minecraft 1.16.5 x Fabric-Loader 0.14.25-1.16.5 not working and giving an error

### ISSUE THREAD

**Issue by ir3stless** [Chocohead/OptiFabric#1727]
`java.lang.NoSuchMethodError: net.fabricmc.loader.FabricLoader.getGameProvider()Lnet/fabricmc/loader/game/GameProvider;
	at me.modmuss50.optifabric.mod.OptifineSetup.getLaunchMinecraftJar(OptifineSetup.java:275)
	at me.modmuss50.optifabric.mod.OptifineSetup.getMinecraftJar(OptifineSetup.java:253)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:81)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at com.chocohead.mm.Plugin$$Lambda$50/1925352804.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
`
![image](https://github.com/Chocohead/OptiFabric/assets/98708817/ef6a16f5-d466-4636-bfd4-881badc023d1)

**Comment by Dracconis** [comment]
Mod list and versions

**Comment by ShubhankKumar** [comment]
No open

**Comment by ShubhankKumar** [comment]
> Mod list and versions

Mods 5

**Comment by Dracconis** [comment]
> No open

You need to open your own ticket and stop hijacking other peoples tickets.

**Comment by v08135vansh** [comment]
Use fabric 0.14.25 maybe? I faced a similar issue and downgrading fabric worked
