### ISSUE TITLE
minecraft 1.17.1 error loading optifabric, fabric loader 0.15.11

### ISSUE THREAD

**Issue by turbo7x** [Chocohead/OptiFabric#1731]
java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 25 more
![IMG_٢٠٢٤٠٧٠٧_٠٠٢٨٠٩](https://github.com/Chocohead/OptiFabric/assets/174908703/880e6fe2-4f69-4ac9-af13-ed84adb49edc)

**Comment by turbo7x** [comment]
When I use loader 0.14.25 the game does not work

**Comment by Dracconis** [comment]
> When I use loader 0.14.25 the game does not work

What error do you get?

**Comment by turbo7x** [comment]
> > When I use loader 0.14.25 the game does not work
> 
> What error do you get?

The screen remains black and the game does not start

**Comment by Dracconis** [comment]
> > > When I use loader 0.14.25 the game does not work
> > 
> > 
> > What error do you get?
> 
> The screen remains black and the game does not start

Ok then lets cover the basics:
MC Launcher being used? - 
List of Mods and versions being used? -

**Comment by turbo7x** [comment]
> > > > When I use loader 0.14.25 the game does not work
> > > 
> > > 
> > > What error do you get?
> > 
> > 
> > The screen remains black and the game does not start
> 
> Ok then lets cover the basics: MC Launcher being used? - List of Mods and versions being used? -

tluncher 
the mods 1.17.1
![IMG_٢٠٢٤٠٧٠٨_١٨١٨٠٨](https://github.com/Chocohead/OptiFabric/assets/174908703/e17865be-9084-4abe-8a34-101abe722b85)
![IMG_٢٠٢٤٠٧٠٨_١٨١٨١٩](https://github.com/Chocohead/OptiFabric/assets/174908703/192699ad-1489-451e-9193-0bd83fbe8fef)

**Comment by Dracconis** [comment]
That doesnt show me all the mods you are using. It only lists the 1s that are in game. What I am looking for is something like this:
![image](https://github.com/Chocohead/OptiFabric/assets/28553348/4fd820cf-0468-42e0-aa25-a0261be0b593)

**Comment by turbo7x** [comment]
> That doesnt show me all the mods you are using. It only lists the 1s that are in game. What I am looking for is something like this: ![image](https://private-user-images.githubusercontent.com/28553348/346624899-4fd820cf-0468-42e0-aa25-a0261be0b593.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NjM4NDUsIm5iZiI6MTcyMDQ2MzU0NSwicGF0aCI6Ii8yODU1MzM0OC8zNDY2MjQ4OTktNGZkODIwY2YtMDQ2OC00MmUwLWFhMjUtYTAyNjFiZTBiNTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDE4MzIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MjgxMjEzYTg0ZjhkNzRhZmEwMTgyNDczNTFiYWQ4N2Y1NTg2YWQzMTdlMDg5MzgxZDVlYjU0ZTVmYjRjNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NnGghMKH7IgMdFxdRkUbT-JkZPUpkKntqQMVcNfS0tY)

These are the same mods. I took them from my phone because I don't have a computer at the moment 
![Screenshot_20240708_213108_ru zdevs zarchiver_edit_28346585265986](https://github.com/Chocohead/OptiFabric/assets/174908703/bcc86e1c-9778-4a9a-8e31-c588a8df38f0)
![Screenshot_20240708_213130](https://github.com/Chocohead/OptiFabric/assets/174908703/67ab6f0e-a0c8-4572-8ef1-993f58b83893)

**Comment by Dracconis** [comment]
Ok well I dont see opftifabric or Optifine in the list of mods. Also you cant use Architectury Mod with optifabric in this version of MC

**Comment by turbo7x** [comment]
> Ok well I dont see opftifabric or Optifine in the list of mods. Also you cant use Architectury Mod with optifabric in this version of MC

I removed them when I found the problem so I could play 
If I remove the architectury mod, will Optifine work?

**Comment by turbo7x** [comment]
> Ok well I dont see opftifabric or Optifine in the list of mods. Also you cant use Architectury Mod with optifabric in this version of MC

Thank you very much. I already deleted the mod and the game worked fine

**Comment by Dracconis** [comment]
> > Ok well I dont see opftifabric or Optifine in the list of mods. Also you cant use Architectury Mod with optifabric in this version of MC
> 
> Thank you very much. I already deleted the mod and the game worked fine

You're welcome and glad you got it working again.
