### ISSUE TITLE
There was an error loading OptiFabric. Failed To Load OptiFine error on 1.18.2.

### ISSUE THREAD

**Issue by Mistyre9309** [Chocohead/OptiFabric#1751]
I know it is a problem with OptiFabric, because whenever I remove it, it works, but optifine doesn't.

I am using OptiFabric version 1.13.16, OptiFine_1.18.2_HD_U_H7, and fabric loader 0.16.0.

Here is my mods list : 
Amplified_Nether_v1.1.1
BetterThirdPerson-Fabric-1.18.2-1.8.1
cloth-config-6.5.116-fabric
CreativeCore_FABRIC_v2.6.12_mc1.18.2
eating-animation-1.8
effective-1.2.1
fabric-api-0.59.1+1.18.2
modmenu-3.2.5
notenoughanimations-fabric-1.7.4-mc1.18.2
optifabric-1.13.16
OptiFine_1.18.2_HD_U_H7
PresenceFootsteps-1.5.1
soundphysics-fabric-1.18.2-1.0.6
starlight-1.0.2+fabric.89b8d9f
visuality-0.4.3

Here is my stack-trace : 
        java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 25 more

**Comment by Dracconis** [comment]
Your problem is because you are using the wrong Fabric API. If you were using Fabric API 0.76.0 then you wouldn't have an issue while using Fabric Loader 0.14.25

**Comment by Mistyre9309** [comment]
I tried this API with with both 0.16.0, and 0.14.25. And it still doesn't work.

Here is my new mods list : 
Amplified_Nether_v1.1.1
BetterThirdPerson-Fabric-1.18.2-1.8.1
cloth-config-6.5.116-fabric
CreativeCore_FABRIC_v2.6.12_mc1.18.2
eating-animation-1.8
effective-1.2.1
fabric-api-0.76.0+1.18.2
modmenu-3.2.5
notenoughanimations-fabric-1.7.4-mc1.18.2
optifabric-1.13.16
OptiFine_1.18.2_HD_U_H7
PresenceFootsteps-1.5.1
soundphysics-fabric-1.18.2-1.0.6
starlight-1.0.2+fabric.89b8d9f
visuality-0.4.3

**Comment by Dracconis** [comment]
Then only try it with the Fabric Loader, optifine, Fabric API, and optifabric. IF that works then add a couple more mods back in and try again. I think you may be getting a mod conflict.

**Comment by Mistyre9309** [comment]
I did, the same problem occurs, could you just recommend some alternatives please?

**Comment by Dracconis** [comment]
> I did, the same problem occurs, could you just recommend some alternatives please?

What Launcher are you using?

**Comment by Mistyre9309** [comment]
Tlauncher

**Comment by Dracconis** [comment]
Did you try this first?
https://tlauncher.org/en/how-install-fabric.html

**Comment by Mistyre9309** [comment]
I just selected fabric 1.18.2 and installed it from the versions list.

**Comment by Dracconis** [comment]
> I just selected fabric 1.18.2 and installed it from the versions list.

That is where you went wrong. As I said you need to use fabric Loader 0.14.25, Fabric API 0.76.0, Optifabric 1.13.16, OptiFine 1.18.2 HD U H9. Those 4 work just fine. IF just those 4 do not work with the TLauncher then you need to speak to the Dev of the TLauncher or find a Launcher Alternative to use.

**Comment by Mistyre9309** [comment]
Are you sure, because tlauncher is the same thing as a normal launcher, just with cracked accounts.

**Comment by Dracconis** [comment]
> Are you sure, because tlauncher is the same thing as a normal launcher, just with cracked accounts.

Yes I am very sure. There are a few documents online that explain the TLauncher and Optifabric. I believe the Dev said something about not working on it or something like that.

**Comment by Mistyre9309** [comment]
oh, okay, thank you very much.

**Comment by Dracconis** [comment]
You're welcome. I wish you the best of luck.
