### ISSUE TITLE
why

### ISSUE THREAD

**Issue by sperma2131** [Chocohead/OptiFabric#1760]
java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 25 more

**Comment by Dracconis** [comment]
Use Fabric Loader 0.14.25, also next time please do a search to see if your issue has already been solved. If this solves your issue please close the ticket.

**Comment by sperma2131** [comment]
i got this:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'fabric-renderer-indigo'!

**Comment by Dracconis** [comment]
Need full mod list with their versions as well as launcher you are using.

**Comment by sperma2131** [comment]
minecraft luncher
mods: 1.18.2 version
betterpvp
elytraswapper
inventoryhud
mousetweaks
optifabric
optifine
hd u h7
oesca
player hearth indiactors
shulker box tolltip
slot lock
smothing swapp
view model
wurst

**Comment by sperma2131** [comment]
and fabric api

**Comment by Dracconis** [comment]
Need the mods versions too

**Comment by sperma2131** [comment]
discord : zidane9068 
i give you screanshot

**Comment by Dracconis** [comment]
> discord : zidane9068 i give you screanshot

You can do screenshots here too just like this:
![image](https://github.com/user-attachments/assets/f0a20b97-b0cb-4d8c-874e-961a1c2a8dfc)

**Comment by sperma2131** [comment]
![Uploading obraz_2024-07-29_213747366.png…]()

**Comment by sperma2131** [comment]
!
![obraz_2024-07-29_213825505](https://github.com/user-attachments/assets/ad288f7c-9461-45e3-b981-335d5135ce79)

**Comment by Dracconis** [comment]
I dont see optifabric or optifine in your list of mods being used.

**Comment by sperma2131** [comment]
![image](https://github.com/user-attachments/assets/8f20aea7-c7f8-49ec-87e1-fc622ddceb73)

**Comment by Dracconis** [comment]
Downgrade your Fabric API to 0.76.0. Make sure you are using the Fabric Loader 0.14.25, Fabric API, Optifabric 1.13.16, Optifine H9 only this time and see if it launches. IF it launches then add half of the mods back in and try again. Keep doing that until either it launches just fine or you get an error.
