### ISSUE TITLE
OptiFabric Hypixel Issues

### ISSUE THREAD

**Issue by GigabyteJplayz** [Chocohead/OptiFabric#177]
Whenever I try to log in using optifabric and optifine on Hypixel, I get kicked to Limbo with the error "An exception occurred in your connection, so you have been routed to limbo!" This doesn't happen on any other servers, here is the fatal error in the Minecraft log:

10:38:11.974
net.minecraft.class_1255
main
Error executing task on Client
java.lang.NullPointerException
	at net.minecraft.class_269.method_1191(class_269.java:199)
	at net.minecraft.class_634.method_11099(class_634.java:2156)
	at net.minecraft.class_2755.method_11860(class_2755.java:122)
	at net.minecraft.class_2755.method_11054(class_2755.java:16)
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:34)
	at net.minecraft.class_2600$$Lambda$4073/1196213240.run(Unknown Source)
	at net.minecraft.class_1255.method_18859(class_1255.java:172)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:134)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1015)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
10:38:11.974
net.minecraft.class_1255
main
Error executing task on Client
java.lang.NullPointerException
	at net.minecraft.class_269.method_1191(class_269.java:199)
	at net.minecraft.class_634.method_11099(class_634.java:2156)
	at net.minecraft.class_2755.method_11860(class_2755.java:122)
	at net.minecraft.class_2755.method_11054(class_2755.java:16)
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:34)
	at net.minecraft.class_2600$$Lambda$4073/1196213240.run(Unknown Source)
	at net.minecraft.class_1255.method_18859(class_1255.java:172)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:134)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1015)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
10:38:11.974
net.minecraft.class_1255
main
Error executing task on Client
java.lang.NullPointerException
	at net.minecraft.class_269.method_1191(class_269.java:199)
	at net.minecraft.class_634.method_11099(class_634.java:2156)
	at net.minecraft.class_2755.method_11860(class_2755.java:122)
	at net.minecraft.class_2755.method_11054(class_2755.java:16)
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:34)
	at net.minecraft.class_2600$$Lambda$4073/1196213240.run(Unknown Source)
	at net.minecraft.class_1255.method_18859(class_1255.java:172)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:134)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1015)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

**Comment by GigabyteJplayz** [comment]
issue was not OptiFabric
