### ISSUE TITLE
World Loading Screen Stuck At 100%

### ISSUE THREAD

**Issue by StarbrandEmerge** [Chocohead/OptiFabric#1780]
I only have the fabric api, optifine and optifabric, in the logs the same text repeats a lot
"java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_2935()" because "this.field_3699" is null
	at net.minecraft.class_634.method_38539(class_634.java:661) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11128(class_634.java:656) ~[client-intermediary.jar:?]
	at net.minecraft.class_2672.method_11528(class_2672.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_2672.method_11054(class_2672.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:40) ~[client-intermediary.jar:?]
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:198) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:163) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:140) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1085) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.14.25.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.25.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.25.jar:?]"

**Comment by Dracconis** [comment]
Which MC Launcher are you using and which MC version?

**Comment by StarbrandEmerge** [comment]
> Which MC Launcher are you using and which MC version?
The default (premium) and 1.18.2

**Comment by Dracconis** [comment]
> > Which MC Launcher are you using and which MC version?
> > The default (premium) and 1.18.2
Need these mods versions fabric api, optifine and optifabric, as well as the Fabric Loader version you are using.

**Comment by StarbrandEmerge** [comment]
> > > Which MC Launcher are you using and which MC version?
> > > The default (premium) and 1.18.2
> > > Need these mods versions fabric api, optifine and optifabric, as well as the Fabric Loader version you are using.

Fabric api 0.76.0
optifabric 1.13.0
optifine 1.18.2_HD_U_H6
the fabric loader its 0.14.25 (idk if theres more versions of the installer but the installer is 1.0.1

**Comment by Dracconis** [comment]
> > > > Which MC Launcher are you using and which MC version?
> > > > The default (premium) and 1.18.2
> > > > Need these mods versions fabric api, optifine and optifabric, as well as the Fabric Loader version you are using.
> 
> Fabric api 0.76.0 optifabric 1.13.0 optifine 1.18.2_HD_U_H6 the fabric loader its 0.14.25 (idk if theres more versions of the installer but the installer is 1.0.1

Update your Optifabric to version 1.13.16

**Comment by StarbrandEmerge** [comment]
> > > > > Which MC Launcher are you using and which MC version?
> > > > > The default (premium) and 1.18.2
> > > > > Need these mods versions fabric api, optifine and optifabric, as well as the Fabric Loader version you are using.
> > 
> > 
> > Fabric api 0.76.0 optifabric 1.13.0 optifine 1.18.2_HD_U_H6 the fabric loader its 0.14.25 (idk if theres more versions of the installer but the installer is 1.0.1
> 
> Update your Optifabric to version 1.13.16

i just did that, it worked, idk why it was the 1.13.0 because i always click on the most recent one, anyways, thank you!

**Comment by Dracconis** [comment]
> > > > > > Which MC Launcher are you using and which MC version?
> > > > > > The default (premium) and 1.18.2
> > > > > > Need these mods versions fabric api, optifine and optifabric, as well as the Fabric Loader version you are using.
> > > 
> > > 
> > > Fabric api 0.76.0 optifabric 1.13.0 optifine 1.18.2_HD_U_H6 the fabric loader its 0.14.25 (idk if theres more versions of the installer but the installer is 1.0.1
> > 
> > 
> > Update your Optifabric to version 1.13.16
> 
> i just did that, it worked, idk why it was the 1.13.0 because i always click on the most recent one, anyways, thank you!

You're welcome and thank you for closing your ticket.
