### ISSUE TITLE
WHAT HELP ME

### ISSUE THREAD

**Issue by dddddddddd-jj** [Chocohead/OptiFabric#1799]
java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at com.chocohead.mm.Plugin$$Lambda$54/1244867001.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:877)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more

**Comment by Dracconis** [comment]
Use Fabric Loader 0.14.25, also next time please do a search to see if your issue has already been solved. If this solves your issue please close the ticket.

**Comment by dddddddddd-jj** [comment]
it didnt work i got error 1

**Comment by Dracconis** [comment]
> it didnt work i got error 1

Then lets cover the basics. MC Launcher being used? All of your mods AND their versions?

**Comment by dddddddddd-jj** [comment]
a minecraft launcher is being used, here are all my mods: (also im using fabrc 1.16.5)

fabric-api-0.42.0+1.16
fabric-tickratechanger-mod-1.0.0 
KronHUD-1.1.1-beta-1.16.2+
optifabric-1.13.16 
OptiFine_1.16.5_HD_U_G8
replaymod-1.16.4-2.6.18

**Comment by Dracconis** [comment]
On the MC Launcher before you click the 'play' button, what profile do you have set?
Also, what happens when you remove the replay mod from the list?

**Comment by dddddddddd-jj** [comment]
what do you mean by what profile is set? also it runs without replaymod

**Comment by Dracconis** [comment]
Ok then if it runs without replay mod that is your problem
This is what I mean by profile (the red box):
![image](https://github.com/user-attachments/assets/b904ca44-490f-41e0-a648-b068a7c4b540)

**Comment by Dracconis** [comment]
> what do you mean by what profile is set? also it runs without replaymod

If this resolves your issue please close this ticket.
