### ISSUE TITLE
Failed to load optifine

### ISSUE THREAD

**Issue by PhucGT** [Chocohead/OptiFabric#1800]
15:44:28.073
launcher
main
Using default game log configuration client-1.12.xml (outputs XML)
15:44:29.302
FabricLoader/GameProvider
main
Loading Minecraft 1.18.1 with Fabric Loader 0.16.2
15:44:29.446
FabricLoader
main
Loading 55 mods:
	- fabric 0.46.6+1.18
	   |-- fabric-api-base 0.4.2+d7c144a865
	   |-- fabric-api-lookup-api-v1 1.5.3+d7c144a865
	   |-- fabric-biome-api-v1 6.0.2+d7c144a865
	   |-- fabric-blockrenderlayer-v1 1.1.10+3ac43d9565
	   |-- fabric-command-api-v1 1.1.7+d7c144a865
	   |-- fabric-commands-v0 0.2.6+b4f4f6cd65
	   |-- fabric-containers-v0 0.1.19+d7c144a865
	   |-- fabric-content-registries-v0 0.4.9+d7c144a865
	   |-- fabric-crash-report-info-v1 0.1.9+3ac43d9565
	   |-- fabric-dimensions-v1 2.1.10+a1d9bbf565
	   |-- fabric-entity-events-v1 1.4.6+d7c144a865
	   |-- fabric-events-interaction-v0 0.4.17+d7c144a865
	   |-- fabric-events-lifecycle-v0 0.2.9+d7c144a865
	   |-- fabric-game-rule-api-v1 1.0.11+d7c144a865
	   |-- fabric-item-api-v1 1.3.1+691a79b565
	   |-- fabric-item-groups-v0 0.3.7+3ac43d9565
	   |-- fabric-key-binding-api-v1 1.0.9+d7c144a865
	   |-- fabric-keybindings-v0 0.2.7+b4f4f6cd65
	   |-- fabric-lifecycle-events-v1 1.4.13+713c266865
	   |-- fabric-loot-tables-v1 1.0.9+d7c144a865
	   |-- fabric-mining-level-api-v1 1.0.7+d7c144a865
	   |-- fabric-mining-levels-v0 0.1.12+b4f4f6cd65
	   |-- fabric-models-v0 0.3.4+d7c144a865
	   |-- fabric-networking-api-v1 1.0.19+d7c144a865
	   |-- fabric-networking-v0 0.3.6+b4f4f6cd65
	   |-- fabric-object-builder-api-v1 1.11.5+737332ce65
	   |-- fabric-object-builders-v0 0.7.13+d7c144a865
	   |-- fabric-particles-v1 0.2.10+526dc1ac65
	   |-- fabric-registry-sync-v0 0.9.2+ad01bfbd65
	   |-- fabric-renderer-api-v1 0.4.11+b0b66fc365
	   |-- fabric-renderer-indigo 0.4.15+6825030165
	   |-- fabric-renderer-registries-v1 3.2.10+b4f4f6cd65
	   |-- fabric-rendering-data-attachment-v1 0.3.5+d7c144a865
	   |-- fabric-rendering-fluids-v1 0.1.19+3ac43d9565
	   |-- fabric-rendering-v0 1.1.12+b4f4f6cd65
	   |-- fabric-rendering-v1 1.10.6+713c266865
	   |-- fabric-resource-conditions-api-v1 1.0.2+d7c144a865
	   |-- fabric-resource-loader-v0 0.4.15+8906aafd65
	   |-- fabric-screen-api-v1 1.0.8+d7c144a865
	   |-- fabric-screen-handler-api-v1 1.1.12+d7c144a865
	   |-- fabric-structure-api-v1 2.1.3+d7c144a865
	   |-- fabric-tag-extensions-v0 1.2.9+d7c144a865
	   |-- fabric-textures-v0 1.0.10+3ac43d9565
	   |-- fabric-tool-attribute-api-v1 1.3.9+fb3b57b465
	   \-- fabric-transfer-api-v1 1.5.10+c329913d65
	- fabricloader 0.16.2
	   \-- mixinextras 0.4.1
	- java 17
	- minecraft 1.18.1
	- modmenu 3.0.1
	- optifabric 1.13.16
	   \-- mm 2.3
	- phosphor 0.8.1
	- replaymod 1.18.1-2.6.18
15:44:29.447
FabricLoader
main
Found 1 non-fabric mod:
	- 1.18.1-OptiFine_HD_U_H4.jar
15:44:38.800
net.fabricmc.fabric.impl.client.indigo.Indigo
Render thread
[Indigo] Compatibility mode enabled.
15:44:40.174
net.minecraft.class_310
Render thread
Backend library: LWJGL version 3.2.2 build 10
15:44:45.040
com.mojang.text2speech.NarratorWindows
Render thread
Narrator library for x64 successfully loaded
15:44:45.384
net.minecraft.class_3304
Render thread
Reloading ResourceManager: Default, Fabric Mods (Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Structure API (v1), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric Transfer API (v1), Fabric Loader, Manningham Mills, Mod Menu, OptiFabric, Phosphor, Replay Mod), replaymod_lang
15:44:49.629
net.minecraft.class_4225
Render thread
OpenAL initialized on device OpenAL Soft on Headphones (OneOdio A70 Stereo)
15:44:49.632
net.minecraft.class_1140
Render thread
Sound engine started
15:44:49.873
net.minecraft.class_1059
Render thread
Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
15:44:49.881
net.minecraft.class_1059
Render thread
Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
15:44:49.883
net.minecraft.class_1059
Render thread
Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
15:44:49.884
net.minecraft.class_1059
Render thread
Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
15:44:49.885
net.minecraft.class_1059
Render thread
Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
15:44:49.885
net.minecraft.class_1059
Render thread
Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
15:44:49.886
net.minecraft.class_1059
Render thread
Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
15:44:51.841
net.minecraft.class_1059
Render thread
Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
15:44:51.844
net.minecraft.class_1059
Render thread
Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
15:44:51.844
net.minecraft.class_1059
Render thread
Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas

**Comment by PhucGT** [comment]
java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:877)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 25 more

**Comment by Dracconis** [comment]
Use Fabric Loader 0.14.25 and update Optifine to H6, also next time please do a search to see if your issue has already been solved. If this solves your issue please close the ticket.

**Comment by PhucGT** [comment]
it still not working

**Comment by Dracconis** [comment]
If it is not working then what error are you getting now?
