### ISSUE TITLE
Minecraft crash 1.20.4

### ISSUE THREAD

**Issue by ma-tteo** [Chocohead/OptiFabric#1810]
mods:
- alternate-current 1.9.0
	- architectury 11.1.17
	- badoptimizations 2.1.4
	- betterbeds 1.3.0
	- betterbiomeblend 1.4.2
	- bettergrass 1.1.0+fabric.1.20.1
	- blocky-bubbles 1.2.0+1.20.4
	- chunky 1.3.146
	- clean-debug 0.4.6
	- clientsidenoteblocks 2.7
	- cloth-config 13.0.121
	   \-- cloth-basic-math 0.6.1
	- cullleaves 3.3.0
	- debugify 1.20.4+1.1
	- entityculling 1.7.0
	- exordium 1.2.1
	- fabric-api 0.97.2+1.20.4
	   |-- fabric-api-base 0.4.37+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.50+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.17+78d798af4f
	   |-- fabric-block-api-v1 1.0.17+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.5+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.47+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.8+78d798af4f
	   |-- fabric-command-api-v1 1.2.42+f71b366f4f
	   |-- fabric-command-api-v2 2.2.21+78d798af4f
	   |-- fabric-commands-v0 0.2.59+df3654b34f
	   |-- fabric-containers-v0 0.1.88+df3654b34f
	   |-- fabric-content-registries-v0 5.0.16+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.11+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.24+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.5+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.6+5c0133444f
	   |-- fabric-dimensions-v1 2.1.63+6605d1a84f
	   |-- fabric-entity-events-v1 1.6.2+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.2+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.75+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.47+78d798af4f
	   |-- fabric-item-api-v1 2.3.0+bcdd12964f
	   |-- fabric-item-group-api-v1 4.0.27+ee30b13a4f
	   |-- fabric-key-binding-api-v1 1.0.42+78d798af4f
	   |-- fabric-keybindings-v0 0.2.40+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.1+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.10+78d798af4f
	   |-- fabric-message-api-v1 6.0.6+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.66+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.9+78d798af4f
	   |-- fabric-models-v0 0.4.8+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.9+6abb6a4b4f
	   |-- fabric-object-builder-api-v1 13.1.0+dba1195c4f
	   |-- fabric-particles-v1 1.1.8+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.22+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.21+ee30b13a4f
	   |-- fabric-renderer-api-v1 3.2.5+78d798af4f
	   |-- fabric-renderer-indigo 1.5.6+d331d3144f
	   |-- fabric-renderer-registries-v1 3.2.54+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.43+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.2+e761c6694f
	   |-- fabric-rendering-v0 1.1.57+df3654b34f
	   |-- fabric-rendering-v1 3.2.1+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.15+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.21+ee30b13a4f
	   |-- fabric-screen-api-v1 2.0.18+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.57+78d798af4f
	   |-- fabric-sound-api-v1 1.0.18+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.12+90f2d7b14f
	   \-- fabric-transitive-access-wideners-v1 5.0.15+78d798af4f
	- fabric-language-kotlin 1.12.1+kotlin.2.0.20
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.20
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.25.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.1
	   |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.5.3
	   |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.5.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.1
	- fabricloader 0.16.3
	   \-- mixinextras 0.4.1
	- fastchest 1.5+1.20.2
	- faster-random 5.1.0
	- fastipping 1.0.4
	- fastitems 1.0.0-1.20.3
	- fastpaintings 1.20.4-1.2.9
	- fastquit 3.0.0+1.20.4
	- ferritecore 6.0.3
	- feytweaks 1.20.4-1.2.8
	- forgeconfigapiport 20.4.3
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- fpsreducer 1.20.4-2.7
	- fzzy_config 0.3.7+1.20.4
	   |-- blue_endless_jankson 1.2.3
	   \-- net_peanuuutz_tomlkt_tomlkt-jvm 0.3.7
	- icterine 1.3.0
	- idletweaks 1.0.8
	- ijmtweaks 1.4.0+1.20
	- java 17
	- krypton 0.2.6
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- ksyxis 1.3.2
	- languagereload 1.6.1+1.20.4
	- lazy-language-loader 0.3.5
	- lazydfu 0.1.3
	- leavesbegone 20.4.1
	- letmedespawn 1.2.1
	- memoryleakfix 1.1.5
	- midnightlib 1.5.3
	- minecraft 1.20.4
	- modelfix 1.14
	- modernfix 5.17.0+mc1.20.4
	- modernui 3.10.1.5
	   |-- com_github_ben-manes_caffeine_caffeine 3.1.7
	   |-- com_vladsch_flexmark_flexmark 0.64.8
	   |-- com_vladsch_flexmark_flexmark-util-ast 0.64.8
	   |-- com_vladsch_flexmark_flexmark-util-builder 0.64.8
	   |-- com_vladsch_flexmark_flexmark-util-collection 0.64.8
	   |-- com_vladsch_flexmark_flexmark-util-data 0.64.8
	   |-- com_vladsch_flexmark_flexmark-util-dependency 0.64.8
	   |-- com_vladsch_flexmark_flexmark-util-format 0.64.8
	   |-- com_vladsch_flexmark_flexmark-util-html 0.64.8
	   |-- com_vladsch_flexmark_flexmark-util-misc 0.64.8
	   |-- com_vladsch_flexmark_flexmark-util-sequence 0.64.8
	   \-- com_vladsch_flexmark_flexmark-util-visitor 0.64.8
	- modmenu 9.2.0
	- moonlight 1.20.4-2.10.3
	- moreculling 1.20.4-0.24.0
	   \-- mixinsquared 0.1.1
	- noisium 2.3.0+mc1.20.2-1.20.4
	- optifabric 1.14.3
	   |-- mm 2.3
	   \-- optifabric-libs 1.14.3
	- packetfixer 1.4.1
	- particle_core 0.2.4+1.20.4
	   \-- conditional-mixin 0.5.1
	- placeholder-api 2.4.0-pre.1+1.20.4
	- purpurclient 1.20.4-31
	   |-- com_google_guava_guava 31.1-jre
	   |-- com_typesafe_config 1.4.2
	   |-- io_leangen_geantyref_geantyref 1.3.12
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- puzzleslib 20.4.52
	- railoptimization 1.0
	- resourcepackchecker 1.20.4-1.2.2
	- rrls 4.0.3+mc1.20.4-fabric
	- servercore 1.5.0+1.20.4
	   |-- fabric-permissions-api-v0 0.3-SNAPSHOT
	   |-- org_yaml_snakeyaml 2.2
	   |-- space_arim_dazzleconf_dazzleconf-core 1.3.0-M2
	   \-- space_arim_dazzleconf_dazzleconf-ext-snakeyaml 1.3.0-M2
	- smoothmenu 1.1.0
	- smoothscrollingrefurbished 1.1.2
	- staaaaaaaaaaaack 1.20.4-1.5-72
	   \-- fiber 0.23.0-2
	- starlight 1.1.3+fabric.f5dcd1a
	- threadtweak 1.20.4-0.1.2
	- tooltipfix 1.1.1-1.20
	- toomanyplayers 1.20.4-1.1.5
	   \-- libgui 9.2.2+1.20.2
	        |-- jankson 6.0.0+j1.2.3
	        \-- libninepatch 1.2.0
	- vanillafix 1.2.1-beta
	- videotape 1.0.0
	- yet_another_config_lib_v3 3.5.0+1.20.4-fabric
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1

crash report (log):
[17:40:00] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.16.3
[17:40:00] [main/INFO]: Loading 177 mods:
	- alternate-current 1.9.0
	- architectury 11.1.17
	- badoptimizations 2.1.4
	- betterbeds 1.3.0
	- betterbiomeblend 1.4.2
	- bettergrass 1.1.0+fabric.1.20.1
	- blocky-bubbles 1.2.0+1.20.4
	- chunky 1.3.146
	- clean-debug 0.4.6
	- clientsidenoteblocks 2.7
	- cloth-config 13.0.121
	   \-- cloth-basic-math 0.6.1
	- cullleaves 3.3.0
	- debugify 1.20.4+1.1
	- entityculling 1.7.0
	- exordium 1.2.1
	- fabric-api 0.97.2+1.20.4
	   |-- fabric-api-base 0.4.37+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.50+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.17+78d798af4f
	   |-- fabric-block-api-v1 1.0.17+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.5+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.47+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.8+78d798af4f
	   |-- fabric-command-api-v1 1.2.42+f71b366f4f
	   |-- fabric-command-api-v2 2.2.21+78d798af4f
	   |-- fabric-commands-v0 0.2.59+df3654b34f
	   |-- fabric-containers-v0 0.1.88+df3654b34f
	   |-- fabric-content-registries-v0 5.0.16+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.11+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.24+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.5+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.6+5c0133444f
	   |-- fabric-dimensions-v1 2.1.63+6605d1a84f
	   |-- fabric-entity-events-v1 1.6.2+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.2+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.75+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.47+78d798af4f
	   |-- fabric-item-api-v1 2.3.0+bcdd12964f
	   |-- fabric-item-group-api-v1 4.0.27+ee30b13a4f
	   |-- fabric-key-binding-api-v1 1.0.42+78d798af4f
	   |-- fabric-keybindings-v0 0.2.40+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.1+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.10+78d798af4f
	   |-- fabric-message-api-v1 6.0.6+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.66+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.9+78d798af4f
	   |-- fabric-models-v0 0.4.8+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.9+6abb6a4b4f
	   |-- fabric-object-builder-api-v1 13.1.0+dba1195c4f
	   |-- fabric-particles-v1 1.1.8+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.22+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.21+ee30b13a4f
	   |-- fabric-renderer-api-v1 3.2.5+78d798af4f
	   |-- fabric-renderer-indigo 1.5.6+d331d3144f
	   |-- fabric-renderer-registries-v1 3.2.54+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.43+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.2+e761c6694f
	   |-- fabric-rendering-v0 1.1.57+df3654b34f
	   |-- fabric-rendering-v1 3.2.1+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.15+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.21+ee30b13a4f
	   |-- fabric-screen-api-v1 2.0.18+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.57+78d798af4f
	   |-- fabric-sound-api-v1 1.0.18+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.12+90f2d7b14f
	   \-- fabric-transitive-access-wideners-v1 5.0.15+78d798af4f
	- fabric-language-kotlin 1.12.1+kotlin.2.0.20
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.20
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.25.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.1
	   |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.5.3
	   |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.5.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.1
	- fabricloader 0.16.3
	   \-- mixinextras 0.4.1
	- fastchest 1.5+1.20.2
	- faster-random 5.1.0
	- fastipping 1.0.4
	- fastitems 1.0.0-1.20.3
	- fastpaintings 1.20.4-1.2.9
	- fastquit 3.0.0+1.20.4
	- ferritecore 6.0.3
	- feytweaks 1.20.4-1.2.8
	- forgeconfigapiport 20.4.3
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- fpsreducer 1.20.4-2.7
	- fzzy_config 0.3.7+1.20.4
	   |-- blue_endless_jankson 1.2.3
	   \-- net_peanuuutz_tomlkt_tomlkt-jvm 0.3.7
	- icterine 1.3.0
	- idletweaks 1.0.8
	- ijmtweaks 1.4.0+1.20
	- java 17
	- krypton 0.2.6
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- ksyxis 1.3.2
	- languagereload 1.6.1+1.20.4
	- lazy-language-loader 0.3.5
	- lazydfu 0.1.3
	- leavesbegone 20.4.1
	- letmedespawn 1.2.1
	- memoryleakfix 1.1.5
	- midnightlib 1.5.3
	- minecraft 1.20.4
	- modelfix 1.14
	- modernfix 5.17.0+mc1.20.4
	- modernui 3.10.1.5
	   |-- com_github_ben-manes_caffeine_caffeine 3.1.7
	   |-- com_vladsch_flexmark_flexmark 0.64.8
	   |-- com_vladsch_flexmark_flexmark-util-ast 0.64.8
	   |-- com_vladsch_flexmark_flexmark-util-builder 0.64.8
	   |-- com_vladsch_flexmark_flexmark-util-collection 0.64.8
	   |-- com_vladsch_flexmark_flexmark-util-data 0.64.8
	   |-- com_vladsch_flexmark_flexmark-util-dependency 0.64.8
	   |-- com_vladsch_flexmark_flexmark-util-format 0.64.8
	   |-- com_vladsch_flexmark_flexmark-util-html 0.64.8
	   |-- com_vladsch_flexmark_flexmark-util-misc 0.64.8
	   |-- com_vladsch_flexmark_flexmark-util-sequence 0.64.8
	   \-- com_vladsch_flexmark_flexmark-util-visitor 0.64.8
	- modmenu 9.2.0
	- moonlight 1.20.4-2.10.3
	- moreculling 1.20.4-0.24.0
	   \-- mixinsquared 0.1.1
	- noisium 2.3.0+mc1.20.2-1.20.4
	- optifabric 1.14.3
	   |-- mm 2.3
	   \-- optifabric-libs 1.14.3
	- packetfixer 1.4.1
	- particle_core 0.2.4+1.20.4
	   \-- conditional-mixin 0.5.1
	- placeholder-api 2.4.0-pre.1+1.20.4
	- purpurclient 1.20.4-31
	   |-- com_google_guava_guava 31.1-jre
	   |-- com_typesafe_config 1.4.2
	   |-- io_leangen_geantyref_geantyref 1.3.12
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- puzzleslib 20.4.52
	- railoptimization 1.0
	- resourcepackchecker 1.20.4-1.2.2
	- rrls 4.0.3+mc1.20.4-fabric
	- servercore 1.5.0+1.20.4
	   |-- fabric-permissions-api-v0 0.3-SNAPSHOT
	   |-- org_yaml_snakeyaml 2.2
	   |-- space_arim_dazzleconf_dazzleconf-core 1.3.0-M2
	   \-- space_arim_dazzleconf_dazzleconf-ext-snakeyaml 1.3.0-M2
	- smoothmenu 1.1.0
	- smoothscrollingrefurbished 1.1.2
	- staaaaaaaaaaaack 1.20.4-1.5-72
	   \-- fiber 0.23.0-2
	- starlight 1.1.3+fabric.f5dcd1a
	- threadtweak 1.20.4-0.1.2
	- tooltipfix 1.1.1-1.20
	- toomanyplayers 1.20.4-1.1.5
	   \-- libgui 9.2.2+1.20.2
	        |-- jankson 6.0.0+j1.2.3
	        \-- libninepatch 1.2.0
	- vanillafix 1.2.1-beta
	- videotape 1.0.0
	- yet_another_config_lib_v3 3.5.0+1.20.4-fabric
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
[17:40:00] [main/WARN]: Found 1 non-fabric mod:
	- OptiFine_1.20.4_HD_U_I7.jar
[17:40:01] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/C:/Users/Matteo/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.15.2+mixin.0.8.7/sponge-mixin-0.15.2+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[17:40:01] [main/INFO]: Compatibility level set to JAVA_16
[17:40:01] [main/INFO]: Compatibility level set to JAVA_17
[17:40:02] [main/INFO]: Loading config from C:\Users\Matteo\AppData\Roaming\.minecraft\config\badoptimizations.txt
[17:40:02] [main/INFO]: Config version: 3
[17:40:02] [main/INFO]: BadOptimizations config dump:
[17:40:02] [main/INFO]: enable_toast_optimizations: true
[17:40:02] [main/INFO]: ignore_mod_incompatibilities: false
[17:40:02] [main/INFO]: lightmap_time_change_needed_for_update: 80
[17:40:02] [main/INFO]: enable_lightmap_caching: true
[17:40:02] [main/INFO]: enable_particle_manager_optimization: true
[17:40:02] [main/INFO]: enable_entity_renderer_caching: true
[17:40:02] [main/INFO]: log_config: true
[17:40:02] [main/INFO]: enable_remove_redundant_fov_calculations: true
[17:40:02] [main/INFO]: config_version: 3
[17:40:02] [main/INFO]: enable_sky_angle_caching_in_worldrenderer: true
[17:40:02] [main/INFO]: enable_block_entity_renderer_caching: true
[17:40:02] [main/INFO]: skycolor_time_change_needed_for_update: 3
[17:40:02] [main/INFO]: enable_entity_flag_caching: true
[17:40:02] [main/INFO]: enable_debug_renderer_disable_if_not_needed: true
[17:40:02] [main/INFO]: enable_sky_color_caching: true
[17:40:02] [main/INFO]: enable_remove_tutorial_if_not_demo: true
[17:40:02] [main/INFO]: show_f3_text: true
[17:40:02] [main/INFO]: Preloading Debugify
[17:40:02] [main/WARN]: Reference map 'fastpaintings-fabric-refmap.json' for fastpaintings.mixins.json could not be read. If this is a development environment you can ignore this message
[17:40:03] [main/WARN]: Reference map 'ForgeConfigAPIPort-Common-refmap.json' for forgeconfigapiport.common.mixins.json could not be read. If this is a development environment you can ignore this message
[17:40:03] [main/INFO]: OptiFine was NOT detected.
[17:40:03] [main/INFO]: OptiFabric was detected.
[17:40:03] [main/WARN]: Reference map 'leavesbegone.fabric.refmap.json' for leavesbegone.fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[17:40:03] [main/WARN]: Reference map 'memoryleakfix-fabric-1.17+-fabric-refmap.json' for memoryleakfix-fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[17:40:03] [main/INFO]: Loaded configuration file for ModernFix 5.17.0+mc1.20.4: 54 options available, 1 override(s) found
[17:40:03] [main/WARN]: Option 'mixin.perf.thread_priorities' overriden (by mods [threadtweak]) to 'false'
[17:40:03] [main/INFO]: Applying Nashorn fix
[17:40:03] [main/WARN]: Reference map 'packetfixer-fabric-fabric-refmap.json' for packetfixer-fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[17:40:04] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/world/biome/BlockColorCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/world/biome/BlockColorCache)
[17:40:04] [main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.world.biome.BlockColorCache was not found betterbiomeblend.mixins.json:MixinBlockColorCache from mod betterbiomeblend
[17:40:04] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/gui/SodiumGameOptionPages (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/gui/SodiumGameOptionPages)
[17:40:04] [main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages was not found betterbiomeblend.mixins.json:MixinSodiumGameOptionPages from mod betterbiomeblend
[17:40:04] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/gui/SodiumGameOptionPages (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/gui/SodiumGameOptionPages)
[17:40:04] [main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages was not found bettergrass.mixins.json:SodiumGameOptionsPagesMixin from mod bettergrass
[17:40:04] [main/WARN]: Error loading class: eu/ha3/presencefootsteps/PFDebugHud (java.lang.ClassNotFoundException: eu/ha3/presencefootsteps/PFDebugHud)
[17:40:04] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/gui/SodiumGameOptionPages (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/gui/SodiumGameOptionPages)
[17:40:04] [main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.gui.SodiumGameOptionPages was not found cullleaves.mixins.json:MixinSodiumGameOptionPages from mod cullleaves
[17:40:05] [main/WARN]: Force disabled MC-122477 because it only applies to OS: LINUX
[17:40:05] [main/WARN]: Force disabled MC-176559 because it's conflicting with: fabric-api
[17:40:05] [main/WARN]: Force disabled MC-22882 because it only applies to OS: MAC
[17:40:05] [main/INFO]: Loading Faster Random.
[17:40:05] [main/INFO]: bre2el.fpsreducer.mixin.MinecraftClientMixin will be applied.
[17:40:05] [main/INFO]: bre2el.fpsreducer.mixin.KeyboardMixin will be applied.
[17:40:05] [main/INFO]: bre2el.fpsreducer.mixin.RenderSystemMixin will be applied.
[17:40:05] [main/INFO]: bre2el.fpsreducer.mixin.WindowMixin will be applied.
[17:40:07] [main/WARN]: Can't get value of: "fixRecipeBookIngredientsWithTags" defaulting to false
[17:40:07] [main/WARN]: Not applying "org.dimdev.vanillafix.bugs.mixins.PlayerInventoryMixin" mixin
[17:40:07] [main/WARN]: Can't get value of: "splitScreenAndTextureProfiler" defaulting to false
[17:40:07] [main/WARN]: Not applying "org.dimdev.vanillafix.bugs.mixins.client.MinecraftClientMixin" mixin
[17:40:07] [main/WARN]: Can't get value of: "fastInterdimensionalTeleportation" defaulting to false
[17:40:07] [main/WARN]: Not applying "org.dimdev.vanillafix.bugs.mixins.client.ClientPlayNetworkHandlerMixin" mixin
[17:40:07] [main/WARN]: Error loading class: net/minecraft/client/render/WorldRenderer$ChunkInfo (java.lang.ClassNotFoundException: net/minecraft/client/render/WorldRenderer$ChunkInfo)
[17:40:07] [main/WARN]: @Mixin target net.minecraft.client.render.WorldRenderer$ChunkInfo was not found vanillafix.textures.mixins.json:ChunkInfoAccessor from mod vanillafix
[17:40:07] [main/WARN]: Not applying "me.replet.client.other.AnvilLevelMaxMixin" mixin
[17:40:07] [main/WARN]: Not applying "me.replet.client.other.AnvilScreenHandlerMixin" mixin
[17:40:07] [main/INFO]: [MemoryLeakFix] Will be applying 3 memory leak fixes!
[17:40:07] [main/INFO]: [MemoryLeakFix] Currently enabled memory leak fixes: [targetEntityLeak, biomeTemperatureLeak, hugeScreenshotLeak]
[17:40:08] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
[17:40:08] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[17:40:08] [main/INFO]: ThreadTweak config initialized
[17:40:11] [main/INFO]: Injecting BlockStateBase cache population hook into getOpacityIfCached from ca.spottedleaf.starlight.mixin.common.blockstate.BlockStateBaseMixin
[17:40:11] [main/INFO]: Injecting BlockStateBase cache population hook into isConditionallyFullOpaque from ca.spottedleaf.starlight.mixin.common.blockstate.BlockStateBaseMixin
[17:40:12] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: Could not initialize class net.optifine.reflect.Reflector
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:482) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.3.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.optifine.reflect.Reflector
	at net.minecraft.class_128.method_555(class_128.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:195) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) ~[fabric-loader-0.16.3-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.3.jar:?]
	... 2 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException: Mixin transformation of net.minecraft.class_327 failed [in thread "main"]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:298) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_557(class_128.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:186) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:345) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) ~[fabric-loader-0.16.3-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.3.jar:?]
	... 2 more

https://github.com/user-attachments/assets/27d99a9c-c0da-403e-9962-ff73a986e353

**Comment by ma-tteo** [comment]
fabric loader version: 0.16.4
minecaft version 1.20.4
launcher: sklauncher
![image](https://github.com/user-attachments/assets/30d5d584-45d7-492a-a4c5-a7c18af7e240)
![image](https://github.com/user-attachments/assets/e4c9051a-4789-4e67-9dc8-985e141d0351)

**Comment by Dracconis** [comment]
Support is only provided for Legitimate Legal Launchers.

**Comment by ma-tteo** [comment]
i have a microsoft account on sklauncher. it's totally fine and legal
