### ISSUE TITLE
please read this i cannot play without optifine pls read

### ISSUE THREAD

**Issue by asumy1** [Chocohead/OptiFabric#1817]
java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:877)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 25 more

**Comment by asumy1** [comment]
[latest.log](https://github.com/user-attachments/files/16873226/latest.log)
this the log file

**Comment by asumy1** [comment]
I tried to do with 0.14.25 fabric Loader it crashed log file 
 
[latest.log](https://github.com/user-attachments/files/16873333/latest.log)

**Comment by asumy1** [comment]
@Dracconis  @Chocohead

**Comment by Dracconis** [comment]
Use Fabric API 0.76.0. Also you may need to use a different launcher as the Pojav Launcher I believe doesnt support optifabric.

**Comment by asumy1** [comment]
bro I used to play 

> Use Fabric API 0.76.0. Also you may need to use a different launcher as the Pojav Launcher I believe doesnt support optifabric.

bro I used to play optifabric 1.18,2 in 2023

**Comment by asumy1** [comment]
and which launchar than
@Dracconis

**Comment by Dracconis** [comment]
I dont know which launchers work for android. I just remember reading that the Dev for Pojav was not going to be working on the launcher to allow or include optifabric.

**Comment by asumy1** [comment]
@Dracconis can I use 1.19.2 sodium or optifabric

**Comment by Dracconis** [comment]
You cant use the 1.19.2 versions for 1.18.2 but yes you can use Sodium to replace OptiFabric/Fine mods. Just make sure you use the version for the version of MC you want to play. If this answers your questions and solves your issue, please close this ticket.

**Comment by asumy1** [comment]
@Dracconis if I use sodium it is not showing blocks

**Comment by Dracconis** [comment]
I am sorry I don't know what to tell you at this point as I have limited knowledge on MC Mobile.

**Comment by asumy1** [comment]
ok i close this
