### ISSUE TITLE
MultiMC Instance Crash

### ISSUE THREAD

**Issue by IconZ1** [Chocohead/OptiFabric#183]
Can someone help me figure out what's wrong, please?  I use MultiMC as my Minecraft launcher.  I'm trying to get a new instance up and running.  However, Minecraft crashes whenever I have OptiFabric (optifabric-1.9.6) and OptiFine (OptiFine_1.16.5_HD_U_G7) loaded.  The instance runs fine without them.

Please let me know if the following crash report is not what you need.

---- Minecraft Crash Report ----
// You're mean.

Time: 2/28/21 6:16 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'imm_ptl_core'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoClassDefFoundError: me/jellysquid/mods/sodium/client/SodiumHooks
	at com.qouteall.hiding_in_the_bushes.sodium_compatibility.SodiumInterfaceInitializer.init(SodiumInterfaceInitializer.java:32)
	at com.qouteall.hiding_in_the_bushes.ModEntryClient.onInitializeClient(ModEntryClient.java:71)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 19 more
Caused by: java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.SodiumHooks
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7069649680 bytes (6742 MB) / 8410103808 bytes (8020 MB) up to 8410103808 bytes (8020 MB)
	CPUs: 6
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms8192m -Xmx8192m
	Fabric Mods: 
		afktape: AFKTape 1.1.1
		amecsapi: Amecs API 1.1.1+mc1.16-rc1
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		appleskin: AppleSkin 1.0.11
		architectury: Architectury 1.8.128
		armor_hud: BerdinskiyBear's ArmorHUD 0.3.0
		audiooutput: AudioOutput 0.0.3
		autoconfig1u: Auto Config v1 Updated 3.3.1
		better_end_skies: Better End Sky 1.1.0
		better_mod_button: Better Mod Button 1.1.4
		betterend: Better End 0.5.1-beta
		betternether: Better Nether 5.0.5
		blue_endless_jankson: jankson 1.2.0
		cardinal-components-base: Cardinal Components API (base) 2.7.2
		cardinal-components-entity: Cardinal Components API (entities) 2.7.2
		cardinal-components-item: Cardinal Components API (items) 2.7.2
		clickthrough: ClickThrough 1.16.4-fabric0.25.1-0.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.14
		coloredcraftingstations: ColoredCraftingStations 1.1.0
		com_electronwill_night-config_core: core 3.6.0
		com_electronwill_night-config_toml: toml 3.6.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		crowdin-translate: CrowdinTranslate 1.2
		curios: Curios API 0.0.11-1.16.4
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		enchantedbookredesign: Enchanted Book Redesign 1.1
		fabric: Fabric API 0.31.0+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9b3753b7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.2
		fallingleaves: Falling Leaves 1.5.0+1.16.5
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		grid: Grid 1.16.4-fabric0.25.1-1.6.4
		imm_ptl_core: Immersive Portals Core 0.80
		immersive_portals: Immersive Portals 0.80
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kyrptconfig: Kytpt Config 1.1.4-1.16
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		libcd: LibCapableData 3.0.3+1.16.3
		lightoverlay: Light Overlay 5.8.0
		lithium: Lithium 0.6.4
		magna: Magna 1.4.2-1.16.2
		minecraft: Minecraft 1.16.5
		modmenu: Mod Menu 1.14.6+build.31
		moreblocksmod: More Blocks Mod 0.1.3
		mousewheelie: Mouse Wheelie 1.6.3+mc1.16.4
		phosphor: Phosphor 0.7.1+build.11
		repurposed_structures: Repurposed Structures 1.16.5-1.8.3
		ring_of_attraction: Ring Of Attraction 1.0.29
		rotten: FleshZ 1.2.2
		roughlyenoughitems: Roughly Enough Items 5.10.184
		roughlyenoughitems-api: REI (API) 5.10.184
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.10.184
		roughlyenoughitems-runtime: REI (Runtime) 5.10.184
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		shuffle: Shuffle 1.2.0
		silkspawners: SilkSpawners 1.0.0
		sodium: Sodium 0.1.0
		sodium-extra: Sodium Extra 0.2.0
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		torohealth: ToroHealth Damage Indicators 1.16.4-fabric-4
		tweed: Tweed API 3.0.0-beta.22
		vanilla-hammers: Vanilla Hammers 3.0.1-1.16.3
		vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
		voyager: Voyager 1.0.0
		waila: Hwyla 1.9.22
		xaerominimap: Xaero's Minimap 21.4.1
		xaeroworldmap: Xaero's World Map 1.12.1
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by Chocohead** [comment]
You can't use Sodium and OptiFabric at the same time. Would have thought it would have actually stopped the game from loading and told you though rather than letting it run anyway.

**Comment by IconZ1** [comment]
Chocohead,

Thanks so much for the reply.  The weird thing is, I don't see Sodium among the list of mods that are being loaded into the game.  So, I'm presuming there's a file or folder left in the instance folder somewhere that I need to find and remove.

[cid:a03a10d4-8cd5-4dd7-bd11-5802855f8665]


Thanks for tipping me off to what's wrong.  I really appreciate you and your work.

Sincerely,
IconZ1

________________________________

**Comment by IconZ1** [comment]
Chocohead,

I did some more testing.  I did find Sodium and Lithium config files, so I removed them and tried re-launching the game again.  It still crashed.  So, I disabled all of the mods, except Fabric API, Modmenu, OptiFabric, and OptiFine.  I then started adding a single mod to that list, one-by-one.

It took a bit but I have determined that the issue is being caused by the mod Better End Sky 1.1.0.  Everything works great, including all the other mods, as long as I don't use that one.

Not sure why there's a conflict, but I'm not really bothered either.  I can happily play without the Better End Sky mod.

Hope the information is useful to you somehow.

Geoff

________________________________

**Comment by Chocohead** [comment]
Looks like whatever compatibility issues Better End Sky 1.1 had with OptiFine they were apparently [fixed in 1.2](https://www.curseforge.com/minecraft/mc-mods/better-end-sky-fabric/files/3182945). Very odd where Sodium is getting loaded from all the same though given it doesn't look like it's including it.
