### ISSUE TITLE
Failed to load OptiFine, Failed to remap jar

### ISSUE THREAD

**Issue by HolyShadowLord** [Chocohead/OptiFabric#188]
java.lang.RuntimeException: Failed to remap jar
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:171)
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:156)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:117)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at com.chocohead.mm.Plugin$$Lambda$182/292890110.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:667)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:542)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
	at net.fabricmc.loader.EntrypointStorage$$Lambda$171/405488475.get(Unknown Source)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:137)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$58/1199673596.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
Caused by: java.nio.file.FileSystemException: C:\Users\shado\curseforge\minecraft\Instances\OriginsSMP\.optifine\OptiFine_1.16.5_HD_U_G7\Optifine-lambdafix.jar: Det går inte att komma åt filen eftersom den
används av en annan process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.checkReadAccess(WindowsFileSystemProvider.java:338)
	at sun.nio.fs.WindowsFileSystemProvider.checkAccess(WindowsFileSystemProvider.java:362)
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:124)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
	at net.fabricmc.tinyremapper.OutputConsumerPath.<init>(OutputConsumerPath.java:116)
	at net.fabricmc.tinyremapper.OutputConsumerPath.<init>(OutputConsumerPath.java:50)
	at net.fabricmc.tinyremapper.OutputConsumerPath$Builder.build(OutputConsumerPath.java:79)
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:164)
	... 43 more

**Comment by Chocohead** [comment]
I'd suggest deleting `C:\Users\shado\curseforge\minecraft\Instances\OriginsSMP\.optifine\OptiFine_1.16.5_HD_U_G7\Optifine-lambdafix.jar` (or the entire .optifine folder just to make sure nothing else strange happens) and try running the game again.

**Comment by HolyShadowLord** [comment]
That worked, thank you.

**Comment by Chocohead** [comment]
Good to hear, I'll look into making sure it doesn't get into situations where this is an issue.

**Comment by Chocohead** [comment]
From OptiFabric 1.8.7 it will attempt to run the OptiFine installer up 3 times if it produces an invalid jar, hopefully this should cover any accidental issues it makes without needing to be manually fixed
