### ISSUE TITLE
Cannot invoke "net.minecraft.class_1297.method_5705(float)" because "$$1" is null

### ISSUE THREAD

**Issue by Snxilmxl** [Chocohead/OptiFabric#1891]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-10-31 01:44:00
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_5705(float)" because "$$1" is null
	at knot//net.minecraft.class_4184.method_19321(class_4184.java:55)
	at knot//net.minecraft.class_757.method_3188(class_757.java:1052)
	at knot//net.minecraft.class_757.method_3192(class_757.java:850)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.minecraft.class_4184.method_19321(class_4184.java:55)
	at knot//net.minecraft.class_757.method_3188(class_757.java:1052)

-- Uptime --
Details:
	JVM uptime: 24.015s
	Wall uptime: 15.303s
	High-res time: 11.156s
	Client ticks: 171 ticks / 8.550s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2501)
	at knot//net.minecraft.class_310.method_54580(class_310.java:949)
	at knot//net.minecraft.class_310.method_1514(class_310.java:905)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 0, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Server brand: ~~ERROR~~ NullPointerException: Cannot read field "field_3944" because "this.field_3729.field_1724" is null
	Server type: Non-integrated multiplayer server
	Tracked entity count: 0

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, appleskin, chunksfadein, chunky, cloth-config, creativecore, distanthorizons, easyanvils, easymagic, eatinganimationid, euphoria_patcher, explosiveenhancement, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fallingleaves, fallingtree, fancyhealthbar, farsight, forgeconfigapiport, fullbrightnesstoggle, held-item-info, highlighter, inventoryhud, invmove, iris, iteminteractions, itemphysic, jade, jadeaddons, jeed, jei, lithium, lootbeams, modmenu, particlerain, reeses-sodium-options, satin, smoothscroll, sodium, sodium-extra, sodiumdynamiclights, sodiumoptionsapi, tooltipfix, visuality, wakes, waveycapes, worldedit, wthit, xaeroworldmap, yet_another_config_lib_v3, zoomify, minecraft:supporteatinganimation, file/§fAnimated §cR§aG§9B §fInv. GUI 1.20.0.zip, file/§d§lA§5n§di§5§lm§da§5t§d§le§5d §4R§6a§ei§an§bb§9o§dw §2§lX§a§lP §rBar.zip, file/animated-items-1_20-1 - 1_4.zip, file/[1.4.1] Enhanced Boss Bars.zip, file/LowOnFire_1.20.1.zip, file/Icons v.1.11.3.zip, file/EnderEyes_1.21_v3.1.zip, file/Clear_water_and_lava_by_WhiterM 1.20.5 v.1.0.zip, file/Animated-Ore+0.5.4-mc1.18-1.21.2.zip, easymagic:default_block_models, easyanvils:default_block_models

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1365249584 bytes (1302 MiB) / 1988100096 bytes (1896 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 4.28
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 8192.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6603
	Graphics card #1 name: NVIDIA GeForce RTX 3070
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 8192.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.15.6603
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 24660.54
	Virtual memory used (MiB): 18404.94
	Swap memory total (MiB): 8350.94
	Swap memory used (MiB): 346.27
	Space in storage for jna.tmpdir (MiB): available: 487735.66, total: 953868.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 487735.66, total: 953868.00
	Space in storage for io.netty.native.workdir (MiB): available: 487735.66, total: 953868.00
	Space in storage for java.io.tmpdir (MiB): available: 52141.22, total: 237713.00
	Space in storage for workdir (MiB): available: 487735.66, total: 953868.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16384m -Xms256m
	Fabric Mods: 
		appleskin: AppleSkin 3.0.5+mc1.21
		badpackets: Bad Packets 0.8.1
		chunksfadein: Chunks Fade In 1.0.3-1.21
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			crowdin-translate: CrowdinTranslate 1.0.0
		chunky: Chunky 1.4.16
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 19.0.0.1
		cobweb: Cobweb 1.1.3
		collective: Collective 7.87
		creativecore: CreativeCore 2.12.19
			net_neoforged_bus: bus 7.2.0
		cupboard: cupboard 1.21-2.7
		distanthorizons: Distant Horizons 2.2.1-a
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
		easyanvils: Easy Anvils 21.1.0
		easyelytratakeoff: Easy Elytra Takeoff 4.4
		easymagic: Easy Magic 21.1.0
		easyshulkerboxes: Easy Shulker Boxes 21.1.0
			iteminteractions: Item Interactions 21.1.0
		eatinganimationid: Eating Animation 1.21+1.9.72
		euphoria_patcher: Euphoria Patcher 0.3.4-fabric
			io_sigpipe_jbsdiff: jbsdiff 1.0
		explosiveenhancement: Explosive Enhancement 1.2.3-1.21.0
		fabric-api: Fabric API 0.107.0+1.21.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.69+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.17+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.1+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.1+7fd4837519
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.2.0+e49211d819
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.22+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.4.0+0f6c53cd19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.1+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.7
			mixinextras: MixinExtras 0.4.1
		fallingleaves: Falling Leaves 1.16.2
		fallingtree: FallingTree 1.21.1.2
		fancyhealthbar: FancyHealthBar 1.1.1
		farsight: Farsight Mod 1.21-4.4
			org_jctools_jctools-core: jctools-core 4.0.1
		forgeconfigapiport: Forge Config API Port 21.1.1
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		fullbrightnesstoggle: Full Brightness Toggle 4.2
		harvest_with_ease: Harvest with ease 9.2.1
		held-item-info: Held Item Info 1.7.0
		highlighter: Highlighter 1.1.11
		iceberg: Iceberg 1.2.7
		inventoryhud: Inventory HUD + 3.4.26
		invmove: InvMove 0.8.8
		iris: Iris 1.8.0-beta.4+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		itemphysic: ItemPhysic 1.8.2
		jade: Jade 15.8.2+fabric
		jadeaddons: Jade Addons 6.0.3+fabric
		java: OpenJDK 64-Bit Server VM 21
		jeed: Just Enough Effects Descriptions 1.21-2.2.8
		jei: Just Enough Items 19.8.4.113
		lithium: Lithium 0.13.1
		lootbeams: LootBeams 2.7.0-mc1.21-.1
		minecraft: Minecraft 1.21.1
		modmenu: Mod Menu 11.0.3
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		mousetweaks: Mouse Tweaks 2.26
		particlerain: Particle Rain 2.1.4
		puzzleslib: Puzzles Lib 21.1.22
		reeses-sodium-options: Reese's Sodium Options 1.8.0-beta.4+mc1.21.1
		smoothscroll: Smooth Scroll 2.1.3
		sodium: Sodium 0.6.0-beta.4+mc1.21.1
		sodium-extra: Sodium Extra 0.6.0-beta.3+mc1.21.1
		sodiumdynamiclights: Sodium Dynamic Lights 1.0.9
		sodiumoptionsapi: Sodium Options API 1.0.2
			mixinsquared: MixinSquared 0.2.0-beta.6
		tooltipfix: ToolTip Fix 1.1.1-1.20
		visuality: Visuality 0.7.7+1.21
		wakes: Wakes 0.3.0+1.21.1
			blue_endless_jankson: jankson 1.2.2
			com_github_jdiemke_delaunay-triangulator_delaunaytriangulator: DelaunayTriangulator 1.0.0
			satin: Satin 2.0.0
		waveycapes: WaveyCapes 1.4.10
		worldedit: WorldEdit 7.3.8+6939-7d32b45
		wthit: wthit 12.4.2
		xaeroworldmap: Xaero's World Map 1.39.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.1+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zoomify: Zoomify 2.14.2+1.21.1
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.2
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.16.7-1.21.1
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 3.2.0 NVIDIA 566.03, NVIDIA Corporation
	Window size: 2560x1440
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, appleskin (incompatible), chunksfadein, chunky, cloth-config, creativecore, distanthorizons (incompatible), easyanvils, easymagic, eatinganimationid, euphoria_patcher, explosiveenhancement, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fallingleaves, fallingtree, fancyhealthbar, farsight, forgeconfigapiport, fullbrightnesstoggle (incompatible), held-item-info, highlighter, inventoryhud, invmove, iris, iteminteractions, itemphysic, jade (incompatible), jadeaddons (incompatible), jeed, jei (incompatible), lithium, lootbeams (incompatible), modmenu, particlerain, reeses-sodium-options, satin, smoothscroll, sodium, sodium-extra, sodiumdynamiclights (incompatible), sodiumoptionsapi (incompatible), tooltipfix, visuality, wakes, waveycapes, worldedit (incompatible), wthit, xaeroworldmap (incompatible), yet_another_config_lib_v3 (incompatible), zoomify, minecraft:supporteatinganimation, file/§fAnimated §cR§aG§9B §fInv. GUI 1.20.0.zip (incompatible), file/§d§lA§5n§di§5§lm§da§5t§d§le§5d §4R§6a§ei§an§bb§9o§dw §2§lX§a§lP §rBar.zip, file/animated-items-1_20-1 - 1_4.zip (incompatible), file/[1.4.1] Enhanced Boss Bars.zip (incompatible), file/LowOnFire_1.20.1.zip (incompatible), file/Icons v.1.11.3.zip, file/EnderEyes_1.21_v3.1.zip, file/Clear_water_and_lava_by_WhiterM 1.20.5 v.1.0.zip (incompatible), file/Animated-Ore+0.5.4-mc1.18-1.21.2.zip, easymagic:default_block_models, easyanvils:default_block_models
	Current Language: en_us
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 12x AMD Ryzen 5 5600X 6-Core Processor

**Comment by Dracconis** [comment]
This github is for Optifabric. Your issue doesn't pertain to Optifabric. My suggestion is to remove all of the mods in the list except Fabric API and see if it will start and allow you into a world. IF everything works the add 1/4th of the mods(including any dependencies those mods might need to work) in your list back into your mods folder and try again. Keep doing this until you either get the same error or a new error. Once you get an error then you know that there is a mod in the last mods you added. From that point remove 1 of the last added mods at a time until you find the 1 causing the error. Then you can report the error to the correct Mod Developer. Please close this ticket.
