### ISSUE TITLE
OptiFine 1.20.6 don't work please help

### ISSUE THREAD

**Issue by Nermaaek** [Chocohead/OptiFabric#1922]
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.HashMap.keySet(HashMap.java:914)
	at java.base/java.util.HashSet.iterator(HashSet.java:182)
	at java.base/java.util.concurrent.ThreadPoolExecutor.interruptIdleWorkers(ThreadPoolExecutor.java:803)
	at java.base/java.util.concurrent.ThreadPoolExecutor.interruptIdleWorkers(ThreadPoolExecutor.java:826)
	at java.base/java.util.concurrent.ThreadPoolExecutor.shutdown(ThreadPoolExecutor.java:1396)
	at me.modmuss50.optifabric.shadow.tinyremapper.TinyRemapper.finish(TinyRemapper.java:332)
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:254)
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:236)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:184)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at com.chocohead.mm.Plugin$$Lambda/0x0000000100319d18.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:877)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)

**Comment by Dracconis** [comment]
1. For future reference this is the GitHub Reporting Tool for Optifabric. 
2. You are receiving this error because Minecraft doesn't have enough memory to run with all of the mods you are using. 
3. Add more memory and the error will stop.
4. If this solves your issue please close this ticket.
