### ISSUE TITLE
Multiple errors as well as freezing when booting up a world

### ISSUE THREAD

**Issue by thea93343** [Chocohead/OptiFabric#1931]
When OptiFabric is enabled (I went through all the mods, it is a problem with OptiFabric), when I attempt to load into a world, I get these two errors and the window becomes unresponsive and drop's my PC's frames immensely.

Error 1:
[14:50:14] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_3130()" because "this.field_3690.field_1724" is null
	at net.minecraft.class_634.method_11106(class_634.java:1251) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11997(class_2788.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11054(class_2788.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:40) ~[client-intermediary.jar:?]
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:198) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:163) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:140) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1085) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.14.25.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.25.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.25.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

Error 2:
[14:50:14] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1937.method_8469(int)" because "$$0" is null
	at net.minecraft.class_2663.method_11469(class_2663.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11148(class_634.java:891) ~[client-intermediary.jar:?]
	at net.minecraft.class_2663.method_11471(class_2663.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_2663.method_11054(class_2663.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:40) ~[client-intermediary.jar:?]
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:198) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:163) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:140) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1085) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.14.25.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.25.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.25.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

These errors are repeated in the log until the application is force-closed via alt-f4 or taskmgr

I noticed an issue from a month ago with a similar log, though I used the method said (enabling the mods one by one to see which one causes the bug), and it is OptiFabric.

Minecraft Version: 1.18.2
Launcher: MultiMC

Mods:
fabric-api-0.75.1+1.18.2.jar
optifabric-1.13.0.jar
collective-fabric-1.18.2-4.51.jar
fullbrightnesstoggle-fabric_1.18.2-15.jar
OptiFine_1.18.2_HD_U_H9.jar
fabric-carpet-1.18.2-1.4.69+v220331.jar
worldedit-mod-7.2.10.jar
redstonetools-1.18.2-2.0.0.jar

Fabric ver:
0.14.25

Java ver:
19.0.1

**Comment by Dracconis** [comment]
Change your Optifabric version to the latest version 1.13.16 as well as your Fabric API to 0.76.0 and try again. If this solves your issue please close this ticket.
