### ISSUE TITLE
OptiFabric

### ISSUE THREAD

**Issue by Azknee1** [Chocohead/OptiFabric#1933]
java.lang.NoClassDefFoundError: net/fabricmc/mappingio/FlatMappingVisitor
	at knot//me.modmuss50.optifabric.mod.IntermediaryContextTransformer.<init>(IntermediaryContextTransformer.java:86)
	at knot//me.modmuss50.optifabric.mod.OptifineSetup$2.lambda$load$9(OptifineSetup.java:324)
	at knot//me.modmuss50.optifabric.mod.ContextualMappingProvider.setContextTransformer(ContextualMappingProvider.java:72)
	at knot//me.modmuss50.optifabric.mod.OptifineSetup$2.load(OptifineSetup.java:324)
	at knot//me.modmuss50.optifabric.shadow.tinyremapper.TinyRemapper.apply$3041763d$58bfb62c(TinyRemapper.java:7703)
	at knot//me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:3903)
	at knot//me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:237)
	at knot//me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:185)
	at knot//me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at knot//com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:877)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.mappingio.FlatMappingVisitor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 34 more

**Comment by Dracconis** [comment]
Which MC Launcher?
Which Fabric Loader version?
List of Mods AND their versions?

**Comment by Azknee1** [comment]
> Which MC Launcher? Which Fabric Loader version? List of Mods AND their versions?

legacy launcher
fabric 16.9
list of mods:
DistantHorizons-2.2.1-a
fabric-api-0.110.0
firstperson-2.4.5
jei-19.21.0.247
Optifabric-Mod-Fabric-1.21.1
OptiFine_1.21.1_HD_U_J1
shulkerboxtooltip-5.1.2

**Comment by Dracconis** [comment]
Two things:
1. Support is not provided for illegal launchers and would suggest you use a legal launcher instead.
2. There is currently no Optifacbric mod available for 1.21+

**Comment by Dracconis** [comment]
If this has solved your issue for now, please close this ticket.

**Comment by HARSHUT69** [comment]
How to download it??

**Comment by Dracconis** [comment]
> How to download it??

If you need support please open your own ticket and stop hijacking other's tickets.
