### ISSUE TITLE
Why can't I enter Minecraft version 1.16.5 it says fabric loader error please help 

### ISSUE THREAD

**Issue by RAVEZGG32** [Chocohead/OptiFabric#1950]
java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at java.util.ArrayList.forEach(Unknown Source)
Please help

**Comment by Asynchro-Dev** [comment]
Just uninstall OptiFabric and optifine mods, i think it conflict with another mods. I recommend you to use Sodium and Iris shaders instead of optifine

**Comment by Dracconis** [comment]
> java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46) at java.util.ArrayList.forEach(Unknown Source) Please help

Use Fabric Loader 0.14.25, also next time please do a search to see if your issue has already been solved. If this solves your issue please close the ticket.

**Comment by Dracconis** [comment]
> Just uninstall OptiFabric and optifine mods, i think it conflict with another mods. I recommend you to use Sodium and Iris shaders instead of optifine

It is not a conflict as it is just a wrong version of the loader.

**Comment by AduPadu07** [comment]
> > java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46) at java.util.ArrayList.forEach(Unknown Source) Please help
> 
> Use Fabric Loader 0.14.25, also next time please do a search to see if your issue has already been solved. If this solves your issue please close the ticket.

It doesn't works

**Comment by Dracconis** [comment]
> > > java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46) at java.util.ArrayList.forEach(Unknown Source) Please help
> > 
> > 
> > Use Fabric Loader 0.14.25, also next time please do a search to see if your issue has already been solved. If this solves your issue please close the ticket.
> 
> It doesn't works

Please do not hijack other's tickets and open your own ticket instead to be able to get support for your issue.
