### ISSUE TITLE
failed to load optifine (1.21.4 0.16.9)

### ISSUE THREAD

**Issue by dsb987** [Chocohead/OptiFabric#1960]
java.lang.IllegalStateException: Unknown invokedynamic bsm: java/lang/runtime/SwitchBootstraps#typeSwitch(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
	at me.modmuss50.optifabric.patcher.MethodComparison.findLambdas(MethodComparison.java:288)
	at me.modmuss50.optifabric.patcher.MethodComparison.findHandles(MethodComparison.java:258)
	at me.modmuss50.optifabric.patcher.MethodComparison.compare(MethodComparison.java:79)
	at me.modmuss50.optifabric.patcher.MethodComparison.<init>(MethodComparison.java:52)
	at me.modmuss50.optifabric.patcher.MethodComparison.<init>(MethodComparison.java:44)
	at me.modmuss50.optifabric.patcher.LambdaRebuilder.findLambdas(LambdaRebuilder.java:155)
	at me.modmuss50.optifabric.patcher.LambdaRebuilder.findLambdas(LambdaRebuilder.java:137)
	at me.modmuss50.optifabric.patcher.LambdaRebuilder.findLambdas(LambdaRebuilder.java:114)
	at me.modmuss50.optifabric.mod.OptifineSetup$1.apply(OptifineSetup.java:152)
	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:165)
	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:129)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:134)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:877)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

**Comment by Dracconis** [comment]
There is no 1.21 version of Optifabric yet.

**Comment by dsb987** [comment]
I changed the description of [fabric.mod.json] in [optifabric-1.14.3.jar]. But it doesn't work as expectation. 
Is there any plans to update this mod to fit newer version of MC？

**Comment by Dracconis** [comment]
I wouldnt have any idea. Will have to wait for Choco.
