### ISSUE TITLE
Issue with 1.17

### ISSUE THREAD

**Issue by fsrastdyyf** [Chocohead/OptiFabric#238]
I have a problem when I try to start minecraft with optifabric and the pre optifine version 1.17. I leave the complete log here: https://paste.ee/p/hmb8e

**Comment by penguinencounter** [comment]
Same sort of error, on start, preview_OptiFine_1.17_HD_U_G9_pre16.
Java 16, MultiMC
https://paste.ee/p/GYR32

**Comment by penguinencounter** [comment]
Mine seems to not like Carpet...
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method doChangeTickPhase(F)F in optifabric.compat.carpet.mixins.json:WorldRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap optifabric-refmap.json`
while yours seems to not like the Architectury API
`Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [optifabric.compat.architectury-A.mixins.json:GameRendererMixin] from phase [DEFAULT] in config [optifabric.compat.architectury-A.mixins.json] FAILED during APPLY`

**Comment by Chocohead** [comment]
Indeed the Carpet and Architectury compat will have updates coming shortly

**Comment by Squirrelcoding** [comment]
I've also had a similar issue: https://pastebin.com/9gXmWhWt

**Comment by Hshem** [comment]
how can i fix this problem

**Comment by sean22922** [comment]
The latest alpha(1.11.6) still crash with Cloth-api and cloth-config, here's the crash log.
```
Description: Rendering screen

org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_757::method_3192(FJZ)V has incompatible changes at opcode 705 in callback net/minecraft/class_757::optifabric_renderScreen.
Expected: [I, I, Lnet/minecraft/class_1041;, Lnet/minecraft/class_4587;]
   Found: [I, Lnet/minecraft/class_1041;, Lnet/minecraft/class_1159;]
	at net.minecraft.class_757.handler$zpe000$optifabric_renderScreen$missing(class_757.java)
	at net.minecraft.class_757.method_3192(class_757.java:1279)
	at net.minecraft.class_310.method_1523(class_310.java:1114)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_757.handler$zpe000$optifabric_renderScreen$missing(class_757.java)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_442
	Mouse location: Scaled: (443, 198). Absolute: (1772.000000, 795.000000)
	Screen size: Scaled: (640, 270). Absolute: (2560, 1080). Scale factor of 4.000000

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, [1.17]_Firewolf_v1.84.zip
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:749)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2537995632 bytes (2420 MiB) / 3288334336 bytes (3136 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 12
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3090
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2204
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6677
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 40104.85
	Virtual memory used (MB): 32736.67
	Swap memory total (MB): 7424.00
	Swap memory used (MB): 792.11
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amecsapi: Amecs API 1.1.4+mc21w16a
		appleskin: AppleSkin mc1.17-2.0.0
		architectury: Architectury 2.0.9
		audiooutput: AudioOutput 0.0.4
		autofish: Autofish 0.9.3
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v4 5.0.34
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		craftpresence: CraftPresence 1.8.2
		fabric: Fabric API 0.35.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.1.0+1d383bb63d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.8+a02b44633d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b4463a0
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463a0
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab6121a0
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121a0
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121a0
		fabricloader: Fabric Loader 0.11.6
		inventoryhud: Inventory HUD + 3.3.2
		java: OpenJDK 64-Bit Server VM 16
		lightoverlay: Light Overlay 6.0.0
		minecraft: Minecraft 1.17
		mm: Manningham Mills 2.2
		modmenu: Mod Menu 2.0.2
		monsters_in_the_closet: Monsters in the Closet 1.0.2+1.17
		mousewheelie: Mouse Wheelie 1.7.3+mc1.17-rc1
		optifabric: OptiFabric 1.11.6
		roughlyenoughitems: Roughly Enough Items 6.0.251-alpha
		skinshine: Skin Shine 1.1.8
		slotlock: SlotLock 1.0.4-BETA+1.17
		tweed: Tweed 3.0.0-beta.26
		voxelmap: VoxelMap 1.10.15
		wthit: wthit 3.6.0
	Launched Version: fabric-loader-0.11.6-1.17
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3090/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.77, NVIDIA Corporation
	Window size: 2560x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/[1.17]_Firewolf_v1.84.zip
	Current Language: 繁體中文 (台灣)
	CPU: 16x Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.17_HD_U_G9_pre21
	OptiFine Build: 20210612-020007
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 466.77
	OpenGlRenderer: NVIDIA GeForce RTX 3090/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.17
	OptiFine jar version: OptiFine_1.17_HD_U_G9_pre21
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/Users/AppData/Roaming/.minecraft/.optifine/OptiFine_1.17_HD_U_G9_pre21/Optifine-mapped.jar
	OptiFabric error: <None>
```

**Comment by Seba244c** [comment]
Architectury and OptiFabric still doesnt work together on 1.17

**Comment by embeddedt** [comment]
Are you using the right versions of each? I had stable results with the following:

![image](https://user-images.githubusercontent.com/42941056/123446046-7d652480-d5a6-11eb-8fc8-4eddd59c4237.png)

**Comment by Seba244c** [comment]
For some reason even though i downloaded OptiFabric yesterday, it was to old. My bad

**Comment by FloofGar** [comment]
Same problem with 1.18.1, architectury version 3.7.22 and any optifabric version
