### ISSUE TITLE
Bug: Issue with Architectury on 1.17

### ISSUE THREAD

**Issue by Gaming32** [Chocohead/OptiFabric#244]
When I try to start Minecraft Fabric 1.17 with both OptiFabric and Architectury installed, I get an error from `optifabric.compat.architectury` failing to apply.

<details>
<summary>"Fatal" crash log</summary>
<pre>
Mixin apply failed optifabric.compat.architectury-A.mixins.json:GameRendererMixin -> net.minecraft.class_757: org.spongepowered.asm.mixin.transformer.throwables.MixinApplicatorException Unexpecteded IllegalArgumentException whilst applying the mixin class: [PreApply Phase -> optifabric.compat.architectury-A.mixins.json:GameRendererMixin]
org.spongepowered.asm.mixin.transformer.throwables.MixinApplicatorException: Unexpecteded IllegalArgumentException whilst applying the mixin class: [PreApply Phase -> optifabric.compat.architectury-A.mixins.json:GameRendererMixin]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:353)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3229)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2335)
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:518)
	at net.minecraft.class_128.<init>(class_128.java:44)
	at net.minecraft.class_128.method_24305(class_128.java:349)
	at net.minecraft.client.main.Main.main(Main.java:137)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.IllegalArgumentException: Can't find Mixin class me/shedaniel/architectury/mixin/fabric/client/MixinGameRenderer targetting net.minecraft.class_757
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.findMixin(InterceptingMixinPlugin.java:81)
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.preApply(InterceptingMixinPlugin.java:50)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.preApply(PluginHandle.java:158)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.preApply(MixinInfo.java:1341)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.preApply(MixinTargetContext.java:1177)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:308)
	... 24 more
</pre>
</details>

<details>
<summary>The rest of the crash log</summary>
<pre>
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3229)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2335)
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:518)
	at net.minecraft.class_128.<init>(class_128.java:44)
	at net.minecraft.class_128.method_24305(class_128.java:349)
	at net.minecraft.client.main.Main.main(Main.java:137)
	... 7 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [optifabric.compat.architectury-A.mixins.json:GameRendererMixin] from phase [DEFAULT] in config [optifabric.compat.architectury-A.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 21 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinApplicatorException: Unexpecteded IllegalArgumentException whilst applying the mixin class: [PreApply Phase -> optifabric.compat.architectury-A.mixins.json:GameRendererMixin]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:353)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 21 more
Caused by: java.lang.IllegalArgumentException: Can't find Mixin class me/shedaniel/architectury/mixin/fabric/client/MixinGameRenderer targetting net.minecraft.class_757
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.findMixin(InterceptingMixinPlugin.java:81)
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.preApply(InterceptingMixinPlugin.java:50)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.preApply(PluginHandle.java:158)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.preApply(MixinInfo.java:1341)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.preApply(MixinTargetContext.java:1177)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:308)
	... 24 more
</pre>
</details>

**Comment by penguinencounter** [comment]
looks similar to #238
