### ISSUE TITLE
Optifabric wont load with pojavlauncher

### ISSUE THREAD

**Issue by Blobanium** [Chocohead/OptiFabric#253]
So I'm trying to load I'm optifabric on pojavlauncher but I get a "failed to load optifine!" 

![image](https://cdn.discordapp.com/attachments/815339970713747489/854052302833582080/Screenshot_20210614-103206_PojavLauncher_Minecraft_Java_Edition_for_Android.jpg)

Stacktrace

java.io.UncheckedIOException: Error modifying /storage/emulated/0/games/PojavLauncher/.minecraft/.optifine/OptiFine_1.16.5_HD_U_G8/Optifine-mapped.jar
	at me.modmuss50.optifabric.util.ZipUtils.transformInPlace(ZipUtils.java:80)
	at me.modmuss50.optifabric.mod.OptifineSetup.generateClassCache(OptifineSetup.java:315)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:158)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:667)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:542)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:137)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.util.zip.ZipException: No such file or directory
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:103)
	at me.modmuss50.optifabric.util.ZipUtils.transformInPlace(ZipUtils.java:76)
	... 28 more

Tell me if I need anything else thanks

**Comment by Blobanium** [comment]
Here's pojavlauncher's repo also if u need it:  https://github.com/PojavLauncherTeam/PojavLauncher

**Comment by Chocohead** [comment]
This looks like Pojav Launcher failing to expose the game directory properly, you're best reporting this to them

**Comment by ZERO1234-hub** [comment]
How did you solve the problem? I really need to know because playing Minecraft without optifine is impossible!
