### ISSUE TITLE
Optifine File problems

### ISSUE THREAD

**Issue by timerunner16** [Chocohead/OptiFabric#257]
I've tried with both the _MOD.jar and the main file, neither of them works.

[09:34:45] [main/INFO]: Loading for game Minecraft 1.16.5
[09:34:45] [ForkJoinPool-1-worker-13/WARN]: Non-Fabric mod JAR at "C:\Users\<my name>\AppData\Roaming\.minecraft\immersive\mods\OptiFine_1.16.5_HD_U_G8_MOD.jar", ignoring
[09:34:46] [main/INFO]: [FabricLoader] Loading 55 mods:
	- cloth-basic-math@0.5.1
	- cloth-config2@4.11.15
	- fabric@0.35.1+1.16
	- fabric-api-base@0.3.0+c88702897d
	- fabric-api-lookup-api-v1@1.1.0+731c05f37d
	- fabric-biome-api-v1@3.1.10+3661eaa17d
	- fabric-blockrenderlayer-v1@1.1.5+ca58154a7d
	- fabric-command-api-v1@1.1.1+351679a77d
	- fabric-commands-v0@0.2.2+ca58154a7d
	- fabric-containers-v0@0.1.11+9354966b7d
	- fabric-content-registries-v0@0.2.1+ca58154a7d
	- fabric-crash-report-info-v1@0.1.3+ca58154a7d
	- fabric-dimensions-v1@2.0.6+61336ba97d
	- fabric-entity-events-v1@1.1.0+c88702897d
	- fabric-events-interaction-v0@0.4.2+ca58154a7d
	- fabric-events-lifecycle-v0@0.2.1+ca58154a7d
	- fabric-game-rule-api-v1@1.0.6+ca58154a7d
	- fabric-item-api-v1@1.2.1+ca58154a7d
	- fabric-item-groups-v0@0.2.7+2868a2287d
	- fabric-key-binding-api-v1@1.0.4+9354966b7d
	- fabric-keybindings-v0@0.2.1+ca58154a7d
	- fabric-lifecycle-events-v1@1.2.1+ca58154a7d
	- fabric-loot-tables-v1@1.0.2+ca58154a7d
	- fabric-mining-levels-v0@0.1.3+ca58154a7d
	- fabric-models-v0@0.3.0+bc7a746f7d
	- fabric-networking-api-v1@1.0.3+e3c9d0627d
	- fabric-networking-blockentity-v0@0.2.8+ca58154a7d
	- fabric-networking-v0@0.3.2+ca58154a7d
	- fabric-object-builder-api-v1@1.9.5+c88702897d
	- fabric-object-builders-v0@0.7.2+ca58154a7d
	- fabric-particles-v1@0.2.4+ca58154a7d
	- fabric-registry-sync-v0@0.7.4+ca58154a7d
	- fabric-renderer-api-v1@0.4.3+0ef801b67d
	- fabric-renderer-indigo@0.4.4+ca58154a7d
	- fabric-renderer-registries-v1@2.3.0+2868a2287d
	- fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d
	- fabric-rendering-fluids-v1@0.1.13+ca58154a7d
	- fabric-rendering-v0@1.1.2+ca58154a7d
	- fabric-rendering-v1@1.6.0+2868a2287d
	- fabric-resource-loader-v0@0.4.6+2868a2287d
	- fabric-screen-api-v1@1.0.0+c045166c7d
	- fabric-screen-handler-api-v1@1.1.5+9354966b7d
	- fabric-structure-api-v1@1.1.11+ca0ef93d7d
	- fabric-tag-extensions-v0@1.1.1+ca58154a7d
	- fabric-textures-v0@1.0.6+ca58154a7d
	- fabric-tool-attribute-api-v1@1.2.7+8183d3957d
	- fabricloader@0.11.6
	- imm_ptl_core@0.90
	- immersive_portals@0.90
	- java@8
	- minecraft@1.16.5
	- mm@2.2
	- modmenu@v1.16.8+unknown.bd9230a
	- optifabric@1.11.1
	- pehkui@2.2.1+1.14.4-1.17
[09:34:46] [main/WARN]: Mod `modmenu` (v1.16.8+unknown.bd9230a) does not respect SemVer - comparison support is limited.
[09:34:46] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/calvi/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[09:34:47] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[09:34:47] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in imm_ptl.mixins.json:common.entity_sync.MixinEntityTracker and should be specified in value
[09:34:47] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval)
[09:35:01] [main/INFO]: [OptiFine] (Reflector) Field not found: World.tileEntitiesToBeRemoved
[09:35:03] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_3489.createOptional
[09:35:07] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[09:35:09] [main/INFO]: Setting user: the_zombie_dude
[09:35:09] [main/INFO]: Definitely not up to no good
[09:35:09] [main/INFO]: Immersive Portals Mod Initializing
[09:35:09] [main/INFO]: Reach entity attributes mod is not present
[09:35:09] [main/INFO]: Pehkui is present
[09:35:10] [main/INFO]: IP Config Applied
[09:35:10] [main/INFO]: Optifine is present
[09:35:10] [main/INFO]: Sodium is not present
[09:35:10] [main/WARN]: WARNING! Mod mm is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[09:35:10] [main/WARN]: WARNING! Mod cloth-basic-math is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[09:35:10] [main/WARN]: WARNING! Mod cloth-config2 is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[09:35:10] [main/INFO]: [Indigo] Registering Indigo renderer!
[09:35:10] [main/INFO]: [Indigo] Compatibility mode enabled.
[09:35:11] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[09:35:13] [main/INFO]: [OptiFine] 
[09:35:13] [main/INFO]: [OptiFine] OptiFine_1.16.5_HD_U_G8
[09:35:13] [main/INFO]: [OptiFine] Build: 20210515-161946
[09:35:13] [main/INFO]: [OptiFine] OS: Windows 10 (amd64) version 10.0
[09:35:13] [main/INFO]: [OptiFine] Java: 1.8.0_51, Oracle Corporation
[09:35:13] [main/INFO]: [OptiFine] VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[09:35:13] [main/INFO]: [OptiFine] LWJGL: 3.3.0 Win32 WGL EGL OSMesa VisualC DLL
[09:35:13] [main/INFO]: [OptiFine] OpenGL: NVIDIA GeForce RTX 2060/PCIe/SSE2, version 4.6.0 NVIDIA 466.47, NVIDIA Corporation
[09:35:13] [main/INFO]: [OptiFine] OpenGL Version: 4.6.0
[09:35:13] [main/INFO]: [OptiFine] Maximum texture size: 32768x32768
[09:35:13] [VersionCheck/INFO]: [OptiFine] Checking for new version
[09:35:13] [main/FATAL]: Mixin apply failed imm_ptl_optifine.mixins.json:MixinShaders_Swap -> net.optifine.shaders.Shaders: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field colorBufferSizes was not located in the target class net.optifine.shaders.Shaders. Using refmap imm_ptl_core-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field colorBufferSizes was not located in the target class net.optifine.shaders.Shaders. Using refmap imm_ptl_core-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:610) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:289) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) [fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.optifine.Config.initDisplay(Config.java:221) [Optifine-mapped.jar:?]
	at net.minecraft.class_4493.method_21973(class_4493.java:429) [intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at com.mojang.blaze3d.platform.GLX._init(GLX.java:151) [intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:1065) [intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:478) [intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:177) [intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[09:35:13] [main/FATAL]: Mixin apply failed imm_ptl_optifine.mixins.json:MixinShaders_Swap -> net.optifine.shaders.Shaders: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field colorBufferSizes was not located in the target class net.optifine.shaders.Shaders. Using refmap imm_ptl_core-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field colorBufferSizes was not located in the target class net.optifine.shaders.Shaders. Using refmap imm_ptl_core-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:610) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:289) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) [fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.optifine.CrashReporter.extendCrashReport(CrashReporter.java:126) [Optifine-mapped.jar:?]
	at net.optifine.CrashReporter.onCrashReport(CrashReporter.java:38) [Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:227) [intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_310.method_1565(class_310.java:785) [intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:186) [intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[09:35:13] [main/INFO]: [STDERR]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[09:35:13] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
[09:35:13] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[09:35:13] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[09:35:13] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[09:35:13] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:35:13] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:35:13] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:35:13] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[09:35:13] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[09:35:13] [main/INFO]: [STDERR]: 	... 2 more
[09:35:13] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[09:35:13] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[09:35:13] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
[09:35:13] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[09:35:13] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[09:35:13] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
[09:35:13] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
[09:35:13] [main/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[09:35:13] [main/INFO]: [STDERR]: 	at net.optifine.CrashReporter.extendCrashReport(CrashReporter.java:126)
[09:35:13] [main/INFO]: [STDERR]: 	at net.optifine.CrashReporter.onCrashReport(CrashReporter.java:38)
[09:35:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_128.method_568(class_128.java:227)
[09:35:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1565(class_310.java:785)
[09:35:13] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:186)
[09:35:13] [main/INFO]: [STDERR]: 	... 7 more
[09:35:13] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [imm_ptl_optifine.mixins.json:MixinShaders_Swap] from phase [DEFAULT] in config [imm_ptl_optifine.mixins.json] FAILED during APPLY
[09:35:13] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
[09:35:13] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
[09:35:13] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
[09:35:13] [main/INFO]: [STDERR]: 	... 18 more
[09:35:13] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field colorBufferSizes was not located in the target class net.optifine.shaders.Shaders. Using refmap imm_ptl_core-refmap.json
[09:35:13] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:610)
[09:35:13] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:289)
[09:35:13] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264)
[09:35:13] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272)
[09:35:13] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
[09:35:13] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[09:35:13] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[09:35:13] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[09:35:13] [main/INFO]: [STDERR]: 	... 18 more
[09:35:13] [VersionCheck/INFO]: [OptiFine] Version found: G7

**Comment by Chocohead** [comment]
This is an issue with Immersive Portals and OptiFine G8 (qouteall/ImmersivePortalsMod#722), in the meantime I think it should be fine using G7.
