### ISSUE TITLE
Error transforming Optifine-mod.jar

### ISSUE THREAD

**Issue by brunoman4006** [Chocohead/OptiFabric#268]
java.io.UncheckedIOException: Error transforming C:\Users\diego\AppData\Roaming\.minecraft\.optifine\OptiFine_1.16.5_HD_U_G7\Optifine-mod.jar
	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:97)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:97)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:667)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:542)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:164)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at me.deftware.client.framework.main.Main.main(Main.java:43)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:102)
	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:95)
	... 28 more

**Comment by Chocohead** [comment]
What version of OptiFabric are you using? It should be making sure the zip/jars it deals with aren't corrupt but clearly not

**Comment by JezaGaia** [comment]
I came here to comment on the exact same issue but trying to explain it showed me my issue, here it is in case it helps : 
I use multimc as loader
I created a 1.17 instance
I edited the instance and added fabric loader in the version tab
I added the fabric API in the mods tab and launched to test it. 
Minecraft launches ok
I added optifabric-1.11.9 in the mods tab
I downloaded optifine   preview_OptiFine_1.17_HD_U_G9_pre21 (latest preview I could find)
I extracted it
I followed a tutorial that said to add the extracted jar it in the version tab where the fabric launcher is installed by using the add to minecraft.jar option.
I tried to launch the game and it crashed with the above message.

When writing the message here to say I had this same issue I tried an extra step, launching the game with optifabric but disabling optifine in the version tab. The game launched but there was an error screen saying optifabric couldn't find optifine in the mods folder. 
I had the idea to grab the extracted optifine jar and adding it to the mods in multimc while still disabled in the version tab and now the game launches prefectly.I created a test world and optifine is active, I checked by zooming.

So maybe check how you installed optifine and see if it's not your issue too ?

**Comment by brunoman4006** [comment]
I installed the OptiFabric from the addons marketplace, then i restarted
the mc, and i get this error
so i decided to delete the jar file and continue without optifine
i should to reinstall it to see if the problem was an erro while
downloading??
