### ISSUE TITLE
error code 0 : Unable to start minecraft (1.16.5) 

### ISSUE THREAD

**Issue by Oytoch** [Chocohead/OptiFabric#276]
![image](https://user-images.githubusercontent.com/26163172/123147910-e68e5000-d45f-11eb-8802-3d8e2d68c696.png)
`Mixin apply failed mixins.jgui.json:MixinKeyboardListener -> net.minecraft.class_309: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on mixins.jgui.json:MixinKeyboardListener->@Inject::keyPressed(I[ZLnet/minecraft/class_4069;IIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (I[ZIIILnet/minecraft/class_4069;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (I[ZLnet/minecraft/class_4069;IIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> mixins.jgui.json:MixinKeyboardListener -> Apply Injections ->  -> Inject -> mixins.jgui.json:MixinKeyboardListener->@Inject::keyPressed(I[ZLnet/minecraft/class_4069;IIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on mixins.jgui.json:MixinKeyboardListener->@Inject::keyPressed(I[ZLnet/minecraft/class_4069;IIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (I[ZIIILnet/minecraft/class_4069;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (I[ZLnet/minecraft/class_4069;IIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> mixins.jgui.json:MixinKeyboardListener -> Apply Injections ->  -> Inject -> mixins.jgui.json:MixinKeyboardListener->@Inject::keyPressed(I[ZLnet/minecraft/class_4069;IIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:517)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:447)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:530)
	at net.minecraft.class_128.method_559(class_128.java:101)
	at net.minecraft.class_128.<init>(class_128.java:54)
	at net.minecraft.class_128.method_24305(class_128.java:425)
	at net.minecraft.client.main.Main.main(Main.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)`
installed mods : 
![image](https://user-images.githubusercontent.com/26163172/123148012-058ce200-d460-11eb-9560-43fd5a461592.png)

Hi. I cant start the game, I have error code 0 in the launcher. I tried to reinstall it many times .

**Comment by Chucky2401** [comment]
Hi, same error for me, too. I keep the 1.11.1 version for the moment.

**Comment by bananasmoothii** [comment]
Same here. I'm using linux. Here is my latest.log
[latest.log](https://github.com/Chocohead/OptiFabric/files/6763056/latest.log)
Edit: thanks @Chucky2401, 1.11.1 works indeed

**Comment by RubixDev** [comment]
Same for me:
```
[11:00:39] [main/FATAL]: Mixin apply failed mixins.jgui.json:MixinKeyboardListener -> net.minecraft.class_309: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on mixins.jgui.json:MixinKeyboardListener->@Inject::keyPressed(I[ZLnet/minecraft/class_4069;IIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (I[ZIIILnet/minecraft/class_4069;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (I[ZLnet/minecraft/class_4069;IIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> mixins.jgui.json:MixinKeyboardListener -> Apply Injections ->  -> Inject -> mixins.jgui.json:MixinKeyboardListener->@Inject::keyPressed(I[ZLnet/minecraft/class_4069;IIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on mixins.jgui.json:MixinKeyboardListener->@Inject::keyPressed(I[ZLnet/minecraft/class_4069;IIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (I[ZIIILnet/minecraft/class_4069;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (I[ZLnet/minecraft/class_4069;IIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> mixins.jgui.json:MixinKeyboardListener -> Apply Injections ->  -> Inject -> mixins.jgui.json:MixinKeyboardListener->@Inject::keyPressed(I[ZLnet/minecraft/class_4069;IIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:517) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:447) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) [fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_202]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_202]
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583) [?:1.8.0_202]
	at java.lang.Class.getDeclaredFields(Class.java:1916) [?:1.8.0_202]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) [Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:530) [Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_559(class_128.java:101) [intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:54) [intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:425) [intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:135) [intermediary-fabric-loader-0.11.6-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
```
With 1.11.1 works as expected

**Comment by Coadon** [comment]
Same here~
[latest.log](https://github.com/Chocohead/OptiFabric/files/6788210/latest.log)
