### ISSUE TITLE
Maybe incompatible with 1.17.1 preview releases

### ISSUE THREAD

**Issue by akyag** [Chocohead/OptiFabric#294]
I am getting this error in MultiMC - 
```
[11:41:49] [main/INFO]: Loading for game Minecraft 1.17.1
[11:41:50] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[11:42:00] [ForkJoinPool-1-worker-7/WARN]: Non-Fabric mod JAR at "/media/data/games/videogames/MultiMC-linux64/instances/21w08b/.minecraft/mods/preview_OptiFine_1.17_HD_U_G9_pre24.jar", ignoring
[11:42:00] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: optifabric requires {minecraft @ [1.16.1 || 1.16.2 || 1.16.3 || 1.16.4 || 1.16.5 || 1.17-alpha.21.8.b || 1.17-beta.4 || 1.17]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195) ~[fabric-loader-0.11.6.jar:?]
	... 13 more
```
Maybe you can add the pre release version to the mods compatibility test or something? I am not really sure here but that's what it looks like on the surface. Mod works fine when I change minecraft version back to 1.17

**Comment by mattrose** [comment]
1.17.1 is now released, and I'm getting this with the default MC launcher.

**Comment by Thorkull** [comment]
I'm seeing this as well. I was working fine with Optifabric 1.11.1 under MC 1.17, but it's not working now with 1.17.1:

``Using onesix launcher.

[20:58:02] [main/INFO]: Loading for game Minecraft 1.17.1
[20:58:02] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: optifabric requires {minecraft @ [1.16.1 || 1.16.2 || 1.16.3 || 1.16.4 || 1.16.5 || 1.17-alpha.21.8.b || 1.17-beta.4 || 1.17]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195) ~[fabric-loader-0.11.6.jar:?]
	... 13 more
Process exited with code 1.`

It looks to me like it's just failing the version number check.

**Comment by RubixDev** [comment]
1.17.1 is just not in the list of supported versions in [fabric.mod.json](https://github.com/Chocohead/OptiFabric/blob/d4e22bc6082c32bf58696c58c768727b48400a4c/src/main/resources/fabric.mod.json#L36), but there is already a PR adding it: #300

**Comment by akyag** [comment]
Only changing that doesn't work, I think. I tried. Optifine doesn't support 1.17.1 yet.

**Comment by akyag** [comment]
With latest optifine release, tha above method of adding version number to fabric.mod.json works. So do that until the PR is included. Cheers!

**Comment by hacooke** [comment]
How can I add this? Would I have to manually compile the jar?

Alternatively does someone have a version of the jar with this fix that they could share for now?

**Comment by birdhimself** [comment]
@Hazza4569 You can open the `.jar` file with WinRAR (or 7-Zip probably, I used WinRAR anyways) and in the archive there's a file called `fabric.mod.json`. Open it (with a text editor) and add `"1.17.1"` to the `"depends.minecraft"` array. Save it and the archiver should ask if you want to save it back to the archive (say yes). That's all.

I could share my `.jar`, but inofficial builds probably shouldn't be linked in the issue section.
