### ISSUE TITLE
There was an error loading Optifabric

### ISSUE THREAD

**Issue by IchigoRedPanda** [Chocohead/OptiFabric#316]
I've tried everything but it keeps giving me this message even tho i have the folder in my mod folder 

https://cdn.discordapp.com/attachments/673293236827193352/865208530651054110/unknown.png

**Comment by brawaru** [comment]
> i have the folder in my mod folder

What folder in mod folder?

Aside from OptiFabric mod you need to download OptiFine JAR for your Minecraft version [from the official OptiFine site](https://optifine.net/downloads) and drop it in `mods` folder too.

<p align=center>
<img src="https://user-images.githubusercontent.com/10401817/125800799-759da1e2-c3cd-4733-8075-467c89f89147.png" alt="Screenshot of two files in mods folder: optifabric-1.11.9.jar and OptiFine_1.16.5_HD_U_G8.jar">
</p>

**Comment by karstenzip** [comment]
I have the same problem. This is the stack-trace:
java.io.UncheckedIOException: Error transforming C:\Users\karst\AppData\Roaming\.minecraft\.optifine\OptiFine_1.17.1_HD_U_G9_pre29\Optifine-mod.jar
	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:108)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:128)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:667)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:542)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:191)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:143)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1587)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1441)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1450)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1263)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:706)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:240)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:171)
	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:135)
	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:105)
	... 28 more

**Comment by leetfin** [comment]
Try deleting the .optifine folder and relaunching

**Comment by karstenzip** [comment]
Thanks! That worked!
