### ISSUE TITLE
OptiFabric failed to load despite using the 1.17.x version

### ISSUE THREAD

**Issue by Potato22** [Chocohead/OptiFabric#328]
OUTPUT
![image](https://user-images.githubusercontent.com/39096741/126825194-5d4a7e39-8eb7-4769-9a5e-b494f5b6b511.png)

I looked over other issues which involve adding the optifine jar mod into the mods folder, I did that but still got the same result. I'm afraid this might be a duplicate of an existing issue but so far I haven't seen one as relevant, let me know if that happens regardless.

"mods folder"
![image](https://user-images.githubusercontent.com/39096741/126825549-aefb551d-82a5-4a85-be03-acf929bc5397.png)

"the OptiFabric fabric.mod.json"
![image](https://user-images.githubusercontent.com/39096741/126825828-f5916a5e-381e-4602-b17e-e1979a8e878b.png)

LOG:
`Error encountered during mixin config postInit step'mixins.mm.json': Failed to setup optifine
java.lang.RuntimeException: Failed to setup optifine
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:54)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:667)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:542)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:191)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:143)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.RuntimeException: An error occurred when trying to find the optifine jar: INCOMPATIBLE
	at me.modmuss50.optifabric.mod.OptifineVersion.findOptifineJar(OptifineVersion.java:44)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:62)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	... 26 more`

EDIT: I noticed that the message said it couldn't read the optifine version "1.16.x G8", which is confusing knowing that this mod is for 1.17.x

**Comment by thatDudo** [comment]
I would suggest redownloading the optifine jar file from here: https://www.optifine.net/downloads
Select the latest version even though they are all previews. Its quite strange that your optifine file is actually not a preview.

**Comment by Potato22** [comment]
what do you mean? it's a "pre26" optifine in the folder, which is the most latest preview of OF at the time of uploading this issue.

**Comment by thatDudo** [comment]
This is the filename I get from downloading: `preview_OptiFine_1.17.1_HD_U_G9_pre32.jar`.
Dude just redownload.

**Comment by Potato22** [comment]
Whoops, forgot to update. The issue is solved by installing the new latest optifine jar MOD which might happen the be doing the same, thank you for replying even though I don't entirely appreciate your pushy suggestion.
