### ISSUE TITLE
Guys help idk why this error is coming i have attached a stack trace down below

### ISSUE THREAD

**Issue by KB3921** [Chocohead/OptiFabric#354]
java.io.UncheckedIOException: Error modifying C:\Users\Rutuja\AppData\Roaming\.minecraft\.optifine\OptiFine_1.17.1_HD_U_G9_pre33\Optifine-mapped.jar
	at me.modmuss50.optifabric.util.ZipUtils.transformInPlace(ZipUtils.java:128)
	at me.modmuss50.optifabric.util.ZipUtils.filterInPlace(ZipUtils.java:93)
	at me.modmuss50.optifabric.mod.OptifineSetup.generateClassCache(OptifineSetup.java:354)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:184)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:667)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:542)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:191)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:143)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.apache.commons.io.FileExistsException: Destination 'C:\Users\Rutuja\AppData\Roaming\.minecraft\.optifine\OptiFine_1.17.1_HD_U_G9_pre33\Optifine-mapped.jar' already exists
	at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2986)
	at me.modmuss50.optifabric.util.ZipUtils.transformInPlace(ZipUtils.java:126)
	... 30 more

**Comment by MissGamerz** [comment]
#357 <--- ur answer is in here
