### ISSUE TITLE
More Enchantments compatibility

### ISSUE THREAD

**Issue by 0xfeeddeadbeef** [Chocohead/OptiFabric#37]
The game crashes when [More Enchantments](https://www.curseforge.com/minecraft/mc-mods/fabric-more-enchantments/files/all) is used alongside the latest version of OptiFabric and OptiFine 1.16.2 HD U G3.

Without OptiFabric it does load and work as intended.

This is the contents of latest.log:

```
[22:33:27] [main/INFO]: Loading for game Minecraft 1.16.2
[22:33:28] [main/INFO]: [FabricLoader] Loading 43 mods: fabric-screen-handler-api-v1@1.1.0+872498414e, minecraft@1.16.2, fabric-renderer-api-v1@0.3.0+8bcfced84e, fabric-networking-blockentity-v0@0.2.5+b50ffc7b4e, fabric-keybindings-v0@0.2.0+3fa9f7c54e, fabric-command-api-v1@1.0.8+5ce533984e, fabricloader@0.9.2+build.206, fabric-tool-attribute-api-v1@1.2.2+ccce563e4e, fabric-structure-api-v1@1.0.1+fb0d9b0e4e, fabric-renderer-indigo@0.4.0+8bcfced84e, moenchantments@1.13.6, fabric-containers-v0@0.1.8+045df74f4e, fabric-object-builder-api-v1@1.7.0+432ea1884e, fabric-item-api-v1@1.1.0+29679fd64e, fabric-crash-report-info-v1@0.1.2+b7f9825d4e, fabric-events-interaction-v0@0.4.0+e2e6cdad4e, fabric-game-rule-api-v1@1.0.1+91555cd14e, fabric-api-base@0.1.3+12a8474c4e, fabric-rendering-v0@1.1.0+534104904e, fabric-rendering-v1@1.3.0+432ea1884e, fabric-key-binding-api-v1@1.0.1+730711c64e, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d4e, mm@2.1, fabric-resource-loader-v0@0.3.1+facf3bbf4e, fabric-textures-v0@1.0.4+eae12eb84e, fabric-content-registries-v0@0.1.9+059ea8664e, fabric-tag-extensions-v0@1.0.3+ac8e8c594e, optifabric@1.4.9, fabric-rendering-fluids-v1@0.1.11+fb0d9b0e4e, fabric-commands-v0@0.2.0+52d308364e, fabric-registry-sync-v0@0.4.5+fcdfdfa14e, fabric-blockrenderlayer-v1@1.1.4+c6a8ea894e, fabric-lifecycle-events-v1@1.2.0+74cc3b204e, fabric-mining-levels-v0@0.1.2+b764ce994e, fabric-renderer-registries-v1@2.1.0+e2862de64e, fabric-loot-tables-v1@1.0.1+432ea1884e, fabric-events-lifecycle-v0@0.2.0+16acbe5b4e, fabric@0.20.1+build.401-1.16, fabric-particles-v1@0.2.2+fb0d9b0e4e, fabric-models-v0@0.1.0+dfdb52d64e, fabric-item-groups-v0@0.2.0+438f96364e, fabric-object-builders-v0@0.7.0+432ea1884e, fabric-networking-v0@0.1.10+e00ecb5f4e
[22:33:28] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.1 Source=file:/C:/Users/Administrator/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.1+build.21/sponge-mixin-0.8.1+build.21.jar Service=Knot/Fabric Env=CLIENT
[22:33:28] [main/FATAL]: Mixin prepare failed preparing net/minecraft/class_156$1 in mixins.mm.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: mixins.mm.json:net/minecraft/class_156$1 target net.minecraft.class_156$1 was loaded too early.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.mm.json:net/minecraft/class_156$1 target net.minecraft.class_156$1 was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:938) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:872) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:668) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:440) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:416) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.9.2+build.206.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-loader-0.9.2+build.206.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) [?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:427) [?:?]
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:251) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.2+build.206.jar:?]
```

**Comment by Chocohead** [comment]
This is an issue in what More Enchantments is doing in its Mixin plugin. They're [using the Minecraft class `Util`](https://gitlab.com/biom4st3r/moenchantments/-/blob/default/src/main/java/com/biom4st3r/moenchantments/Plugin.java#L36), which is a big no-no as it means no mod can apply Mixins to it.
