### ISSUE TITLE
Crashing on Chunk Generation

### ISSUE THREAD

**Issue by fadillzzz** [Chocohead/OptiFabric#39]
I recently updated OptiFabric 1.14.10 and have started having this issue in my single player world.

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 06/09/20 17:34
Description: Exception ticking world

java.lang.UnsatisfiedLinkError: net.minecraft.class_3898.onChunkGenerated(Lnet/minecraft/class_3193;Lnet/minecraft/class_2791;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V
	at net.minecraft.class_3898.onChunkGenerated(Native Method)
	at net.minecraft.class_3898.handler$big000$doOnChunkGenerated(class_3898.java:3715)
	at net.minecraft.class_3898.lambda$null$17(class_3898.java:678)
	at net.minecraft.class_3898$$Lambda$6097/996524117.apply(Unknown Source)
	at net.minecraft.class_2806.method_17034(class_2806.java:112)
	at net.minecraft.class_2806$$Lambda$1945/656508392.doWork(Unknown Source)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.lambda$null$18(class_3898.java:677)
	at net.minecraft.class_3898$$Lambda$6095/1547825010.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.lambda$chunkGenerate$20(class_3898.java:675)
	at net.minecraft.class_3898$$Lambda$6092/727858680.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3900$$Lambda$6016/1251737767.run(Unknown Source)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	at net.minecraft.class_3846.run(class_3846.java:105)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_3898.onChunkGenerated(Native Method)
	at net.minecraft.class_3898.handler$big000$doOnChunkGenerated(class_3898.java:3715)
	at net.minecraft.class_3898.lambda$null$17(class_3898.java:678)
	at net.minecraft.class_3898$$Lambda$6097/996524117.apply(Unknown Source)
	at net.minecraft.class_2806.method_17034(class_2806.java:112)
	at net.minecraft.class_2806$$Lambda$1945/656508392.doWork(Unknown Source)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.lambda$null$18(class_3898.java:677)
	at net.minecraft.class_3898$$Lambda$6095/1547825010.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.lambda$chunkGenerate$20(class_3898.java:675)
	at net.minecraft.class_3898$$Lambda$6092/727858680.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3900$$Lambda$6016/1251737767.run(Unknown Source)

-- Affected level --
Details:
	All players: 1 total; [class_3222['fadillzzz'/4860, l='ServerLevel[New World]', x=219.83, y=70.80, z=-219.26]]
	Chunk stats: ServerChunkCache: 3552
	Level dimension: minecraft:overworld
	Level spawn location: World: (-240,66,160), Chunk: (at 0,4,0 in -15,10; contains blocks -240,0,160 to -225,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 390049 game time, 395349 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 14835 (now: true), thunder time: 9417 (now: true)
	Known server brands: vanilla, forge, fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:808)
	at net.minecraft.class_1132.method_3748(class_1132.java:120)
	at net.minecraft.server.MinecraftServer.handler$bbj000$modifiedRunLoop(MinecraftServer.java:3797)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:648)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
	at net.minecraft.server.MinecraftServer$$Lambda$5904/933717156.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 886669168 bytes (845 MB) / 2080374784 bytes (1984 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 20
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		blue_endless_jankson: jankson +
		carpet: Carpet Mod in Fabric 1.4.9
		carpet-extra: Carpet Extra 1.4.8
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.7.0-unstable
		fabric: Fabric API 0.20.1+build.401-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c4e
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd64e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1884e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.7.0+432ea1884e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea1884e
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e4e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.5+fcdfdfa14e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.0+8bcfced84e
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.0+8bcfced84e
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.11+fb0d9b0e4e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.0+432ea1884e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-structure-api-v1: Fabric Structure API (v1) 1.0.1+fb0d9b0e4e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e4e
		fabricloader: Fabric Loader 0.9.3+build.207
		fiber: fiber 0.23.0-2
		inventorysorter: Inventory Sorter 1.7.2-1.16
		kyrptconfig: Kytpt Config 1.1.2-1.16
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		minecraft: Minecraft 1.16.2
		minihud: MiniHUD 0.19.0-dev.20200819.013355
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 1.14.6+build.31
		multiconnect: MultiConnect 1.3.18
		multiconnect-api: MultiConnect API 1.3.18
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		optifabric: OptiFabric 1.4.10
		tweakeroo: Tweakeroo 0.10.0-dev.20200903.015620
	Player Count: 1 / 8; [class_3222['fadillzzz'/4860, l='ServerLevel[New World]', x=219.83, y=70.80, z=-219.26]]
	Data Packs: vanilla (incompatible), fabric/fabric-tool-attribute-api-v1
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
	OptiFine Version: OptiFine_1.16.2_HD_U_G3
	OptiFine Build: 20200829-104659
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: ComplementaryShaders 3.02.zip
	OpenGlVersion: 4.6.0 NVIDIA 452.06
	OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 20
```

**Comment by Chocohead** [comment]
Bit of an accident with the 1.4.10 jar I think, the 1.5.0 one should be fine however.
