### ISSUE TITLE
Incompatible to fabric loader 12.2

### ISSUE THREAD

**Issue by gapGoat** [Chocohead/OptiFabric#398]
not compatible to fabric loader 12.2

**Comment by 0xfeeddeadbeef** [comment]
Full error stack trace:

```
net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'OptiFabric' (optifabric) 1.11.20 (H:\minecraft1171\mods\optifabric-1.11.20.jar).
Unmet dependency listing:
	 - Mod 'OptiFabric' (optifabric) requires any version between 0.8.0 (inclusive) and 0.12 (exclusive) of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.12.2!
		 - Mod 'Fabric Loader' (fabricloader) 0.12.2 is being loaded from C:\Users\User\AppData\Roaming\.minecraft\libraries\net\fabricmc\fabric-loader\0.12.2\fabric-loader-0.12.2.jar
Inactive mods:
	 - mod 'OptiFabric' (optifabric) 1.11.20, reason: to remove
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.34, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b44633d, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+c88702897d, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.7+b7ab61213d, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.8+a00e834b18, reason: same version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.4+198a96213d, reason: newer version active
	 - mod 'Manningham Mills' (mm) 2.3, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:203)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:183)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:119)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by 0xfeeddeadbeef** [comment]
Here's a modified version which works with fabric-loader 0.12.*:

[optifabric-1.11.20.jar](https://storage.googleapis.com/optifabric/optifabric-1.11.20.jar)

[VirusTotal scan results](https://www.virustotal.com/gui/file/69d14126249e858324f662d5d02a5d7f61ba16485174e87f4439ca221c9ff520)
