### ISSUE TITLE
Issue with optifine 1.16.15

### ISSUE THREAD

**Issue by ArgonRetter** [Chocohead/OptiFabric#403]
**I recently tried to get optifine to work with fabric. I was using fabric before, and after adding optifabric and optifine it keeps giving me:** 

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
Exit Code: -1

**Here's the crash report:**

---- Minecraft Crash Report ----
// There are four lights!

Time: 10/22/21 1:36 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.optifine.CustomColors.getWorldSkyColor(CustomColors.java:1555)
	at net.minecraft.class_758.method_3210(class_758.java:89)
	at com.mamiyaotaru.voxelmap.Map.getSkyColor(Map.java:1037)
	at com.mamiyaotaru.voxelmap.Map.calculateCurrentLightAndSkyColor(Map.java:1008)
	at com.mamiyaotaru.voxelmap.Map.onTickInGame(Map.java:703)
	at com.mamiyaotaru.voxelmap.VoxelMap.onTickInGame(VoxelMap.java:189)
	at com.mamiyaotaru.voxelmap.fabricmod.FabricModVoxelMap.renderOverlay(FabricModVoxelMap.java:74)
	at net.minecraft.class_329.handler$zef000$onRenderGameOverlay(class_329.java:2831)
	at net.minecraft.class_329.method_1753(class_329.java:439)
	at net.minecraft.class_757.method_3192(class_757.java:765)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.optifine.CustomColors.getWorldSkyColor(CustomColors.java:1555)
	at net.minecraft.class_758.method_3210(class_758.java:89)
	at com.mamiyaotaru.voxelmap.Map.getSkyColor(Map.java:1037)
	at com.mamiyaotaru.voxelmap.Map.calculateCurrentLightAndSkyColor(Map.java:1008)
	at com.mamiyaotaru.voxelmap.Map.onTickInGame(Map.java:703)
	at com.mamiyaotaru.voxelmap.VoxelMap.onTickInGame(VoxelMap.java:189)
	at com.mamiyaotaru.voxelmap.fabricmod.FabricModVoxelMap.renderOverlay(FabricModVoxelMap.java:74)
	at net.minecraft.class_329.handler$zef000$onRenderGameOverlay(class_329.java:2831)
	at net.minecraft.class_329.method_1753(class_329.java:439)

-- Affected level --
Details:
	All players: 6 total; [class_746['Argon_Retter'/302386, l='ClientLevel', x=2.51, y=67.00, z=-28.59], class_745['die3dietrichs'/302384, l='ClientLevel', x=2.51, y=67.00, z=-28.59], class_745['Tara_Belle'/302367, l='ClientLevel', x=2.42, y=69.50, z=-26.18], class_745['§d§l§oMini-Games'/1761, l='ClientLevel', x=8.50, y=69.00, z=-71.43], class_745['§a§l§oCreative'/1758, l='ClientLevel', x=-3.51, y=69.00, z=-71.51], class_745['§6§l§oRathnir'/1767, l='ClientLevel', x=-0.55, y=69.00, z=-76.53]]
	Chunk stats: Client Chunk Cache: 169, 81
	Level dimension: minecraft:overworld
	Level spawn location: World: (2,67,-29), Chunk: (at 2,4,3 in 0,-2; contains blocks 0,0,-32 to 15,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 124878 game time, 8605500 day time
	Server brand: Waterfall <- Airplane
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:617)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 702813416 bytes (670 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancedchat: AdvancedChat 3.2.0-1.16.5
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.11.14
		crowdin-translate: CrowdinTranslate 1.2
		durabilityviewer: Giselbaers Durability Viewer 1.16.5-fabric0.30.0-1.10
		fabric: Fabric API 0.39.2+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+2b6fb8d77d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+efd7b8cf7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+95b14da07d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+5badb62d7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.2+2f5f89687d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.3+f941baf07d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.1+kotlin.1.5.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.4+5badb62d7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+f3e8589e7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+6afaa13c7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+ca0ef93d7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.2.0+e1956bbf7d
		fabricloader: Fabric Loader 0.11.7
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		horsestatsvanilla: Horse Stats Vanilla 4.1.7
		inventoryhud: Inventory HUD + 3.4.0
		inventoryprofiles: Inventory Profiles 0.4.2
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		libgui: LibGui 3.3.5+1.16.5
		malilib: MaLiLib 0.10.0-dev.21+arne.5
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.2
		modmenu: Mod Menu 1.16.12
		optifabric: OptiFabric 1.11.9
		orderly: Orderly 2.0.0-alpha.10-1.16
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		voxelmap: VoxelMap 1.10.15
		waila: Hwyla 1.9.22
	Launched Version: fabric-loader-0.11.7-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 48
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: ComplementaryShaders_v4.1.zip
	OpenGlVersion: 4.6.0 NVIDIA 456.71
	OpenGlRenderer: GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.5
	OptiFine jar version: OptiFine_1.16.5_HD_U_G8
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/erago/AppData/Roaming/.minecraft/.optifine/OptiFine_1.16.5_HD_U_G8/Optifine-mapped.jar
	OptiFabric error: <None>

**I am not a coder and have no real idea what any of this means. Any help is appreciated.**

**Comment by TheeSplatt** [comment]
Same thing is happening with me, I hope this gets fixed soon cuz my potato laptop has huge lagspikes
