### ISSUE TITLE
OptiFabric canot find OptiFine HD U H1 1.17.1

### ISSUE THREAD

**Issue by CERIBES** [Chocohead/OptiFabric#419]
The when the game loads and its almost done I get an error MSG that optifabric cannot find optfine jar.
![Optifabric](https://user-images.githubusercontent.com/76491480/140285677-04aad8eb-d5b6-4d63-95db-134b85485e4c.jpg)

OptiFine HD U H1 1.17.1

Fabric Loader 0.11.7

Optifabric 1.11.20

**Comment by 0xfeeddeadbeef** [comment]
I have tried the workaround described in [#374](https://github.com/Chocohead/OptiFabric/issues/374#issuecomment-924491077), and it does not work anymore:

```
java.lang.NoSuchMethodError: 'net.fabricmc.loader.game.GameProvider net.fabricmc.loader.FabricLoader.getGameProvider()'
	at me.modmuss50.optifabric.mod.OptifineSetup.getLaunchMinecraftJar(OptifineSetup.java:338)
	at me.modmuss50.optifabric.mod.OptifineSetup.getMinecraftJar(OptifineSetup.java:316)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:96)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:134)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by CERIBES** [comment]
Reverted back to Optifine U G9 version and everything loaded ok.

**Comment by Rezanans-wow** [comment]
Same

**Comment by thiagogebrimm** [comment]
Same

**Comment by iBrezz** [comment]
> Reverted back to Optifine U G9 version and everything loaded ok.

If i use optifine u g9 i still dont work idk why

**Comment by drathmorgh** [comment]
I would love to go back to G9 but it doesn't show the custom Shulker inventory. as this is a key feature for me it looks like I'm waiting until it's resolved.
