### ISSUE TITLE
OptiFabric Don't work on Fabric 0.11.X to 0.12.X with OptiFine_1.17.1 HD U G9

### ISSUE THREAD

**Issue by Maxime66410** [Chocohead/OptiFabric#421]
Hello, it is totally impossible to be able to use OptiFabric under all possible versions, a crash returning an error code 0 with no error in the logs.

Basics log of the launcher :

`[01:22:10] [main/INFO]: Loading for game Minecraft 1.17.1
[01:22:10] [ForkJoinPool-1-worker-9/WARN]: Non-Fabric mod JAR at "C:\Users\max66\AppData\Roaming\.minecraft\mods\OptiFine_1.17.1_HD_U_G9.jar", ignoring
[01:22:10] [main/INFO]: [FabricLoader] Loading 61 mods:
	- apoli@2.0.5
	- calio@1.3.0
	- cardinal-components-base@3.1.1
	- cardinal-components-entity@3.1.1
	- cloth-basic-math@0.5.1
	- cloth-config2@5.0.34
	- fabric@0.42.0+1.17
	- fabric-api-base@0.4.0+5847535018
	- fabric-api-lookup-api-v1@1.3.1+5847535018
	- fabric-biome-api-v1@3.2.2+5847535018
	- fabric-blockrenderlayer-v1@1.1.6+5847535018
	- fabric-command-api-v1@1.1.4+5847535018
	- fabric-commands-v0@0.2.3+5847535018
	- fabric-containers-v0@0.1.13+5847535018
	- fabric-content-registries-v0@0.3.1+5847535018
	- fabric-crash-report-info-v1@0.1.6+5847535018
	- fabric-dimensions-v1@2.0.13+5847535018
	- fabric-entity-events-v1@1.3.1+5847535018
	- fabric-events-interaction-v0@0.4.11+5847535018
	- fabric-events-lifecycle-v0@0.2.2+5847535018
	- fabric-game-rule-api-v1@1.0.8+5847535018
	- fabric-item-api-v1@1.2.5+5847535018
	- fabric-item-groups-v0@0.3.1+5847535018
	- fabric-key-binding-api-v1@1.0.5+5847535018
	- fabric-keybindings-v0@0.2.3+5847535018
	- fabric-lifecycle-events-v1@1.4.5+5847535018
	- fabric-loot-tables-v1@1.0.5+5847535018
	- fabric-mining-level-api-v1@1.0.1+5847535018
	- fabric-mining-levels-v0@0.1.4+5847535018
	- fabric-models-v0@0.3.1+5847535018
	- fabric-networking-api-v1@1.0.14+5847535018
	- fabric-networking-blockentity-v0@0.2.12+5847535018
	- fabric-networking-v0@0.3.3+5847535018
	- fabric-object-builder-api-v1@1.10.10+5847535018
	- fabric-object-builders-v0@0.7.4+5847535018
	- fabric-particles-v1@0.2.5+5847535018
	- fabric-registry-sync-v0@0.7.13+5847535018
	- fabric-renderer-api-v1@0.4.5+5847535018
	- fabric-renderer-indigo@0.4.9+5847535018
	- fabric-renderer-registries-v1@3.2.5+5847535018
	- fabric-rendering-data-attachment-v1@0.1.6+5847535018
	- fabric-rendering-fluids-v1@0.2.0+5847535018
	- fabric-rendering-v0@1.1.6+5847535018
	- fabric-rendering-v1@1.10.0+5847535018
	- fabric-resource-loader-v0@0.4.9+5847535018
	- fabric-screen-api-v1@1.0.5+5847535018
	- fabric-screen-handler-api-v1@1.1.9+5847535018
	- fabric-structure-api-v1@1.1.14+5847535018
	- fabric-tag-extensions-v0@1.2.2+5847535018
	- fabric-textures-v0@1.0.7+5847535018
	- fabric-tool-attribute-api-v1@1.3.0+5847535018
	- fabric-transfer-api-v1@1.5.0+5847535018
	- fabricloader@0.11.7
	- fallflyinglib@3.0.0-beta.2
	- java@16
	- minecraft@1.17.1
	- mm@2.3
	- optifabric@1.11.20
	- origins@1.1.4
	- playerabilitylib@1.3.0
	- reach-entity-attributes@2.1.1
[01:22:10] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/max66/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[01:22:10] [main/INFO]: Compatibility level set to JAVA_16
[01:22:11] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[01:22:13] [main/ERROR]: Critical injection failure: LVT in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V has incompatible changes at opcode 969 in callback net/minecraft/class_761::getEntity.
Expected: [Lnet/minecraft/class_3695;, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, Lnet/minecraft/class_4597$class_4598;, Ljava/util/Iterator;, Lnet/minecraft/class_1297;]
   Found: [Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, I]
`

**Comment by StayKwimp** [comment]
Weird, it works for me (with fabric 0.11.7 1.17.1 and OF G9). Do you have any other mods installed in your mods folder?

On a side note, I can find an error in the log you sent: 

> [01:22:13] [main/ERROR]: Critical injection failure: LVT in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V has incompatible changes at opcode 969 in callback net/minecraft/class_761::getEntity. Expected: [Lnet/minecraft/class_3695;, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, Lnet/minecraft/class_4597$class_4598;, Ljava/util/Iterator;, Lnet/minecraft/class_1297;] Found: [Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, I]

**Comment by SkeleBones** [comment]
I seem to be having a similar issue. I tried to use the newer version of Optifine which doesn't work so I reinstalled G9 which also doesn't work now for some reason. 

java.lang.NoSuchMethodError: 'net.fabricmc.loader.game.GameProvider net.fabricmc.loader.FabricLoader.getGameProvider()'
	at me.modmuss50.optifabric.mod.OptifineSetup.getLaunchMinecraftJar(OptifineSetup.java:338)
	at me.modmuss50.optifabric.mod.OptifineSetup.getMinecraftJar(OptifineSetup.java:316)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:96)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:134)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by SkeleBones** [comment]
I seem to be having a similar issue. I tried to use the newer version of optifine which doesn't work so I reinstalled G9 which also doesn't work now for some reason. I am using the modified version of OptiFabric so I can use it on the new version of Fabric. It worked before I tried to use the newer version of Optifine.

Stack-Trace

java.lang.NoSuchMethodError: 'net.fabricmc.loader.game.GameProvider net.fabricmc.loader.FabricLoader.getGameProvider()'
	at me.modmuss50.optifabric.mod.OptifineSetup.getLaunchMinecraftJar(OptifineSetup.java:338)
	at me.modmuss50.optifabric.mod.OptifineSetup.getMinecraftJar(OptifineSetup.java:316)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:96)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:134)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Maxime66410** [comment]
> Weird, it works for me (with fabric 0.11.7 1.17.1 and OF G9). Do you have any other mods installed in your mods folder?
> 
> On a side note, I can find an error in the log you sent:
> 
> > [01:22:13] [main/ERROR]: Critical injection failure: LVT in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V has incompatible changes at opcode 969 in callback net/minecraft/class_761::getEntity. Expected: [Lnet/minecraft/class_3695;, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, Lnet/minecraft/class_4597$class_4598;, Ljava/util/Iterator;, Lnet/minecraft/class_1297;] Found: [Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, I]

I have just Origins and OptiFabric.

**Comment by C4uTi0N** [comment]
Someone fixed the version issue in this post:
https://github.com/Chocohead/OptiFabric/issues/410
