### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Felix0163** [Chocohead/OptiFabric#426]
net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'OptiFabric' (optifabric) 1.11.20 (C:\Users\Felix\AppData\Roaming\.minecraft\mods\optifabric-1.11.20.jar).
Unmet dependency listing:
	 - Mod 'OptiFabric' (optifabric) requires any version between 0.8.0 (inclusive) and 0.12 (exclusive) of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.12.5!
		 - Mod 'Fabric Loader' (fabricloader) 0.12.5 is being loaded from C:\Users\Felix\AppData\Roaming\.minecraft\libraries\net\fabricmc\fabric-loader\0.12.5\fabric-loader-0.12.5.jar
Inactive mods:
	 - mod 'OptiFabric' (optifabric) 1.11.20, reason: to remove
	 - mod 'Manningham Mills' (mm) 2.3, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:203)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:183)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:119)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

what am I doing wrong ? I tried to change version of anything but to no avail

**Comment by MysticMia** [comment]
(Not a developer) It's because you're using the latest Fabric version: 0.12.5; and the developer of OptiFabric hasn't updated the mod yet. A solutions are to: go back to 0.11, wait until the mod updates, or remove the mod until it updates.

**Comment by ZekerZhayard** [comment]
same as https://github.com/Chocohead/OptiFabric/issues/394

**Comment by headhuntercertified** [comment]
is someoe able to explain to me how to revert back to 0.11   i am stuck on 0.12.5
