### ISSUE TITLE
Can't seem to load version OptiFine 1.17.1_HD_U_H1 at all. 

### ISSUE THREAD

**Issue by plushycat** [Chocohead/OptiFabric#431]
Output Log:
https://pastebin.com/BGPSWQ29

In-game error:
![image](https://user-images.githubusercontent.com/70093629/141262790-6a89b203-74a7-4a86-a87f-ec51cd6b5327.png)

fabric loader version:
![image](https://user-images.githubusercontent.com/70093629/141262841-0448113d-5949-4633-9f2c-22f2a4e1e00c.png)

mods folder:
![image](https://user-images.githubusercontent.com/70093629/141262959-2dfb8f6f-682c-47c0-a934-b3447e28e410.png)

**Comment by aytimothy** [comment]
Looks like I'm not the only one having it. Also worth putting in the crash log, which for me (might not be same for you) is:

```java
[20:52:09] [main/ERROR]: Error encountered during mixin config postInit step'mixins.mm.json': Failed to setup optifine
java.lang.RuntimeException: Failed to setup optifine
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:54) ~[optifabric-1.11.20.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340) ~[16696742-5629-4941-a2e3-2e01b8b9f9d3.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:667) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:542) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.7.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-loader-0.11.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106) ~[fabric-loader-0.11.7.jar:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[?:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104) ~[fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:191) ~[fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:143) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.io.FileNotFoundException: Could not find optifine jar
	at me.modmuss50.optifabric.mod.OptifineVersion.findOptifineJar(OptifineVersion.java:67) ~[optifabric-1.11.20.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:62) ~[optifabric-1.11.20.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41) ~[optifabric-1.11.20.jar:?]
	... 34 more
[20:52:09] [main/WARN]: Error loading class: net/optifine/render/ChunkVisibility (java.lang.ClassNotFoundException: net/optifine/render/ChunkVisibility)
[20:52:09] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[20:52:09] [main/WARN]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersRender)
[20:52:09] [main/WARN]: Error loading class: net/coderbot/iris/uniforms/CommonUniforms (java.lang.ClassNotFoundException: net/coderbot/iris/uniforms/CommonUniforms)
[20:52:09] [main/WARN]: Error loading class: net/coderbot/iris/Iris (java.lang.ClassNotFoundException: net/coderbot/iris/Iris)
```

**Comment by TheGreenSquare** [comment]
Can reproduce. Same loader version too.

**Comment by VidTu** [comment]
There's already [a milestone](https://github.com/Chocohead/OptiFabric/milestone/3).

**Comment by ZekerZhayard** [comment]
https://github.com/Chocohead/OptiFabric/issues/374
