### ISSUE TITLE
Mod resolution encountered an incompatible mod set!

### ISSUE THREAD

**Issue by Ziondaman** [Chocohead/OptiFabric#436]
i cant run optifine just keep crashing 
and i trid older versons

error log dump:
net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'OptiFabric' (optifabric) 1.11.20 (C:\Users\user\AppData\Roaming\.minecraft\mods\optifabric-1.11.20.jar).
Unmet dependency listing:
	 - Mod 'OptiFabric' (optifabric) requires any version between 0.8.0 (inclusive) and 0.12 (exclusive) of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.12.0!
		 - Mod 'Fabric Loader' (fabricloader) 0.12.0 is being loaded from the mods directory or supplied through the command line.
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:140)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:41)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:197)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:183)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:119)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

the mods that i have installed:
voicechat-fabric-1.17.1-1.1.9
Pehkui-2.5.31.14.4-1.18
Origins-1.17-1.1.4
OptiFine_1.17.1_HD_U_G9
optifabric-1.11.20
moborigins-1.7.0
fabric-api-0.42.01.17
extraorigins-1.17-10(1)

**Comment by ZekerZhayard** [comment]
same as https://github.com/Chocohead/OptiFabric/issues/394

**Comment by Ziondaman** [comment]
ye it looks like it

**Comment by tinu1976ch** [comment]
looks like the problem with fabric-loader 0.12.5 is that in file
src/main/resources/fabric.mod.json
on line 35 the value should be <=0.12.5 instead of 0.12
how to change that?
