### ISSUE TITLE
Crash when opening option screen

### ISSUE THREAD

**Issue by domanhthang2110** [Chocohead/OptiFabric#461]
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method actionPerformed(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in optifabric.optifine.mixins.json:VideoOptionsScreenMixin from mod (unknown) failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap optifabric-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1381)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 32 more
`

**Comment by ZaneFlynt01** [comment]
I was using this with my brother last night and we couldn't open the options, chat, and some other things without our games crashing.

**Comment by domanhthang2110** [comment]
> I was using this with my brother last night and we couldn't open the options, chat, and some other things without our games crashing.

I redownloaded the mod and it works, maybe you try too

**Comment by Chocohead** [comment]
Duplicate of #455

You'll want to update to OptiFabric v1.12.2+

**Comment by PROGAMER1500** [comment]
its not working still
please help me

**Comment by PROGAMER1500** [comment]
nvm
i fixed it somehow
