### ISSUE TITLE
Error: optifine-mapped.jar

### ISSUE THREAD

**Issue by storiofmylife** [Chocohead/OptiFabric#462]
I'm not sure what's happening here. The only other mod I have is the replay mod. I'm using Fabric 11.7, Optifine H1, and I've tried both Optifabric 1.12.0 and 1.12.2. I've also tried using it on a fresh instance and it gives the same error. 

java.io.UncheckedIOException: Error modifying C:\Users\britt\Twitch\Minecraft\Instances\fwends\.optifine\OptiFine_1.17.1_HD_U_H1\Optifine-mapped.jar
	at me.modmuss50.optifabric.util.ZipUtils.transformInPlace(ZipUtils.java:152)
	at me.modmuss50.optifabric.util.ZipUtils.filterInPlace(ZipUtils.java:117)
	at me.modmuss50.optifabric.mod.OptifineSetup.generateClassCache(OptifineSetup.java:389)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:188)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:43)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:667)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:542)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:191)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:143)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.io.FileNotFoundException: C:\Users\britt\Twitch\Minecraft\Instances\fwends\.optifine\OptiFine_1.17.1_HD_U_H1\Optifine-mapped.jar (The process cannot access the file because it is being used by another process)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:343)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:258)
	at java.base/java.io.RandomAccessFile$2.openAndDelete(RandomAccessFile.java:1195)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1254)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:706)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:240)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:171)
	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:159)
	at me.modmuss50.optifabric.util.ZipUtils.transformInPlace(ZipUtils.java:147)
	... 30 more

**Comment by Crescidious** [comment]
same

java.io.UncheckedIOException: Error modifying C:\Users\Danie\curseforge\minecraft\Instances\Private\.optifine\OptiFine_1.17.1_HD_U_G9\Optifine-mapped.jar
	at me.modmuss50.optifabric.util.ZipUtils.transformInPlace(ZipUtils.java:152)
	at me.modmuss50.optifabric.util.ZipUtils.filterInPlace(ZipUtils.java:117)
	at me.modmuss50.optifabric.mod.OptifineSetup.generateClassCache(OptifineSetup.java:394)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:188)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:43)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.language.kotlin.KotlinAdapter.create(KotlinAdapter.java)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:134)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.io.FileNotFoundException: C:\Users\Danie\curseforge\minecraft\Instances\Private\.optifine\OptiFine_1.17.1_HD_U_G9\Optifine-mapped.jar (The process cannot access the file because it is being used by another process)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:343)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:258)
	at java.base/java.io.RandomAccessFile$2.openAndDelete(RandomAccessFile.java:1195)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1254)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:706)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:240)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:171)
	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:159)
	at me.modmuss50.optifabric.util.ZipUtils.transformInPlace(ZipUtils.java:147)
	... 26 more

**Comment by Otapic** [comment]
found the same issue on the latest versions, if you're ok with downgrading fabric to 0.11.7 and the fabric api to 0.39.x as well as optifabric to 1.11.20 it should work with any 1.17 OF versions

**Comment by Crescidious** [comment]
I found out what the issue was. If you go and right click on the .minecraft folder and uncheck "read only" the mapped.jar can be modified or whatever. The "read only" may come back but it somehow fixed everything regardless.

**Comment by storiofmylife** [comment]
The second solution didn't work with me, but the first one did! It wouldn't recognize optifine H1 but using G9 works fine! Thank you so much! @Otapic @Carinyc
