### ISSUE TITLE
Mixin transformation crash 1.18

### ISSUE THREAD

**Issue by Solarity991** [Chocohead/OptiFabric#491]
The game crashed whilst batching chunks
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_853 failed
Exit Code: 255

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 12/3/21, 6:35 PM
Description: Batching chunks

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_853 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:234)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_6850.method_39969(class_6850.java:64)
	at net.minecraft.class_846$class_851.createRegionRenderCache(class_846.java:1398)
	at net.minecraft.class_846$class_851.makeChunkCacheOF(class_846.java:1387)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:960)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:904)
	at net.minecraft.class_846.method_22757(class_846.java:195)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229)
	... 16 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fabric-rendering-data-attachment-v1.mixins.json:client.MixinChunkRendererRegion] from phase [DEFAULT] in config [fabric-rendering-data-attachment-v1.mixins.json] from mod [fabric-rendering-data-attachment-v1] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 19 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on init could not find any targets matching 'Lnet/minecraft/class_853;method_3689(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;I)Lnet/minecraft/class_853;' in net.minecraft.class_853. Using refmap fabric-rendering-data-attachment-v1-refmap.json [PREINJECT Applicator Phase -> fabric-rendering-data-attachment-v1.mixins.json:client.MixinChunkRendererRegion -> Prepare Injections ->  -> handler$zfk000$init(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;IIII[[Lnet/minecraft/class_2818;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at jdk.internal.reflect.GeneratedConstructorAccessor24.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:234)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_6850.method_39969(class_6850.java:64)

-- Affected level --
Details:
	All players: 1 total; [class_746['Solarity991'/211, l='ClientLevel', x=-53.11, y=70.00, z=80.07]]
	Chunk stats: 529, 293
	Level dimension: minecraft:overworld
	Level spawn location: World: (-48,70,64), Section: (at 0,6,0 in -3,4,4; chunk contains blocks -48,-64,64 to -33,319,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 34039 game time, 6000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:517)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_846.method_39958(class_846.java:206)
	at net.minecraft.class_310.method_1514(class_310.java:722)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, VanillaTweaks_r534408.zip

-- System Details --
Details:
	Minecraft Version: 1.18
	Minecraft Version ID: 1.18
	Operating System: Mac OS X (x86_64) version 12.0.1
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 812209808 bytes (774 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple G13G
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 9216.00
	Virtual memory used (MB): 6920.58
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 175.50
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.43.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cda9
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.5+3ac43d95a9
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+3ac43d95a9
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95a9
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95a9
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cda9
		fabric-containers-v0: Fabric Containers (v0) 0.1.17+3ac43d95a9
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73da9
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95a9
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571a9
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378aa9
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.15+3ac43d95a9
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.5+b4f4f6cda9
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95a9
		fabric-item-api-v1: Fabric Item API (v1) 1.2.7+3ac43d95a9
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95a9
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3a9
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cda9
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335a9
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95a9
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95a9
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cda9
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95a9
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95a9
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cda9
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.13+3ac43d95a9
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.7+3ac43d95a9
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1aca9
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95a9
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95a9
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95a9
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cda9
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.2.3+3ac43d95a9
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95a9
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cda9
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378aa9
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95a9
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95a9
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95a9
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7a9
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95a9
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95a9
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55a9
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.4+b4f4f6cda9
		fabricloader: Fabric Loader 0.12.8
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.18
		mm: Manningham Mills 2.3
		optifabric: OptiFabric 1.12.7
	Launched Version: fabric-loader-0.12.8-1.18
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: Apple M1 GL version 4.1 Metal - 76.1, Apple
	Window size: 1708x960
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/VanillaTweaks_r534408.zip
	Current Language: English (US)
	CPU: 8x Apple M1
	Server Running: true
	Player Count: 1 / 8; [class_3222['Solarity991'/211, l='ServerLevel[Test]', x=-53.11, y=70.00, z=80.07]]
	Data Packs: vanilla, Fabric Mods
	OptiFine Version: OptiFine_1.18_HD_U_H3_pre6
	OptiFine Build: 20211203-233335
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.29 Lite.zip
	OpenGlVersion: 4.1 Metal - 76.1
	OpenGlRenderer: Apple M1
	OpenGlVendor: Apple
	CpuCount: 8

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.18
	OptiFine jar version: OptiFine_1.18_HD_U_H3_pre6
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: /Users/braedenparker/Library/Application Support/minecraft/.optifine/OptiFine_1.18_HD_U_H3_pre6/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by INFINI7I** [comment]
Use OptiFine_1.18_HD_U_H3_pre5
I have same trouble too. On pre6 and higher Minecraft crushes when loading the world

**Comment by 4g0tt3nSou1** [comment]
> Use OptiFine_1.18_HD_U_H3_pre5 I have same trouble too. On pre6 and higher Minecraft crushes when loading the world

OptiFine isn't listing those builds any more, Care to share it? I am experiencing the same crash on both pre7/pre8

**Comment by DeanoLS** [comment]
> > Use OptiFine_1.18_HD_U_H3_pre5 I have same trouble too. On pre6 and higher Minecraft crushes when loading the world
> 
> OptiFine isn't listing those builds any more, Care to share it? I am experiencing the same crash on both pre7/pre8

I don't have pre5 downloaded but pre7 seems to work for me so you should try that instead. if you use my versions of mods it may work for you. fabric-api-0.44.0+ 1.18.jar, optifabric-1.12.7.jar. the fabric launcher version is 0.12.8-1.18

**Comment by Solarity991** [comment]
> > > Use OptiFine_1.18_HD_U_H3_pre5 I have same trouble too. On pre6 and higher Minecraft crushes when loading the world
> > 
> > 
> > OptiFine isn't listing those builds any more, Care to share it? I am experiencing the same crash on both pre7/pre8
> 
> I don't have pre5 downloaded but pre7 seems to work for me so you should try that instead. if you use my versions of mods it may work for you. fabric-api-0.44.0+ 1.18.jar, optifabric-1.12.7.jar. the fabric launcher version is 0.12.8-1.18

pre7 doesn't work for me, I might try on pre4, didn't get pre5 :/

**Comment by INFINI7I** [comment]
It's OptiFine_1.18_HD_U_H3_pre5
[OptiFine.zip](https://github.com/Chocohead/OptiFabric/files/7662272/OptiFine.zip)

**Comment by Mw3y** [comment]
I've tried multiple versions of Optifine and it still doesn't work. Here's my crash report: https://www.toptal.com/developers/hastebin/vukabufode.properties

**Comment by GlacialWaters** [comment]
> It's OptiFine_1.18_HD_U_H3_pre5 [OptiFine.zip](https://github.com/Chocohead/OptiFabric/files/7662272/OptiFine.zip)

Thanks, using this solved it for me.
