### ISSUE TITLE
OptiFabric + Minecraft 1.18.1

### ISSUE THREAD

**Issue by PetyXbron** [Chocohead/OptiFabric#519]
Fabric error
```
Mod 'OptiFabric' (optifabric) 1.12.7 requires version 1.16.1, version 1.16.2, version 1.16.3, version 1.16.4, version 1.16.5, version 1.17-alpha.21.8.b, version 1.17-beta.4, version 1.17, version 1.17.1, version 1.18-beta.1 or version 1.18 of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1-beta.1!
```
Can you please update OptiFabric to **Minecraft 1.18.1**?
Using **OptiFine HD U H4 pre1**

**Comment by fayearth** [comment]
Same here #511 
You can try temporary solution there until choco updates optifabric

**Comment by Cagomei** [comment]
what is the temporary fix

**Comment by fayearth** [comment]
[#511](https://github.com/Chocohead/OptiFabric/issues/511#issuecomment-991844190)

**Comment by ChromesDuzez** [comment]
if you had to guess how long do you think we'll have to wait for an official 1.18.1 release from choco?

**Comment by PetyXbron** [comment]
> [#511](https://github.com/Chocohead/OptiFabric/issues/511#issuecomment-991844190)

@fayearth did you fixed the bug with FabricAPI? 🤔

**Comment by fayearth** [comment]
No. Optifine (H3 or above) and Optifabric (https://github.com/Chocohead/OptiFabric/files/7698247/Optifabric-Artifact.zip) works fine without FabricAPI in the mod folder

**Comment by fayearth** [comment]
No. Optifine (H3 or above) and optifabric ([Optifabric-Artifact.zip](https://github.com/Chocohead/OptiFabric/files/7698247/Optifabric-Artifact.zip)) works fine without fabricAPI in the mod folder.
So, the only thing we can do right now is remove fabricAPI and all mods that depend on it (99% of fabric mods)

**Comment by mkikets99** [comment]
Just for info: Changing `depends -> minecraft -> + 1.18.1` in [fabric.mod.json](https://github.com/Chocohead/OptiFabric/blob/llama/src/main/resources/fabric.mod.json) start client with Optifine 1.18.1 U H4 with 
Optifabric 1.27.7
and 
Fabric 0.12.11

**Comment by mkikets99** [comment]
The main problem is when connecting to "server" instance...

```
[Render thread/ERROR]: Mixin apply for mod fabric-rendering-data-attachment-v1 failed fabric-rendering-data-attachment-v1.mixins.json:client.MixinChunkRendererRegionBuilder -> net.minecraft.class_6850: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on fabric-rendering-data-attachment-v1.mixins.json:client.MixinChunkRendererRegionBuilder->@Inject::create(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;IIII[[Lnet/minecraft/class_6850$class_6851;)V from mod fabric-rendering-data-attachment-v1! Expected (Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V but found (Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;IIII[[Lnet/minecraft/class_6850$class_6851;)V [INJECT Applicator Phase -> fabric-rendering-data-attachment-v1.mixins.json:client.MixinChunkRendererRegionBuilder -> Apply Injections ->  -> Inject -> fabric-rendering-data-attachment-v1.mixins.json:client.MixinChunkRendererRegionBuilder->@Inject::create(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;IIII[[Lnet/minecraft/class_6850$class_6851;)V from mod fabric-rendering-data-attachment-v1]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on fabric-rendering-data-attachment-v1.mixins.json:client.MixinChunkRendererRegionBuilder->@Inject::create(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;IIII[[Lnet/minecraft/class_6850$class_6851;)V from mod fabric-rendering-data-attachment-v1! Expected (Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V but found (Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;IIII[[Lnet/minecraft/class_6850$class_6851;)V [INJECT Applicator Phase -> fabric-rendering-data-attachment-v1.mixins.json:client.MixinChunkRendererRegionBuilder -> Apply Injections ->  -> Inject -> fabric-rendering-data-attachment-v1.mixins.json:client.MixinChunkRendererRegionBuilder->@Inject::create(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;IIII[[Lnet/minecraft/class_6850$class_6851;)V from mod fabric-rendering-data-attachment-v1]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:565) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:495) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1374) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-loader-0.12.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.minecraft.class_761.method_3269(class_761.java:3414) [client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1720) [client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1539) [client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:1156) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1117) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.11.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by backryun** [comment]
> Just for info: Changing `depends -> minecraft -> + 1.18.1` in [fabric.mod.json](https://github.com/Chocohead/OptiFabric/blob/llama/src/main/resources/fabric.mod.json) start client with Optifine 1.18.1 U H4 with Optifabric 1.27.7 and Fabric 0.12.11

I saw already somebody try to do it, but it isn`t helpful. because optifabric is independent mod and injected lots of API.
You have to exclude API.jar and try it again.
