### ISSUE TITLE
OptiFabric not working 1.18.1

### ISSUE THREAD

**Issue by sapsicle** [Chocohead/OptiFabric#522]
I'm running a couple mods, but the error report seems to single out OptiFabric

Mods:
![image](https://user-images.githubusercontent.com/93958541/145852786-ecab2a0b-4c17-4c74-a792-33ed8991fb38.png)

Error (stacktrace):

net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace 'Minecraft' (minecraft) 1.18.1 with version 1.18-beta.1 or version 1.18.
Unmet dependency listing:
	 - Mod 'OptiFabric' (optifabric) 1.12.7 requires version 1.16.1, version 1.16.2, version 1.16.3, version 1.16.4, version 1.16.5, version 1.17-alpha.21.8.b, version 1.17-beta.4, version 1.17, version 1.17.1, version 1.18-beta.1 or version 1.18 of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
		 - 'Minecraft' (minecraft) 1.18.1 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
	 - 'Minecraft' (minecraft) 1.18.1, reason: to replace
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace 'Minecraft' (minecraft) 1.18.1 with version 1.18-beta.1 or version 1.18.
Unmet dependency listing:
	 - Mod 'OptiFabric' (optifabric) 1.12.7 requires version 1.16.1, version 1.16.2, version 1.16.3, version 1.16.4, version 1.16.5, version 1.17-alpha.21.8.b, version 1.17-beta.4, version 1.17, version 1.17.1, version 1.18-beta.1 or version 1.18 of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
		 - 'Minecraft' (minecraft) 1.18.1 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
	 - 'Minecraft' (minecraft) 1.18.1, reason: to replace
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more

**Comment by ChromesDuzez** [comment]
its cuz currently optifabric on minecraft 1.18.1 does not work with the fabric api

**Comment by FXCourel** [comment]
Because OptiFabric is not released yet for 1.18.1
