### ISSUE TITLE
OptiFabric not working with sodium

### ISSUE THREAD

**Issue by aidenjcheng** [Chocohead/OptiFabric#546]
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sodium' (sodium) 0.4.0-alpha5+build.9 (/Users/.../Library/Application Support/minecraft/mods/sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar) with any version that is compatible with:
		 - optifabric 1.12.10
Unmet dependency listing:
	 - Mod 'Sodium' (sodium) 0.4.0-alpha5+build.9 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
		 - Mod 'OptiFabric' (optifabric) 1.12.10 is being loaded from /Users/.../Library/Application Support/minecraft/mods/optifabric-1.12.10.jar
Inactive mods:
	 - mod 'Sodium' (sodium) 0.4.0-alpha5+build.9, reason: to replace
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.3+d154e2c614, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	 - mod 'joml' (org_joml_joml) 1.10.2, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sodium' (sodium) 0.4.0-alpha5+build.9 (/Users/.../Library/Application Support/minecraft/mods/sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar) with any version that is compatible with:
		 - optifabric 1.12.10
Unmet dependency listing:
	 - Mod 'Sodium' (sodium) 0.4.0-alpha5+build.9 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
		 - Mod 'OptiFabric' (optifabric) 1.12.10 is being loaded from /Users/.../Library/Application Support/minecraft/mods/optifabric-1.12.10.jar
Inactive mods:
	 - mod 'Sodium' (sodium) 0.4.0-alpha5+build.9, reason: to replace
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.3+d154e2c614, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	 - mod 'joml' (org_joml_joml) 1.10.2, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more

**Comment by mAngelo-dev** [comment]
Try remove sodium since optifine does almost the same sodium does...sodium and optifine never were compatible, prob never will.

**Comment by aidenjcheng** [comment]
ty🙏 finally fixed it
