### ISSUE TITLE
Opti fabric cannot play in 1.18

### ISSUE THREAD

**Issue by Scoooolzs** [Chocohead/OptiFabric#547]
full error:
```
ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
Replace 'Minecraft' (minecraft) 1.18.1 with version 1.18-beta.1 or version 1.18.
Unmet dependency listing:
Mod 'OptiFabric' (optifabric) 1.12.7 requires version 1.16.1, version 1.16.2, version 1.16.3, version 1.16.4, version 1.16.5, version 1.17-alpha.21.8.b, version 1.17-beta.4, version 1.17, version 1.17.1, version 1.18-beta.1 or version 1.18 of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
'Minecraft' (minecraft) 1.18.1 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
'Minecraft' (minecraft) 1.18.1, reason: to replace
mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446388, reason: newer version active
mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.8+c8aba2f314, reason: newer version active
mod 'Fabric Key Bindings (v0)' (fabric-keybindings-v0) 0.2.6+b4f4f6cd14, reason: newer version active
mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.18+3ac43d9514, reason: newer version active
mod 'Fabric Networking (v0)' (fabric-networking-v0) 0.3.5+b4f4f6cd14, reason: newer version active
mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.8+a00e834b88, reason: newer version active
mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.4+cbda931888, reason: newer version active
<html>at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)<br/>at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)<br/>at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)<br/>at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)<br/>at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)<br/>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)</html>
```

**Comment by Scoooolzs** [comment]
lol i am downloading the old version of optifabric lol
