### ISSUE TITLE
Optifrabric not working with Fabric 0.12.12

### ISSUE THREAD

**Issue by Springboks26** [Chocohead/OptiFabric#563]
On start up when loading it immediately crashes leaving this message

Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'OptiFabric' (optifabric) 1.12.10 (D:\Instances\Better Minecraft [FABRIC] - 1.18.1\mods\optifabric-1.12.10.jar).
Unmet dependency listing:
	 - Mod 'Iris' (iris) 1.1.3 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
		 - Mod 'OptiFabric' (optifabric) 1.12.10 is being loaded from D:\Instances\Better Minecraft [FABRIC] - 1.18.1\mods\optifabric-1.12.10(1).jar
Inactive mods:
	 - mod 'OptiFabric' (optifabric) 1.12.10, reason: to remove
	 - mod 'jankson' (blue_endless_jankson) 1.2.1, reason: same version active
	 - mod 'jankson' (blue_endless_jankson) 1.2.1, reason: same version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 4.0.0, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 4.0.0, reason: newer version active
	 - mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.0.42, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.0.45, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.1.48, reason: same version active
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.34, reason: unknown
	 - mod 'core' (com_electronwill_night-config_core) 3.6.3, reason: newer version active
	 - mod 'toml' (com_electronwill_night-config_toml) 3.6.3, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.1.3+12a8474cfa, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.0+65d505fc9c, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd65, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.5+65d505fc9c, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.8+c8aba2f3c8, reason: newer version active
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.10+c15ca33565, reason: newer version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.3+d154e2c614, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.9+65d505fc9c, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9565, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.7+3ac43d95c8, reason: newer version active
	 - mod 'Fabric Tag Extensions (v0)' (fabric-tag-extensions-v0) 1.2.5+3ac43d9565, reason: newer version active
	 - mod 'Kyrpt Config' (kyrptconfig) 1.2.3-1.18, reason: newer version active
	 - mod 'LibGui' (libgui) 5.0.0-beta.2+1.18-rc1, reason: newer version active
	 - mod 'LibGui' (libgui) 5.1.0+1.18, reason: newer version active
	 - mod 'megane-applied-energistics-2' (megane-applied-energistics-2) 6.2.0+10.0.0-alpha.1, reason: unknown
	 - mod 'megane-dml-simulacrum' (megane-dml-simulacrum) 6.2.0+0.5.0-beta2, reason: unknown
	 - mod 'megane-extra-generators' (megane-extra-generators) 6.2.0+1.1.1-BETA-1.18, reason: unknown
	 - mod 'megane-industrial-revolution' (megane-industrial-revolution) 6.2.0+1.13.1-BETA, reason: unknown
	 - mod 'megane-lib-block-attributes' (megane-lib-block-attributes) 6.2.0+0.10.0, reason: unknown
	 - mod 'megane-modern-industrialization' (megane-modern-industrialization) 6.2.0+1.0.0-alpha.02, reason: unknown
	 - mod 'megane-reborn-core' (megane-reborn-core) 6.2.0+5.1.0-beta.2, reason: unknown
	 - mod 'megane-team-reborn-energy' (megane-team-reborn-energy) 6.2.0+2.0.0-beta1, reason: unknown
	 - mod 'megane-tech-reborn' (megane-tech-reborn) 6.2.0+5.1.0-beta.2, reason: unknown
	 - mod 'megane-wireless-networks' (megane-wireless-networks) 6.2.0+1.4.0, reason: unknown
	 - mod 'OmegaConfig' (omega-config) 1.0.8, reason: newer version active
	 - mod 'OmegaConfig' (omega-config) 1.0.8, reason: newer version active
	 - mod 'lambdajcommon' (org_aperlambda_lambdajcommon) 1.8.1, reason: same version active
	 - mod 'shulkerutils' (shulkerutils) 1.0.4-1.18, reason: same version active
	 - mod 'SpruceUI' (spruceui) 3.3.0+1.17, reason: same version active
	 - mod 'ThonkUtil' (thonkutil) 1.3, reason: newer version active
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more

**Comment by VidTu** [comment]
Iris is incompatible with optifabric.

**Comment by Springboks26** [comment]
After removing Iris and it sodium additions the game still crashes but lease no log and i just get error code 0

**Comment by backryun** [comment]
Iris is not work with optifine, because the perpose is same.
Optifine is working for shader and perfomence increase.
Iris is working for shader.
So, two same shader mod can`t with work. just exclude Iris,sodium,lithium will work.

**Comment by Springboks26** [comment]
After removing Iris, sodium, lithium, and indium i crashed but cant find the issue in logs as this is all i see for the reason of the crash

[23:03:03] [Render thread/INFO]: Failed to find module info for D:\Install\bin\b22b-b3ec-4c14-187d\lwjgl.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:207) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
[23:03:03] [Render thread/INFO]: Failed to find module info for D:\Install\bin\b22b-b3ec-4c14-187d\jemalloc.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:207) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
[23:03:03] [Render thread/INFO]: Failed to find module info for D:\Install\bin\b22b-b3ec-4c14-187d\glfw.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:207) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
[23:03:05] [CraftPresence-ShutDown-Handler/INFO]: Shutting down CraftPresence...
