### ISSUE TITLE
Randomly crashing with this Crash Report

### ISSUE THREAD

**Issue by joegriffin2000** [Chocohead/OptiFabric#57]
Thanks for updating optifabric to 1.16.3 btw!

I have no clue but randomly when I am playing survival with a couple of other mods installed I get a crash report with this text as follows:

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 9/19/20 8:10 PM
Description: Unexpected error

org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_338::method_1805(Lnet/minecraft/class_4587;I)V has incompatible changes at opcode 349 in callback net/minecraft/class_338::render.
Expected: [I, I, Z, D, I, D, D, D, D, I, I, Lnet/minecraft/class_303;, D, I, I, I, D]
   Found: [I, I, I, Z, D, I, D, D, D, D, I, I, Lnet/minecraft/class_303;, I, D, I, I]
	at net.minecraft.class_338.handler$zcn000$render$missing(class_338.java)
	at net.minecraft.class_338.method_1805(class_338.java:116)
	at net.minecraft.class_329.method_1753(class_329.java:420)
	at net.minecraft.class_757.method_3192(class_757.java:765)
	at net.minecraft.class_310.method_1523(class_310.java:1023)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

This is only the first part of the crash report, if additional information is needed I am attaching the crash report file into this post.
[crash-2020-09-19_20.10.16-client.txt](https://github.com/Chocohead/OptiFabric/files/5250962/crash-2020-09-19_20.10.16-client.txt)

**Comment by Chocohead** [comment]
It will have been crashing whenever something was sent to the chat, as one of Chat-Head's Mixins was the cause of that crash.
