### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Mcboyo** [Chocohead/OptiFabric#570]
[18:55:25] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[18:55:25] [ForkJoinPool-1-worker-3/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[18:55:25] [ForkJoinPool-1-worker-10/WARN]: The mod "extraalchemy" contains invalid entries in its mod json:
- Invalid entry in person "contribution" at line 19 column 21
[18:55:25] [main/WARN]: Warnings were found!
 - Mod 'Cardinal Components API (items)' (cardinal-components-item) 4.0.1 conflicts with any version of mod 'OptiFabric' (optifabric), which is present with the following versions: 1.12.10!
	 - While this won't prevent you from starting the game, the developer(s) of mod 'Cardinal Components API (items)' (cardinal-components-item) have found that this combination may cause issues. You should remove one of the mods or check for updates that resolve the issue.
	 - Mod 'OptiFabric' (optifabric) 1.12.10 is being loaded from C:\Users\jaimo\AppData\Roaming\gdlauncher_next\instances\Minecraft fabric\mods\optifabric-1.12.10.jar
 - Mod 'FullSlabs' (full_slabs) 3.3.2 recommends version 0.10.0-dev.26 or later of malilib, which is missing!
	 - You should install version 0.10.0-dev.26 or later of malilib for the optimal experience.
 - Mod 'Repurposed Structures' (repurposed_structures) 3.2.0+1.18.1 recommends version 1.0.0 or later of no_null_processors, which is missing!
	 - You should install version 1.0.0 or later of no_null_processors for the optimal experience.
 - Mod 'Satin' (satin) 1.7.0 conflicts with any version of mod 'OptiFabric' (optifabric), which is present with the following versions: 1.12.10!
	 - While this won't prevent you from starting the game, the developer(s) of mod 'Satin' (satin) have found that this combination may cause issues. You should remove one of the mods or check for updates that resolve the issue.
	 - Mod 'OptiFabric' (optifabric) 1.12.10 is being loaded from C:\Users\jaimo\AppData\Roaming\gdlauncher_next\instances\Minecraft fabric\mods\optifabric-1.12.10.jar
[18:55:25] [main/INFO]: Loading 205 mods:
	- adorn 3.1.0+1.18.1
	- advanced_runtime_resource_pack 0.2.9 via carrier
	- advancedcompass 1.2.6
	- advancementframes 1.18-1.5.0
	- advancementinfo 1.18-fabric0.43.1-1.3
	- advancementplaques 1.4.3
	- alloy_forgery 2.0.8+1.18
	- ambientenvironment 7.0.3
	- amecsapi 1.3.3+mc1.18-pre1 via backslot
	- appleskin mc1.18-2.2.0
	- architectury 3.4.9
	- backslot 1.2.4
	- balm-fabric 2.4.0+0
	- bclib 1.2.2
	- bedrockwaters 1.6.0+1.18.1
	- betteranimalsplus 1.18.1-11.0.3
	- betterend 1.0.0
	- betternether 6.0.8
	- betterthirdperson 1.6.0
	- blockus 2.3.4+1.18.1
	- blue_endless_jankson 1.2.1 via jankson
	- blur 2.4.1
	- bosses_of_mass_destruction 1.3.3-1.18
	- cardinal-components-base 4.0.1 via rpgstats
	- cardinal-components-entity 4.0.1 via rpgstats
	- cardinal-components-item 4.0.1 via xp_storage
	- cardinal-components-world 4.0.0 via bosses_of_mass_destruction
	- carrier 1.9.0
	- chalk 1.2.1
	- cleancut 1.18-4.0-fabric
	- cleardespawn 1.1.5
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.1.48
	- cloth-config-lite 2.0.6 via omega-config-gui
	- collective-fabric 3.14
	- columns 1.2.0
	- com_electronwill_night-config_core 3.6.3 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.3 via forgeconfigapiport
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- comforts 1.0.0-1.18
	- croptosis 1.4.2
	- cyclepaintings-fabric 2.1
	- damagetilt 1.18-fabric-0.1.2
	- darkness 2.0.89
	- darkpaintings 9.0.2
	- dehydration 1.2.7
	- disable_custom_worlds_advice 1.4
	- dragonloot 1.0.10
	- dungeons_arise 2.1.49c-fabric
	- dynmus 1.4.0
	- effective 1.1
	- eldritch_mobs 1.10.2
	- enchant_giver 1.1.0 via mcdw
	- enchdesc 9.0.8
	- endgoblintraders 1.4.2
	- enhancedcelestials 2.0.6
	- environmentz 1.2.1
	- equipmentcompare 1.2.11
	- extraalchemy 1.7.0
	- fabric 0.45.2+1.18
	- fabric-api-base 0.4.1+b4f4f6cd65 via fabric
	- fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a965 via fabric
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d9565 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.18+d154e2c665 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.9+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
	- fabric-item-api-v1 1.3.0+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.8+c8aba2f365 via fabric
	- fabric-keybindings-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
	- fabric-mining-levels-v0 0.1.8+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.3+3ac43d9565 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.1+3b82842e65 via fabric
	- fabric-object-builders-v0 0.7.9+3ac43d9565 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.9.0+befed49e65 via fabric
	- fabric-renderer-api-v1 0.4.9+3ac43d9565 via fabric
	- fabric-renderer-indigo 0.4.12+3ac43d9565 via fabric
	- fabric-renderer-registries-v1 3.2.7+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.9+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.3+6b21378a65 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9565 via fabric
	- fabric-screen-api-v1 1.0.7+3ac43d9565 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
	- fabric-structure-api-v1 2.0.8+295197a765 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
	- fabric-textures-v0 1.0.9+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.5+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
	- fabricloader 0.12.12
	- farsighted-mobs 1.1-1.18
	- fiber 0.23.0-2 via collective-fabric
	- forgeconfigapiport 3.1.0
	- full_slabs 3.3.2
	- geckolib3 3.0.23
	- goblintraders 1.4.1
	- graveyard 1.1
	- guild 0.3.7
	- herdspanic 1.0.4
	- highlighter 1.1.2
	- iceberg 1.0.38
	- illuminations 1.10.2
	- inventoryhud 3.4.2
	- inventorysorter 1.8.4-1.18
	- itemborders 1.1.5
	- itemmodelfix 1.0.3+1.18
	- jankson 4.0.0+j1.2.0 via adorn
	- java 17
	- kanos_config 0.1.4+1.14.4-1.17.1 via statement
	- kiwi 5.2.2
	- kyrptconfig 1.3.4-1.18 via inventorysorter
	- legendarytooltips 1.2.1
	- libcd 3.0.3+1.16.3 via adorn
	- libgui 5.1.0+1.18 via rpgstats
	- libninepatch 1.1.0 via libgui
	- lootcrates 2.7.0-1.18.1
	- maelstrom_library 1.2.3-1.18-rc3 via bosses_of_mass_destruction
	- mcda 1.9.0
	- mcdw 4.0.2
	- merchantmarkers 1.1.0
	- micalibria 2.0.0 via full_slabs
	- midnightlib 0.3.1 via blur
	- minecraft 1.18.1
	- mm 2.3 via optifabric
	- mobs_attempt_parkour 0.2.4-1.18
	- modmenu 3.0.1
	- morevillagers-fabric 3.1.0-SNAPSHOT
	- mousetweaks 2.20
	- multipart_entities 1.1.4-1.18-rc3 via bosses_of_mass_destruction
	- mythic-mounts 1.18-4.0
	- mythicmetals 0.11.1
	- netherportalfix 9.0.0
	- notenoughanimations 1.4.0
	- omega-config 1.1.0 via reroll
	- omega-config-gui 1.2.1-1.18.1 via reroll
	- optifabric 1.12.10
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- owo 0.3.14+1.18
	- packet_tweaker 0.2.0+1.18-pre1 via server_translations_api
	- peepingcreepers 1.1-1.18
	- pickupnotifier 3.1.0
	- puzzleslib 3.1.3
	- quartzelv 2.0.1+1.18
	- ratsmischief 1.3.4
	- reach-entity-attributes 2.1.1 via mcdw
	- realisticfirespread 1.18-1
	- repurposed_structures 3.2.0+1.18.1
	- reroll 1.4.0-1.18.1
	- respawnablepets 1.18-1
	- rpgdifficulty 1.0.8
	- rpgstats 4.3.3+1.18.1
	- satin 1.7.0 via blur
	- seedfix 1.0.0 via terralith
	- server_translations_api 1.4.8+1.18-pre1 via rpgstats
	- skinlayers 1.3.1
	- skyvillages 1.0.1-1.18.1-fabric
	- snowrealmagic 3.1.0
	- sound_physics_remastered 1.18.1-1.0.3
	- staffofbuilding 1.4.1-1.18.1
	- statement 4.2.0+1.14.4-1.18.1 via full_slabs
	- statement_vanilla_compatibility 1.0.1+1.16.5-1.17 via statement
	- stoneholm 1.4.1
	- terraform-wood-api-v1 2.0.2 via blockus
	- terralith 2.0.8
	- thonkutil 2.6.0+1.18
	- thonkutil-base 1.4.0+6a7a08aec8 via thonkutil
	- thonkutil-capes-v1 1.2.0+a46c8f89c8 via thonkutil
	- thonkutil-coords-v1 1.0.6+6a7a08aec8 via thonkutil
	- thonkutil-customization 1.0.1+6a7a08aec8 via thonkutil
	- thonkutil-legacy 1.0.7+6fa117f8c8 via thonkutil
	- thonkutil-potions-v0 1.2.5+6a7a08aec8 via thonkutil
	- thonkutil-trades-v1 1.1.5+6a7a08aec8 via thonkutil
	- tinyskeletons 3.1.0
	- trashslot 11.0.1
	- villagernames-fabric 3.5
	- voidtotem 1.18.1-1.1.0
	- waterdripsound 1.18-0.3.0
	- waystones 2.4.1
	- xaeroworldmap 1.19.0
	- xp_storage 1.4.3+1.18
[18:55:25] [main/WARN]: Mod `appleskin` (mc1.18-2.2.0) does not respect SemVer - comparison support is limited.
[18:55:25] [main/WARN]: Mod `dungeons_arise` (2.1.49c-fabric) does not respect SemVer - comparison support is limited.
[18:55:25] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/jaimo/AppData/Roaming/gdlauncher_next/datastore/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[18:55:25] [main/INFO]: Compatibility level set to JAVA_16
[18:55:25] [main/INFO]: Compatibility level set to JAVA_17
[18:55:26] [main/WARN]: Error loading class: io/github/apace100/origins/command/OriginCommand (java.lang.ClassNotFoundException: io/github/apace100/origins/command/OriginCommand)
[18:55:26] [main/WARN]: @Mixin target io.github.apace100.origins.command.OriginCommand was not found dehydration.mixins.json:compat.OriginCommandMixin
[18:55:26] [main/WARN]: Error loading class: io/github/apace100/origins/component/PlayerOriginComponent (java.lang.ClassNotFoundException: io/github/apace100/origins/component/PlayerOriginComponent)
[18:55:26] [main/WARN]: @Mixin target io.github.apace100.origins.component.PlayerOriginComponent was not found dehydration.mixins.json:compat.PlayerOriginComponentMixin
[18:55:26] [main/WARN]: Error loading class: io/github/apace100/origins/command/OriginCommand (java.lang.ClassNotFoundException: io/github/apace100/origins/command/OriginCommand)
[18:55:26] [main/WARN]: @Mixin target io.github.apace100.origins.command.OriginCommand was not found environmentz.mixins.json:compat.OriginCommandMixin
[18:55:26] [main/WARN]: Error loading class: io/github/apace100/origins/component/PlayerOriginComponent (java.lang.ClassNotFoundException: io/github/apace100/origins/component/PlayerOriginComponent)
[18:55:26] [main/WARN]: @Mixin target io.github.apace100.origins.component.PlayerOriginComponent was not found environmentz.mixins.json:compat.PlayerOriginComponentMixin
[18:55:26] [main/INFO]: I used the json to destroy the json
[18:55:27] [main/WARN]: Method overwrite conflict for compatSync in environmentz.mixins.json:ServerPlayerEntityMixin, previously written by net.dehydration.mixin.ServerPlayerEntityMixin. Skipping method.
[18:55:28] [main/ERROR]: Critical injection failure: LVT in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V has incompatible changes at opcode 1815 in callback optifabric.compat.staffofbuilding.mixins.json:WorldRendererMixin->@Inject::renderWandHighlight(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_3695;Lnet/minecraft/class_243;DDDLnet/minecraft/class_1159;ZLnet/minecraft/class_4604;ZFZIIJJJJJJZLnet/minecraft/class_4597$class_4598;)V from mod (unknown).
 Expected: [Lnet/minecraft/class_3695;, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, I, I, J, J, J, J, J, J, Z, Lnet/minecraft/class_4597$class_4598;]
    Found: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, Z, Lnet/minecraft/class_4597$class_4598;, I, I, Ljava/util/Collection;, Z, Lnet/minecraft/class_4604;, Lnet/minecraft/class_239;, Lit/unimi/dsi/fastutil/longs/Long2ObjectMap$Entry;]
Available: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, Z, Lnet/minecraft/class_4597$class_4598;, I, I, Ljava/util/Collection;, Z, Lnet/minecraft/class_4604;, Lnet/minecraft/class_239;, Lit/unimi/dsi/fastutil/longs/Long2ObjectMap$Entry;, Lnet/minecraft/class_2338;, D, Lnet/minecraft/class_2586;, D, Lnet/minecraft/class_4597;, D, I, Ljava/util/SortedSet;, I, Lnet/minecraft/class_4587$class_4665;, Lnet/minecraft/class_4588;]
[18:55:28] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[1.18.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_761 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:284) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[1.18.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:284) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[1.18.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V has incompatible changes at opcode 1815 in callback optifabric.compat.staffofbuilding.mixins.json:WorldRendererMixin->@Inject::renderWandHighlight(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_3695;Lnet/minecraft/class_243;DDDLnet/minecraft/class_1159;ZLnet/minecraft/class_4604;ZFZIIJJJJJJZLnet/minecraft/class_4597$class_4598;)V from mod (unknown).
 Expected: [Lnet/minecraft/class_3695;, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, I, I, J, J, J, J, J, J, Z, Lnet/minecraft/class_4597$class_4598;]
    Found: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, Z, Lnet/minecraft/class_4597$class_4598;, I, I, Ljava/util/Collection;, Z, Lnet/minecraft/class_4604;, Lnet/minecraft/class_239;, Lit/unimi/dsi/fastutil/longs/Long2ObjectMap$Entry;]
Available: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, Z, Lnet/minecraft/class_4597$class_4598;, I, I, Ljava/util/Collection;, Z, Lnet/minecraft/class_4604;, Lnet/minecraft/class_239;, Lit/unimi/dsi/fastutil/longs/Long2ObjectMap$Entry;, Lnet/minecraft/class_2338;, D, Lnet/minecraft/class_2586;, D, Lnet/minecraft/class_4597;, D, I, Ljava/util/SortedSet;, I, Lnet/minecraft/class_4587$class_4665;, Lnet/minecraft/class_4588;]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:545) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:495) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1374) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:284) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[1.18.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 2 more

**Comment by Pectacular** [comment]
Read the beginning of the log. You will understand what to do.
