### ISSUE TITLE
optifabric dont work with my mods

### ISSUE THREAD

**Issue by pomidor112** [Chocohead/OptiFabric#583]
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'OptiFabric' (optifabric) 1.12.10 (C:\Users\user\AppData\Roaming\Crystal-Launcher\instances\u.koj\.minecraft\mods\optifabric-1.12.10 (1).jar).
Unmet dependency listing:
	 - Mod 'LambDynamicLights' (lambdynlights) 1.3.4+1.16 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
		 - Mod 'OptiFabric' (optifabric) 1.12.10 is being loaded from C:\Users\user\AppData\Roaming\Crystal-Launcher\instances\u.koj\.minecraft\mods\optifabric-1.12.10 (1).jar
Inactive mods:
	 - mod 'OptiFabric' (optifabric) 1.12.10, reason: to remove
	 - mod 'Auto Config v1 Updated' (autoconfig1u) 3.2.0-unstable, reason: newer version active
	 - mod 'Auto Config v1 Updated' (autoconfig1u) 3.2.2, reason: newer version active
	 - mod 'Auto Config v1 Updated' (autoconfig1u) 3.3.1, reason: same version active
	 - mod 'jankson' (blue_endless_jankson) 1.2.0, reason: same version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 2.6.0, reason: newer version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 2.7.2, reason: newer version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 2.7.9, reason: newer version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 2.7.12, reason: newer version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 2.8.0, reason: newer version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 2.8.1, reason: newer version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 2.8.3, reason: same version active
	 - mod 'Cardinal Components API (blocks)' (cardinal-components-block) 2.7.12, reason: newer version active
	 - mod 'Cardinal Components API (blocks)' (cardinal-components-block) 2.8.3, reason: same version active
	 - mod 'Cardinal Components API (chunks)' (cardinal-components-chunk) 2.7.12, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 2.6.0, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 2.7.2, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 2.7.9, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 2.7.12, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 2.8.0, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 2.8.1, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 2.8.3, reason: same version active
	 - mod 'Cardinal Components API (items)' (cardinal-components-item) 2.7.2, reason: newer version active
	 - mod 'Cardinal Components API (items)' (cardinal-components-item) 2.7.9, reason: newer version active
	 - mod 'Cardinal Components API (utilities)' (cardinal-components-util) 2.6.0, reason: newer version active
	 - mod 'Cardinal Components API (worlds)' (cardinal-components-world) 2.7.12, reason: newer version active
	 - mod 'Cloth API' (cloth-api) 1.2.1, reason: newer version active
	 - mod 'Cloth Client Events v0' (cloth-client-events-v0) 1.5.47, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 4.5.6, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 4.7.0-unstable, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 4.8.2, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 4.8.3, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 4.11.14, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 4.11.15, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 4.11.19, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 4.11.26, reason: same version active
	 - mod 'core' (com_electronwill_night-config_core) 3.6.2, reason: newer version active
	 - mod 'core' (com_electronwill_night-config_core) 3.6.2, reason: newer version active
	 - mod 'core' (com_electronwill_night-config_core) 3.6.2, reason: newer version active
	 - mod 'toml' (com_electronwill_night-config_toml) 3.6.2, reason: newer version active
	 - mod 'toml' (com_electronwill_night-config_toml) 3.6.2, reason: newer version active
	 - mod 'toml' (com_electronwill_night-config_toml) 3.6.2, reason: newer version active
	 - mod 'toml4j' (com_moandjiezana_toml_toml4j) 0.7.2, reason: same version active
	 - mod 'EngiLib' (engilib) 1.0.0+1.16.4, reason: newer version active
	 - mod 'Fabric API' (fabric) 0.29.3+1.16, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.1.3+12a8474c34, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.1.3+12a8474ca7, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.2.0+daa38b3d7d, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.2.0+ab87788d3a, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.2.1+9354966b7d, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+c88702897d, reason: same version active
	 - mod 'Fabric Biome API (v1)' (fabric-biome-api-v1) 3.1.1+ca58154a7d, reason: newer version active
	 - mod 'Fabric BlockRenderLayer Registration (v1)' (fabric-blockrenderlayer-v1) 1.1.4+6a2618f53a, reason: newer version active
	 - mod 'Fabric BlockRenderLayer Registration (v1)' (fabric-blockrenderlayer-v1) 1.1.5+ca58154a7d, reason: same version active
	 - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.0.9+6a2618f53a, reason: newer version active
	 - mod 'Fabric Content Registries (v0)' (fabric-content-registries-v0) 0.2.1+ca58154a7d, reason: same version active
	 - mod 'Fabric Crash Report Info (v1)' (fabric-crash-report-info-v1) 0.1.2+b7f9825d3a, reason: newer version active
	 - mod 'Fabric Crash Report Info (v1)' (fabric-crash-report-info-v1) 0.1.3+ca58154a7d, reason: same version active
	 - mod 'Fabric Item Groups (v0)' (fabric-item-groups-v0) 0.2.2+cbe9176f3a, reason: newer version active
	 - mod 'Fabric Item Groups (v0)' (fabric-item-groups-v0) 0.2.3+ca58154a7d, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.4+9354966b7d, reason: same version active
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.2.0+ffb68a873a, reason: newer version active
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.2.1+ca58154a7d, reason: same version active
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.2.1+ca58154a7d, reason: same version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.1+ca58154a7d, reason: newer version active
	 - mod 'Fabric Networking Block Entity (v0)' (fabric-networking-blockentity-v0) 0.2.7+a03e98793a, reason: newer version active
	 - mod 'Fabric Networking (v0)' (fabric-networking-v0) 0.1.10+e00ecb5fa7, reason: newer version active
	 - mod 'Fabric Networking (v0)' (fabric-networking-v0) 0.3.1+2a4333d33a, reason: newer version active
	 - mod 'Fabric Networking (v0)' (fabric-networking-v0) 0.3.2+ca58154a7d, reason: same version active
	 - mod 'Fabric Object Builder API (v1)' (fabric-object-builder-api-v1) 1.9.3+ca58154a7d, reason: newer version active
	 - mod 'Fabric Registry Sync (v0)' (fabric-registry-sync-v0) 0.7.3+be155ae23a, reason: newer version active
	 - mod 'Fabric Registry Sync (v0)' (fabric-registry-sync-v0) 0.7.4+ca58154a7d, reason: same version active
	 - mod 'Fabric Renderer Registries (v1)' (fabric-renderer-registries-v1) 2.2.1+ca58154a7d, reason: newer version active
	 - mod 'Fabric Rendering (v1)' (fabric-rendering-v1) 1.5.1+ca58154a7d, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.1+0d4d7e343a, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.2+ca58154a7d, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.2+ca58154a7d, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.2+ca58154a7d, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.0+c045166c7d, reason: same version active
	 - mod 'Fabric Structure API (v1)' (fabric-structure-api-v1) 1.1.4+ca58154a7d, reason: same version active
	 - mod 'Fabric Tag Extensions (v0)' (fabric-tag-extensions-v0) 1.1.1+ca58154a7d, reason: same version active
	 - mod 'Fabric Tag Extensions (v0)' (fabric-tag-extensions-v0) 1.1.1+ca58154a7d, reason: same version active
	 - mod 'Fabric Tool Attribute API (v1)' (fabric-tool-attribute-api-v1) 1.2.6+ca58154a7d, reason: newer version active
	 - mod 'LibBlockAttributes (Core)' (libblockattributes_core) 0.8.8, reason: same version active
	 - mod 'LibBlockAttributes (Fluids)' (libblockattributes_fluids) 0.8.8, reason: same version active
	 - mod 'LibGui' (libgui) 3.0.0-beta.1+1.16.2-rc2, reason: newer version active
	 - mod 'LibGui' (libgui) 3.2.2+1.16.3, reason: newer version active
	 - mod 'LibGui' (libgui) 3.3.3+1.16.5, reason: newer version active
	 - mod 'Libstructure' (libstructure) 1.3, reason: newer version active
	 - mod 'Manningham Mills' (mm) 2.3, reason: inactive parent mod (nested jar)
	 - mod 'OmegaConfig' (omega-config) 1.0.2, reason: newer version active
	 - mod 'Reach Entity Attribute' (reach-entity-attributes) 1.0.1, reason: newer version active
	 - mod 'Terraform Biome Builder API (v1)' (terraform-biome-builder-api-v1) 1.0.3, reason: newer version active
	 - mod 'Terraform Config API (v1)' (terraform-config-api-v1) 1.0.2, reason: newer version active
	 - mod 'Terraform Overworld Biome Extensions API (v1)' (terraform-overworld-biome-extensions-api-v1) 1.0.2, reason: newer version active
	 - mod 'Terraform Shapes API (v1)' (terraform-shapes-api-v1) 1.0.2, reason: newer version active
	 - mod 'Terraform Surfaces API (v1)' (terraform-surfaces-api-v1) 1.0.2, reason: newer version active
	 - mod 'Terraform Tree API (v1)' (terraform-tree-api-v1) 1.0.3, reason: newer version active
	 - mod 'Terraform Wood API (v1)' (terraform-wood-api-v1) 1.0.2, reason: newer version active
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29)
	at crystallauncher.MineClient.start(MineClient.java:206)
	at crystallauncher.MineClient.main(MineClient.java:36)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'OptiFabric' (optifabric) 1.12.10 (C:\Users\user\AppData\Roaming\Crystal-Launcher\instances\u.koj\.minecraft\mods\optifabric-1.12.10 (1).jar).
Unmet dependency listing:
	 - Mod 'LambDynamicLights' (lambdynlights) 1.3.4+1.16 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
		 - Mod 'OptiFabric' (optifabric) 1.12.10 is being loaded from C:\Users\user\AppData\Roaming\Crystal-Launcher\instances\u.koj\.minecraft\mods\optifabric-1.12.10 (1).jar
Inactive mods:
	 - mod 'OptiFabric' (optifabric) 1.12.10, reason: to remove
	 - mod 'Auto Config v1 Updated' (autoconfig1u) 3.2.0-unstable, reason: newer version active
	 - mod 'Auto Config v1 Updated' (autoconfig1u) 3.2.2, reason: newer version active
	 - mod 'Auto Config v1 Updated' (autoconfig1u) 3.3.1, reason: same version active
	 - mod 'jankson' (blue_endless_jankson) 1.2.0, reason: same version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 2.6.0, reason: newer version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 2.7.2, reason: newer version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 2.7.9, reason: newer version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 2.7.12, reason: newer version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 2.8.0, reason: newer version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 2.8.1, reason: newer version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 2.8.3, reason: same version active
	 - mod 'Cardinal Components API (blocks)' (cardinal-components-block) 2.7.12, reason: newer version active
	 - mod 'Cardinal Components API (blocks)' (cardinal-components-block) 2.8.3, reason: same version active
	 - mod 'Cardinal Components API (chunks)' (cardinal-components-chunk) 2.7.12, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 2.6.0, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 2.7.2, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 2.7.9, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 2.7.12, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 2.8.0, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 2.8.1, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 2.8.3, reason: same version active
	 - mod 'Cardinal Components API (items)' (cardinal-components-item) 2.7.2, reason: newer version active
	 - mod 'Cardinal Components API (items)' (cardinal-components-item) 2.7.9, reason: newer version active
	 - mod 'Cardinal Components API (utilities)' (cardinal-components-util) 2.6.0, reason: newer version active
	 - mod 'Cardinal Components API (worlds)' (cardinal-components-world) 2.7.12, reason: newer version active
	 - mod 'Cloth API' (cloth-api) 1.2.1, reason: newer version active
	 - mod 'Cloth Client Events v0' (cloth-client-events-v0) 1.5.47, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 4.5.6, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 4.7.0-unstable, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 4.8.2, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 4.8.3, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 4.11.14, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 4.11.15, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 4.11.19, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 4.11.26, reason: same version active
	 - mod 'core' (com_electronwill_night-config_core) 3.6.2, reason: newer version active
	 - mod 'core' (com_electronwill_night-config_core) 3.6.2, reason: newer version active
	 - mod 'core' (com_electronwill_night-config_core) 3.6.2, reason: newer version active
	 - mod 'toml' (com_electronwill_night-config_toml) 3.6.2, reason: newer version active
	 - mod 'toml' (com_electronwill_night-config_toml) 3.6.2, reason: newer version active
	 - mod 'toml' (com_electronwill_night-config_toml) 3.6.2, reason: newer version active
	 - mod 'toml4j' (com_moandjiezana_toml_toml4j) 0.7.2, reason: same version active
	 - mod 'EngiLib' (engilib) 1.0.0+1.16.4, reason: newer version active
	 - mod 'Fabric API' (fabric) 0.29.3+1.16, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.1.3+12a8474c34, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.1.3+12a8474ca7, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.2.0+daa38b3d7d, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.2.0+ab87788d3a, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.2.1+9354966b7d, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+c88702897d, reason: same version active
	 - mod 'Fabric Biome API (v1)' (fabric-biome-api-v1) 3.1.1+ca58154a7d, reason: newer version active
	 - mod 'Fabric BlockRenderLayer Registration (v1)' (fabric-blockrenderlayer-v1) 1.1.4+6a2618f53a, reason: newer version active
	 - mod 'Fabric BlockRenderLayer Registration (v1)' (fabric-blockrenderlayer-v1) 1.1.5+ca58154a7d, reason: same version active
	 - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.0.9+6a2618f53a, reason: newer version active
	 - mod 'Fabric Content Registries (v0)' (fabric-content-registries-v0) 0.2.1+ca58154a7d, reason: same version active
	 - mod 'Fabric Crash Report Info (v1)' (fabric-crash-report-info-v1) 0.1.2+b7f9825d3a, reason: newer version active
	 - mod 'Fabric Crash Report Info (v1)' (fabric-crash-report-info-v1) 0.1.3+ca58154a7d, reason: same version active
	 - mod 'Fabric Item Groups (v0)' (fabric-item-groups-v0) 0.2.2+cbe9176f3a, reason: newer version active
	 - mod 'Fabric Item Groups (v0)' (fabric-item-groups-v0) 0.2.3+ca58154a7d, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.4+9354966b7d, reason: same version active
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.2.0+ffb68a873a, reason: newer version active
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.2.1+ca58154a7d, reason: same version active
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.2.1+ca58154a7d, reason: same version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.1+ca58154a7d, reason: newer version active
	 - mod 'Fabric Networking Block Entity (v0)' (fabric-networking-blockentity-v0) 0.2.7+a03e98793a, reason: newer version active
	 - mod 'Fabric Networking (v0)' (fabric-networking-v0) 0.1.10+e00ecb5fa7, reason: newer version active
	 - mod 'Fabric Networking (v0)' (fabric-networking-v0) 0.3.1+2a4333d33a, reason: newer version active
	 - mod 'Fabric Networking (v0)' (fabric-networking-v0) 0.3.2+ca58154a7d, reason: same version active
	 - mod 'Fabric Object Builder API (v1)' (fabric-object-builder-api-v1) 1.9.3+ca58154a7d, reason: newer version active
	 - mod 'Fabric Registry Sync (v0)' (fabric-registry-sync-v0) 0.7.3+be155ae23a, reason: newer version active
	 - mod 'Fabric Registry Sync (v0)' (fabric-registry-sync-v0) 0.7.4+ca58154a7d, reason: same version active
	 - mod 'Fabric Renderer Registries (v1)' (fabric-renderer-registries-v1) 2.2.1+ca58154a7d, reason: newer version active
	 - mod 'Fabric Rendering (v1)' (fabric-rendering-v1) 1.5.1+ca58154a7d, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.1+0d4d7e343a, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.2+ca58154a7d, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.2+ca58154a7d, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.2+ca58154a7d, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.0+c045166c7d, reason: same version active
	 - mod 'Fabric Structure API (v1)' (fabric-structure-api-v1) 1.1.4+ca58154a7d, reason: same version active
	 - mod 'Fabric Tag Extensions (v0)' (fabric-tag-extensions-v0) 1.1.1+ca58154a7d, reason: same version active
	 - mod 'Fabric Tag Extensions (v0)' (fabric-tag-extensions-v0) 1.1.1+ca58154a7d, reason: same version active
	 - mod 'Fabric Tool Attribute API (v1)' (fabric-tool-attribute-api-v1) 1.2.6+ca58154a7d, reason: newer version active
	 - mod 'LibBlockAttributes (Core)' (libblockattributes_core) 0.8.8, reason: same version active
	 - mod 'LibBlockAttributes (Fluids)' (libblockattributes_fluids) 0.8.8, reason: same version active
	 - mod 'LibGui' (libgui) 3.0.0-beta.1+1.16.2-rc2, reason: newer version active
	 - mod 'LibGui' (libgui) 3.2.2+1.16.3, reason: newer version active
	 - mod 'LibGui' (libgui) 3.3.3+1.16.5, reason: newer version active
	 - mod 'Libstructure' (libstructure) 1.3, reason: newer version active
	 - mod 'Manningham Mills' (mm) 2.3, reason: inactive parent mod (nested jar)
	 - mod 'OmegaConfig' (omega-config) 1.0.2, reason: newer version active
	 - mod 'Reach Entity Attribute' (reach-entity-attributes) 1.0.1, reason: newer version active
	 - mod 'Terraform Biome Builder API (v1)' (terraform-biome-builder-api-v1) 1.0.3, reason: newer version active
	 - mod 'Terraform Config API (v1)' (terraform-config-api-v1) 1.0.2, reason: newer version active
	 - mod 'Terraform Overworld Biome Extensions API (v1)' (terraform-overworld-biome-extensions-api-v1) 1.0.2, reason: newer version active
	 - mod 'Terraform Shapes API (v1)' (terraform-shapes-api-v1) 1.0.2, reason: newer version active
	 - mod 'Terraform Surfaces API (v1)' (terraform-surfaces-api-v1) 1.0.2, reason: newer version active
	 - mod 'Terraform Tree API (v1)' (terraform-tree-api-v1) 1.0.3, reason: newer version active
	 - mod 'Terraform Wood API (v1)' (terraform-wood-api-v1) 1.0.2, reason: newer version active
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 10 more

**Comment by Chris6ix** [comment]
@pomidor112 
Instead of opening an issue and pasting this huge thing twice, first read the error and try to understand it yourself...Jesus, its really not hard.
It clearly says at the begging that your mod "LambDynamicLights" is incompatible with OptiFabric...this is probably because OptiFabric is made for OptiFine which already has its own Dynamic Lights feature...
It literally says on the mod page in RED TEXT that "OptiFabric is obviously incompatible." so pls just read before you do stuff...
Why on earth would want a mod that gives you dynamic lights when you`re already using OptiFabric/OptiFine???
Remove "LambDynamicLights" and its fixed...

Oh and btw clean your MC install its horrible...you have like 5 different versions of some Fabric stuff installed that will fill up your logs and make them unnecessarily big and harder to read (Delete the ".fabric" folder and launch your game with fabric once)

You can close this issue as its not a problem with OptiFabric
