### ISSUE TITLE
1.18 doesn't work with replay mod?

### ISSUE THREAD

**Issue by KingKhaledYT** [Chocohead/OptiFabric#592]
Whenever I launch minecraft with replay mod is says:

net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace 'Minecraft' (minecraft) 1.17.1 with any version between 1.16.2 (inclusive) and 1.17- (exclusive).
Unmet dependency listing:
	 - Mod 'Fabric API' (fabric) 0.25.1+build.416-1.16 requires any version between 1.16.2-alpha.20.28.a (inclusive) and 1.17- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.17.1!
		 - 'Minecraft' (minecraft) 1.17.1 is an environment reference and usually requires installation or launcher changes to adjust
	 - Mod 'Fabric Tag Extensions (v0)' (fabric-tag-extensions-v0) 1.0.3+ac8e8c593a requires any version between 1.16-alpha.20.14.a (inclusive) and 1.17- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.17.1!
		 - 'Minecraft' (minecraft) 1.17.1 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
	 - 'Minecraft' (minecraft) 1.17.1, reason: to replace
	 - mod 'Fabric API Base' (fabric-api-base) 0.2.0+9f0fb4b83a, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.1+730711c63a, reason: newer version active
	 - mod 'Fabric Key Bindings (v0)' (fabric-keybindings-v0) 0.2.0+3fa9f7c53a, reason: newer version active
	 - mod 'Fabric Networking (v0)' (fabric-networking-v0) 0.1.10+e00ecb5f3a, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.3.1+facf3bbf3a, reason: newer version active
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace 'Minecraft' (minecraft) 1.17.1 with any version between 1.16.2 (inclusive) and 1.17- (exclusive).
Unmet dependency listing:
	 - Mod 'Fabric API' (fabric) 0.25.1+build.416-1.16 requires any version between 1.16.2-alpha.20.28.a (inclusive) and 1.17- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.17.1!
		 - 'Minecraft' (minecraft) 1.17.1 is an environment reference and usually requires installation or launcher changes to adjust
	 - Mod 'Fabric Tag Extensions (v0)' (fabric-tag-extensions-v0) 1.0.3+ac8e8c593a requires any version between 1.16-alpha.20.14.a (inclusive) and 1.17- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.17.1!
		 - 'Minecraft' (minecraft) 1.17.1 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
	 - 'Minecraft' (minecraft) 1.17.1, reason: to replace
	 - mod 'Fabric API Base' (fabric-api-base) 0.2.0+9f0fb4b83a, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.1+730711c63a, reason: newer version active
	 - mod 'Fabric Key Bindings (v0)' (fabric-keybindings-v0) 0.2.0+3fa9f7c53a, reason: newer version active
	 - mod 'Fabric Networking (v0)' (fabric-networking-v0) 0.1.10+e00ecb5f3a, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.3.1+facf3bbf3a, reason: newer version active
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more

**Comment by FileOfName** [comment]
It looks like you have an outdated Fabric API. Try downloading the latest version from CurseForge (https://www.curseforge.com/minecraft/mc-mods/fabric-api). These kinds of errors usually happen when the mod's dependencies aren't fulfilled. Most of the time OptiFabric causes Mixins errors. Also, it says you're running Minecraft 1.17.1.
