### ISSUE TITLE
Error launching Fabric 1.16.5 with OptiFabric

### ISSUE THREAD

**Issue by ComeOnBear** [Chocohead/OptiFabric#606]
**Latest.log linked below!**
[latest.log](https://github.com/Chocohead/OptiFabric/files/8099123/latest.log)

**Mods list**
![Screenshot 2022-02-18 171556](https://user-images.githubusercontent.com/34274925/154730739-1f1dab4c-dc35-4101-8b74-d65073fac341.png)

**Yes I know i use wurst, ignore that.**

Heres the stack trace

java.lang.NoSuchMethodError: net.fabricmc.loader.FabricLoader.getGameProvider()Lnet/fabricmc/loader/game/GameProvider;
	at me.modmuss50.optifabric.mod.OptifineSetup.getLaunchMinecraftJar(OptifineSetup.java:299)
	at me.modmuss50.optifabric.mod.OptifineSetup.getMinecraftJar(OptifineSetup.java:277)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:84)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at com.chocohead.mm.Plugin$$Lambda$56/1037942373.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:567)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:134)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by ghost** [comment]
are you using the latest Fabric Launcher? I actually can't see from your bug log why its failing, so could you upload a copy of the full latest.log from /logs to pastebin please?

**Comment by ComeOnBear** [comment]
> are you using the latest Fabric Launcher? I actually can't see from your bug log why its failing, so could you upload a copy of the full latest.log from /logs to pastebin please?

https://pastebin.com/9y5prvuV
Here you go!
I am using the latest Fabric installer, I changed the version to 12.0 after I saw a thread saying it didn't work with 13.0!
Am I doing something wrong, because it didn't work either when I used 13.0
Thanks for the fast reply!

**Comment by topia** [comment]
I think you are using too old optifabric (1.11.1), which is incompatible with fabric-loader 0.12.

**Comment by ghost** [comment]
> I think you are using too old optifabric (1.11.1), which is incompatible with fabric-loader 0.12.

Dang, yeah its probably the fabric loader, im not sure which version the 1.16.5 Optifabric is built on, unfortunately.

EDIT: Your Log is referencing Sodium, which is Incompatible with Optifine. Its also referencing that Optifine wasn't found according to the log at 199.

**Comment by ComeOnBear** [comment]
new issue, I tried to use the latest OptiFabric for 1.16.5, and i got this issue.
![image](https://user-images.githubusercontent.com/34274925/154969824-5699058a-5fd6-4841-b094-aa6c204009e9.png)

**Comment by topia** [comment]
Why did you pick 1.11.9? How about Optifabric 1.12.10?

**Comment by ComeOnBear** [comment]
That was the latest version on CurseForge for minecraft version 1.16.5

**Comment by ghost** [comment]
> That was the latest version on CurseForge for minecraft version 1.16.5

Install 0.11.7 in Fabric installer for 1.16.5, then try again. The error just tells you 0.12 is too high for Optifabric to run on 1.16 is all.

**Comment by topia** [comment]
Although fabric loader 0.11.7 may work with optifabric 1.11.9, I can see optifabric 1.12.10 marked as compatible with 1.16.1 to 1.16.5.
https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3568115

If you are using 1.16 (not 1.16.x), never mind.

**Comment by ghost** [comment]
> > I think you are using too old optifabric (1.11.1), which is incompatible with fabric-loader 0.12.
> 
> Dang, yeah its probably the fabric loader, im not sure which version the 1.16.5 Optifabric is built on, unfortunately.



> Although fabric loader 0.11.7 may work with optifabric 1.11.9, I can see optifabric 1.12.10 marked as compatible with 1.16.1 to 1.16.5. https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3568115
> 
> If you are using 1.16 (not 1.16.x), never mind.

It may be marked as compatible, but hes using a specific 1.16 version, which is what he wanted help with.

**Comment by ComeOnBear** [comment]
> > That was the latest version on CurseForge for minecraft version 1.16.5
> 
> Install 0.11.7 in Fabric installer for 1.16.5, then try again. The error just tells you 0.12 is too high for Optifabric to run on 1.16 is all.
