### ISSUE TITLE
Error with Optifabric 1.13.0 and Architectury v4.1.35

### ISSUE THREAD

**Issue by gwsy** [Chocohead/OptiFabric#659]
Optifabric 1.13.0
Architectury v4.1.35
Fabric loader 0.13.3

In the above environment, I get an error like the one in the image.
![image](https://user-images.githubusercontent.com/9270349/160272375-588e0e50-d167-4f90-80e7-71ba1900f363.png)

**Comment by gwsy** [comment]
my mod list
![image](https://user-images.githubusercontent.com/9270349/160272456-273cd660-8320-4727-994b-beaa6672ccd5.png)

**Comment by gwsy** [comment]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Architectury' (architectury) 4.1.35 with version 1.2.72 or earlier or version 1.3.77 or later that is compatible with:
		 - optifabric 1.13.0
Unmet dependency listing:
	 - Mod 'Architectury' (architectury) 4.1.35 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.0!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by topia** [comment]
https://github.com/architectury/architectury-api/issues/226
architectury's dependency is not updated yet.

**Comment by gwsy** [comment]
> [architectury/architectury-api#226](https://github.com/architectury/architectury-api/issues/226) architectury's dependency is not updated yet.

Thanks for the quick reply!
Will it work if fabricloader is lower than 1.12.11?

**Comment by topia** [comment]
If you want to play minecraft 1.18.2 with Architectury, I think you can't downgrade fabric-loader to 1.12.
I suggest waiting for the updated architectury or trying dependency override as suggested in the issue.

**Comment by gwsy** [comment]
Well... thanks for the clarification!

**Comment by ghost** [comment]
Can be closed now. Architectuary pushed a fix
