### ISSUE TITLE
Errer-Code: 1-Architectury + Modern Industrialization+Bewitchment

### ISSUE THREAD

**Issue by ZombieKeks** [Chocohead/OptiFabric#662]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'OptiFabric' (optifabric) 1.12.10 (C:\Users\keksb\curseforge\minecraft\Instances\Cygnus 2.0\mods\optifabric-1.12.10.jar).
Unmet dependency listing:
	 - Mod 'Architectury' (architectury) 3.7.31 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
	 - Mod 'Bewitchment' (bewitchment) 1.18-14 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
	 - Mod 'Sodium' (sodium) 0.4.0-alpha6+build.14 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
	 - Mod 'Iris' (iris) 1.2.0-pre is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
	 - Mod 'LambdaBetterGrass' (lambdabettergrass) 1.2.2+1.17 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
	 - Mod 'LambDynamicLights' (lambdynlights) 2.1.0+1.17 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
	 - Mod 'Lithium' (lithium) 0.7.8 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
	 - Mod 'Modern Industrialization' (modern_industrialization) 1.0.5 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by ghost** [comment]
Oh this ones pretty simple. You're using an outdated version of Optifabric for a start, Sodium, Lithium, Phosphor are incompatible with Optifabric, Bewitchment is marked as incompatible, You need to update Architectuary, or use the Fabric Override json to load it. Iris is Shaders, which Optifine does, Dynamic Lights and Better Grass are also part of Optifine. As for Modern Industrialization, i'd sway heavily at Mixins or some code there. It looks pretty intensive, and the Developer recommends Sodium anyway, so you shouldn't be using Optifabric.

**Comment by ZombieKeks** [comment]
Thanks for your reply!)
I did the steps u give me but runned in to a new problem

[crash-2022-03-28_18.23.06-client.txt](https://github.com/Chocohead/OptiFabric/files/8364705/crash-2022-03-28_18.23.06-client.txt)
[crash-2022-03-28_18.23.03-server.txt](https://github.com/Chocohead/OptiFabric/files/8364706/crash-2022-03-28_18.23.03-server.txt)

**Comment by ghost** [comment]
Seems your issue now is related to Enhanced Celestials. Judging from the issues, i'd say the modpack you're using is orientated around Sodium / Lithium / Phosphor / Iris instead of Optifine / Optifabric. You'll probably also have more compatibility issues in future. I can't see why Enhanced Celestials would break except for the new Loader Version.

**Comment by ZombieKeks** [comment]
Thanks for your efford. I tried evertything u told me to try, new loader on farbic 0.12.12, then I tried with different versions of architectury and optifabric + all versions of optifine, same with the 0.13.3 laoder with deleted cofigs. And when I get it to work, then it gives me the error from here https://github.com/Chocohead/OptiFabric/issues/454

If u wanna continue the troubleshorting for 350+ mods let me know. :) Thanks for your responses and have a great time.

**Comment by ghost** [comment]
At this point, I’d delete optifabric and Optifine, and just run the Modpack with sodium and Iris, as the creator of Modern Industrialization suggests anyway. You’re pretty correct that 350+ mods is a bit much to troubleshoot, especially when some of them probably do features of Optifine for use with sodium. For example, I play Better Minecraft on a server I run, but cant run Optifabric in the pack without breaking it. I just use Sodium which it provides

**Comment by ZombieKeks** [comment]
Hello, its me; I deleted 124 Mods and tried with fabric 0.12.12 and 0.13.3 (1.18.1) and want to sent u a last log, if u want to look in to it


[crash-2022-03-31_21.39.28-client.txt](https://github.com/Chocohead/OptiFabric/files/8392669/crash-2022-03-31_21.39.28-client.txt)

**Comment by ZombieKeks** [comment]
[crash-2022-03-31_22.06.37-client.txt](https://github.com/Chocohead/OptiFabric/files/8392784/crash-2022-03-31_22.06.37-client.txt)

**Comment by ghost** [comment]
First one is related to enhanced celestials, the second I’m gonna throw a guess at being related to the discussion in #630 about mixins, as I’ve never seen that before.
