### ISSUE TITLE
no sirve optifabric 1.14.4

### ISSUE THREAD

**Issue by danilorincon43** [Chocohead/OptiFabric#671]
Uncaught exception in thread "main"
java.lang.RuntimeException: Mixin transformation of net.minecraft.client.main.Main failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:414)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: net.fabricmc.loader.api.metadata.ModMetadata.getCustomElement(Ljava/lang/String;)Lcom/google/gson/JsonElement;
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:287)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 6 more

**Comment by Sjouwer** [comment]
OptiFabric for 1.14.4 doesn't support the latest Fabric API and Loader.
I've forked it and updated the mod though, it now seems to work fine for me:
https://github.com/Sjouwer/OptiFabric-1.14.4-Updated/releases

**Comment by danilorincon43** [comment]
> OptiFabric para 1.14.4 no es compatible con la API y el cargador de Fabric más recientes. Sin embargo, lo bifurqué y actualicé el mod, ahora parece funcionar bien para mí: https://github.com/Sjouwer/OptiFabric-1.14.4-Updated/releases

si gracias ya me funciono, ahora tengo otro problema, cuando me intento meter al nether se me queda en la pantalla de cargando terreno de hay no pasa ayuda porfa, perdón por las molestias

**Comment by aaron072B** [comment]
y cual de los dos te descargaste?
