### ISSUE TITLE
Error 1.18.2

### ISSUE THREAD

**Issue by ghost** [Chocohead/OptiFabric#686]
OptiFine_1.18.2_HD_U_H7 or OptiFine_1.18.2_HD_U_H6 with Optifacbric gives me a error on Startup.

There was an error loading OptiFabric!

Failed to load OptiFine, please report this!

Failed to remap jar

I have tested different Fabric and Fabric Api Versions allways the same problem

**Comment by ghost** [comment]
java.lang.RuntimeException: Failed to remap jar
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:226)
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:211)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:165)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:43)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:157)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.io.IOException: the jar file R:\Temp\optifabric12046473040767433321\Optifine-remapped.jar can't be written
	at net.fabricmc.tinyremapper.OutputConsumerPath.<init>(OutputConsumerPath.java:114)
	at net.fabricmc.tinyremapper.OutputConsumerPath.<init>(OutputConsumerPath.java:47)
	at net.fabricmc.tinyremapper.OutputConsumerPath$Builder.build(OutputConsumerPath.java:76)
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:219)
	... 27 more
