### ISSUE TITLE
Incompatible in 1.18.2 with sodium. (FIX NOW)

### ISSUE THREAD

**Issue by Ihateoptifabric** [Chocohead/OptiFabric#698]
Hello, i want to get some more fps on the complementary shaders (i use tlauncher) when i have everything ready and installed, i launch it and sent me this error, please fix it as soon as possible:
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sodium' (sodium) 0.4.1+build.15 with any version that is compatible with:
		 - optifabric 1.13.0
Unmet dependency listing:
	 - Mod 'Sodium' (sodium) 0.4.1+build.15 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.0!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by catuesuol** [comment]
they are not going to make optifabric compatible with sodium cause it makes no sense

**Comment by Ihateoptifabric** [comment]
And then, how i install Shaders in sodium?

**Comment by Shaddh** [comment]
To have functioning shaders with Sodium, you will have to install Iris Shaders.

**Comment by skedgyedgy** [comment]
-- dude optifine is fundamentally incompatible with sodium, they both make different changes to minecraft's code that are incompatible with each other. that's why it's marked as an incompatible mod. sodium is an alternative to optifine, they are mutually exclusive. chill out fr, the fact that you're unironically naming yourself "ihateoptifcabric" and going karen at the devs because you had one single issue is unacceptable
