### ISSUE TITLE
Java runtime configuration error

### ISSUE THREAD

**Issue by Freightliner-fs65** [Chocohead/OptiFabric#715]
I have Optifabric 1.18.2 installed with no incompatible mods but when I attempt to launch the game. However, the game did not launch and gave me an error code saying "An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience. This crash may be caused by a invalid Java Runtime configuration. check any custom configuration settings. does anyone know a fix to this?

**Comment by amarisa4321** [comment]
I'm getting that error as well, not sure how to fix it, though.

**Comment by same-drenth** [comment]
I have the same Issue. Here is some info that I managed to gather https://pastebin.com/ckjvTts7

**Comment by osfanbuff63** [comment]
> I have the same Issue. Here is some info that I managed to gather https://pastebin.com/ckjvTts7

Could you paste your whole log?

As well, are you using OptiFine HD_U_H6 or H7?

**Comment by same-drenth** [comment]
H7 and I dont know how to find the whole log afterwards

**Comment by osfanbuff63** [comment]
Ok, try using H6? I think it's only *officially* compatible with H6 for 1.18.2, not H7. If you need help with that lmk

**Comment by same-drenth** [comment]
Thank you, I also read that you need to thoroughly check that the other mods that you are using are specifically made for the version that you are using and that completely solved any issue that I was having

**Comment by same-drenth** [comment]
> Thank you, I also read that you need to thoroughly check that the other mods that you are using are specifically made for the version that you are using and that completely solved any issue that I was having

I was too fast with posting this. My game doesn't crash anymore while loading in a world but I don't seem to have my hotbar. I can only see my hotbar when I press esc

**Comment by osfanbuff63** [comment]
Are you in F1 mode possibly? If not, could you send a screenshot?

**Comment by same-drenth** [comment]
I know for a fact that my hud isnt suppost to be disabled because of what I see when I hit esc and pressing the cinematic button doesn't change anything.
![2022-05-21_18 02 54](https://user-images.githubusercontent.com/12864136/169659877-b94a62f0-2bcb-44fe-9e2b-7165bf15663b.png)
![2022-05-21_18 02 57](https://user-images.githubusercontent.com/12864136/169659881-67b5faf1-d1df-414c-b013-19dc1ec2dbb4.png)

**Comment by same-drenth** [comment]
It could very well be the result of optifabric clashing with other mods that I have, I'll see if I can deduce witch one it is

**Comment by same-drenth** [comment]
I figured out that it is an issue with the Xaeros minimap mod clashing with optifabric. I'm gonna try to see if updating Xaeros mod helps

**Comment by 10AMTiger** [comment]
I have this issue but using H6 still doesn't work. There are no incompatible mods interfering either. It seems to just be something between these two mods.

**Comment by 10AMTiger** [comment]
> I have this issue but using H6 still doesn't work. There are no incompatible mods interfering either. It seems to just be something between these two mods.

If I only use Optifine and not Optifabric it will run but it won't actually be using optifine. It's definitely something with the Optifabric mod itself.

**Comment by osfanbuff63** [comment]
@Jaytee253 could you provide a log of this happening?

**Comment by 10AMTiger** [comment]
> @Jaytee253 could you provide a log of this happening?

@osfanbuff63  Here you go. I'm pretty sure this is what you are asking for. If not then please clarify, (I've never really done any of this before...).

[09:20:37] [main/INFO]: Loading Minecraft 1.18 with Fabric Loader 0.14.6
[09:20:38] [main/INFO]: Loading 60 mods:
	- apoli 2.2.0 via origins
	- calio 1.4.2 via apoli
	- cardinal-components-base 4.0.0-alpha.1+21w37a via apoli
	- cardinal-components-entity 4.0.0-alpha.1+21w37a via apoli
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.0.42 via apoli
	- fabric 0.43.1+1.18
	- fabric-api-base 0.4.1+b4f4f6cd14 via fabric
	- fabric-api-lookup-api-v1 1.3.5+3ac43d9514 via fabric
	- fabric-biome-api-v1 6.0.1+3ac43d9514 via fabric
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d9514 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d9514 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cd14 via fabric
	- fabric-containers-v0 0.1.18+d154e2c614 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d14 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9514 via fabric
	- fabric-dimensions-v1 2.1.7+43d2957114 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a14 via fabric
	- fabric-events-interaction-v0 0.4.15+3ac43d9514 via fabric
	- fabric-events-lifecycle-v0 0.2.5+b4f4f6cd14 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9514 via fabric
	- fabric-item-api-v1 1.2.7+3ac43d9514 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9514 via fabric
	- fabric-key-binding-api-v1 1.0.8+c8aba2f314 via fabric
	- fabric-keybindings-v0 0.2.6+b4f4f6cd14 via fabric
	- fabric-lifecycle-events-v1 1.4.10+c15ca33514 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9514 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9514 via fabric
	- fabric-mining-levels-v0 0.1.7+b4f4f6cd14 via fabric
	- fabric-models-v0 0.3.3+3ac43d9514 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9514 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd14 via fabric
	- fabric-object-builder-api-v1 1.10.13+3ac43d9514 via fabric
	- fabric-object-builders-v0 0.7.7+3ac43d9514 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac14 via fabric
	- fabric-registry-sync-v0 0.8.5+3ac43d9514 via fabric
	- fabric-renderer-api-v1 0.4.9+3ac43d9514 via fabric
	- fabric-renderer-indigo 0.4.12+3ac43d9514 via fabric
	- fabric-renderer-registries-v1 3.2.7+b4f4f6cd14 via fabric
	- fabric-rendering-data-attachment-v1 0.3.3+d154e2c614 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9514 via fabric
	- fabric-rendering-v0 1.1.9+b4f4f6cd14 via fabric
	- fabric-rendering-v1 1.10.3+6b21378a14 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9514 via fabric
	- fabric-screen-api-v1 1.0.7+3ac43d9514 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9514 via fabric
	- fabric-structure-api-v1 2.0.8+295197a714 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9514 via fabric
	- fabric-textures-v0 1.0.9+3ac43d9514 via fabric
	- fabric-tool-attribute-api-v1 1.3.4+7de09f5514 via fabric
	- fabric-transfer-api-v1 1.5.4+b4f4f6cd14 via fabric
	- fabricloader 0.14.6
	- java 17
	- minecraft 1.18
	- mm 2.3 via optifabric
	- optifabric 1.12.7
	- origins 1.3.0
	- playerabilitylib 1.3.0 via apoli
	- reach-entity-attributes 2.1.1 via origins
	- voicechat 1.18-2.1.22
[09:20:38] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/jayte/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[09:20:38] [main/INFO]: Compatibility level set to JAVA_16
[09:20:40] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[09:20:41] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[09:20:42] [main/ERROR]: Critical injection failure: LVT in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V has incompatible changes at opcode 993 in callback apoli.mixins.json:WorldRendererMixin from mod apoli->@Inject::getEntity(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_3695;ZLnet/minecraft/class_243;DDDLnet/minecraft/class_1159;ZLnet/minecraft/class_4604;ZLnet/minecraft/class_4597$class_4598;Ljava/util/Iterator;Lnet/minecraft/class_1297;)V.
 Expected: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, Lnet/minecraft/class_4597$class_4598;, Ljava/util/Iterator;, Lnet/minecraft/class_1297;]
    Found: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, Z]
Available: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, Z, Lnet/minecraft/class_4597$class_4598;, I, I, Ljava/util/Collection;, Ljava/util/Iterator;, Ljava/util/List;, Ljava/util/Iterator;, Lnet/minecraft/class_1297;, Lnet/minecraft/class_4597;, Lnet/minecraft/class_4618;, I]
[09:20:42] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[fabric-loader-0.14.6-1.18.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) ~[fabric-loader-0.14.6.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_761 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:418) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:284) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[fabric-loader-0.14.6-1.18.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) ~[fabric-loader-0.14.6.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:284) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[fabric-loader-0.14.6-1.18.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) ~[fabric-loader-0.14.6.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V has incompatible changes at opcode 993 in callback apoli.mixins.json:WorldRendererMixin from mod apoli->@Inject::getEntity(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_3695;ZLnet/minecraft/class_243;DDDLnet/minecraft/class_1159;ZLnet/minecraft/class_4604;ZLnet/minecraft/class_4597$class_4598;Ljava/util/Iterator;Lnet/minecraft/class_1297;)V.
 Expected: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, Lnet/minecraft/class_4597$class_4598;, Ljava/util/Iterator;, Lnet/minecraft/class_1297;]
    Found: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, Z]
Available: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, Z, Lnet/minecraft/class_4597$class_4598;, I, I, Ljava/util/Collection;, Ljava/util/Iterator;, Ljava/util/List;, Ljava/util/Iterator;, Lnet/minecraft/class_1297;, Lnet/minecraft/class_4597;, Lnet/minecraft/class_4618;, I]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:547) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1378) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:284) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[fabric-loader-0.14.6-1.18.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) ~[fabric-loader-0.14.6.jar:?]
	... 2 more

**Comment by osfanbuff63** [comment]
Yep, that's what I was looking for!

I think this is possibly an issue with the Fabric Loader being too new. So, I'd try (if you don't want to update your MC version):

- Make a new Fabric Loader profile using a 0.13.x version, which I believe is when 1.18(.1) was the newest version
- Update OptiFabric. OptiFabric's newest version *should* still be compatible (1.13.0).

You might want to update to 1.18.1 since 1.18 and 1.18.1 are the same version but 1.18.1 fixes the log4j vulnerability, and most mods' 1.18 versions are compatible with 1.18.1.

**Comment by 10AMTiger** [comment]
Alright. I will try that with 1.18.1. The reason why I went to 1.18 was that I was getting the same error with 1.18.2. I think I understood that the Fabric Loader was too new somewhere along the line. That issue was confined to just a server I was trying to set up though, not the actual client which I'm trying to fix now.

I will let you know if it works.

**Comment by 10AMTiger** [comment]
Updated everything to 1.18.1. Ended up getting the same runtime issue but it the message seemed different from the usual crash messages before.

![image](https://user-images.githubusercontent.com/57071055/171268092-ed661225-6ea0-420e-b649-0e1f9050abca.png)

I also have the crash report here:

[crash-2022-05-31_12.18.48-client.txt](https://github.com/Chocohead/OptiFabric/files/8808727/crash-2022-05-31_12.18.48-client.txt)

Here is the logs if you need it as well:

[latest.log](https://github.com/Chocohead/OptiFabric/files/8808749/latest.log)

I did do what you said of making the Fabric Loader using the 1.13 version and also updated Optifabric. Hopefully what I sent helps.
