### ISSUE TITLE
Optifabric crashes upon startup.

### ISSUE THREAD

**Issue by Nyameliaaaa** [Chocohead/OptiFabric#736]
MC Version: 1.18.2
Fabric Version: 0.14.7
Optifine Version: 1.18.2 HD U H7
--

Crash log:
```A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'optifabric'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'optifabric'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	... 2 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'optifabric'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of me.modmuss50.optifabric.mod.OptifabricLoadGuard failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:418)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 5 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fabric-registry-sync-v0.mixins.json:MixinDynamicRegistryManager from mod fabric-registry-sync-v0] from phase [DEFAULT] in config [fabric-registry-sync-v0.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Mixin target type mismatch: net.minecraft.class_5455 is an interface in org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard@66bacdbc
	at org.spongepowered.asm.mixin.transformer.MixinInfo$SubType.validateTarget(MixinInfo.java:553)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1027)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1008)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:896)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:869)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
	... 20 more
```

**Comment by MazeWave** [comment]
Same error !

**Comment by Booscatwo** [comment]
Me too!

**Comment by ghost** [comment]
Downgrade fabric launcher and Fabric API to 0.13.3 - 0.14.5, and install a Fabric API lower than 0.55. There was a change added in that update that currently breaks Optifabric.

**Comment by Booscatwo** [comment]
My fabric launcher is already on 13.3, and my API is on  46.6....

**Comment by Booscatwo** [comment]
![Screenshot 2022-06-12 092311](https://user-images.githubusercontent.com/107288939/173240278-c2a8ce5d-ebb8-491c-8a32-f70969846afc.png)

**Comment by Booscatwo** [comment]
![Screenshot 2022-06-12 092408](https://user-images.githubusercontent.com/107288939/173240327-1c917616-8f9b-4643-8ca5-2482473d6659.png)
These are my mods

**Comment by ghost** [comment]
> ![Screenshot 2022-06-12 092408](https://user-images.githubusercontent.com/107288939/173240327-1c917616-8f9b-4643-8ca5-2482473d6659.png)
> These are my mods

Hmm, I assumed you were on the latest version, my apologies. It could be a mod incompatibility, you could remove each one and reinstall one by one to work it out.

**Comment by Booscatwo** [comment]
I removed all my mods but maliblib, api, optifabric, and optifine, and it doesn't crash anymore, but it goes to the Mojang logo, the white bar loads to the end, then resets to the beginning, loads to end, resets, and keeps going endlessly

**Comment by thatbusinesscheems** [comment]
getting same issue, im on 1.18.2, fabric launcher 0.13.3 and api 0.47.7
i have latest optifine, latest optifabric, latest version of origins for 1.18.2 and fabric api
