### ISSUE TITLE
Quilt support?

### ISSUE THREAD

**Issue by cjtganzon** [Chocohead/OptiFabric#751]
Will you add support for Quilt in the future? Currently, it crashes trying to use it and the normal Fabric loader works fine.

**Comment by y2k04** [comment]
Can confirm. Here is the log: [https://pastebin.com/SmUVU3Nz](https://pastebin.com/SmUVU3Nz)

**Comment by topia** [comment]
```
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.util.version.VersionParsingException
```

This stack trace shows that the quilt-loader's fabric mod compatibility layer doesn't provide the necessary class for optifabric.
I think that the quilt-loader should provide that class.

But although if it's implemented, optifabric has a fabric API compatibility mixin (patching to fabric API), so developing the patch to qsl/quilted-fabric-api is also necessary. it's not an easy task, I think.

**Comment by jplusc** [comment]
Just copying over my log and such from a diff issue I opened about this before I saw this one : )

....

** Exception while loading entries for entrypoint 'mm:early_risers'  **


Is there anything that can be done to make optifabric more compatible with quilt as other fabric mods seem to do well on quilt,

or is this something that quilt needs to do to make quilt more compatible with your mod?

I'd really like to keep optifine over sodium and your mod has made that possible for me for a long time.

thanks for all your work!!




```
[11:15:26] [main/ERROR]: Error encountered during mixin config postInit step 'mixins.mm.json' from mod 'mm': Exception while loading entries for entrypoint 'mm:early_risers' provided by 'optifabric'
org.quiltmc.loader.impl.entrypoint.QuiltEntrypointException: Exception while loading entries for entrypoint 'mm:early_risers' provided by 'optifabric'
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.getEntrypoints(EntrypointStorage.java:177) ~[quilt-loader-0.17.0.jar:?]
	at org.quiltmc.loader.impl.QuiltLoaderImpl.getEntrypoints(QuiltLoaderImpl.java:364) ~[quilt-loader-0.17.0.jar:?]
	at org.quiltmc.loader.api.QuiltLoader.getEntrypoints(QuiltLoader.java:51) ~[quilt-loader-0.17.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.getEntrypoints(FabricLoaderImpl.java:50) ~[quilt-loader-0.17.0.jar:?]
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340) ~[Fabric-ASM-v2.3.jar-8706edde-901e-4a1e-938d-d7679776b24a-nested.jar:?]
```

full log:
https://paste.ee/p/GEoY8 (expired new link below)
https://paste.denizenscript.com/View/99181

**Comment by leo60228** [comment]
Quilt doesn't attempt compatibility with internal APIs. In general, mods are heavily discouraged from using them, even on Fabric, and they could break at any time.
