### ISSUE TITLE
Game crashes with every optifine preview version

### ISSUE THREAD

**Issue by MarcPG1905** [Chocohead/OptiFabric#770]
My game crashes when I connect to a server and notenoughcrashes is saying:
![image](https://user-images.githubusercontent.com/87030363/177949716-ef3f12fb-a967-428b-b42d-8d03a15907d5.png)

And when I go back to title screen and reconnect, it crashes another time.
I also tried to tuurn off connected textures, emissive textures, custom sky, cem and random entities but it wont work.
And when I load a single player world, I get the error:
Connection Lost
Invalid player data

I dont know why this is happening and when I remove optifine and optifabric, everything works fine.
Here is a log/crash text or something like this when I connect to a server:

```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 08.07.22, 10:27
Description: Unexpected error

java.lang.ArithmeticException: / by zero
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.1)
	at net.minecraft.client.MinecraftClient.handler$zgc000$bobbyUpdate(MinecraftClient:4889)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1098)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:734)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$bmo000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:18439)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:761)
	at net.minecraft.client.main.Main.main(Main:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:573)

-- Affected level --
Details:
	All players: 1 total; [class_746['MarcPG1905'/205694, l='ClientLevel', x=8.50, y=65.00, z=8.50]]
	Chunk stats: 5041, 0 F: 0 L: 0 U: 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (-53,96,0), Section: (at 11,0,0 in -4,6,0; chunk contains blocks -64,0,0 to -49,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 0 game time, 0 day time
	Server brand: Hypixel BungeeCord (1.3.0) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:573)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:758)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$bmo000$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:18439)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Eclectic Trove 1.19, CleanMC, MarcPG1905's PVP overlay v1, Fabric Mods, loadmyresources.hiddenpack, visualoverhaul/rounddiscs, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 500667208 bytes (477 MiB) / 1677721600 bytes (1600 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12600K
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 3,69
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 16
	Graphics card #0 name: Intel(R) UHD Graphics 770
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024,00
	Graphics card #0 deviceId: 0x4680
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1660
	Memory slot #0 capacity (MB): 16384,00
	Memory slot #0 clockSpeed (GHz): 3,47
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384,00
	Memory slot #1 clockSpeed (GHz): 3,47
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37405,72
	Virtual memory used (MB): 16706,53
	Swap memory total (MB): 4864,00
	Swap memory used (MB): 0,00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.19-fabric0.53.3-1.3.1
		advancementplaques: Advancement Plaques 1.4.5
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.7.28
		armored-elytra: Armored Elytra 4.0.0+build.20
		baritone: Baritone 1.8.3-125-g9c2134e6
		bebooks: Better Enchanted Books 1.4.1
		betterf3: BetterF3 1.3.0
		big_items_duh: Big items, duh! 1.1.3+mc1.19
			amecsapi: Amecs API 1.3.6+mc22w17a
			coat: Coat 1.0.0-beta.18+mc22w17a
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.6.0+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc22w17a
		bobby: Bobby 4.0.0
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		bookshelf: Bookshelf 14.0.2
		brb: Better Recipe Book 1.6.0
		breakfree: Break Free 1.1.0
		chat_heads: Chat Heads 0.6.0
		cleanview: CleanView 1.19-v1-fabric
		cleardespawn: Clear Despawn 1.1.8
		clickadv: Clickable Advancements Mod 2.5
		clickthrough: ClickThrough 1.19-fabric0.53.3-0.4
			crowdin-translate: CrowdinTranslate 1.4+1.19
			gbfabrictools: GBfabrictools 1.3.4+1.19
		cloth-config: Cloth Config v6 7.0.72
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+1
		colormeoutlines: Color Me Outlines 1.1.1
		controlling: Controlling For Fabric 10.0+2
		custom_hud: CustomHud 2.1.0+1.19
		customstars: Custom Stars 1.1+1.19
		dcch: DCCH 2.0+1.17
		deathlog: DeathLog 0.2.10+1.19
		detailab: Detail Armor Bar 2.6.2+1.19-fabric
		double_hotbar: Double Hotbar 1.2.0
		dynamiccrosshair: Dynamic Crosshair 3.1+1.19
		eatinganimationid: Eating Animation 1.8.1
		ecs: Elytra/Chestplate Swapper 1.2.1-MC1.19
		enchantment_lore: Enchantment Lore 1.2.7
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		fabric: Fabric API 0.57.0+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.1+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		fastload: Fast Load 1.1.5
		flytre_lib: FlytreLib 1.8.5
		forgeconfigapiport: Forge Config API Port 4.0.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		freecam: Freecam 1.1.2
		hatlist: Hat List 1.3
		horsestatsvanilla: Horse Stats Vanilla 4.2.0
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		iceberg: Iceberg 1.0.38
		iknowwhatimdoing: I Know What I'm Doing 4.1.0
		illuminations: Illuminations 1.10.6
		inventoryhud: Inventory HUD + 3.4.2
		inventoryprofilesnext: Inventory Profiles Next 1.5.3
		inventorytabs: Inventory Tabs 0.7.0-1.19.x
		invmove: InvMove 0.8.0
		isxander-main-menu-credits: Main Menu Credits 1.1.1
		itemmodelfix: Item Model Fix 1.0.3+1.19
		java: OpenJDK 64-Bit Server VM 17
		jukeboxparticles: Jukebox Particles 1.0.0
		konkrete: Konkrete 1.3.3
		krypton: Krypton 0.2.0
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lazy-language-loader: lazy-language-loader 0.3.1
		lazydfu: LazyDFU 0.1.3
		legendarytooltips: Legendary Tooltips 1.2.6
		linsapi: LinsAPI 1.1
		loadmyresources: Load My Resources 1.0.1
		lowfire: Low Fire 1.19-3.0.0
		mainmenuchanger: Main Menu Changer 1.1.0
		make_bubbles_pop: Make Bubbles Pop Mod 0.0.2-1.19
		minecraft: Minecraft 1.19
		modmenu: Mod Menu 4.0.0
		morecosmetics: MoreCosmetics 1.1.1
		mousewheelie: Mouse Wheelie 1.10.1+mc1.19-pre1
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
		neat: Neat 1.8-31-FABRIC
			fiber: fiber 0.23.0-2
		nochatreports: No Chat Reports 1.19-v1.2.3
		notenoughcrashes: Not Enough Crashes 4.1.6+1.19
		notifmod: NotifMod 1.2.6
		offershud: OffersHUD 1.19-1.1.0
		optifabric: OptiFabric 1.13.5
			mm: Manningham Mills 2.3
		ostoverhaul: Ost Overhaul 0.2.4
		particlerain: Particle Rain 2.0.0
		perspektive: perspektive 1.1.0
		presencefootsteps: Presence Footsteps 1.6.1
			kirin: Kirin UI 1.11.0
		quickreplant: quickreplant 1.1.1
		raised: Raised 1.1.1
		realisticitemdrops: Realistic Item Drops 1.1-1.19
		replaymod: Replay Mod 1.19-2.6.6
		roughlyenoughitems: Roughly Enough Items 9.1.503
		roughlyenoughprofessions: Roughly Enough Professions 1.1.0
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		savesettings: Save Settings 1.1.0
		screencopy: Screencopy 1.2.1
			com_github_ramanrajarathinam_native-utils: native-utils 1.0.0
			io_github_imurx_arboard: arboard 1.1.1
		shulkerboxtooltip: Shulker Box Tooltip 3.0.10+1.19
		signtools: Sign Tools 1.0.0
		simple_utilities: Simple HUD Utilities 2.5.0
			autoconfig1u: Auto Config v1 Updated 3.3.1
		skinlayers: 3d Skin Layers 1.4.6-mc1.19-rc2
		smoothboot: Smooth Boot 1.19-1.7.1
		smoothswapping: Smooth Swapping 0.4.5
		sound_physics_remastered: Sound Physics Remastered 1.19-1.0.6
		spellchecker: Spell Checker 2.1.0
		stairautojump: StairAutoJump 0.0.3
		statuseffecttimer: Status Effect Timer 1.1.1+1.19
		stendhal: Stendhal 1.3.3-1.19
		timestamp_chat: Timestamp Chat 2.2
		titlechanger: TitleChanger unspecified
		tooltiptweaks: Tooltip Tweaks 1.1.0
		visuality: Visuality 0.5.0
		visualoverhaul: VisualOverhaul 4.1.1
			midnightlib: MidnightLib 0.5.2
		vmp: Very Many Players 0.2.0+beta.5.0
		waxednotwaxed: Waxed Not Waxed 1.0d
		worldedit: WorldEdit 7.2.11-beta-01+6200-0877589
		worldeditcui: WorldEditCUI 1.19+01
		wpit: WPIT 1.5.1+1.19
		xaerominimap: Xaero's Minimap 22.10.1
		xaeroworldmap: Xaero's World Map 1.24.0
		zihusekeyboardwithmenu: UseKeyboardWithMenu 1.0.0
	Launched Version: fabric-loader-0.14.8-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) UHD Graphics 770 GL version 3.2.0 - Build 30.0.101.1660, Intel
	Window size: 1718x1360
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 173538523) Generic error' x 2
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/Eclectic Trove 1.19, file/CleanMC, file/MarcPG1905's PVP overlay v1
	Current Language: English (US)
	CPU: 16x 12th Gen Intel(R) Core(TM) i5-12600K
	Client Crashes Since Restart: 2
	Integrated Server Crashes Since Restart: 0
	OptiFine Version: OptiFine_1.19_HD_U_H8_pre8
	OptiFine Build: 20220707-190615
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 - Build 30.0.101.1660
	OpenGlRenderer: Intel(R) UHD Graphics 770
	OpenGlVendor: Intel
	CpuCount: 16
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Not Enough Crashes (notenoughcrashes)

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.19
	OptiFine jar version: OptiFine_1.19_HD_U_H8_pre8
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/marcg/AppData/Roaming/.minecraft/versions/PG-Client Premium/.optifine/OptiFine_1.19_HD_U_H8_pre8/Optifine-mapped.jar
	OptiFabric error: <None>
```

**Comment by Sebyx1** [comment]
For me it crashes at startup.
But only with OptiFabric. It works without OptiFabric.

**Comment by snurre0** [comment]
Crashing on startup is an entirely different issue.

I think the reported issue here has to do with the Bobby mod. I get the same exact error "java.lang.ArithmeticException: / by zero" when I combine optifabric/optifine with Bobby. If I remove either Bobby, or optifabric/optifine, I can join servers just fine.

I created a blank minecraft fabric profile with fabric version 0.14.8.
I added bobby-4.0.0.jar and optifabric-1.13.5.jar.
I then tested both OptiFine_1.19_HD_U_H8.jar and preview_OptiFine_1.19_HD_U_H9_pre1.jar.

The game crashes every time I try to join a server.
If I remove either Bobby, or optifabric/optifine, I can join just fine.

Crash report:
```

---- Minecraft Crash Report ----
// Why did you do that?

Time: 7/13/22, 4:30 PM
Description: Unexpected error

java.lang.ArithmeticException: / by zero
	at net.minecraft.class_310.handler$zzf000$bobbyUpdate(class_310.java:2889)
	at net.minecraft.class_310.method_1523(class_310.java:1098)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:573)

-- Affected level --
Details:
	All players: 1 total; [class_746['SnuRRe0'/88040, l='ClientLevel', x=-2964.40, y=132.99, z=10023.61]]
	Chunk stats: 361, 157 F: 0 L: 0 U: 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (-6401,40,-6154), Section: (at 15,8,6 in -401,2,-385; chunk contains blocks -6416,-64,-6160 to -6401,319,-6145), Region: (-13,-13; contains chunks -416,-416 to -385,-385, blocks -6656,-64,-6656 to -6145,319,-6145)
	Level time: 72721 game time, 1200641750 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:573)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:758)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 700613072 bytes (668 MiB) / 2394947584 bytes (2284 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 12
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1650 with Max-Q Design
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f91
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9649
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9b41
	Graphics card #1 versionInfo: DriverVersion=30.0.100.9864
	Graphics card #2 name: Citrix Indirect Display Adapter
	Graphics card #2 vendor: Citrix Systems Inc. (0x5853)
	Graphics card #2 VRAM (MB): 0.00
	Graphics card #2 deviceId: 0x1003
	Graphics card #2 versionInfo: DriverVersion=12.40.44.247
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: LPDDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: LPDDR3
	Virtual memory max (MB): 23350.23
	Virtual memory used (MB): 13694.23
	Swap memory total (MB): 7168.00
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		bobby: Bobby 4.0.0
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		fabric: Fabric API 0.57.0+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabricloader: Fabric Loader 0.14.8
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19
		optifabric: OptiFabric 1.13.5
			mm: Manningham Mills 2.3
	Launched Version: fabric-loader-0.14.8-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1650 with Max-Q Design/PCIe/SSE2 GL version 3.2.0 NVIDIA 496.49, NVIDIA Corporation
	Window size: 1024x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
	OptiFine Version: OptiFine_1.19_HD_U_H9_pre1
	OptiFine Build: 20220712-174104
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 496.49
	OpenGlRenderer: NVIDIA GeForce GTX 1650 with Max-Q Design/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.19
	OptiFine jar version: OptiFine_1.19_HD_U_H9_pre1
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/snurr/Twitch/Minecraft/Instances/mc1.19/.optifine/OptiFine_1.19_HD_U_H9_pre1/Optifine-mapped.jar
	OptiFabric error: <None>


```
