### ISSUE TITLE
Error Loading OptiFabric (Error modifying OptiFine file)

### ISSUE THREAD

**Issue by uTyphoon** [Chocohead/OptiFabric#777]
This is the log from an attempt at running optifabric with optifine for 1.16.5. I also have replay mod in my mods folder. It tells me that there was an error modifying the optifine .jar file. I had no trouble running this set of mods on another laptop, yet when I redownloaded all the files over now this error is happening.

[18:52:04] [main/WARN]: Reference map 'mixins.nonmmlauncher.replaymod.refmap.json' for mixins.nonmmlauncher.replaymod.json could not be read. If this is a development environment you can ignore this message
[18:52:21] [main/ERROR]: Error encountered during mixin config postInit step'mixins.mm.json': Failed to setup optifine
java.lang.RuntimeException: Failed to setup optifine
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:51) ~[optifabric-1.9.2.jar:?]
	at com.chocohead.mm.Plugin$$Lambda$83/1448805967.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51]
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:339) ~[1477c11b-2831-4c73-acbf-1425a0db8ac1.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:667) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:542) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.2.jar:0.9.2+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.11.2.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_51]
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.EntrypointStorage$$Lambda$69/331122245.get(Unknown Source) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:137) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.2.jar:?]
Caused by: java.io.UncheckedIOException: Error modifying C:\Users\USERNAME_THING\AppData\Roaming\.minecraft\.optifine\OptiFine_1.16.5_HD_U_G7\Optifine-mapped.jar
	at me.modmuss50.optifabric.util.ZipUtils.transformInPlace(ZipUtils.java:80) ~[optifabric-1.9.2.jar:?]
	at me.modmuss50.optifabric.patcher.PatchSplitter.generateClassCache(PatchSplitter.java:22) ~[optifabric-1.9.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:120) ~[optifabric-1.9.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:38) ~[optifabric-1.9.2.jar:?]
	... 27 more
Caused by: java.io.FileNotFoundException: C:\Users\USERNAME_THING\AppData\Roaming\.minecraft\.optifine\OptiFine_1.16.5_HD_U_G7\Optifine-mapped.jar (Access is denied)
	at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_51]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_51]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_51]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[?:1.8.0_51]
	at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1142) ~[commons-io-2.5.jar:2.5]
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1088) ~[commons-io-2.5.jar:2.5]
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1040) ~[commons-io-2.5.jar:2.5]
	at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2993) ~[commons-io-2.5.jar:2.5]
	at me.modmuss50.optifabric.util.ZipUtils.transformInPlace(ZipUtils.java:78) ~[optifabric-1.9.2.jar:?]
	at me.modmuss50.optifabric.patcher.PatchSplitter.generateClassCache(PatchSplitter.java:22) ~[optifabric-1.9.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:120) ~[optifabric-1.9.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:38) ~[optifabric-1.9.2.jar:?]
	... 27 more
[18:52:21] [main/WARN]: Error loading class: net/optifine/render/ChunkVisibility (java.lang.ClassNotFoundException: net/optifine/render/ChunkVisibility)
[18:52:21] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[18:52:21] [main/WARN]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersRender)
[18:52:21] [main/WARN]: Error loading class: net/coderbot/iris/uniforms/CommonUniforms (java.lang.ClassNotFoundException: net/coderbot/iris/uniforms/CommonUniforms)
[18:52:21] [main/WARN]: Error loading class: net/coderbot/iris/Iris (java.lang.ClassNotFoundException: net/coderbot/iris/Iris)
[18:52:25] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:52:26] [main/INFO]: Setting user: iTyphoon
[18:52:26] [main/INFO]: Definitely not up to no good
[18:52:26] [main/INFO]: [Indigo] Registering Indigo renderer!
[18:52:26] [main/INFO]: [Indigo] Compatibility mode enabled.
[18:52:27] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[18:52:30] [main/INFO]: Narrator library for x64 successfully loaded
[18:52:30] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Renderer API (v1), Fabric Key Bindings (v0), Fabric Loader, Fabric Transfer API (v1), Fabric Structure API (v1), Fabric Containers (v0), Fabric Dimensions API (v1), Fabric Object Builder API (v1), Fabric Game Rule API (v1), Fabric API Base, Fabric Rendering Data Attachment (v1), Manningham Mills, Fabric Textures (v0), Fabric Rendering Fluids (v1), Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric API, Fabric Particles (v1), Fabric Networking (v0), Fabric API Lookup API (v1), Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), Fabric Command API (v1), Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Events Interaction (v0), Fabric Crash Report Info (v1), Fabric Item API (v1), Fabric Entity Events (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Key Binding API (v1), Replay Mod, Fabric Resource Loader (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), OptiFabric, Fabric Commands (v0), Fabric Registry Sync (v0), Fabric Mining Levels (v0), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Models (v0), Fabric Item Groups (v0), Fabric Object Builders (v0)), replaymod_lang
[18:52:34] [main/INFO]: OpenAL initialized.
[18:52:34] [main/INFO]: Sound engine started
[18:52:34] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[18:52:34] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[18:52:34] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[18:52:34] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[18:52:34] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[18:52:34] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[18:52:34] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[18:52:35] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[18:52:35] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[18:52:35] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[18:54:56] [main/INFO]: Stopping!

**Comment by YoinkYoinkerson** [comment]
I have this exact issue
