### ISSUE TITLE
1.19 Exception while loading entries for entrypoint 'mm:early_risers' (quilt api)

### ISSUE THREAD

**Issue by jplusc** [Chocohead/OptiFabric#781]
Some of the mods I use have migrated from fabric -> quilt.

I am still able to use all of them as they are built for fabric and run on the quilt api, or they now have quilt only versions.

However, I cannot get optifabric to run on quilt.

Is there anything that can be done to make optifabric more compatible with quilt as other fabric mods seem to do well on quilt,

or is this something that quilt needs to do to make quilt more compatible with your mod?

I'd really like to keep optifine over sodium and your mod has made that possible for me for a long time.

thanks for all your work!!

```
[11:15:26] [main/ERROR]: Error encountered during mixin config postInit step 'mixins.mm.json' from mod 'mm': Exception while loading entries for entrypoint 'mm:early_risers' provided by 'optifabric'
org.quiltmc.loader.impl.entrypoint.QuiltEntrypointException: Exception while loading entries for entrypoint 'mm:early_risers' provided by 'optifabric'
	at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.getEntrypoints(EntrypointStorage.java:177) ~[quilt-loader-0.17.0.jar:?]
	at org.quiltmc.loader.impl.QuiltLoaderImpl.getEntrypoints(QuiltLoaderImpl.java:364) ~[quilt-loader-0.17.0.jar:?]
	at org.quiltmc.loader.api.QuiltLoader.getEntrypoints(QuiltLoader.java:51) ~[quilt-loader-0.17.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.getEntrypoints(FabricLoaderImpl.java:50) ~[quilt-loader-0.17.0.jar:?]
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340) ~[Fabric-ASM-v2.3.jar-8706edde-901e-4a1e-938d-d7679776b24a-nested.jar:?]
```

full log:
https://paste.ee/p/GEoY8

**Comment by topia** [comment]
duplicate of #751?

**Comment by jplusc** [comment]
oops, yep.  I missed that other open issue.  I'll close this : )
