### ISSUE TITLE
Crash 1.19 + Origins

### ISSUE THREAD

**Issue by KernelN** [Chocohead/OptiFabric#783]
(optifabric-1.13.5 + OptiFine_1.19_HD_U_H8 + Origins-1.19-1.6.2) is not working, I'm not sure if it's fixable. just reporting.
![image](https://user-images.githubusercontent.com/34839646/178540693-af0334bc-55ce-4749-85cd-32755944b176.png)

**Comment by Andy1x** [comment]
could you add a crash report or the latest.log?

**Comment by KernelN** [comment]
Time: 12/7/22 13:10
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_778 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_776.<init>(class_776.java:50)
	at net.minecraft.class_310.<init>(class_310.java:557)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 10 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method addInfo(Lnet/minecraft/class_1920;Lnet/minecraft/class_1087;Lnet/minecraft/class_2680;Lnet/minecraft/class_2338;Lnet/minecraft/class_4587;Lnet/minecraft/class_4588;ZLjava/util/Random;JILjava/lang/Object;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;ZLnet/minecraft/class_243;Ljava/lang/Throwable;Lnet/minecraft/class_128;Lnet/minecraft/class_129;)V in optifabric.compat.fabric-renderer-api.mixins.json:BlockModelRendererMixin from mod optifabric failed injection check, (0/1) succeeded. Scanned 2 target(s). Using refmap optifabric-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 13 more

**Comment by KernelN** [comment]
-- OptiFabric --
Details:
	OptiFine jar designed for: 1.19
	OptiFine jar version: OptiFine_1.19_HD_U_H8
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/Ale/AppData/Roaming/.minecraft/.optifine/OptiFine_1.19_HD_U_H8/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by Ezxsanna** [comment]
its happening to me too
maybe u remove it until it resolves

**Comment by Andy1x** [comment]
Interesting, the problem seems to be with Fabric Renderer API, I'm not sure why it's causing issues with Origins as of yet

**Comment by Andy1x** [comment]
I replicated the issue, which actually is with Apoli which Origins uses. See here:
`[18:42:39] [main/ERROR]: Critical injection failure: LVT in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V has incompatible changes at opcode 1025 in callback apoli.mixins.json:WorldRendererMixin from mod apoli->@Inject::getEntity(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_3695;ZLnet/minecraft/class_243;DDDLnet/minecraft/class_1159;ZLnet/minecraft/class_4604;FZZLnet/minecraft/class_4597$class_4598;Ljava/util/Iterator;Lnet/minecraft/class_1297;)V.
 Expected: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, F, Z, Z, Lnet/minecraft/class_4597$class_4598;, Ljava/util/Iterator;, Lnet/minecraft/class_1297;]
    Found: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, Z, Z, Lnet/minecraft/class_4597$class_4598;]
Available: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, Z, Z, Lnet/minecraft/class_4597$class_4598;, I, I, Ljava/util/Collection;, Ljava/util/Iterator;, Ljava/util/List;, Ljava/util/Iterator;, Lnet/minecraft/class_1297;, Lnet/minecraft/class_4597;, Lnet/minecraft/class_4618;, I]` 

The issue only occurs with Optifabric/Optifine, not if only Origins is installed, so a new mixin needs to be made to fix this. I'll see if I can make a fix but don't count on it lol I'm new to this 

Also attached my latest.log as it looks different to yours.
[latest.log](https://github.com/Chocohead/OptiFabric/files/9095642/latest.log)

**Comment by KernelN** [comment]
> its happening to me too maybe u remove it until it resolves

Yeah, I dropped optifine for a while, I just wanted to report it now that I found the conflicting files in case it helps

**Comment by KernelN** [comment]
> I replicated the issue, which actually is with Apoli which Origins uses. See here: `[18:42:39] [main/ERROR]: Critical injection failure: LVT in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V has incompatible changes at opcode 1025 in callback apoli.mixins.json:WorldRendererMixin from mod apoli->@Inject::getEntity(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_3695;ZLnet/minecraft/class_243;DDDLnet/minecraft/class_1159;ZLnet/minecraft/class_4604;FZZLnet/minecraft/class_4597$class_4598;Ljava/util/Iterator;Lnet/minecraft/class_1297;)V. Expected: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, F, Z, Z, Lnet/minecraft/class_4597$class_4598;, Ljava/util/Iterator;, Lnet/minecraft/class_1297;] Found: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, Z, Z, Lnet/minecraft/class_4597$class_4598;] Available: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, Z, Z, Lnet/minecraft/class_4597$class_4598;, I, I, Ljava/util/Collection;, Ljava/util/Iterator;, Ljava/util/List;, Ljava/util/Iterator;, Lnet/minecraft/class_1297;, Lnet/minecraft/class_4597;, Lnet/minecraft/class_4618;, I]`
> 
> The issue only occurs with Optifabric/Optifine, not if only Origins is installed, so a new mixin needs to be made to fix this. I'll see if I can make a fix but don't count on it lol I'm new to this
> 
> Also attached my latest.log as it looks different to yours. [latest.log](https://github.com/Chocohead/OptiFabric/files/9095642/latest.log)

Thanks a lot! I didn't expect the community to be this active tbh

**Comment by Ezxsanna** [comment]
hm
idk if they are gonna fix it...

**Comment by Andy1x** [comment]
My laptop is currently sent off for repairs so I can’t work on it right now!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
