### ISSUE TITLE
Meeting a crash between Optfabric/Optfine/fabric(1.16.5)

### ISSUE THREAD

**Issue by SunsetRest** [Chocohead/OptiFabric#786]
1 or more years ago, it worked pretty good. 6 months ago, I used to think that I was my fault. But on these days, when I returned to play MC1.16.5 fabric again, I realized that it may not be a special issue, instead of a bug(I guess).
     Here we are. There are only 3 mods: fabric-api-0.42.0+1.16.jar & optifabric-1.9.6.jar & OptiFine-1.16.5_HD_U_G8.jar. (I think they didn't out of time, because when fabric itself worked alone, it goes well. )
     In additon, Java 8 & Java 17 have been tested, none of them worked.(maybe it is not problem, I guess)
     And reporter said that: "Failed to load Optifine ...... 'net.fabricmc.loader.game.Gameprovider net.fabricmc.loader.FabricLoader.getGameProvider()' "
     Below here are some details about "stack-trace":
     java.lang.NoSuchMethodError: 'net.fabricmc.loader.game.GameProvider net.fabricmc.loader.FabricLoader.getGameProvider()'
	at me.modmuss50.optifabric.mod.OptifineSetup.getLaunchMinecraftJar(OptifineSetup.java:275)
	at me.modmuss50.optifabric.mod.OptifineSetup.getMinecraftJar(OptifineSetup.java:253)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:81)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

In the end, if you have any question, I'd like to give more info.(As a bug, it happened so offen that didn't like a bug)LOL
I think these info maybe enough, hoping Optifabric can be better~

**Comment by SunsetRest** [comment]
IMPORTANT: Now I am updating to 1.11.1 version. I guess it can be worked!

**Comment by SunsetRest** [comment]
oops. with java 8, it doen't work.

**Comment by SunsetRest** [comment]
Below here are the latest details about "stack-trace":
java.lang.NoSuchMethodError: net.fabricmc.loader.FabricLoader.getGameProvider()Lnet/fabricmc/loader/game/GameProvider;
	at me.modmuss50.optifabric.mod.OptifineSetup.getLaunchMinecraftJar(OptifineSetup.java:299)
	at me.modmuss50.optifabric.mod.OptifineSetup.getMinecraftJar(OptifineSetup.java:277)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:84)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by SunsetRest** [comment]
I don't know why. It just make no sense. :(

**Comment by topia** [comment]
I'm not sure why did you pick an old version, 1.9.x. Did you try optifabric-1.13.5 already?

**Comment by SunsetRest** [comment]
emm, 1.11.1 already,but no 1.13.5
&nbsp;


林铂添
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tatsuya ***@***.***&gt;; 
发送时间: 2022年7月14日(星期四) 晚上11:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Chocohead/OptiFabric] Meeting a crash between Optfabric/Optfine/fabric(1.16.5) (Issue #786)





 
I'm not sure why did you pick an old version, 1.9.x. Did you try optifabric-1.13.5 already?

**Comment by SunsetRest** [comment]
I will have  another test, as you say.

**Comment by SunsetRest** [comment]
huh, I think I got your mean. I miss the small notice below the Forge (I misstake that it only for 1.19). The problem solved. Great idea. (Sorry for my stupid)

**Comment by SunsetRest** [comment]
I will write a notice for the mod carryer in my country(I think his blog need updating)

**Comment by SunsetRest** [comment]
3Q

**Comment by topia** [comment]
older optifabric is incompatible with the recent fabric-loader (not fabric API). so if you install a newer fabric-loader, you should install a newer optifabric too.

**Comment by SunsetRest** [comment]
Got it. I have write a small info for this under the old blog
