### ISSUE TITLE
No connected textures with OptiFine 1.16.2 HD_U_G3

### ISSUE THREAD

**Issue by DrakoTrogdor** [Chocohead/OptiFabric#8]
No connected textures are working for me with latest OptiFine 1.16.2 HD_U_G3 when on Fast connected textures.
Changing to Fancy connected textures throws the following error:
[ERROR/minecraft.class_1008]: OpenGL API ERROR: 1281 (GL_INVALID_VALUE error generated. Invalid size and/or offsets.)
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL31C.glCopyBufferSubData(Native Method) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL31.glCopyBufferSubData(GL31.java:298) [lwjgl-opengl-3.2.2.jar:build 10]
	at net.minecraft.class_4493.copyBufferSubData(class_4493.java:2085) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.optifine.render.VboRegion.copyVboData(VboRegion.java:243) [Optifine-mapped.jar:?]
	at net.optifine.render.VboRegion.compactRanges(VboRegion.java:157) [Optifine-mapped.jar:?]
	at net.optifine.render.VboRegion.finishDraw(VboRegion.java:338) [Optifine-mapped.jar:?]
	at net.minecraft.class_761.drawRegion(class_761.java:2307) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_761.method_3251(class_761.java:2228) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1597) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1022) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:693) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1023) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:656) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.2-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.2+build.206.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[11:39:23] [ERROR/optifine.Config]: [OptiFine] OpenGL error: 1281 (Invalid value), at: Copy VBO range

**Comment by Chocohead** [comment]
Is this with render regions enabled? I'd also try it with just OptiFine alone (ie without Fabric at all), as it is very likely this is an issue with OptiFine itself along the lines of [this](https://github.com/sp614x/optifine/issues/2779#issuecomment-667285073).

**Comment by DrakoTrogdor** [comment]
Did some more rigorous testing this morning, CTM works fine with a fresh install of optifine and/or optifabric, including with and without other mods...issue seems to be with the Euclid mod.  I will attempt to troubleshoot with that repo or find a replacement.
Sorry for not being more thorough beforehand!
