### ISSUE TITLE
Optifine Not DETECTED

### ISSUE THREAD

**Issue by G-Glafus** [Chocohead/OptiFabric#800]
Fabric 1.19 crashing with exit code 1...in the log It's saying Optifabric detected and Optifine NOT Detected.This is with Optifabric 1.13.8 and Optifine HD U H8.

**Comment by topia** [comment]
I confirmed to use them. Could you provide full log lines and the list of files in the mod folder?
Could you try to re-check that you have a correct optifine archive? (my `OptiFine_1.19_HD_U_H8.jar` is 6,730,635 bytes, for confirming)

my mod folder:
```
fabric-api-0.58.0+1.19.jar
optifabric-1.13.8.jar
OptiFine_1.19_HD_U_H8.jar
```

loader and Minecraft version:
```
[16:52:21] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
```

**Comment by G-Glafus** [comment]
![image](https://user-images.githubusercontent.com/109846515/180739772-5d5dec58-d5aa-4ab6-a297-619d1b11e2d4.png)

It seems I have accidently deleted the fabric api (this isnt the .minecraft/mods folder ) but the fabric api version is _fabric-api-0.57.0+1.19.jar_

> [12:04:73] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[12:04:85] [main/INFO]: Loading 77 mods:
	- appleskin 2.4.0+mc1.19
	- architectury 5.9.31
	- betterf3 1.3.1
	- betterthirdperson 1.8.1
	- blue_endless_jankson 1.2.1 via kyrptconfig
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 7.0.73
	- clumps 9.0.0+3
	- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
	- custom-crosshair-mod 1.5.0-fabric
	- entityculling 1.5.2-mc1.19
	- essentialgui 1.8+1.19
	- fabric 0.57.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via modmenu
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
	- fabric-blockrenderlayer-v1 1.1.18+9ff28f40a9 via fabric
	- fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
	- fabric-commands-v0 0.2.23+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.27+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.2.0+07df213ea9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.1.1+a680b9b4a9 via fabric
	- fabric-dimensions-v1 2.1.28+a6d2f785a9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.25+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.4+767db26ea9 via fabric
	- fabric-item-groups-v0 0.3.25+9ff28f40a9 via fabric
	- fabric-key-binding-api-v1 1.0.18+9ff28f40a9 via modmenu
	- fabric-keybindings-v0 0.2.16+df3654b3a9 via fabric
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via modmenu
	- fabric-loot-api-v2 1.1.0+03a4e568a9 via fabric
	- fabric-loot-tables-v1 1.1.3+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.10+33fbc738a9 via fabric
	- fabric-models-v0 0.3.15+9ff28f40a9 via fabric
	- fabric-networking-api-v1 1.0.27+7fe97409a9 via fabric
	- fabric-networking-v0 0.3.14+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.7+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-registry-sync-v0 0.9.17+23c4cfefa9 via fabric
	- fabric-renderer-api-v1 1.0.8+9ff28f40a9 via fabric
	- fabric-renderer-indigo 0.6.9+1f92344ea9 via fabric
	- fabric-renderer-registries-v1 3.2.18+df3654b3a9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-rendering-v0 1.1.20+df3654b3a9 via fabric
	- fabric-rendering-v1 1.10.14+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.5+a6d2f785a9 via modmenu
	- fabric-screen-api-v1 1.0.24+f05effafa9 via modmenu
	- fabric-screen-handler-api-v1 1.2.6+9ff28f40a9 via fabric
	- fabric-textures-v0 1.0.18+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabricloader 0.14.8
	- ferritecore 4.2.1
	- fpsreducer 1.19-2.0.2
	- gammautils 1.6.9
	- inventoryhud 3.4.2
	- inventorysorter 1.8.8-1.19
	- java 17
	- kyrptconfig 1.4.6-1.19 via inventorysorter
	- lazydfu 0.1.3
	- minecraft 1.19
	- mm 2.3 via shulkerboxtooltip
	- modmenu 4.0.4
	- notenoughcrashes 4.1.6+1.19
	- optifabric 1.13.8
	- roughlyenoughitems 9.1.517
	- shulkerboxtooltip 3.0.10+1.19
	- starlight 1.1.1+fabric.ae22326
	- voicechat 1.19-2.2.45
[12:04:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/hamdan/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[12:04:91] [main/INFO]: Compatibility level set to JAVA_16
[12:04:93] [main/INFO]: Compatibility level set to JAVA_17
[12:04:65] [main/INFO]: **OptiFine was NOT detected.**
[12:04:96] [main/INFO]: **OptiFabric was detected.**
[12:04:68] [main/INFO]: bre2el.fpsreducer.mixin.MinecraftClientMixin will be applied.
[12:04:68] [main/INFO]: bre2el.fpsreducer.mixin.KeyboardMixin will be applied.
[12:04:68] [main/INFO]: bre2el.fpsreducer.mixin.RenderSystemMixin will be applied.
[12:04:68] [main/INFO]: bre2el.fpsreducer.mixin.WindowMixin will be applied.
Found existing patched optifine jar, using that
[12:04:61] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[12:04:73] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[12:04:62] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.util.crash.CrashReport.asString(CrashReport:173)
	at net.minecraft.util.crash.CrashReport.initCrashReport(CrashReport:343)
	at net.minecraft.client.main.Main.main(Main:152)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_315 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:3297)
	at java.lang.Class.getDeclaredFields(Class.java:2371)
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:499)
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector spoofDisplayOnlyKeyBinds(Lnet/minecraft/class_304;)Ljava/lang/String; in net.kyrptonaught.kyrptconfig.json:displaykeybind.GameOptionsMixin from mod kyrptconfig failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap kyrptconfig-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 18 more

[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (121 ms)
[Launcher] Minecraft closed with exit code: 1
flush now
Here I am!
flush now
[Launcher] Launcher exited.

**Comment by topia** [comment]
```
- inventorysorter 1.8.8-1.19
...
- kyrptconfig 1.4.6-1.19 via inventorysorter
...
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector spoofDisplayOnlyKeyBinds(Lnet/minecraft/class_304;)Ljava/lang/String; in net.kyrptonaught.kyrptconfig.json:displaykeybind.GameOptionsMixin from mod kyrptconfig failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap kyrptconfig-refmap.json
```
I think this is a mod compatibility issue between optifabric and kyrptconfig (via inventorysorter).
Could you check if the optifabric works without it?

**Comment by G-Glafus** [comment]
On Mon, 25 Jul 2022 at 12:57 PM Tatsuya Noda ***@***.***>
wrote:

> - inventorysorter 1.8.8-1.19
> ...
> - kyrptconfig 1.4.6-1.19 via inventorysorter
> ...
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector spoofDisplayOnlyKeyBinds(Lnet/minecraft/class_304;)Ljava/lang/String; in net.kyrptonaught.kyrptconfig.json:displaykeybind.GameOptionsMixin from mod kyrptconfig failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap kyrptconfig-refmap.json
>
> I think this is a mod compatibility issue between optifabric and
> kyrptconfig (via inventorysorter).
> Could you check if the optifabric works without it?
>
I checked and optifabric works without it...Thank you for your time
