### ISSUE TITLE
Incompatibilities with All Of Fabric 5 Modpack mods

### ISSUE THREAD

**Issue by Combreaker** [Chocohead/OptiFabric#809]
Hi, i can't launch AllOfFabric5 with this mod.

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Lithium' (lithium) 0.7.10 with any version that is compatible with:
		 - optifabric 1.13.8
	 - Replace mod 'Modern Industrialization' (modern_industrialization) 1.2.1 with any version that is compatible with:
		 - optifabric 1.13.8
	 - Replace mod 'Sodium' (sodium) 0.4.1+build.15 with version 0.4.1 that is compatible with:
		 - optifabric 1.13.8
	 - Replace mod 'Bewitchment' (bewitchment) 1.18-22 with any version that is compatible with:
		 - optifabric 1.13.8
	 - Replace mod 'Iris' (iris) 1.2.5 with any version that is compatible with:
		 - optifabric 1.13.8
	 - Replace mod 'Create' (create) mc1.18.2_v0.4.1+637 with any version that is compatible with:
		 - optifabric 1.13.8
Unmet dependency listing:
	 - Mod 'Bewitchment' (bewitchment) 1.18-22 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.8!
	 - Mod 'Create' (create) mc1.18.2_v0.4.1+637 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.8!
	 - Mod 'Sodium' (sodium) 0.4.1+build.15 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.8!
	 - Mod 'Iris' (iris) 1.2.5 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.8!
	 - Mod 'Lithium' (lithium) 0.7.10 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.8!
	 - Mod 'Modern Industrialization' (modern_industrialization) 1.2.1 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.8!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by topia** [comment]
They declared it incompatible with optifabric. Some of these mod are not compatible by design (as I know, at least sodium, lithium, and iris). And some of these mod don't want to make compatible with optifabric (requires hard work).

Anyway, optifabric can't do anything about it because they declare it.
