### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by vinnyg0621** [Chocohead/OptiFabric#86]
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 10/30/20 11:40 AM
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_329.<init>(class_329.java:168)
	at net.minecraft.class_310.<init>(class_310.java:543)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixin.chatbubbles.json:MixinChatListenerHud] from phase [DEFAULT] in config [mixin.chatbubbles.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 16 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on postSay could not find any targets matching 'Lnet/minecraft/class_335;method_1794(Lnet/minecraft/class_2556;Lnet/minecraft/class_2561;)V' in net.minecraft.class_335. Using refmap mixin.chatbubbles.refmap.json [PREINJECT Applicator Phase -> mixin.chatbubbles.json:MixinChatListenerHud -> Prepare Injections ->  -> handler$zzg000$postSay(Lnet/minecraft/class_2556;Lnet/minecraft/class_2561;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at sun.reflect.GeneratedConstructorAccessor13.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.3
	OptiFine jar version: OptiFine_1.16.3_HD_U_G4_pre2
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:\Users\vinny.DESKTOP-HD3PDS0\OneDrive\Desktop\Minecraft\OptiFabric 1.16\.optifine\OptiFine_1.16.3_HD_U_G4_pre2\Optifine-mapped.jar
	OptiFabric error: <None>
Stacktrace:
	at net.minecraft.class_128.handler$zbo000$fillSystemDetails(class_128.java:523)
	at net.minecraft.class_128.<init>(class_128.java:55)
	at net.minecraft.class_128.method_560(class_128.java:417)
	at net.minecraft.client.main.Main.main(Main.java:183)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- Initialization --
Details:

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1582485216 bytes (1509 MB) / 2818572288 bytes (2688 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 1.11.1+1.16.3
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		autoconfig1u: Auto Config v1 Updated 3.2.2
		campanion: Campanion 1.2.0+build.39
		chatbubbles: ChatBubbles 1.0.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.1
		cobbletable: Cobblestone Crafting Table 1.0.0
		connectiblechains: Connectible Chains 1.0.1
		crumbs: Crumbs 1.0.1+1.16.3-fabric
		decorative: Decorative 3.0.0
		fabric: Fabric API 0.24.3+build.414-1.16
		fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
		fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a95
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a95
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a95
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab95
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a95
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a95
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a95
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a95
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a95
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b46237995
		fabricloader: Fabric Loader 0.10.5+build.213
		firstperson: FirstpersonModel 1.3.0
		jankson: Jankson 3.0.1+j1.2.0
		kirin: Kirin UI 1.7-1.16.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.0.0+1.16.3
		midnight-hats: Midnight Hats 1.0.2
		minecraft: Minecraft 1.16.3
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 1.14.6+build.31
		optifabric: OptiFabric 1.7.0
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		pling: Pling 1.2.0
		presencefootsteps: Presence Footsteps r28+1.16.2
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		repurposed_structures: Repurposed Structures 1.16.3-1.6.9
		rocks: This Rocks! 1.0.0
		simplexterrain: Simplex Terrain 0.7.0
		soaring-clouds: Soaring Clouds 1.2.0-1.16
		voyager: Voyager 1.0.0
		woods_and_mires: Woods and Mires 1.0.2+1.16.3
		worldedit: WorldEdit 7.2.0-rc2+a615e01
	Launched Version: fabric-loader-0.10.5+build.213-1.16.3
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) Vega 3 Graphics GL version 4.6.13547 Compatibility Profile Context 25.20.15030.4, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 4x AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx 
	OptiFine Version: OptiFine_1.16.3_HD_U_G4_pre2
	OptiFine Build: 20201007-190609
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13547 Compatibility Profile Context 25.20.15030.4
	OpenGlRenderer: AMD Radeon(TM) Vega 3 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by vinnyg0621** [comment]
I really don't know why crash reports don't tell you what you can do to fix them >:(

**Comment by Chocohead** [comment]
There's a limit to how clever the crash reporting can be given it can never be sure of what code the mods running might do.

In this case at least this is from Chat Bubbles only supporting 1.15.2 (and below with earlier versions).

**Comment by vinnyg0621** [comment]
but I took out chat bubbles and then it was still crashing!

**Comment by Chocohead** [comment]
Then it will be something else as well... But without the crash report there's no way of guessing what
