### ISSUE TITLE
cant launch fabric

### ISSUE THREAD

**Issue by Seal077** [Chocohead/OptiFabric#862]
i tried to launch fabric on the newest version (0.14.9) and it said that i needed the version of optifabric 1.13.16, but i already had it on the folder. Tried lauching it on a later version of fabric and the log said:

<html>at org.objectweb.asm.ClassReader.&lt;init&gt;(ClassReader.java:199)<br>at org.objectweb.asm.ClassReader.&lt;init&gt;(ClassReader.java:180)<br>at org.objectweb.asm.ClassReader.&lt;init&gt;(ClassReader.java:166)<br>at net.fabricmc.tinyremapper.TinyRemapper.analyze(TinyRemapper.java:571)<br>at net.fabricmc.tinyremapper.TinyRemapper.access$400(TinyRemapper.java:73)<br>at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:525)<br>at net.fabricmc.tinyremapper.TinyRemapper$2.visitFile(TinyRemapper.java:521)<br>at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)<br>at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)<br>at net.fabricmc.tinyremapper.TinyRemapper.readFile(TinyRemapper.java:521)<br>at net.fabricmc.tinyremapper.TinyRemapper.access$200(TinyRemapper.java:73)<br>at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:492)<br>at net.fabricmc.tinyremapper.TinyRemapper$1$1.get(TinyRemapper.java:488)<br>at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)<br>at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)<br>at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)<br>at java.base/java.lang.Thread.run(Thread.java:833)</html>

please help
thank you 
ps- im trying to launch fabric with tweekaroo and optifabric and their  dependencies.

**Comment by topia** [comment]
Unfortunately, I can't find all the essential information (such as which part causes it). Did you cut off your stacktrace? If so, please upload full of latest.log.
