### ISSUE TITLE
Game Crashed on boot with latest of everything crash is adverted when Optifine is not present

### ISSUE THREAD

**Issue by OPcouchpotato** [Chocohead/OptiFabric#878]
Here's the crash report:
![image](https://user-images.githubusercontent.com/113820090/190889206-ccbdb996-3498-4311-bf28-e3b8ea546880.png)

Description: Initializing game

java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/class_5944.<init>(Lnet/minecraft/class_5912;Ljava/lang/String;Lnet/minecraft/class_293;)V @7: invokespecial
  Reason:
    Type uninitializedThis (current frame, stack[2]) is not assignable to 'net/minecraft/class_5944'
  Current Frame:
    bci: @7
    flags: { flagThisUninit }
    locals: { uninitializedThis, 'net/minecraft/class_5912', 'java/lang/String', 'net/minecraft/class_293' }
    stack: { uninitializedThis, 'net/minecraft/class_5912', uninitializedThis, 'java/lang/String', 'net/minecraft/class_5912', 'java/lang/String', 'net/minecraft/class_293' }
  Bytecode:
    0000000: 2a2b 2a2c 2b2c 2db7 005d 59c7 000d bb00
    0000010: 5f59 1261 b700 64bf 2db7 0067 b1       
  Stackmap Table:
    full_frame(@24,{UninitializedThis,Object[#110],Object[#112],Object[#114]},{UninitializedThis,Object[#110],Object[#116]})

	at net.minecraft.class_757.method_34521(class_757.java:446)
	at net.minecraft.class_310.<init>(class_310.java:631)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by OPcouchpotato** [comment]
Blur Is incompatible with OptiFine
