### ISSUE TITLE
Looped loading screen because of Optifabric

### ISSUE THREAD

**Issue by Red4048** [Chocohead/OptiFabric#889]
the same as someone's else's issue but its on the latest version of fabric, fabric api, optifabric and optifine for 1.16.5

i have the latest.log here: https://paste.ee/p/jXZJ9

**Comment by topia** [comment]
> i have the latest.log here: https://paste.ee/p/jXZJ9

```
Caused by: java.lang.UnsupportedOperationException
	at me.jellysquid.mods.hydrogen.common.collections.FixedArrayList.clear(FixedArrayList.java:106) ~[hydrogen-fabric-mc1.16.5-0.2.jar:?]
	at net.optifine.model.BlockModelUtils.replaceTexture(BlockModelUtils.java:178) ~[Optifine-mapped.jar:?]
```

This stack trace shows the incompatibility between optifine and hydrogen.
