### ISSUE TITLE
1.19.2 not loading

### ISSUE THREAD

**Issue by florianreuth** [Chocohead/OptiFabric#891]
### Crashlog

java.lang.NullPointerException: Cannot invoke "net.fabricmc.mapping.tree.ClassDef.getName(String)" because "option" is null
	at me.modmuss50.optifabric.mod.OptifineSetup.createMappings(OptifineSetup.java:267)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:167)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

**Comment by RealIndica** [comment]
Same here. Trying to develop a fabric mod alongside optifine, but I'm getting the same error : 
```
Failed to setup optifine:
java.lang.NullPointerException: Cannot invoke "net.fabricmc.mapping.tree.ClassDef.getName(String)" because "option" is null
        at me.modmuss50.optifabric.mod.OptifineSetup.createMappings(OptifineSetup.java:267)
        at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:167)
        at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:46)
        at java.base/java.util.ArrayList.forEach(Unknown Source)
        at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
        at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
        at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

Anyone have any ideas?

**Comment by topia** [comment]
I don't know the details, but your crash point is changed by this commit: https://github.com/Chocohead/OptiFabric/commit/cd4fcb27cb650f8c20ee6d464167165a69f42cc0#diff-da5bb78a5f5a8071fd9e26c20bdbeff23b0f9e6d8e124403eea464b2000b7397L267-R292.
So, it might be fixed on the artifact from the latest build: https://github.com/Chocohead/OptiFabric/actions/runs/4119428620.

**Comment by RealIndica** [comment]
> I don't know the details, but your crash point is changed by this commit: [cd4fcb2#diff-da5bb78a5f5a8071fd9e26c20bdbeff23b0f9e6d8e124403eea464b2000b7397L267-R292](https://github.com/Chocohead/OptiFabric/commit/cd4fcb27cb650f8c20ee6d464167165a69f42cc0#diff-da5bb78a5f5a8071fd9e26c20bdbeff23b0f9e6d8e124403eea464b2000b7397L267-R292). So, it might be fixed on the artifact from the latest build: https://github.com/Chocohead/OptiFabric/actions/runs/4119428620.

Can confirm, the build provided has fixed this issue.

Thank you!
