### ISSUE TITLE
1.19.2 Incompatible mod set!

### ISSUE THREAD

**Issue by Pyma21** [Chocohead/OptiFabric#916]
I have this error every time:

"Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'OptiFabric' (optifabric) 1.13.10 (C:\Users\Ambrose\AppData\Roaming\.minecraft\Mods\optifabric-1.13.10.jar).
Unmet dependency listing:
	 - Mod 'OptiFabric' (optifabric) 1.13.10 requires version 1.16.1, version 1.16.2, version 1.16.3, version 1.16.4, version 1.16.5, version 1.17-alpha.21.8.b, version 1.17-beta.4, version 1.17, version 1.17.1, version 1.18-beta.1, version 1.18, version 1.18.1, version 1.18.2, version 1.19 or version 1.19.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)"

**Comment by topia** [comment]
because you're using old optifabric and it doesn't support 1.19.2.
Could you try optifabric-1.13.16?
