### ISSUE TITLE
Not working with create mod 

### ISSUE THREAD

**Issue by RapFalp** [Chocohead/OptiFabric#949]
I have all up to date mods but it just doesn't work!

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Create' (create) 0.5.0g-796+1.19.2 with any version that is compatible with:
		 - optifabric 1.13.16
Unmet dependency listing:
	 - Mod 'Create' (create) 0.5.0g-796+1.19.2 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.16!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by topia** [comment]
This is intended by the author of the create: https://github.com/Fabricators-of-Create/Create/issues/675#issuecomment-1345723070
