### ISSUE TITLE
A LOT OF INCOMPATIBILITY -- PLEASE FIX

### ISSUE THREAD

**Issue by ereese99** [Chocohead/OptiFabric#955]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'OptiFabric' (optifabric) 1.13.16 (C:\Users\erees\curseforge\minecraft\Instances\Future Fabric\mods\optifabric-1.13.16.jar).
Unmet dependency listing:
	 - Mod 'Bewitchment' (bewitchment) 1.19-6 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.16!
	 - Mod 'Create' (create) 0.5.0g-796+1.19.2 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.16!
	 - Mod 'Hibernal Herbs' (hibernalherbs) 0.5.3 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.16!
	 - Mod 'ImmediatelyFast' (immediatelyfast) 1.1.8 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.16!
	 - Mod 'Sodium' (sodium) 0.4.4+build.18 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.16!
	 - Mod 'LambdaBetterGrass' (lambdabettergrass) 1.3.0+1.19 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.16!
	 - Mod 'LambDynamicLights' (lambdynlights) 2.2.0+1.19.2 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.16!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by topia** [comment]
These incompatibilities are marked by their developer explicitly. These devs don't want to support optifabric/optifine (due to the difficulty) or don't work together by design (provides similar functionality: sodium etc).

**Comment by itsMarkiS** [comment]
sodium and lambdynamiclights
they will never ever work with optifine and optifabric
