### ISSUE TITLE
Fixed

### ISSUE THREAD

**Issue by kitsueee** [Chocohead/OptiFabric#959]
[12:35:48] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.14.13
[12:35:48] [ForkJoinPool-1-worker-5/WARN]: Mod wurst uses the version v7.31-MC1.16.5 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v7'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[12:35:48] [main/INFO]: Loading 51 mods:
	- fabric 0.42.0+1.16
	- fabric-api-base 0.4.0+3cc0f0907d via fabric
	- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d via fabric
	- fabric-biome-api-v1 3.1.13+3cc0f0907d via fabric
	- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d via fabric
	- fabric-command-api-v1 1.1.3+3cc0f0907d via fabric
	- fabric-commands-v0 0.2.3+3cc0f0907d via fabric
	- fabric-containers-v0 0.1.12+3cc0f0907d via fabric
	- fabric-content-registries-v0 0.2.5+3cc0f0907d via fabric
	- fabric-crash-report-info-v1 0.1.4+3cc0f0907d via fabric
	- fabric-dimensions-v1 2.0.8+3cc0f0907d via fabric
	- fabric-entity-events-v1 1.2.4+3cc0f0907d via fabric
	- fabric-events-interaction-v0 0.4.5+3cc0f0907d via fabric
	- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d via fabric
	- fabric-game-rule-api-v1 1.0.7+3cc0f0907d via fabric
	- fabric-item-api-v1 1.2.2+3cc0f0907d via fabric
	- fabric-item-groups-v0 0.3.1+3cc0f0907d via fabric
	- fabric-key-binding-api-v1 1.0.5+3cc0f0907d via fabric
	- fabric-keybindings-v0 0.2.2+3cc0f0907d via fabric
	- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d via fabric
	- fabric-loot-tables-v1 1.0.3+3cc0f0907d via fabric
	- fabric-mining-levels-v0 0.1.4+3cc0f0907d via fabric
	- fabric-models-v0 0.3.1+3cc0f0907d via fabric
	- fabric-networking-api-v1 1.0.5+3cc0f0907d via fabric
	- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d via fabric
	- fabric-networking-v0 0.3.3+3cc0f0907d via fabric
	- fabric-object-builder-api-v1 1.9.6+3cc0f0907d via fabric
	- fabric-object-builders-v0 0.7.3+3cc0f0907d via fabric
	- fabric-particles-v1 0.2.5+3cc0f0907d via fabric
	- fabric-registry-sync-v0 0.7.6+3cc0f0907d via fabric
	- fabric-renderer-api-v1 0.4.5+3cc0f0907d via fabric
	- fabric-renderer-indigo 0.4.5+3cc0f0907d via fabric
	- fabric-renderer-registries-v1 2.3.1+3cc0f0907d via fabric
	- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d via fabric
	- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d via fabric
	- fabric-rendering-v0 1.1.3+3cc0f0907d via fabric
	- fabric-rendering-v1 1.6.1+3cc0f0907d via fabric
	- fabric-resource-loader-v0 0.4.8+3cc0f0907d via fabric
	- fabric-screen-api-v1 1.0.1+3cc0f0907d via fabric
	- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d via fabric
	- fabric-structure-api-v1 1.1.12+3cc0f0907d via fabric
	- fabric-tag-extensions-v0 1.1.2+3cc0f0907d via fabric
	- fabric-textures-v0 1.0.7+3cc0f0907d via fabric
	- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d via fabric
	- fabric-transfer-api-v1 1.5.0+3cc0f0907d via fabric
	- fabricloader 0.14.13
	- java 8
	- minecraft 1.16.5
	- mm 2.1 via optifabric
	- optifabric 1.9.2
	- wurst v7.31-MC1.16.5
[12:35:48] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/ashga/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[12:35:49] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache)
[12:35:49] [main/ERROR]: Error encountered during mixin config postInit step 'mixins.mm.json' from mod 'mm': Failed to setup optifine
java.lang.RuntimeException: Failed to setup optifine
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:51) ~[optifabric-1.9.2.jar:?]
	at com.chocohead.mm.Plugin$$Lambda$46/2044337856.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51]
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:339) ~[mm-2.1-858bd3ca659b5c0.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) [fabric-loader-0.14.13.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_51]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.13.jar:?]
Caused by: java.lang.NoSuchMethodError: net.fabricmc.loader.FabricLoader.getGameProvider()Lnet/fabricmc/loader/game/GameProvider;
	at me.modmuss50.optifabric.mod.OptifineSetup.getLaunchMinecraftJar(OptifineSetup.java:265) ~[optifabric-1.9.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getMinecraftJar(OptifineSetup.java:243) ~[optifabric-1.9.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:73) ~[optifabric-1.9.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:38) ~[optifabric-1.9.2.jar:?]
	... 26 more
[12:35:57] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:35:58] [main/INFO]: Setting user: BellaForma
[12:35:58] [main/INFO]: Definitely not up to no good
[12:35:58] [main/INFO]: [STDOUT]: Starting Wurst Client...
[12:36:00] [main/INFO]: [Indigo] Registering Indigo renderer!
[12:36:00] [main/INFO]: [Indigo] Compatibility mode enabled.
[12:36:01] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[12:36:04] [main/INFO]: Narrator library for x64 successfully loaded
[12:36:04] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking Block Entity (v0), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Structure API (v1), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric Transfer API (v1), Fabric Loader, Manningham Mills, OptiFabric, Wurst Client)
[12:36:08] [main/INFO]: OpenAL initialized.
[12:36:08] [main/INFO]: Sound engine started
[12:36:08] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[12:36:09] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[12:36:09] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[12:36:09] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[12:36:09] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[12:36:09] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[12:36:09] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[12:36:10] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[12:36:10] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[12:36:10] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[12:36:19] [main/INFO]: Stopping!

**Comment by topia** [comment]
For reference: The latest supported version for 1.16 is 1.13.16.
