### ISSUE TITLE
when will 1.19.3 come out

### ISSUE THREAD

**Issue by anco0569y56** [Chocohead/OptiFabric#971]

**Comment by TobyJennings1** [comment]
https://github.com/Chocohead/OptiFabric/suites/10842483751/artifacts/546227349

**Comment by DaSavage507** [comment]
> https://github.com/Chocohead/OptiFabric/suites/10842483751/artifacts/546227349

just leads to 404 page for me

**Comment by TobyJennings1** [comment]
login then it will work

**Comment by TobyJennings1** [comment]
works fine for me, triggers a download

**Comment by DaSavage507** [comment]
> login then it will work

ah thx

**Comment by nbtc971** [comment]
Which of the JAR files do we load up?

**Comment by bnnt29** [comment]
> https://github.com/Chocohead/OptiFabric/suites/10842483751/artifacts/546227349

where did you find that link and what is the link for the version released some hours ago?

**Comment by VicLeComique** [comment]
do i unzip the file?

**Comment by Robjamrobrox** [comment]
If you extract from the link it says it's 1.13

**Comment by bnnt29** [comment]
ah, thx found it

**Comment by INeedOptiFabric** [comment]
> works fine for me, triggers a download

whenever i try to open minecraft with it says it requires mmversion 2.0

**Comment by PotsThePotato** [comment]
For anyone having issues launching the game and receiving and "Exit code: 1" try updating your fabric api to the newest release.

**Comment by RoyalScribblz** [comment]
@PotsThePotato 
I am getting that error exit code I'm using:
fabric-api-0.75.1+1.19.3.jar
optifabric-1.13.20.jar
preview_OptiFine_1.19.3_HD_U_I2_pre5.jar

**Comment by Athar42** [comment]
Because you need the latest dev build, 1.13.21 which support pre4 and up.
==> https://github.com/Chocohead/OptiFabric/suites/11122716797/artifacts/566927779 (release 1.13.21)

**Comment by Gabocota** [comment]
preview_OptiFine_1.19.3_HD_U_I2_pre5
fabric-api-0.75.1+1.19.3
optifabric-1.13.21-dev

says it needs mm version 2.0 which I have no idea what it is

**Comment by Athar42** [comment]
Don't use the "-dev", just the one without it, should work.

**Comment by panpomidoras** [comment]
i have something like that 
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_128.method_568(class_128.java:175)
	at net.minecraft.class_128.method_24305(class_128.java:345)
	at net.minecraft.client.main.Main.method_44604(Main.java:159)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2371)
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:497)
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 16 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [optifabric.compat.architectury-AB.newerer-mixins.json:GameRendererNewererMixin from mod optifabric] from phase [DEFAULT] in config [optifabric.compat.architectury-AB.newerer-mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 19 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> optifabric.compat.architectury-AB.newerer-mixins.json:GameRendererNewererMixin from mod optifabric -> Apply Methods -> (FJZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;IILnet/minecraft/class_1041;FLnet/minecraft/class_1159;Lnet/minecraft/class_4587;)V:renderScreenPre -> Transform LVT -> var=matrix -> desc=Lnet/minecraft/class_1159;]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:510)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:533)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:519)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:386)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 19 more
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: net.minecraft.class_1159
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:1002)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:962)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformLVT(MixinTargetContext.java:563)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:469)
	... 26 more

**Comment by ApoRaven** [comment]
I run it with the updated one no -dev
it just says game crashed 
![image](https://user-images.githubusercontent.com/44433530/223192256-1d53707c-4cef-4c4a-98ae-ce23cf9200f1.png)
![image](https://user-images.githubusercontent.com/44433530/223192312-22768478-1208-4c37-9660-9e76a8bfe246.png)

**Comment by Athar42** [comment]
Could be a plugin conflict.

I would try with only Optifine, optifabric and fabric-api (the minimal base, just to ensure the game run with it, and then, add half of the othern mods, test again, etc. until it fail and you found the bad one)

**Comment by Macanudo08** [comment]
> For anyone having issues launching the game and receiving and "Exit code: 1" try updating your fabric api to the newest release.

It says  exit code:1 and i have the latest version of fabric api
Which of the four files should i add?

**Comment by Tom1969** [comment]
Install the Fabric 0.11.2 and use fabric-api-0.75.1+1.19.3.jar solved my Problem of the Exit code:1 Error

**Comment by Dragonik1** [comment]
@Tom1969 it still shows me the exit code 1

**Comment by Tom1969** [comment]
Rename the mod folder, make a new folder with the name mods and copy only the following mods in the new mods folder:

- fabric-api-0.75.1
- optifabric-1.13.21
- preview_OptiFine_1.19.3_HD_U_I2_pre5

Then start the game.

When the game starts, exit the game, copy the next mod from the renamed mods folder to the new one and start the game.
Repeat this steps to check who mod will crash the game.

**Comment by p6117** [comment]
I installed the 1.19.3 beta (optifabric-1.13.20.jar) from the link above, however the client says "Optifine requires 1.19.2 you are running 1.19.3"

If this is for 1.19.3 why does it say it requires 1.19.2?

Installed:
fabric-api-0.75.1+1.19.3
litematica-fabric-1.19.3-0.13.1
malilib-fabric-1.19.3-0.14.0
optifabric-1.13.20
OptiFine_1.19.2_HD_U_I1

**Comment by Mekae23** [comment]
It was JustEnougItems that crashed it for me.

**Comment by topia** [comment]
> I installed the 1.19.3 beta (optifabric-1.13.20.jar) from the link above, however the client says "Optifine requires 1.19.2 you are running 1.19.3"
> 
> If this is for 1.19.3 why does it say it requires 1.19.2?

You need the "optifine for 1.19.3" (preview version).

**Comment by 71-o** [comment]
Mine keeps not responding with V below, dont really understand what to do. Sorry if ive missed something 
![image](https://user-images.githubusercontent.com/127689588/224578825-2d8c174e-c800-445e-b6fa-db89a16ef230.png)
![image](https://user-images.githubusercontent.com/127689588/224578847-c8457597-5913-4afe-a814-a13d537a4bf5.png)

**Comment by p6117** [comment]
> > I installed the 1.19.3 beta (optifabric-1.13.20.jar) from the link above, however the client says "Optifine requires 1.19.2 you are running 1.19.3"
> > If this is for 1.19.3 why does it say it requires 1.19.2?
> 
> You need the "optifine for 1.19.3" (preview version).
 
 
 Just tried it and my game crashes. I can use an Optifine client just fine, but when I try to launch my Fabric/litematica one with optifine/optifabric it doesnt work.

**Comment by toygurt1** [comment]
It kept crashing all the time and maybe it's a rookie mistake but I feel like this might help some people:
 Managed to make it work. All I needed to do was open the preview_OptiFine_1.19.3_HD_U_I2_pre3.jar instead of dragging it to the mods folder, and extract it to the mods folder (which creates Optifine mod instead of the client installer).

Currently works with mods such as Mouse-Tweaks-Mod-Fabric-1.19.3 and litematica-fabric-1.19.3-0.13.1 but still crashes whenever I add architectury-7.1.70-fabric which I need to have in order to use light-overlay-7.0.2 so that's a bummer.

**Comment by p6117** [comment]
> It kept crashing all the time and maybe it's a rookie mistake but I feel like this might help some people: Managed to make it work. All I needed to do was open the preview_OptiFine_1.19.3_HD_U_I2_pre3.jar instead of dragging it to the mods folder, and extract it to the mods folder (which creates Optifine mod instead of the client installer).
> 
> Currently works with mods such as Mouse-Tweaks-Mod-Fabric-1.19.3 and litematica-fabric-1.19.3-0.13.1 but still crashes whenever I add architectury-7.1.70-fabric which I need to have in order to use light-overlay-7.0.2 so that's a bummer.

What do you mean "and extract it to the mods folder?" there is nothing to extract.

Idk why I'm still having problems with it. I installed Optifine properly, and i have all of the correct versions. I still get an error saying i have 1.19.2 and need 1.19.3 when I HAVE 1.19.3

**Comment by topia** [comment]
> > You need the "optifine for 1.19.3" (preview version).
> 
> Just tried it and my game crashes. I can use an Optifine client just fine, but when I try to launch my Fabric/litematica one with optifine/optifabric it doesnt work.

Even if you encounter the game crashing, it's the only way to work. an optifine release works only with a specified Minecraft release.
It seems like you encountered mod compatibility issues, so please try with the limited mod set first - fabric API + optifine + optifabric.

**Comment by p6117** [comment]
> > > You need the "optifine for 1.19.3" (preview version).
> > 
> > 
> > Just tried it and my game crashes. I can use an Optifine client just fine, but when I try to launch my Fabric/litematica one with optifine/optifabric it doesnt work.
> 
> Even if you encounter the game crashing, it's the only way to work. an optifine release works only with a specified Minecraft release. It seems like you encountered mod compatibility issues, so please try with the limited mod set first - fabric API + optifine + optifabric.

All of my mods work together fine until I throw Optifabric in.
The only mods I have are the following anyway:
Fabric API
Litematica
Malilib
Optifine

**Comment by Athar42** [comment]
You seems to use an Optifine for 1.19.2... ("OptiFine_1.19.2_HD_U_I1").

Also, take the "Beta" optifabric-1.13.21

**Comment by matsyui** [comment]
> Install the Fabric 0.11.2 and use fabric-api-0.75.1+1.19.3.jar solved my Problem of the Exit code:1 Error


Saw this comment but it is not working.. 

Update: I tried using optifabric-1.13.21 still not working

![Screenshot_1](https://user-images.githubusercontent.com/62344860/225822552-967d11ec-b6a8-4c6d-8d70-0586b71b1fc6.png)

**Comment by topia** [comment]
You need optifabric 1.13.21 instead of 1.13.20 for optifine pre4+.

**Comment by topia** [comment]
Please upload the latest log for digging the exit 1 problem.

**Comment by noway64** [comment]
@mashwishi how you even get the optifabric 1.13.21? I got only 1.13.20??

**Comment by noway64** [comment]
@toygurt1 It cant find the 1.19.3? Help someone please me

**Comment by Tom1969** [comment]
> @mashwishi how you even get the optifabric 1.13.21? I got only 1.13.20??

Find it under #971 from post of Athar42
https://github.com/Chocohead/OptiFabric/issues/971#issuecomment-1445162818

**Comment by Dracconis** [comment]
Currently optifabric1.13.21+optifine pre4+ will not work with any mod that requires architectury until the new patch is applied. YOu will notice when trying to use it IF you see this or similar error in the log:
"Mixin apply for mod optifabric failed optifabric.compat.architectury-AB.**newerer**-mixins.json", the word in bold needs to be newererer (yes 3 -er's) in order for optifabric1.13.21+optifine pre4+ as mentioned here:
https://github.com/Chocohead/OptiFabric/pull/1002

**Comment by GamingGuyRob** [comment]
> Currently optifabric1.13.21+optifine pre4+ will not work with any mod that requires architectury until the new patch is applied. YOu will notice when trying to use it IF you see this or similar error in the log: "Mixin apply for mod optifabric failed optifabric.compat.architectury-AB.**newerer**-mixins.json", the word in bold needs to be newererer (yes 3 -er's) in order for optifabric1.13.21+optifine pre4+ as mentioned here: #1002

Is the new patch available yet?

**Comment by Dracconis** [comment]
No it is not or at least I have not been able to find it.

**Comment by SkyKingPX** [comment]
Fabric API isn't compatible with optifabric

**Comment by Dracconis** [comment]
> 

You would be wrong sir. IF you are only using the Fabric API for 1.19.3 AND Optifabric that is linked here in this thread in combination with optifine 1.19.3 pre4 and up, it will work just fine. It may also work with other mods as well so long as those mods dont require architectury. Otherwise you will need to follow the instructions in the thread that was in my last comment to get everything working for 1.19.3.

**Comment by SkyKingPX** [comment]
@Dracconis And how to do this?

**Comment by Dracconis** [comment]
As I said look at my previous comment that takes you to the thread about fixing it and how to get the new version of optifabric so that it works not only with optifine but any mod requiring Architectury.

**Comment by danielsjun** [comment]
When I try to launch, it says I need to install mm version 2.0 or later. What is mm?

**Comment by topia** [comment]
> When I try to launch, it says I need to install mm version 2.0 or later. What is mm?

Why do you want to use Actions build? the newest one is [published](https://www.curseforge.com/minecraft/mc-mods/optifabric/files/4455920) via curseforge.
By the way, do not use suffixed jars. mm is an embedded mod.
