### ISSUE TITLE
version 0.7.1 for 1.14.4 crashes when there is entity in the world, OptiFine_1.14.4_HD_U_F5

### ISSUE THREAD

**Issue by anaizy31** [Chocohead/OptiFabric#98]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 11/14/20 5:37 AM
Description: Exception in server tick loop

java.lang.NoSuchFieldError: field_6209
	at net.minecraft.class_1308.method_6118(class_1308.java:749)
	at net.minecraft.class_3231.method_18757(class_3231.java:250)
	at net.minecraft.class_3231.method_18760(class_3231.java:211)
	at net.minecraft.class_3898$class_3208.method_18736(class_3898.java:1198)
	at net.minecraft.class_3898$class_3208.method_18729(class_3898.java:1209)
	at net.minecraft.class_3898.method_18701(class_3898.java:982)
	at net.minecraft.class_3215.method_18755(class_3215.java:485)
	at net.minecraft.class_3218.method_18778(class_3218.java:958)
	at net.minecraft.class_3218.method_14175(class_3218.java:889)
	at net.minecraft.class_3218.method_8649(class_3218.java:819)
	at net.minecraft.class_1299.method_5899(class_1299.java:294)
	at net.minecraft.class_1299.method_5894(class_1299.java:284)
	at net.minecraft.class_1826.method_7884(class_1826.java:82)
	at net.minecraft.class_1799.method_7981(class_1799.java:189)
	at net.minecraft.class_3225.method_14262(class_3225.java:323)
	at net.minecraft.class_3244.method_12046(class_3244.java:922)
	at net.minecraft.class_2885.method_12547(class_2885.java:36)
	at net.minecraft.class_2885.method_11054(class_2885.java:10)
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:33)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:170)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:135)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:706)
	at net.minecraft.class_1255.method_18857(class_1255.java:148)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:691)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:646)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2494736584 bytes (2379 MB) / 3694657536 bytes (3523 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx4096m
	Fabric Mods: 
		fabric: Fabric API 0.23.2+1.14
		fabric-api-base: Fabric API Base 0.1.2+28f8190f42
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.1+28f8190f42
		fabric-command-api-v1: Fabric Command API (v1) 1.0.1+b534aa0c42
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+bfd4c99d42
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+28f8190f42
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.2+28f8190f42
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+28f8190f42
		fabric-dimensions-v1: fabric-dimensions-v1 0.1.1+e15ff88642
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+a35b4edd42
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+12fccc5b42
		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+a35b4edd42
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+7ce6c57742
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+253decf242
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+85811ffb42
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+12fccc5b42
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.1+28f8190f42
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+c3dba7cb42
		fabric-models-v0: Fabric Models (v0) 0.1.0+933c24c242
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.1+28f8190f42
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e7757afe42
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.0.0+002fcb6542
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.3.0+39c719f942
		fabric-particles-v1: fabric-particles-v1 0.2.1+e9056b2242
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.3+28f8190f42
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.1.1+933c24c242
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.1.15+b712afff42
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.2+28f8190f42
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.3+28f8190f42
		fabric-rendering-v0: Fabric Rendering (v0) 0.1.2+28f8190f42
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.4+28f8190f42
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+d423005742
		fabric-textures-v0: Fabric Textures (v0) 0.1.4+933c24c242
		fabricloader: Fabric Loader 0.10.6+build.214
		minecraft: Minecraft 1.14.4
		mm: Manningham Mills 1.8
		optifabric: Optifabric 0.7.1
		org_slf4j_slf4j-api: slf4j-api 1.7.29
		org_slf4j_slf4j-simple: slf4j-simple 1.7.29
		org_zeroturnaround_zt-zip: zt-zip 1.13
	Player Count: 1 / 8; [class_3222['player'/1, l='world', x=-102.29, y=56.00, z=224.92]]
	Data Packs: fabric/fabric-mining-levels-v0, vanilla
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
	OptiFine Version: OptiFine_1.14.4_HD_U_F5
	OptiFine Build: 20191204-141250
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 451.67
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
#@!@# Game crashed! Crash report saved to: #@!@# C:\MultiMC\instances\1.14.4 fabric\.minecraft\crash-reports\crash-2020-11-14_05.37.56-server.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.

**Comment by anaizy31** [comment]
if I load any save file with mobs in it the game immediately crashes. When I load a save file with no mobs in it it crashes when I summon/use spawn egg to spawn a mob.

**Comment by Chocohead** [comment]
If you use an older Fabric API version does this happen to go away? Thinking it might be a similar cause to #13

**Comment by sunnyye1** [comment]
same issue, crash while loading entity

seems okay with old version of fabric api

**Comment by Sjouwer** [comment]
So I know this is a very old issue, so there might be no longer any interest, however I forked OptiFabric and backported some stuff to get it working again on the latest 1.14 Fabric API and Fabric Loader 12. I'm sure I could have done a lot of things better and maybe even backport more stuff, but it seems to work fine for me and it was exactly what I needed. The only issue atm is that it's not backwards compatible with older Fabric Loader versions, however older API versions are perfectly fine to use.
https://github.com/Sjouwer/OptiFabric-1.14.4-Updated

@Chocohead
If you want I'd be willing to make a pull request for a 1.14 branch. I'm not quite sure though what the best way to do that is, since I basically only backported stuff, so might be better if I could discuss it  first with you if possible.
