### ISSUE TITLE
Minecraft 1.16.5 - "Failed to load optifine, please report this!" 

### ISSUE THREAD

**Issue by CorruptCopper** [Chocohead/OptiFabric#995]
When the mojang screen is done loading, shows this error instead of Title Screen. I am using fabric version 0.14.14 and minecraft version 1.16.5. I am playing minecraft after a long time and I remember that I used to be able to run version 1.16.5 with these mods installed. Here is a screen shot
![Capture](https://user-images.githubusercontent.com/128062782/225654063-9d9833cd-5a49-46f3-9583-a365ad0ef8f0.PNG)
There are the mods that I am using - 
![Capture2](https://user-images.githubusercontent.com/128062782/225657598-9da55853-1a4d-413b-80ec-b567bc3bbcf0.PNG)
And this is the stack-trace 
java.lang.NoSuchMethodError: net.fabricmc.loader.FabricLoader.getGameProvider()Lnet/fabricmc/loader/game/GameProvider;
	at me.modmuss50.optifabric.mod.OptifineSetup.getLaunchMinecraftJar(OptifineSetup.java:275)
	at me.modmuss50.optifabric.mod.OptifineSetup.getMinecraftJar(OptifineSetup.java:253)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:81)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at com.chocohead.mm.Plugin$$Lambda$47/1340057206.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by ghost** [comment]
Your kyxsis is a forge download not fabric

**Comment by CorruptCopper** [comment]
> Your kyxsis is a forge download not fabric

Oh yeah I just noticed. I removed it and then tried running it but still gives the same error

**Comment by CorruptCopper** [comment]
Also btw I know that I'm using an older version of optifabric which is 1.9.6 and the latest version is 1.11.9 (for mc 1.16.5) but when I use version 1.11.9, it gives the error telling that this version of optifabric requires that the fabric loader version must be lower than 0.12 but I'm using other mods that require the fabric version to be higher than 0.12

**Comment by topia** [comment]
Please re-check curseforge. optifabric latest version for 1.16 is 1.13.16, not 1.11.9.

**Comment by CorruptCopper** [comment]
> Please re-check curseforge. optifabric latest version for 1.16 is 1.13.16, not 1.11.9.

Optifabric version 1.13.16 is for minecraft version 1.19.2 and not compatible with minecraft version 1.16.5
The highest optifabric version that is compatible with mc version 1.16.5 is optifabric version 1.11.9

**Comment by topia** [comment]
Why do you think that? Did you try it?
https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3961344

**Comment by CorruptCopper** [comment]
> Why do you think that? Did you try it? https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3961344

Ooof. I feel like an idiot. I thought that when it said 1.19.2 it was meant only for that version. Game works fine now. Tysm man!
