### ISSUE TITLE
Optifabric is not working?

### ISSUE THREAD

**Issue by MrPeeper** [Chocohead/OptiFabric#997]
When I open Minecraft with optifabric and optifine if does this

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'OptiFabric' (optifabric) 1.13.16 with any version that is compatible with:
		 - minecraft 1.19.4
Unmet dependency listing:
	 - Mod 'OptiFabric' (optifabric) 1.13.16 requires version 1.16.1, version 1.16.2, version 1.16.3, version 1.16.4, version 1.16.5, version 1.17-alpha.21.8.b, version 1.17-beta.4, version 1.17, version 1.17.1, version 1.18-beta.1, version 1.18, version 1.18.1, version 1.18.2, version 1.19, version 1.19.1 or version 1.19.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by topia** [comment]
1.19.4 isn't supported yet, and it won't release until an optifine release.

**Comment by ghost** [comment]
Now that optifine pre1 is out im trying to patch an action build as a quick fix

**Comment by mincailon** [comment]
plz fix 1.16.5 optifarbic it broke

**Comment by topia** [comment]
> plz fix 1.16.5 optifarbic it broke

I can't confirm that. You should write the detail (such as latest.log) to report issues. But first of all, if you didn't search for issues, please do it and check those contents are applied to you. For example, #995
